using Kermalis.PokemonBattleEngine.Data;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Kermalis.PokemonBattleEngine.Localization
{
    public static class PBEItemLocalization
    {
        public static ReadOnlyDictionary<PBEItem, PBELocalizedString> Names { get; } = new ReadOnlyDictionary<PBEItem, PBELocalizedString>(new Dictionary<PBEItem, PBELocalizedString>()
        {
            { PBEItem.None, new PBELocalizedString("--", "--") },
            { PBEItem.AbsorbBulb, new PBELocalizedString("Absorb Bulb", "きゅうこん") },
            { PBEItem.AdamantOrb, new PBELocalizedString("Adamant Orb", "こんごうだま") },
            { PBEItem.AguavBerry, new PBELocalizedString("Aguav Berry", "バンジのみ") },
            { PBEItem.AirBalloon, new PBELocalizedString("Air Balloon", "ふうせん") },
            { PBEItem.AmuletCoin, new PBELocalizedString("Amulet Coin", "おまもりこばん") },
            { PBEItem.Antidote, new PBELocalizedString("Antidote", "どくけし") },
            { PBEItem.ApicotBerry, new PBELocalizedString("Apicot Berry", "ズアのみ") },
            { PBEItem.ArmorFossil, new PBELocalizedString("Armor Fossil", "たてのカセキ") },
            { PBEItem.AspearBerry, new PBELocalizedString("Aspear Berry", "ナナシのみ") },
            { PBEItem.Awakening, new PBELocalizedString("Awakening", "ねむけざまし") },
            { PBEItem.BabiriBerry, new PBELocalizedString("Babiri Berry", "リリバのみ") },
            { PBEItem.BalmMushroom, new PBELocalizedString("BalmMushroom", "かおるキノコ") },
            { PBEItem.BelueBerry, new PBELocalizedString("Belue Berry", "ベリブのみ") },
            { PBEItem.BerryJuice, new PBELocalizedString("Berry Juice", "きのみジュース") },
            { PBEItem.BigMushroom, new PBELocalizedString("Big Mushroom", "おおきなキノコ") },
            { PBEItem.BigNugget, new PBELocalizedString("Big Nugget", "でかいきんのたま") },
            { PBEItem.BigPearl, new PBELocalizedString("Big Pearl", "おおきなしんじゅ") },
            { PBEItem.BigRoot, new PBELocalizedString("Big Root", "おおきなねっこ") },
            { PBEItem.BindingBand, new PBELocalizedString("Binding Band", "しめつけバンド") },
            { PBEItem.BlackBelt, new PBELocalizedString("Black Belt", "くろおび") },
            { PBEItem.BlackFlute, new PBELocalizedString("Black Flute", "くろいビードロ") },
            { PBEItem.BlackGlasses, new PBELocalizedString("BlackGlasses", "くろいメガネ") },
            { PBEItem.BlackSludge, new PBELocalizedString("Black Sludge", "くろいヘドロ") },
            { PBEItem.BlkApricorn, new PBELocalizedString("Blk Apricorn", "くろぼんぐり") },
            { PBEItem.BluApricorn, new PBELocalizedString("Blu Apricorn", "あおぼんぐり") },
            { PBEItem.BlueFlute, new PBELocalizedString("Blue Flute", "あおいビードロ") },
            { PBEItem.BlueScarf, new PBELocalizedString("Blue Scarf", "あおいバンダナ") },
            { PBEItem.BlueShard, new PBELocalizedString("Blue Shard", "あおいかけら") },
            { PBEItem.BlukBerry, new PBELocalizedString("Bluk Berry", "ブリーのみ") },
            { PBEItem.BridgeMailD, new PBELocalizedString("Bridge Mail D", "ブリッジメールＨ") },
            { PBEItem.BridgeMailM, new PBELocalizedString("Bridge Mail M", "ブリッジメールＷ") },
            { PBEItem.BridgeMailS, new PBELocalizedString("Bridge Mail S", "ブリッジメールＳ") },
            { PBEItem.BridgeMailT, new PBELocalizedString("Bridge Mail T", "ブリッジメールＣ") },
            { PBEItem.BridgeMailV, new PBELocalizedString("Bridge Mail V", "ブリッジメールＶ") },
            { PBEItem.BrightPowder, new PBELocalizedString("BrightPowder", "ひかりのこな") },
            { PBEItem.BugGem, new PBELocalizedString("Bug Gem", "むしのジュエル") },
            { PBEItem.BurnDrive, new PBELocalizedString("Burn Drive", "ブレイズカセット") },
            { PBEItem.BurnHeal, new PBELocalizedString("Burn Heal", "やけどなおし") },
            { PBEItem.Calcium, new PBELocalizedString("Calcium", "リゾチウム") },
            { PBEItem.Carbos, new PBELocalizedString("Carbos", "インドメタシン") },
            { PBEItem.Casteliacone, new PBELocalizedString("Casteliacone", "ヒウンアイス") },
            { PBEItem.CellBattery, new PBELocalizedString("Cell Battery", "じゅうでんち") },
            { PBEItem.Charcoal, new PBELocalizedString("Charcoal", "もくたん") },
            { PBEItem.ChartiBerry, new PBELocalizedString("Charti Berry", "ヨロギのみ") },
            { PBEItem.CheriBerry, new PBELocalizedString("Cheri Berry", "クラボのみ") },
            { PBEItem.CherishBall, new PBELocalizedString("Cherish Ball", "プレシャスボール") },
            { PBEItem.ChestoBerry, new PBELocalizedString("Chesto Berry", "カゴのみ") },
            { PBEItem.ChilanBerry, new PBELocalizedString("Chilan Berry", "ホズのみ") },
            { PBEItem.ChillDrive, new PBELocalizedString("Chill Drive", "フリーズカセット") },
            { PBEItem.ChoiceBand, new PBELocalizedString("Choice Band", "こだわりハチマキ") },
            { PBEItem.ChoiceScarf, new PBELocalizedString("Choice Scarf", "こだわりスカーフ") },
            { PBEItem.ChoiceSpecs, new PBELocalizedString("Choice Specs", "こだわりメガネ") },
            { PBEItem.ChopleBerry, new PBELocalizedString("Chople Berry", "ヨプのみ") },
            { PBEItem.ClawFossil, new PBELocalizedString("Claw Fossil", "ツメのカセキ") },
            { PBEItem.CleanseTag, new PBELocalizedString("Cleanse Tag", "きよめのおふだ") },
            { PBEItem.CleverWing, new PBELocalizedString("Clever Wing", "せいしんのハネ") },
            { PBEItem.CobaBerry, new PBELocalizedString("Coba Berry", "バコウのみ") },
            { PBEItem.ColburBerry, new PBELocalizedString("Colbur Berry", "ナモのみ") },
            { PBEItem.CometShard, new PBELocalizedString("Comet Shard", "すいせいのかけら") },
            { PBEItem.CornnBerry, new PBELocalizedString("Cornn Berry", "モコシのみ") },
            { PBEItem.CoverFossil, new PBELocalizedString("Cover Fossil", "ふたのカセキ") },
            { PBEItem.CustapBerry, new PBELocalizedString("Custap Berry", "イバンのみ") },
            { PBEItem.DampMulch, new PBELocalizedString("Damp Mulch", "じめじめこやし") },
            { PBEItem.DampRock, new PBELocalizedString("Damp Rock", "しめったいわ") },
            { PBEItem.DarkGem, new PBELocalizedString("Dark Gem", "あくのジュエル") },
            { PBEItem.DawnStone, new PBELocalizedString("Dawn Stone", "めざめいし") },
            { PBEItem.DeepSeaScale, new PBELocalizedString("DeepSeaScale", "しんかいのウロコ") },
            { PBEItem.DeepSeaTooth, new PBELocalizedString("DeepSeaTooth", "しんかいのキバ") },
            { PBEItem.DestinyKnot, new PBELocalizedString("Destiny Knot", "あかいいと") },
            { PBEItem.DireHit, new PBELocalizedString("Dire Hit", "クリティカッター") },
            { PBEItem.DiveBall, new PBELocalizedString("Dive Ball", "ダイブボール") },
            { PBEItem.DomeFossil, new PBELocalizedString("Dome Fossil", "こうらのカセキ") },
            { PBEItem.DouseDrive, new PBELocalizedString("Douse Drive", "アクアカセット") },
            { PBEItem.DracoPlate, new PBELocalizedString("Draco Plate", "りゅうのプレート") },
            { PBEItem.DragonFang, new PBELocalizedString("Dragon Fang", "りゅうのキバ") },
            { PBEItem.DragonGem, new PBELocalizedString("Dragon Gem", "ドラゴンジュエル") },
            { PBEItem.DragonScale, new PBELocalizedString("Dragon Scale", "りゅうのウロコ") },
            { PBEItem.DreadPlate, new PBELocalizedString("Dread Plate", "こわもてプレート") },
            { PBEItem.DreamBall, new PBELocalizedString("Dream Ball", "ドリームボール") },
            { PBEItem.DubiousDisc, new PBELocalizedString("Dubious Disc", "あやしいパッチ") },
            { PBEItem.DurinBerry, new PBELocalizedString("Durin Berry", "ドリのみ") },
            { PBEItem.DuskBall, new PBELocalizedString("Dusk Ball", "ダークボール") },
            { PBEItem.DuskStone, new PBELocalizedString("Dusk Stone", "やみのいし") },
            { PBEItem.EarthPlate, new PBELocalizedString("Earth Plate", "だいちのプレート") },
            { PBEItem.EjectButton, new PBELocalizedString("Eject Button", "だっしゅつボタン") },
            { PBEItem.Electirizer, new PBELocalizedString("Electirizer", "エレキブースター") },
            { PBEItem.ElectricGem, new PBELocalizedString("Electric Gem", "でんきのジュエル") },
            { PBEItem.Elixir, new PBELocalizedString("Elixir", "ピーピーエイダー") },
            { PBEItem.EnergyPowder, new PBELocalizedString("EnergyPowder", "ちからのこな") },
            { PBEItem.EnergyRoot, new PBELocalizedString("Energy Root", "ちからのねっこ") },
            { PBEItem.EnigmaBerry, new PBELocalizedString("Enigma Berry", "ナゾのみ") },
            { PBEItem.EscapeRope, new PBELocalizedString("Escape Rope", "あなぬけのヒモ") },
            { PBEItem.Ether, new PBELocalizedString("Ether", "ピーピーエイド") },
            { PBEItem.Everstone, new PBELocalizedString("Everstone", "かわらずのいし") },
            { PBEItem.Eviolite, new PBELocalizedString("Eviolite", "しんかのきせき") },
            { PBEItem.ExpertBelt, new PBELocalizedString("Expert Belt", "たつじんのおび") },
            { PBEItem.ExpShare, new PBELocalizedString("Exp. Share", "がくしゅうそうち") },
            { PBEItem.FastBall, new PBELocalizedString("Fast Ball", "スピードボール") },
            { PBEItem.FavoredMail, new PBELocalizedString("Favored Mail", "だいすきメール") },
            { PBEItem.FightingGem, new PBELocalizedString("Fighting Gem", "かくとうジュエル") },
            { PBEItem.FigyBerry, new PBELocalizedString("Figy Berry", "フィラのみ") },
            { PBEItem.FireGem, new PBELocalizedString("Fire Gem", "ほのおのジュエル") },
            { PBEItem.FireStone, new PBELocalizedString("Fire Stone", "ほのおのいし") },
            { PBEItem.FistPlate, new PBELocalizedString("Fist Plate", "こぶしのプレート") },
            { PBEItem.FlameOrb, new PBELocalizedString("Flame Orb", "かえんだま") },
            { PBEItem.FlamePlate, new PBELocalizedString("Flame Plate", "ひのたまプレート") },
            { PBEItem.FloatStone, new PBELocalizedString("Float Stone", "かるいし") },
            { PBEItem.FluffyTail, new PBELocalizedString("Fluffy Tail", "エネコのシッポ") },
            { PBEItem.FlyingGem, new PBELocalizedString("Flying Gem", "ひこうのジュエル") },
            { PBEItem.FocusBand, new PBELocalizedString("Focus Band", "きあいのハチマキ") },
            { PBEItem.FocusSash, new PBELocalizedString("Focus Sash", "きあいのタスキ") },
            { PBEItem.FreshWater, new PBELocalizedString("Fresh Water", "おいしいみず") },
            { PBEItem.FriendBall, new PBELocalizedString("Friend Ball", "フレンドボール") },
            { PBEItem.FullHeal, new PBELocalizedString("Full Heal", "なんでもなおし") },
            { PBEItem.FullIncense, new PBELocalizedString("Full Incense", "まんぷくおこう") },
            { PBEItem.FullRestore, new PBELocalizedString("Full Restore", "かいふくのくすり") },
            { PBEItem.GanlonBerry, new PBELocalizedString("Ganlon Berry", "リュガのみ") },
            { PBEItem.GeniusWing, new PBELocalizedString("Genius Wing", "ちりょくのハネ") },
            { PBEItem.GhostGem, new PBELocalizedString("Ghost Gem", "ゴーストジュエル") },
            { PBEItem.GooeyMulch, new PBELocalizedString("Gooey Mulch", "ねばねばこやし") },
            { PBEItem.GrassGem, new PBELocalizedString("Grass Gem", "くさのジュエル") },
            { PBEItem.GreatBall, new PBELocalizedString("Great Ball", "スーパーボール") },
            { PBEItem.GreenScarf, new PBELocalizedString("Green Scarf", "みどりのバンダナ") },
            { PBEItem.GreenShard, new PBELocalizedString("Green Shard", "みどりのかけら") },
            { PBEItem.GreetMail, new PBELocalizedString("Greet Mail", "はじめてメール") },
            { PBEItem.GrepaBerry, new PBELocalizedString("Grepa Berry", "ウブのみ") },
            { PBEItem.GripClaw, new PBELocalizedString("Grip Claw", "ねばりのかぎづめ") },
            { PBEItem.GriseousOrb, new PBELocalizedString("Griseous Orb", "はっきんだま") },
            { PBEItem.GrnApricorn, new PBELocalizedString("Grn Apricorn", "みどぼんぐり") },
            { PBEItem.GroundGem, new PBELocalizedString("Ground Gem", "じめんのジュエル") },
            { PBEItem.GrowthMulch, new PBELocalizedString("Growth Mulch", "すくすくこやし") },
            { PBEItem.GuardSpec, new PBELocalizedString("Guard Spec.", "エフェクトガード") },
            { PBEItem.HabanBerry, new PBELocalizedString("Haban Berry", "ハバンのみ") },
            { PBEItem.HardStone, new PBELocalizedString("Hard Stone", "かたいいし") },
            { PBEItem.HealBall, new PBELocalizedString("Heal Ball", "ヒールボール") },
            { PBEItem.HealPowder, new PBELocalizedString("Heal Powder", "ばんのうごな") },
            { PBEItem.HealthWing, new PBELocalizedString("Health Wing", "たいりょくのハネ") },
            { PBEItem.HeartScale, new PBELocalizedString("Heart Scale", "ハートのウロコ") },
            { PBEItem.HeatRock, new PBELocalizedString("Heat Rock", "あついいわ") },
            { PBEItem.HeavyBall, new PBELocalizedString("Heavy Ball", "ヘビーボール") },
            { PBEItem.HelixFossil, new PBELocalizedString("Helix Fossil", "かいのカセキ") },
            { PBEItem.HondewBerry, new PBELocalizedString("Hondew Berry", "ロメのみ") },
            { PBEItem.Honey, new PBELocalizedString("Honey", "あまいミツ") },
            { PBEItem.HPUp, new PBELocalizedString("HP Up", "マックスアップ") },
            { PBEItem.HyperPotion, new PBELocalizedString("Hyper Potion", "すごいキズぐすり") },
            { PBEItem.IapapaBerry, new PBELocalizedString("Iapapa Berry", "イアのみ") },
            { PBEItem.IceGem, new PBELocalizedString("Ice Gem", "こおりのジュエル") },
            { PBEItem.IceHeal, new PBELocalizedString("Ice Heal", "こおりなおし") },
            { PBEItem.IciclePlate, new PBELocalizedString("Icicle Plate", "つららのプレート") },
            { PBEItem.IcyRock, new PBELocalizedString("Icy Rock", "つめたいいわ") },
            { PBEItem.InquiryMail, new PBELocalizedString("Inquiry Mail", "しつもんメール") },
            { PBEItem.InsectPlate, new PBELocalizedString("Insect Plate", "たまむしプレート") },
            { PBEItem.Iron, new PBELocalizedString("Iron", "ブロムヘキシン") },
            { PBEItem.IronBall, new PBELocalizedString("Iron Ball", "くろいてっきゅう") },
            { PBEItem.IronPlate, new PBELocalizedString("Iron Plate", "こうてつプレート") },
            { PBEItem.JabocaBerry, new PBELocalizedString("Jaboca Berry", "ジャポのみ") },
            { PBEItem.KasibBerry, new PBELocalizedString("Kasib Berry", "カシブのみ") },
            { PBEItem.KebiaBerry, new PBELocalizedString("Kebia Berry", "ビアーのみ") },
            { PBEItem.KelpsyBerry, new PBELocalizedString("Kelpsy Berry", "ネコブのみ") },
            { PBEItem.KingsRock, new PBELocalizedString("King’s Rock", "おうじゃのしるし") },
            { PBEItem.LaggingTail, new PBELocalizedString("Lagging Tail", "こうこうのしっぽ") },
            { PBEItem.LansatBerry, new PBELocalizedString("Lansat Berry", "サンのみ") },
            { PBEItem.LavaCookie, new PBELocalizedString("Lava Cookie", "フエンせんべい") },
            { PBEItem.LaxIncense, new PBELocalizedString("Lax Incense", "のんきのおこう") },
            { PBEItem.LeafStone, new PBELocalizedString("Leaf Stone", "リーフのいし") },
            { PBEItem.Leftovers, new PBELocalizedString("Leftovers", "たべのこし") },
            { PBEItem.Lemonade, new PBELocalizedString("Lemonade", "ミックスオレ") },
            { PBEItem.LeppaBerry, new PBELocalizedString("Leppa Berry", "ヒメリのみ") },
            { PBEItem.LevelBall, new PBELocalizedString("Level Ball", "レベルボール") },
            { PBEItem.LiechiBerry, new PBELocalizedString("Liechi Berry", "チイラのみ") },
            { PBEItem.LifeOrb, new PBELocalizedString("Life Orb", "いのちのたま") },
            { PBEItem.LightBall, new PBELocalizedString("Light Ball", "でんきだま") },
            { PBEItem.LightClay, new PBELocalizedString("Light Clay", "ひかりのねんど") },
            { PBEItem.LikeMail, new PBELocalizedString("Like Mail", "おすすめメール") },
            { PBEItem.LoveBall, new PBELocalizedString("Love Ball", "ラブラブボール") },
            { PBEItem.LuckIncense, new PBELocalizedString("Luck Incense", "こううんのおこう") },
            { PBEItem.LuckyEgg, new PBELocalizedString("Lucky Egg", "しあわせタマゴ") },
            { PBEItem.LuckyPunch, new PBELocalizedString("Lucky Punch", "ラッキーパンチ") },
            { PBEItem.LumBerry, new PBELocalizedString("Lum Berry", "ラムのみ") },
            { PBEItem.LureBall, new PBELocalizedString("Lure Ball", "ルアーボール") },
            { PBEItem.LustrousOrb, new PBELocalizedString("Lustrous Orb", "しらたま") },
            { PBEItem.LuxuryBall, new PBELocalizedString("Luxury Ball", "ゴージャスボール") },
            { PBEItem.MachoBrace, new PBELocalizedString("Macho Brace", "きょうせいギプス") },
            { PBEItem.Magmarizer, new PBELocalizedString("Magmarizer", "マグマブースター") },
            { PBEItem.Magnet, new PBELocalizedString("Magnet", "じしゃく") },
            { PBEItem.MagoBerry, new PBELocalizedString("Mago Berry", "マゴのみ") },
            { PBEItem.MagostBerry, new PBELocalizedString("Magost Berry", "ゴスのみ") },
            { PBEItem.MasterBall, new PBELocalizedString("Master Ball", "マスターボール") },
            { PBEItem.MaxElixir, new PBELocalizedString("Max Elixir", "ピーピーマックス") },
            { PBEItem.MaxEther, new PBELocalizedString("Max Ether", "ピーピーリカバー") },
            { PBEItem.MaxPotion, new PBELocalizedString("Max Potion", "まんたんのくすり") },
            { PBEItem.MaxRepel, new PBELocalizedString("Max Repel", "ゴールドスプレー") },
            { PBEItem.MaxRevive, new PBELocalizedString("Max Revive", "げんきのかたまり") },
            { PBEItem.MeadowPlate, new PBELocalizedString("Meadow Plate", "みどりのプレート") },
            { PBEItem.MentalHerb, new PBELocalizedString("Mental Herb", "メンタルハーブ") },
            { PBEItem.MetalCoat, new PBELocalizedString("Metal Coat", "メタルコート") },
            { PBEItem.MetalPowder, new PBELocalizedString("Metal Powder", "メタルパウダー") },
            { PBEItem.Metronome, new PBELocalizedString("Metronome", "メトロノーム") },
            { PBEItem.MicleBerry, new PBELocalizedString("Micle Berry", "ミクルのみ") },
            { PBEItem.MindPlate, new PBELocalizedString("Mind Plate", "ふしぎのプレート") },
            { PBEItem.MiracleSeed, new PBELocalizedString("Miracle Seed", "きせきのタネ") },
            { PBEItem.MoomooMilk, new PBELocalizedString("Moomoo Milk", "モーモーミルク") },
            { PBEItem.MoonBall, new PBELocalizedString("Moon Ball", "ムーンボール") },
            { PBEItem.MoonStone, new PBELocalizedString("Moon Stone", "つきのいし") },
            { PBEItem.MuscleBand, new PBELocalizedString("Muscle Band", "ちからのハチマキ") },
            { PBEItem.MuscleWing, new PBELocalizedString("Muscle Wing", "きんりょくのハネ") },
            { PBEItem.MysticWater, new PBELocalizedString("Mystic Water", "しんぴのしずく") },
            { PBEItem.NanabBerry, new PBELocalizedString("Nanab Berry", "ナナのみ") },
            { PBEItem.NestBall, new PBELocalizedString("Nest Ball", "ネストボール") },
            { PBEItem.NetBall, new PBELocalizedString("Net Ball", "ネットボール") },
            { PBEItem.NeverMeltIce, new PBELocalizedString("NeverMeltIce", "とけないこおり") },
            { PBEItem.NomelBerry, new PBELocalizedString("Nomel Berry", "ノメルのみ") },
            { PBEItem.NormalGem, new PBELocalizedString("Normal Gem", "ノーマルジュエル") },
            { PBEItem.Nugget, new PBELocalizedString("Nugget", "きんのたま") },
            { PBEItem.OccaBerry, new PBELocalizedString("Occa Berry", "オッカのみ") },
            { PBEItem.OddIncense, new PBELocalizedString("Odd Incense", "あやしいおこう") },
            { PBEItem.OddKeystone, new PBELocalizedString("Odd Keystone", "かなめいし") },
            { PBEItem.OldAmber, new PBELocalizedString("Old Amber", "ひみつのコハク") },
            { PBEItem.OldGateau, new PBELocalizedString("Old Gateau", "もりのヨウカン") },
            { PBEItem.OranBerry, new PBELocalizedString("Oran Berry", "オレンのみ") },
            { PBEItem.OvalStone, new PBELocalizedString("Oval Stone", "まんまるいし") },
            { PBEItem.PamtreBerry, new PBELocalizedString("Pamtre Berry", "シーヤのみ") },
            { PBEItem.ParalyzeHeal, new PBELocalizedString("Paralyze Heal", "まひなおし") },
            { PBEItem.ParkBall, new PBELocalizedString("Park Ball", "パークボール") },
            { PBEItem.PasshoBerry, new PBELocalizedString("Passho Berry", "イトケのみ") },
            { PBEItem.PassOrb, new PBELocalizedString("Pass Orb", "デルダマ") },
            { PBEItem.PayapaBerry, new PBELocalizedString("Payapa Berry", "ウタンのみ") },
            { PBEItem.Pearl, new PBELocalizedString("Pearl", "しんじゅ") },
            { PBEItem.PearlString, new PBELocalizedString("Pearl String", "おだんごしんじゅ") },
            { PBEItem.PechaBerry, new PBELocalizedString("Pecha Berry", "モモンのみ") },
            { PBEItem.PersimBerry, new PBELocalizedString("Persim Berry", "キーのみ") },
            { PBEItem.PetayaBerry, new PBELocalizedString("Petaya Berry", "ヤタピのみ") },
            { PBEItem.PinapBerry, new PBELocalizedString("Pinap Berry", "パイルのみ") },
            { PBEItem.PinkScarf, new PBELocalizedString("Pink Scarf", "ピンクのバンダナ") },
            { PBEItem.PlumeFossil, new PBELocalizedString("Plume Fossil", "はねのカセキ") },
            { PBEItem.PnkApricorn, new PBELocalizedString("Pnk Apricorn", "ももぼんぐり") },
            { PBEItem.PoisonBarb, new PBELocalizedString("Poison Barb", "どくバリ") },
            { PBEItem.PoisonGem, new PBELocalizedString("Poison Gem", "どくのジュエル") },
            { PBEItem.PokeBall, new PBELocalizedString("Poké Ball", "モンスターボール") },
            { PBEItem.PokeDoll, new PBELocalizedString("Poké Doll", "ピッピにんぎょう") },
            { PBEItem.PokeToy, new PBELocalizedString("Poké Toy", "ポケじゃらし") },
            { PBEItem.PomegBerry, new PBELocalizedString("Pomeg Berry", "ザロクのみ") },
            { PBEItem.Potion, new PBELocalizedString("Potion", "キズぐすり") },
            { PBEItem.PowerAnklet, new PBELocalizedString("Power Anklet", "パワーアンクル") },
            { PBEItem.PowerBand, new PBELocalizedString("Power Band", "パワーバンド") },
            { PBEItem.PowerBelt, new PBELocalizedString("Power Belt", "パワーベルト") },
            { PBEItem.PowerBracer, new PBELocalizedString("Power Bracer", "パワーリスト") },
            { PBEItem.PowerHerb, new PBELocalizedString("Power Herb", "パワフルハーブ") },
            { PBEItem.PowerLens, new PBELocalizedString("Power Lens", "パワーレンズ") },
            { PBEItem.PowerWeight, new PBELocalizedString("Power Weight", "パワーウエイト") },
            { PBEItem.PPMax, new PBELocalizedString("PP Max", "ポイントマックス") },
            { PBEItem.PPUp, new PBELocalizedString("PP Up", "ポイントアップ") },
            { PBEItem.PremierBall, new PBELocalizedString("Premier Ball", "プレミアボール") },
            { PBEItem.PrettyWing, new PBELocalizedString("Pretty Wing", "きれいなハネ") },
            { PBEItem.PrismScale, new PBELocalizedString("Prism Scale", "きれいなウロコ") },
            { PBEItem.Protector, new PBELocalizedString("Protector", "プロテクター") },
            { PBEItem.Protein, new PBELocalizedString("Protein", "タウリン") },
            { PBEItem.PsychicGem, new PBELocalizedString("Psychic Gem", "エスパージュエル") },
            { PBEItem.PureIncense, new PBELocalizedString("Pure Incense", "きよめのおこう") },
            { PBEItem.QualotBerry, new PBELocalizedString("Qualot Berry", "タポルのみ") },
            { PBEItem.QuickBall, new PBELocalizedString("Quick Ball", "クイックボール") },
            { PBEItem.QuickClaw, new PBELocalizedString("Quick Claw", "せんせいのツメ") },
            { PBEItem.QuickPowder, new PBELocalizedString("Quick Powder", "スピードパウダー") },
            { PBEItem.RabutaBerry, new PBELocalizedString("Rabuta Berry", "ラブタのみ") },
            { PBEItem.RageCandyBar, new PBELocalizedString("Rage Candy Bar", "いかりまんじゅう") },
            { PBEItem.RareBone, new PBELocalizedString("Rare Bone", "きちょうなホネ") },
            { PBEItem.RareCandy, new PBELocalizedString("Rare Candy", "ふしぎなアメ") },
            { PBEItem.RawstBerry, new PBELocalizedString("Rawst Berry", "チーゴのみ") },
            { PBEItem.RazorClaw, new PBELocalizedString("Razor Claw", "するどいツメ") },
            { PBEItem.RazorFang, new PBELocalizedString("Razor Fang", "するどいキバ") },
            { PBEItem.RazzBerry, new PBELocalizedString("Razz Berry", "ズリのみ") },
            { PBEItem.ReaperCloth, new PBELocalizedString("Reaper Cloth", "れいかいのぬの") },
            { PBEItem.RedApricorn, new PBELocalizedString("Red Apricorn", "あかぼんぐり") },
            { PBEItem.RedCard, new PBELocalizedString("Red Card", "レッドカード") },
            { PBEItem.RedFlute, new PBELocalizedString("Red Flute", "あかいビードロ") },
            { PBEItem.RedScarf, new PBELocalizedString("Red Scarf", "あかいバンダナ") },
            { PBEItem.RedShard, new PBELocalizedString("Red Shard", "あかいかけら") },
            { PBEItem.RelicBand, new PBELocalizedString("Relic Band", "こだいのうでわ") },
            { PBEItem.RelicCopper, new PBELocalizedString("Relic Copper", "こだいのどうか") },
            { PBEItem.RelicCrown, new PBELocalizedString("Relic Crown", "こだいのおうかん") },
            { PBEItem.RelicGold, new PBELocalizedString("Relic Gold", "こだいのきんか") },
            { PBEItem.RelicSilver, new PBELocalizedString("Relic Silver", "こだいのぎんか") },
            { PBEItem.RelicStatue, new PBELocalizedString("Relic Statue", "こだいのせきぞう") },
            { PBEItem.RelicVase, new PBELocalizedString("Relic Vase", "こだいのツボ") },
            { PBEItem.RepeatBall, new PBELocalizedString("Repeat Ball", "リピートボール") },
            { PBEItem.Repel, new PBELocalizedString("Repel", "むしよけスプレー") },
            { PBEItem.ReplyMail, new PBELocalizedString("Reply Mail", "おかえしメール") },
            { PBEItem.ResistWing, new PBELocalizedString("Resist Wing", "ていこうのハネ") },
            { PBEItem.RevivalHerb, new PBELocalizedString("Revival Herb", "ふっかつそう") },
            { PBEItem.Revive, new PBELocalizedString("Revive", "げんきのかけら") },
            { PBEItem.RindoBerry, new PBELocalizedString("Rindo Berry", "リンドのみ") },
            { PBEItem.RingTarget, new PBELocalizedString("Ring Target", "ねらいのまと") },
            { PBEItem.RockGem, new PBELocalizedString("Rock Gem", "いわのジュエル") },
            { PBEItem.RockIncense, new PBELocalizedString("Rock Incense", "がんせきおこう") },
            { PBEItem.RockyHelmet, new PBELocalizedString("Rocky Helmet", "ゴツゴツメット") },
            { PBEItem.RootFossil, new PBELocalizedString("Root Fossil", "ねっこのカセキ") },
            { PBEItem.RoseIncense, new PBELocalizedString("Rose Incense", "おはなのおこう") },
            { PBEItem.RowapBerry, new PBELocalizedString("Rowap Berry", "レンブのみ") },
            { PBEItem.RSVPMail, new PBELocalizedString("RSVP Mail", "おさそいメール") },
            { PBEItem.SacredAsh, new PBELocalizedString("Sacred Ash", "せいなるはい") },
            { PBEItem.SafariBall, new PBELocalizedString("Safari Ball", "サファリボール") },
            { PBEItem.SalacBerry, new PBELocalizedString("Salac Berry", "カムラのみ") },
            { PBEItem.ScopeLens, new PBELocalizedString("Scope Lens", "ピントレンズ") },
            { PBEItem.SeaIncense, new PBELocalizedString("Sea Incense", "うしおのおこう") },
            { PBEItem.SharpBeak, new PBELocalizedString("Sharp Beak", "するどいくちばし") },
            { PBEItem.ShedShell, new PBELocalizedString("Shed Shell", "きれいなぬけがら") },
            { PBEItem.ShellBell, new PBELocalizedString("Shell Bell", "かいがらのすず") },
            { PBEItem.ShinyStone, new PBELocalizedString("Shiny Stone", "ひかりのいし") },
            { PBEItem.ShoalSalt, new PBELocalizedString("Shoal Salt", "あさせのしお") },
            { PBEItem.ShoalShell, new PBELocalizedString("Shoal Shell", "あさせのかいがら") },
            { PBEItem.ShockDrive, new PBELocalizedString("Shock Drive", "イナズマカセット") },
            { PBEItem.ShucaBerry, new PBELocalizedString("Shuca Berry", "シュカのみ") },
            { PBEItem.SilkScarf, new PBELocalizedString("Silk Scarf", "シルクのスカーフ") },
            { PBEItem.SilverPowder, new PBELocalizedString("SilverPowder", "ぎんのこな") },
            { PBEItem.SitrusBerry, new PBELocalizedString("Sitrus Berry", "オボンのみ") },
            { PBEItem.SkullFossil, new PBELocalizedString("Skull Fossil", "ずがいのカセキ") },
            { PBEItem.SkyPlate, new PBELocalizedString("Sky Plate", "あおぞらプレート") },
            { PBEItem.SmokeBall, new PBELocalizedString("Smoke Ball", "けむりだま") },
            { PBEItem.SmoothRock, new PBELocalizedString("Smooth Rock", "さらさらいわ") },
            { PBEItem.SodaPop, new PBELocalizedString("Soda Pop", "サイコソーダ") },
            { PBEItem.SoftSand, new PBELocalizedString("Soft Sand", "やわらかいすな") },
            { PBEItem.SootheBell, new PBELocalizedString("Soothe Bell", "やすらぎのすず") },
            { PBEItem.SoulDew, new PBELocalizedString("Soul Dew", "こころのしずく") },
            { PBEItem.SpellTag, new PBELocalizedString("Spell Tag", "のろいのおふだ") },
            { PBEItem.SpelonBerry, new PBELocalizedString("Spelon Berry", "ノワキのみ") },
            { PBEItem.SplashPlate, new PBELocalizedString("Splash Plate", "しずくプレート") },
            { PBEItem.SpookyPlate, new PBELocalizedString("Spooky Plate", "もののけプレート") },
            { PBEItem.SportBall, new PBELocalizedString("Sport Ball", "コンペボール") },
            { PBEItem.StableMulch, new PBELocalizedString("Stable Mulch", "ながながこやし") },
            { PBEItem.Stardust, new PBELocalizedString("Stardust", "ほしのすな") },
            { PBEItem.StarfBerry, new PBELocalizedString("Starf Berry", "スターのみ") },
            { PBEItem.StarPiece, new PBELocalizedString("Star Piece", "ほしのかけら") },
            { PBEItem.SteelGem, new PBELocalizedString("Steel Gem", "はがねのジュエル") },
            { PBEItem.Stick, new PBELocalizedString("Stick", "ながねぎ") },
            { PBEItem.StickyBarb, new PBELocalizedString("Sticky Barb", "くっつきバリ") },
            { PBEItem.StonePlate, new PBELocalizedString("Stone Plate", "がんせきプレート") },
            { PBEItem.SunStone, new PBELocalizedString("Sun Stone", "たいようのいし") },
            { PBEItem.SuperPotion, new PBELocalizedString("Super Potion", "いいキズぐすり") },
            { PBEItem.SuperRepel, new PBELocalizedString("Super Repel", "シルバースプレー") },
            { PBEItem.SweetHeart, new PBELocalizedString("Sweet Heart", "ハートスイーツ") },
            { PBEItem.SwiftWing, new PBELocalizedString("Swift Wing", "しゅんぱつのハネ") },
            { PBEItem.TamatoBerry, new PBELocalizedString("Tamato Berry", "マトマのみ") },
            { PBEItem.TangaBerry, new PBELocalizedString("Tanga Berry", "タンガのみ") },
            { PBEItem.ThanksMail, new PBELocalizedString("Thanks Mail", "かんしゃメール") },
            { PBEItem.ThickClub, new PBELocalizedString("Thick Club", "ふといホネ") },
            { PBEItem.Thunderstone, new PBELocalizedString("Thunderstone", "かみなりのいし") },
            { PBEItem.TimerBall, new PBELocalizedString("Timer Ball", "タイマーボール") },
            { PBEItem.TinyMushroom, new PBELocalizedString("TinyMushroom", "ちいさなキノコ") },
            { PBEItem.ToxicOrb, new PBELocalizedString("Toxic Orb", "どくどくだま") },
            { PBEItem.ToxicPlate, new PBELocalizedString("Toxic Plate", "もうどくプレート") },
            { PBEItem.TwistedSpoon, new PBELocalizedString("TwistedSpoon", "まがったスプーン") },
            { PBEItem.UltraBall, new PBELocalizedString("Ultra Ball", "ハイパーボール") },
            { PBEItem.UpGrade, new PBELocalizedString("Up-Grade", "アップグレード") },
            { PBEItem.WacanBerry, new PBELocalizedString("Wacan Berry", "ソクノのみ") },
            { PBEItem.WaterGem, new PBELocalizedString("Water Gem", "みずのジュエル") },
            { PBEItem.WaterStone, new PBELocalizedString("Water Stone", "みずのいし") },
            { PBEItem.WatmelBerry, new PBELocalizedString("Watmel Berry", "カイスのみ") },
            { PBEItem.WaveIncense, new PBELocalizedString("Wave Incense", "さざなみのおこう") },
            { PBEItem.WepearBerry, new PBELocalizedString("Wepear Berry", "セシナのみ") },
            { PBEItem.WhiteFlute, new PBELocalizedString("White Flute", "しろいビードロ") },
            { PBEItem.WhiteHerb, new PBELocalizedString("White Herb", "しろいハーブ") },
            { PBEItem.WhtApricorn, new PBELocalizedString("Wht Apricorn", "しろぼんぐり") },
            { PBEItem.WideLens, new PBELocalizedString("Wide Lens", "こうかくレンズ") },
            { PBEItem.WikiBerry, new PBELocalizedString("Wiki Berry", "ウイのみ") },
            { PBEItem.WiseGlasses, new PBELocalizedString("Wise Glasses", "ものしりメガネ") },
            { PBEItem.XAccuracy, new PBELocalizedString("X Accuracy", "ヨクアタール") },
            { PBEItem.XAttack, new PBELocalizedString("X Attack", "プラスパワー") },
            { PBEItem.XDefend, new PBELocalizedString("X Defend", "ディフェンダー") },
            { PBEItem.XSpDef, new PBELocalizedString("X Sp. Def", "スペシャルガード") },
            { PBEItem.XSpecial, new PBELocalizedString("X Special", "スペシャルアップ") },
            { PBEItem.XSpeed, new PBELocalizedString("X Speed", "スピーダー") },
            { PBEItem.YacheBerry, new PBELocalizedString("Yache Berry", "ヤチェのみ") },
            { PBEItem.YellowFlute, new PBELocalizedString("Yellow Flute", "きいろビードロ") },
            { PBEItem.YellowScarf, new PBELocalizedString("Yellow Scarf", "きいろのバンダナ") },
            { PBEItem.YellowShard, new PBELocalizedString("Yellow Shard", "きいろいかけら") },
            { PBEItem.YlwApricorn, new PBELocalizedString("Ylw Apricorn", "きぼんぐり") },
            { PBEItem.ZapPlate, new PBELocalizedString("Zap Plate", "いかずちプレート") },
            { PBEItem.Zinc, new PBELocalizedString("Zinc", "キトサン") },
            { PBEItem.ZoomLens, new PBELocalizedString("Zoom Lens", "フォーカスレンズ") }
        });
    }
}
