using Kermalis.PokemonBattleEngine.Data;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Kermalis.PokemonBattleEngine.Localization
{
    public static class PBEItemLocalization
    {
        public static ReadOnlyDictionary<PBEItem, PBELocalizedString> Names { get; } = new ReadOnlyDictionary<PBEItem, PBELocalizedString>(new Dictionary<PBEItem, PBELocalizedString>()
        {
            { PBEItem.None, new PBELocalizedString("--", "--", "--", "--", "--", "--", "--") },
            { PBEItem.AbsorbBulb, new PBELocalizedString("きゅうこん", "구근", "Bulbe", "Knolle", "Tubérculo", "Bulbo", "Absorb Bulb") },
            { PBEItem.AdamantOrb, new PBELocalizedString("こんごうだま", "금강옥", "Orbe Adamant", "Adamant-Orb", "Diamansfera", "Adamasfera", "Adamant Orb") },
            { PBEItem.AguavBerry, new PBELocalizedString("バンジのみ", "아바열매", "Baie Gowav", "Gauvebeere", "Baya Guaya", "Baccaguava", "Aguav Berry") },
            { PBEItem.AirBalloon, new PBELocalizedString("ふうせん", "풍선", "Ballon", "Luftballon", "Globo Helio", "Palloncino", "Air Balloon") },
            { PBEItem.AmuletCoin, new PBELocalizedString("おまもりこばん", "부적금화", "Pièce Rune", "Münzamulett", "Mon. Amuleto", "Monetamuleto", "Amulet Coin") },
            { PBEItem.Antidote, new PBELocalizedString("どくけし", "해독제", "Antidote", "Gegengift", "Antídoto", "Antidoto", "Antidote") },
            { PBEItem.ApicotBerry, new PBELocalizedString("ズアのみ", "규살열매", "Baie Abriko", "Apikobeere", "Baya Aricoc", "Baccacocca", "Apicot Berry") },
            { PBEItem.ArmorFossil, new PBELocalizedString("たてのカセキ", "방패의화석", "Foss. Armure", "Panzerfossil", "Fósil Coraza", "Fossilscudo", "Armor Fossil") },
            { PBEItem.AspearBerry, new PBELocalizedString("ナナシのみ", "배리열매", "Baie Willia", "Wilbirbeere", "Baya Perasi", "Baccaperina", "Aspear Berry") },
            { PBEItem.Awakening, new PBELocalizedString("ねむけざまし", "잠깨는약", "Réveil", "Aufwecker", "Despertar", "Sveglia", "Awakening") },
            { PBEItem.BabiriBerry, new PBELocalizedString("リリバのみ", "바리비열매", "Baie Babiri", "Babiribeere", "Baya Baribá", "Baccababiri", "Babiri Berry") },
            { PBEItem.BalmMushroom, new PBELocalizedString("かおるキノコ", "향기버섯", "Champi Suave", "Duftpilz", "Seta Aroma", "Profumfungo", "BalmMushroom") },
            { PBEItem.BelueBerry, new PBELocalizedString("ベリブのみ", "루베열매", "Baie Myrte", "Myrtilbeere", "Baya Andano", "Baccartillo", "Belue Berry") },
            { PBEItem.BerryJuice, new PBELocalizedString("きのみジュース", "나무열매쥬스", "Jus de Baie", "Beerensaft", "Zumo de Baya", "Succodibacca", "Berry Juice") },
            { PBEItem.BigMushroom, new PBELocalizedString("おおきなキノコ", "큰버섯", "Gros Champi", "Riesenpilz", "Seta Grande", "Grande Fungo", "Big Mushroom") },
            { PBEItem.BigNugget, new PBELocalizedString("でかいきんのたま", "큰금구슬", "Maxi Pépite", "Riesennugget", "Maxipepita", "Granpepita", "Big Nugget") },
            { PBEItem.BigPearl, new PBELocalizedString("おおきなしんじゅ", "큰진주", "Grande Perle", "Riesenperle", "Perla Grande", "Grande Perla", "Big Pearl") },
            { PBEItem.BigRoot, new PBELocalizedString("おおきなねっこ", "큰뿌리", "Grosseracine", "Großwurzel", "Raíz Grande", "Granradice", "Big Root") },
            { PBEItem.BindingBand, new PBELocalizedString("しめつけバンド", "조임밴드", "B. Étreinte", "Klammerband", "Ban. Atadura", "Legafascia", "Binding Band") },
            { PBEItem.BlackBelt, new PBELocalizedString("くろおび", "검은띠", "Ceint.Noire", "Schwarzgurt", "Cinturón Negro", "Cinturanera", "Black Belt") },
            { PBEItem.BlackFlute, new PBELocalizedString("くろいビードロ", "검정비드로", "Flûte Noire", "Schwarze Flöte", "Flauta Negra", "Flauto Nero", "Black Flute") },
            { PBEItem.BlackGlasses, new PBELocalizedString("くろいメガネ", "검은안경", "Lunet.Noires", "Schattenglas", "Gafas de Sol", "Occhialineri", "BlackGlasses") },
            { PBEItem.BlackSludge, new PBELocalizedString("くろいヘドロ", "검은진흙", "Boue Noire", "Giftschleim", "Lodo Negro", "Fangopece", "Black Sludge") },
            { PBEItem.BlkApricorn, new PBELocalizedString("くろぼんぐり", "검은규토리", "Noigrume Noir", "Aprikoko Swz", "Bonguri Neg", "Ghic. Nera", "Blk Apricorn") },
            { PBEItem.BluApricorn, new PBELocalizedString("あおぼんぐり", "파란규토리", "Noigrume Bleu", "Aprikoko Blu", "Bonguri Azu", "Ghic. Blu", "Blu Apricorn") },
            { PBEItem.BlueFlute, new PBELocalizedString("あおいビードロ", "파랑비드로", "Flûte Bleue", "Blaue Flöte", "Flauta Azul", "Flauto Blu", "Blue Flute") },
            { PBEItem.BlueScarf, new PBELocalizedString("あおいバンダナ", "파랑밴드", "Foulard Bleu", "Blauer Schal", "Pañuelo Azul", "Fascia Blu", "Blue Scarf") },
            { PBEItem.BlueShard, new PBELocalizedString("あおいかけら", "파랑조각", "Tesson Bleu", "Indigostück", "Parte Azul", "Coccio Blu", "Blue Shard") },
            { PBEItem.BlukBerry, new PBELocalizedString("ブリーのみ", "블리열매", "Baie Remu", "Morbbeere", "Baya Oram", "Baccamora", "Bluk Berry") },
            { PBEItem.BridgeMailD, new PBELocalizedString("ブリッジメールＨ", "브리지메일M", "Lettre Pont Y", "Brückbrief M", "Carta Puente F", "Mess. Libec.", "Bridge Mail D") },
            { PBEItem.BridgeMailM, new PBELocalizedString("ブリッジメールＷ", "브리지메일W", "Lettre Pont I", "Brückbrief W", "Carta Puente P", "Mess. Merav.", "Bridge Mail M") },
            { PBEItem.BridgeMailS, new PBELocalizedString("ブリッジメールＳ", "브리지메일S", "Lettre Pont S", "Brückbrief H", "Carta Puente S", "Mess. Frec.", "Bridge Mail S") },
            { PBEItem.BridgeMailT, new PBELocalizedString("ブリッジメールＣ", "브리지메일C", "Lettre Pont F", "Brückbrief Z", "Carta Puente A", "Mess. Prop.", "Bridge Mail T") },
            { PBEItem.BridgeMailV, new PBELocalizedString("ブリッジメールＶ", "브리지메일V", "Lettre Pont H", "Brückbrief D", "Carta Puente V", "Mess. Vill.", "Bridge Mail V") },
            { PBEItem.BrightPowder, new PBELocalizedString("ひかりのこな", "반짝가루", "Poudreclaire", "Blendpuder", "Polvo Brillo", "Luminpolvere", "BrightPowder") },
            { PBEItem.BugGem, new PBELocalizedString("むしのジュエル", "벌레주얼", "Joyau Insect", "Käferjuwel", "G. Bicho", "Bijoucoleot.", "Bug Gem") },
            { PBEItem.BurnDrive, new PBELocalizedString("ブレイズカセット", "블레이즈카세트", "Module Pyro", "Flammenmodul", "PiroROM", "Piromodulo", "Burn Drive") },
            { PBEItem.BurnHeal, new PBELocalizedString("やけどなおし", "화상치료제", "Anti-Brûle", "Feuerheiler", "Antiquemar", "Antiscottatura", "Burn Heal") },
            { PBEItem.Calcium, new PBELocalizedString("リゾチウム", "리보플라빈", "Calcium", "Kalzium", "Calcio", "Calcio", "Calcium") },
            { PBEItem.Carbos, new PBELocalizedString("インドメタシン", "알칼로이드", "Carbone", "Carbon", "Carburante", "Carburante", "Carbos") },
            { PBEItem.Casteliacone, new PBELocalizedString("ヒウンアイス", "구름아이스", "Glace Volute", "Stratos-Eis", "Porcehelado", "Conostropoli", "Casteliacone") },
            { PBEItem.CellBattery, new PBELocalizedString("じゅうでんち", "충전지", "Pile", "Akku", "Pila", "Ricaripila", "Cell Battery") },
            { PBEItem.Charcoal, new PBELocalizedString("もくたん", "목탄", "Charbon", "Holzkohle", "Carbón", "Carbonella", "Charcoal") },
            { PBEItem.ChartiBerry, new PBELocalizedString("ヨロギのみ", "루미열매", "Baie Charti", "Chiaribeere", "Baya Alcho", "Baccaciofo", "Charti Berry") },
            { PBEItem.CheriBerry, new PBELocalizedString("クラボのみ", "버치열매", "Baie Ceriz", "Amrenabeere", "Baya Zreza", "Baccaliegia", "Cheri Berry") },
            { PBEItem.CherishBall, new PBELocalizedString("プレシャスボール", "프레셔스볼", "Mémoire Ball", "Jubelball", "Gloria Ball", "Pregio Ball", "Cherish Ball") },
            { PBEItem.ChestoBerry, new PBELocalizedString("カゴのみ", "유루열매", "Baie Maron", "Maronbeere", "Baya Atania", "Baccastagna", "Chesto Berry") },
            { PBEItem.ChilanBerry, new PBELocalizedString("ホズのみ", "카리열매", "Baie Zalis", "Latchibeere", "Baya Chilan", "Baccacinlan", "Chilan Berry") },
            { PBEItem.ChillDrive, new PBELocalizedString("フリーズカセット", "프리즈카세트", "Module Cryo", "Gefriermodul", "CrioROM", "Gelomodulo", "Chill Drive") },
            { PBEItem.ChoiceBand, new PBELocalizedString("こだわりハチマキ", "구애머리띠", "Band. Choix", "Wahlband", "Cin. Elegida", "Bendascelta", "Choice Band") },
            { PBEItem.ChoiceScarf, new PBELocalizedString("こだわりスカーフ", "구애스카프", "Mouch. Choix", "Wahlschal", "Pañ. Elegido", "Stolascelta", "Choice Scarf") },
            { PBEItem.ChoiceSpecs, new PBELocalizedString("こだわりメガネ", "구애안경", "Lunet. Choix", "Wahlglas", "Gafas Elegid", "Lentiscelta", "Choice Specs") },
            { PBEItem.ChopleBerry, new PBELocalizedString("ヨプのみ", "로플열매", "Baie Pomroz", "Rospelbeere", "Baya Pomaro", "Baccarosmel", "Chople Berry") },
            { PBEItem.ClawFossil, new PBELocalizedString("ツメのカセキ", "발톱화석", "Foss. Griffe", "Klauenfossil", "Fósil Garra", "Fossilunghia", "Claw Fossil") },
            { PBEItem.CleanseTag, new PBELocalizedString("きよめのおふだ", "순결의부적", "Rune Purif.", "Schutzband", "Amuleto", "Velopuro", "Cleanse Tag") },
            { PBEItem.CleverWing, new PBELocalizedString("せいしんのハネ", "정신력날개", "Aile Mental", "Espritfeder", "P. Mente", "Piumintuito", "Clever Wing") },
            { PBEItem.CobaBerry, new PBELocalizedString("バコウのみ", "바코열매", "Baie Cobaba", "Kobabeere", "Baya Kouba", "Baccababa", "Coba Berry") },
            { PBEItem.ColburBerry, new PBELocalizedString("ナモのみ", "마코열매", "Baie Lampou", "Burleobeere", "Baya Dillo", "Baccaxan", "Colbur Berry") },
            { PBEItem.CometShard, new PBELocalizedString("すいせいのかけら", "혜성조각", "Morc. Comète", "Kometstück", "Frag. Cometa", "Pezzo Cometa", "Comet Shard") },
            { PBEItem.CornnBerry, new PBELocalizedString("モコシのみ", "수숙열매", "Baie Siam", "Saimbeere", "Baya Mais", "Baccavena", "Cornn Berry") },
            { PBEItem.CoverFossil, new PBELocalizedString("ふたのカセキ", "덮개화석", "Foss. Plaque", "Schildfossil", "Fósil Tapa", "Fossiltappo", "Cover Fossil") },
            { PBEItem.CustapBerry, new PBELocalizedString("イバンのみ", "애슈열매", "Baie Chérim", "Eipfelbeere", "Baya Chiri", "Baccacrela", "Custap Berry") },
            { PBEItem.DampMulch, new PBELocalizedString("じめじめこやし", "축축이비료", "Fertihumide", "Feuchtmulch", "Abono Lento", "Fertilidro", "Damp Mulch") },
            { PBEItem.DampRock, new PBELocalizedString("しめったいわ", "축축한바위", "Roche Humide", "Nassbrocken", "Roca Lluvia", "Rocciaumida", "Damp Rock") },
            { PBEItem.DarkGem, new PBELocalizedString("あくのジュエル", "악주얼", "Joyau Ténèbr", "Unlichtjuwel", "G. Siniestra", "Bijoubuio", "Dark Gem") },
            { PBEItem.DawnStone, new PBELocalizedString("めざめいし", "각성의돌", "Pierre Aube", "Funkelstein", "Piedra Alba", "Pietralbore", "Dawn Stone") },
            { PBEItem.DeepSeaScale, new PBELocalizedString("しんかいのウロコ", "심해의비늘", "Écailleocéan", "Abyssplatte", "Escama Marina", "Squamabissi", "DeepSeaScale") },
            { PBEItem.DeepSeaTooth, new PBELocalizedString("しんかいのキバ", "심해의이빨", "Dent Océan", "Abysszahn", "Diente Marino", "Denteabissi", "DeepSeaTooth") },
            { PBEItem.DestinyKnot, new PBELocalizedString("あかいいと", "빨간실", "Nœud Destin", "Fatumknoten", "Lazo Destino", "Destincomune", "Destiny Knot") },
            { PBEItem.DireHit, new PBELocalizedString("クリティカッター", "크리티컬커터", "Muscle +", "Angriffplus", "Directo", "Supercolpo", "Dire Hit") },
            { PBEItem.DiveBall, new PBELocalizedString("ダイブボール", "다이브볼", "Scuba Ball", "Tauchball", "Buceo Ball", "Sub Ball", "Dive Ball") },
            { PBEItem.DomeFossil, new PBELocalizedString("こうらのカセキ", "껍질화석", "Fossile Dome", "Domfossil", "Fósil Domo", "Domofossile", "Dome Fossil") },
            { PBEItem.DouseDrive, new PBELocalizedString("アクアカセット", "아쿠아카세트", "Module Aqua", "Aquamodul", "HidroROM", "Idromodulo", "Douse Drive") },
            { PBEItem.DracoPlate, new PBELocalizedString("りゅうのプレート", "용의플레이트", "Plaque Draco", "Dracotafel", "Tabla Draco", "Lastradrakon", "Draco Plate") },
            { PBEItem.DragonFang, new PBELocalizedString("りゅうのキバ", "용의이빨", "Croc Dragon", "Drachenzahn", "Colmillodrag", "Dentedidrago", "Dragon Fang") },
            { PBEItem.DragonGem, new PBELocalizedString("ドラゴンジュエル", "드래곤주얼", "Joyau Dragon", "Drakojuwel", "G. Dragón", "Bijoudrago", "Dragon Gem") },
            { PBEItem.DragonScale, new PBELocalizedString("りゅうのウロコ", "용의비늘", "Ecailledraco", "Drachenhaut", "Escama Dragón", "Squama Drago", "Dragon Scale") },
            { PBEItem.DreadPlate, new PBELocalizedString("こわもてプレート", "공포플레이트", "Plaque Ombre", "Furchttafel", "Tabla Oscura", "Lastratimore", "Dread Plate") },
            { PBEItem.DreamBall, new PBELocalizedString("ドリームボール", "드림볼", "Rêve Ball", "Traumball", "Ensueño Ball", "Dream Ball", "Dream Ball") },
            { PBEItem.DubiousDisc, new PBELocalizedString("あやしいパッチ", "괴상한패치", "CD Douteux", "Dubiosdisc", "Disco Extraño", "Dubbiodisco", "Dubious Disc") },
            { PBEItem.DurinBerry, new PBELocalizedString("ドリのみ", "두리열매", "Baie Durin", "Durinbeere", "Baya Rudion", "Baccadurian", "Durin Berry") },
            { PBEItem.DuskBall, new PBELocalizedString("ダークボール", "다크볼", "Sombre Ball", "Finsterball", "Ocaso Ball", "Scuro Ball", "Dusk Ball") },
            { PBEItem.DuskStone, new PBELocalizedString("やみのいし", "어둠의돌", "Pierre Nuit", "Finsterstein", "Piedra Noche", "Neropietra", "Dusk Stone") },
            { PBEItem.EarthPlate, new PBELocalizedString("だいちのプレート", "대지플레이트", "Plaque Terre", "Erdtafel", "Tabla Terrax", "Lastrageo", "Earth Plate") },
            { PBEItem.EjectButton, new PBELocalizedString("だっしゅつボタン", "탈출버튼", "Bouton Fuite", "Fluchtknopf", "Botón Escape", "Pulsantefuga", "Eject Button") },
            { PBEItem.Electirizer, new PBELocalizedString("エレキブースター", "에레키부스터", "Électriseur", "Stromisierer", "Electrizador", "Elettritore", "Electirizer") },
            { PBEItem.ElectricGem, new PBELocalizedString("でんきのジュエル", "전기주얼", "Joyau Électrik", "Elektrojuwel", "G. Eléctrica", "Bijouelettro", "Electric Gem") },
            { PBEItem.Elixir, new PBELocalizedString("ピーピーエイダー", "PP에이더", "Élixir", "Elixier", "Elixir", "Elisir", "Elixir") },
            { PBEItem.EnergyPowder, new PBELocalizedString("ちからのこな", "힘의가루", "Poudrénergie", "Energiestaub", "Polvoenergía", "Polvenergia", "EnergyPowder") },
            { PBEItem.EnergyRoot, new PBELocalizedString("ちからのねっこ", "힘의뿌리", "Racinénergie", "Kraftwurzel", "Raíz Energía", "Radicenergia", "Energy Root") },
            { PBEItem.EnigmaBerry, new PBELocalizedString("ナゾのみ", "의문열매", "Baie Enigma", "Enigmabeere", "Baya Enigma", "Baccaenigma", "Enigma Berry") },
            { PBEItem.EscapeRope, new PBELocalizedString("あなぬけのヒモ", "동굴탈출로프", "Corde Sortie", "Fluchtseil", "Cuerda Huida", "Fune di Fuga", "Escape Rope") },
            { PBEItem.Ether, new PBELocalizedString("ピーピーエイド", "PP에이드", "Huile", "Äther", "Éter", "Etere", "Ether") },
            { PBEItem.Everstone, new PBELocalizedString("かわらずのいし", "변함없는돌", "Pierre Stase", "Ewigstein", "Piedraeterna", "Pietrastante", "Everstone") },
            { PBEItem.Eviolite, new PBELocalizedString("しんかのきせき", "진화의휘석", "Évoluroc", "Evolith", "Mineral Evol", "Evolcondensa", "Eviolite") },
            { PBEItem.ExpertBelt, new PBELocalizedString("たつじんのおび", "달인의띠", "Ceinture Pro", "Expertengurt", "Cinta Experto", "Abilcintura", "Expert Belt") },
            { PBEItem.ExpShare, new PBELocalizedString("がくしゅうそうち", "학습장치", "Multi Exp", "EP-Teiler", "Repartir Exp", "Condiv. Esp.", "Exp. Share") },
            { PBEItem.FastBall, new PBELocalizedString("スピードボール", "스피드볼", "Speed Ball", "Turboball", "Rapid Ball", "Rapid Ball", "Fast Ball") },
            { PBEItem.FavoredMail, new PBELocalizedString("だいすきメール", "애호메일", "Lettre Fan", "Faiblebrief", "Carta Favoritos", "Messaggio TVB", "Favored Mail") },
            { PBEItem.FightingGem, new PBELocalizedString("かくとうジュエル", "격투주얼", "Joyau Combat", "Kampfjuwel", "G. Lucha", "Bijoulotta", "Fighting Gem") },
            { PBEItem.FigyBerry, new PBELocalizedString("フィラのみ", "무화열매", "Baie Figuy", "Giefebeere", "Baya Higog", "Baccafico", "Figy Berry") },
            { PBEItem.FireGem, new PBELocalizedString("ほのおのジュエル", "불꽃주얼", "Joyau Feu", "Feuerjuwel", "G. Fuego", "Bijoufuoco", "Fire Gem") },
            { PBEItem.FireStone, new PBELocalizedString("ほのおのいし", "불꽃의돌", "Pierre Feu", "Feuerstein", "Piedra Fuego", "Pietrafocaia", "Fire Stone") },
            { PBEItem.FistPlate, new PBELocalizedString("こぶしのプレート", "주먹플레이트", "Plaque Poing", "Fausttafel", "Tabla Fuerte", "Lastrapugno", "Fist Plate") },
            { PBEItem.FlameOrb, new PBELocalizedString("かえんだま", "화염구슬", "Orbe Flamme", "Heiß-Orb", "Llamasfera", "Fiammosfera", "Flame Orb") },
            { PBEItem.FlamePlate, new PBELocalizedString("ひのたまプレート", "불구슬플레이트", "Plaque Flamme", "Feuertafel", "Tabla Llama", "Lastrarogo", "Flame Plate") },
            { PBEItem.FloatStone, new PBELocalizedString("かるいし", "가벼운돌", "Pierrallégée", "Leichtstein", "Piedra Pómez", "Pietralieve", "Float Stone") },
            { PBEItem.FluffyTail, new PBELocalizedString("エネコのシッポ", "에나비꼬리", "Queue Skitty", "Eneco-Rute", "Cola Skitty", "Coda Skitty", "Fluffy Tail") },
            { PBEItem.FlyingGem, new PBELocalizedString("ひこうのジュエル", "비행주얼", "Joyau Vol", "Flugjuwel", "G. Voladora", "Bijouvolante", "Flying Gem") },
            { PBEItem.FocusBand, new PBELocalizedString("きあいのハチマキ", "기합의머리띠", "Bandeau", "Fokus-Band", "Cinta Focus", "Bandana", "Focus Band") },
            { PBEItem.FocusSash, new PBELocalizedString("きあいのタスキ", "기합의띠", "Ceint. Force", "Fokusgurt", "Banda Focus", "Focalnastro", "Focus Sash") },
            { PBEItem.FreshWater, new PBELocalizedString("おいしいみず", "맛있는물", "Eau Fraîche", "Tafelwasser", "Agua Fresca", "Acqua Fresca", "Fresh Water") },
            { PBEItem.FriendBall, new PBELocalizedString("フレンドボール", "프렌드볼", "Copain Ball", "Freundesball", "Amigo Ball", "Friend Ball", "Friend Ball") },
            { PBEItem.FullHeal, new PBELocalizedString("なんでもなおし", "만병통치제", "Total Soin", "Hyperheiler", "Restau. Todo", "Cura Totale", "Full Heal") },
            { PBEItem.FullIncense, new PBELocalizedString("まんぷくおこう", "만복향로", "Encens Plein", "Lahmrauch", "Incie. Lento", "Gonfioaroma", "Full Incense") },
            { PBEItem.FullRestore, new PBELocalizedString("かいふくのくすり", "회복약", "Guérison", "Top-Genesung", "Restaurar Todo", "Ricarica Totale", "Full Restore") },
            { PBEItem.GanlonBerry, new PBELocalizedString("リュガのみ", "용아열매", "Baie Lingan", "Linganbeere", "Baya Gonlan", "Baccalongan", "Ganlon Berry") },
            { PBEItem.GeniusWing, new PBELocalizedString("ちりょくのハネ", "지력날개", "Aile Esprit", "Geniefeder", "P. Intelecto", "Piumingegno", "Genius Wing") },
            { PBEItem.GhostGem, new PBELocalizedString("ゴーストジュエル", "고스트주얼", "Joyau Spectr", "Geistjuwel", "G. Fantasma", "Bijouspettro", "Ghost Gem") },
            { PBEItem.GooeyMulch, new PBELocalizedString("ねばねばこやし", "끈적끈적비료", "Fertiglu", "Neumulch", "Abono Brote", "Fertilcolla", "Gooey Mulch") },
            { PBEItem.GrassGem, new PBELocalizedString("くさのジュエル", "풀주얼", "Joyau Plante", "Pflanzjuwel", "G. Planta", "Bijouerba", "Grass Gem") },
            { PBEItem.GreatBall, new PBELocalizedString("スーパーボール", "수퍼볼", "Super Ball", "Superball", "Super Ball", "Mega Ball", "Great Ball") },
            { PBEItem.GreenScarf, new PBELocalizedString("みどりのバンダナ", "초록밴드", "Foulard Vert", "Grüner Schal", "Pañuelo Verde", "Fascia Verde", "Green Scarf") },
            { PBEItem.GreenShard, new PBELocalizedString("みどりのかけら", "초록조각", "Tesson Vert", "Grünstück", "Parte Verde", "Coccio Verde", "Green Shard") },
            { PBEItem.GreetMail, new PBELocalizedString("はじめてメール", "첫메일", "Lettre Salut", "Grußbrief", "Carta Inicial", "Messaggio Inizio", "Greet Mail") },
            { PBEItem.GrepaBerry, new PBELocalizedString("ウブのみ", "또뽀열매", "Baie Résin", "Labrusbeere", "Baya Uvav", "Baccauva", "Grepa Berry") },
            { PBEItem.GripClaw, new PBELocalizedString("ねばりのかぎづめ", "끈기갈고리손톱", "Accro Griffe", "Griffklaue", "Garra Garfio", "Presartigli", "Grip Claw") },
            { PBEItem.GriseousOrb, new PBELocalizedString("はっきんだま", "백금옥", "Orbe Platiné", "Platinum-Orb", "Griseosfera", "Grigiosfera", "Griseous Orb") },
            { PBEItem.GrnApricorn, new PBELocalizedString("みどぼんぐり", "초록규토리", "Noigrume Vert", "Aprikoko Grn", "Bonguri Ver", "Ghic. Verde", "Grn Apricorn") },
            { PBEItem.GroundGem, new PBELocalizedString("じめんのジュエル", "땅주얼", "Joyau Sol", "Bodenjuwel", "G. Tierra", "Bijouterra", "Ground Gem") },
            { PBEItem.GrowthMulch, new PBELocalizedString("すくすくこやし", "무럭무럭비료", "Fertipousse", "Wachsmulch", "Abono Rápido", "Fertilrapido", "Growth Mulch") },
            { PBEItem.GuardSpec, new PBELocalizedString("エフェクトガード", "이펙트가드", "Défense Spéciale", "Megablock", "Protec. Especial", "Superguardia", "Guard Spec.") },
            { PBEItem.HabanBerry, new PBELocalizedString("ハバンのみ", "하반열매", "Baie Fraigo", "Terirobeere", "Baya Anjiro", "Baccahaban", "Haban Berry") },
            { PBEItem.HardStone, new PBELocalizedString("かたいいし", "딱딱한돌", "Pierre Dure", "Granitstein", "Piedra Dura", "Pietradura", "Hard Stone") },
            { PBEItem.HealBall, new PBELocalizedString("ヒールボール", "힐볼", "Soin Ball", "Heilball", "Sana Ball", "Cura Ball", "Heal Ball") },
            { PBEItem.HealPowder, new PBELocalizedString("ばんのうごな", "만능가루", "Poudre Soin", "Heilpuder", "Polvo Curación", "Polvocura", "Heal Powder") },
            { PBEItem.HealthWing, new PBELocalizedString("たいりょくのハネ", "체력날개", "Aile Santé", "Heilfeder", "P. Vigor", "Piumsalute", "Health Wing") },
            { PBEItem.HeartScale, new PBELocalizedString("ハートのウロコ", "하트비늘", "Écaillecœur", "Herzschuppe", "Esc. Corazón", "Squama Cuore", "Heart Scale") },
            { PBEItem.HeatRock, new PBELocalizedString("あついいわ", "뜨거운바위", "Roche Chaude", "Heißbrocken", "Roca Calor", "Rocciacalda", "Heat Rock") },
            { PBEItem.HeavyBall, new PBELocalizedString("ヘビーボール", "헤비볼", "Masse Ball", "Schwerball", "Peso Ball", "Peso Ball", "Heavy Ball") },
            { PBEItem.HelixFossil, new PBELocalizedString("かいのカセキ", "조개화석", "Nautile", "Helixfossil", "Fósil Hélix", "Helixfossile", "Helix Fossil") },
            { PBEItem.HondewBerry, new PBELocalizedString("ロメのみ", "로매열매", "Baie Lonme", "Honmelbeere", "Baya Meluce", "Baccamelon", "Hondew Berry") },
            { PBEItem.Honey, new PBELocalizedString("あまいミツ", "달콤한꿀", "Miel", "Honig", "Miel", "Miele", "Honey") },
            { PBEItem.HPUp, new PBELocalizedString("マックスアップ", "맥스업", "PV Plus", "KP-Plus", "Más PS", "PS-Su", "HP Up") },
            { PBEItem.HyperPotion, new PBELocalizedString("すごいキズぐすり", "고급상처약", "Hyper Potion", "Hypertrank", "Hiperpoción", "Iperpozione", "Hyper Potion") },
            { PBEItem.IapapaBerry, new PBELocalizedString("イアのみ", "파야열매", "Baie Papaya", "Yapabeere", "Baya Pabaya", "Baccapaia", "Iapapa Berry") },
            { PBEItem.IceGem, new PBELocalizedString("こおりのジュエル", "얼음주얼", "Joyau Glace", "Eisjuwel", "G. Hielo", "Bijoughiac.", "Ice Gem") },
            { PBEItem.IceHeal, new PBELocalizedString("こおりなおし", "얼음상태치료제", "Antigel", "Eisheiler", "Antihielo", "Antigelo", "Ice Heal") },
            { PBEItem.IciclePlate, new PBELocalizedString("つららのプレート", "고드름플레이트", "Plaque Glace", "Frosttafel", "Tabla Helada", "Lastragelo", "Icicle Plate") },
            { PBEItem.IcyRock, new PBELocalizedString("つめたいいわ", "차가운바위", "Roche Glace", "Eisbrocken", "Roca Helada", "Rocciafredda", "Icy Rock") },
            { PBEItem.InquiryMail, new PBELocalizedString("しつもんメール", "질문메일", "Lettre Demande", "Fragebrief", "Carta Pregunta", "Messaggio Chiedi", "Inquiry Mail") },
            { PBEItem.InsectPlate, new PBELocalizedString("たまむしプレート", "비단벌레플레이트", "Plaque Insecte", "Käfertafel", "Tabla Bicho", "Lastrabaco", "Insect Plate") },
            { PBEItem.Iron, new PBELocalizedString("ブロムヘキシン", "사포닌", "Fer", "Eisen", "Hierro", "Ferro", "Iron") },
            { PBEItem.IronBall, new PBELocalizedString("くろいてっきゅう", "검은철구", "Balle Fer", "Eisenkugel", "Bola Férrea", "Ferropalla", "Iron Ball") },
            { PBEItem.IronPlate, new PBELocalizedString("こうてつプレート", "강철플레이트", "Plaque Fer", "Eisentafel", "Tabla Acero", "Lastraferro", "Iron Plate") },
            { PBEItem.JabocaBerry, new PBELocalizedString("ジャポのみ", "자보열매", "Baie Jaboca", "Jabocabeere", "Baya Jaboca", "Baccajaba", "Jaboca Berry") },
            { PBEItem.KasibBerry, new PBELocalizedString("カシブのみ", "수불열매", "Baie Sédra", "Zitarzbeere", "Baya Drasi", "Baccacitrus", "Kasib Berry") },
            { PBEItem.KebiaBerry, new PBELocalizedString("ビアーのみ", "으름열매", "Baie Kébia", "Grarzbeere", "Baya Kebia", "Baccakebia", "Kebia Berry") },
            { PBEItem.KelpsyBerry, new PBELocalizedString("ネコブのみ", "시마열매", "Baie Alga", "Setangbeere", "Baya Algama", "Baccalga", "Kelpsy Berry") },
            { PBEItem.KingsRock, new PBELocalizedString("おうじゃのしるし", "왕의징표석", "Roche Royale", "King-Stein", "Roca del Rey", "Roccia di Re", "King’s Rock") },
            { PBEItem.LaggingTail, new PBELocalizedString("こうこうのしっぽ", "느림보꼬리", "Ralentiqueue", "Schwerschweif", "Cola Plúmbea", "Rallentocoda", "Lagging Tail") },
            { PBEItem.LansatBerry, new PBELocalizedString("サンのみ", "랑사열매", "Baie Lansat", "Lansatbeere", "Baya Zonlan", "Baccalangsa", "Lansat Berry") },
            { PBEItem.LavaCookie, new PBELocalizedString("フエンせんべい", "용암전병", "Lava Cookie", "Lavakeks", "Galleta Lava", "Lavottino", "Lava Cookie") },
            { PBEItem.LaxIncense, new PBELocalizedString("のんきのおこう", "무사태평향로", "Encens Doux", "Laxrauch", "Incie. Suave", "Distraroma", "Lax Incense") },
            { PBEItem.LeafStone, new PBELocalizedString("リーフのいし", "리프의돌", "Pierreplante", "Blattstein", "Piedra Hoja", "Pietrafoglia", "Leaf Stone") },
            { PBEItem.Leftovers, new PBELocalizedString("たべのこし", "먹다남은음식", "Restes", "Überreste", "Restos", "Avanzi", "Leftovers") },
            { PBEItem.Lemonade, new PBELocalizedString("ミックスオレ", "후르츠밀크", "Limonade", "Limonade", "Limonada", "Lemonsucco", "Lemonade") },
            { PBEItem.LeppaBerry, new PBELocalizedString("ヒメリのみ", "과사열매", "Baie Mepo", "Jonagobeere", "Baya Zanama", "Baccamela", "Leppa Berry") },
            { PBEItem.LevelBall, new PBELocalizedString("レベルボール", "레벨볼", "Niveau Ball", "Levelball", "Nivel Ball", "Level Ball", "Level Ball") },
            { PBEItem.LiechiBerry, new PBELocalizedString("チイラのみ", "치리열매", "Baie Lichii", "Lydzibeere", "Baya Lichi", "Baccalici", "Liechi Berry") },
            { PBEItem.LifeOrb, new PBELocalizedString("いのちのたま", "생명의구슬", "Orbe Vie", "Leben-Orb", "Vidasfera", "Assorbisfera", "Life Orb") },
            { PBEItem.LightBall, new PBELocalizedString("でんきだま", "전기구슬", "Balle Lumière", "Kugelblitz", "Bola Luminosa", "Elettropalla", "Light Ball") },
            { PBEItem.LightClay, new PBELocalizedString("ひかりのねんど", "빛의점토", "Lumargile", "Lichtlehm", "Refleluz", "Creta Luce", "Light Clay") },
            { PBEItem.LikeMail, new PBELocalizedString("おすすめメール", "추천메일", "Lettre Avis", "Insiderbrief", "Carta Gustos", "Mess. Sugg.", "Like Mail") },
            { PBEItem.LoveBall, new PBELocalizedString("ラブラブボール", "러브러브볼", "Love Ball", "Sympaball", "Amor Ball", "Love Ball", "Love Ball") },
            { PBEItem.LuckIncense, new PBELocalizedString("こううんのおこう", "행운의향로", "Encens Veine", "Glücksrauch", "Incie. Duplo", "Fortunaroma", "Luck Incense") },
            { PBEItem.LuckyEgg, new PBELocalizedString("しあわせタマゴ", "행복의알", "Œuf Chance", "Glücks-Ei", "Huevo Suerte", "Fortunuovo", "Lucky Egg") },
            { PBEItem.LuckyPunch, new PBELocalizedString("ラッキーパンチ", "럭키펀치", "Poing Chance", "Lucky Punch", "Puño Suerte", "Fortunpugno", "Lucky Punch") },
            { PBEItem.LumBerry, new PBELocalizedString("ラムのみ", "리샘열매", "Baie Prine", "Prunusbeere", "Baya Ziuela", "Baccaprugna", "Lum Berry") },
            { PBEItem.LureBall, new PBELocalizedString("ルアーボール", "루어볼", "Appât Ball", "Köderball", "Cebo Ball", "Esca Ball", "Lure Ball") },
            { PBEItem.LustrousOrb, new PBELocalizedString("しらたま", "백옥", "Orbe Perlé", "Weiß-Orb", "Lustresfera", "Splendisfera", "Lustrous Orb") },
            { PBEItem.LuxuryBall, new PBELocalizedString("ゴージャスボール", "럭셔리볼", "Luxe Ball", "Luxusball", "Lujo Ball", "Chic Ball", "Luxury Ball") },
            { PBEItem.MachoBrace, new PBELocalizedString("きょうせいギプス", "교정깁스", "Brac. Macho", "Machoband", "Vestidura", "Crescicappa", "Macho Brace") },
            { PBEItem.Magmarizer, new PBELocalizedString("マグマブースター", "마그마부스터", "Magmariseur", "Magmaisierer", "Magmatizador", "Magmatore", "Magmarizer") },
            { PBEItem.Magnet, new PBELocalizedString("じしゃく", "자석", "Aimant", "Magnet", "Imán", "Calamita", "Magnet") },
            { PBEItem.MagoBerry, new PBELocalizedString("マゴのみ", "마고열매", "Baie Mago", "Magobeere", "Baya Ango", "Baccamango", "Mago Berry") },
            { PBEItem.MagostBerry, new PBELocalizedString("ゴスのみ", "고스티열매", "Baie Mangou", "Magostbeere", "Baya Aostan", "Baccagostan", "Magost Berry") },
            { PBEItem.MasterBall, new PBELocalizedString("マスターボール", "마스터볼", "Master Ball", "Meisterball", "Master Ball", "Master Ball", "Master Ball") },
            { PBEItem.MaxElixir, new PBELocalizedString("ピーピーマックス", "PP맥스", "Max Élixir", "Top-Elixier", "Elixir Máximo", "Elisir Max", "Max Elixir") },
            { PBEItem.MaxEther, new PBELocalizedString("ピーピーリカバー", "PP회복", "Huile Max", "Top-Äther", "Éter Máximo", "Etere Max", "Max Ether") },
            { PBEItem.MaxPotion, new PBELocalizedString("まんたんのくすり", "풀회복약", "Potion Max", "Top-Trank", "Poción Máxima", "Pozione Max", "Max Potion") },
            { PBEItem.MaxRepel, new PBELocalizedString("ゴールドスプレー", "골드스프레이", "Max Repousse", "Top-Schutz", "Máx. Repel", "Repell. Max", "Max Repel") },
            { PBEItem.MaxRevive, new PBELocalizedString("げんきのかたまり", "기력의덩어리", "Rappel Max", "Top-Beleber", "Máx. Revivir", "Revital. Max", "Max Revive") },
            { PBEItem.MeadowPlate, new PBELocalizedString("みどりのプレート", "초록플레이트", "Plaque Herbe", "Wiesentafel", "Tabla Pradal", "Lastraprato", "Meadow Plate") },
            { PBEItem.MentalHerb, new PBELocalizedString("メンタルハーブ", "멘탈허브", "Herbe Mental", "Mentalkraut", "Hier. Mental", "Mentalerba", "Mental Herb") },
            { PBEItem.MetalCoat, new PBELocalizedString("メタルコート", "금속코트", "Peau Métal", "Metallmantel", "Rev. Metálico", "Metalcoperta", "Metal Coat") },
            { PBEItem.MetalPowder, new PBELocalizedString("メタルパウダー", "금속파우더", "Poudre Métal", "Metallstaub", "Polvo Metálico", "Metalpolvere", "Metal Powder") },
            { PBEItem.Metronome, new PBELocalizedString("メトロノーム", "메트로놈", "Métronome", "Metronom", "Metrónomo", "Plessimetro", "Metronome") },
            { PBEItem.MicleBerry, new PBELocalizedString("ミクルのみ", "미클열매", "Baie Micle", "Wunfrubeere", "Baya Lagro", "Baccaracolo", "Micle Berry") },
            { PBEItem.MindPlate, new PBELocalizedString("ふしぎのプレート", "이상한플레이트", "Plaque Esprit", "Hirntafel", "Tabla Mental", "Lastramente", "Mind Plate") },
            { PBEItem.MiracleSeed, new PBELocalizedString("きせきのタネ", "기적의씨", "Grain Miracl", "Wundersaat", "Semilla Milagro", "Miracolseme", "Miracle Seed") },
            { PBEItem.MoomooMilk, new PBELocalizedString("モーモーミルク", "튼튼밀크", "Lait Meumeu", "Kuhmuh-Milch", "Leche Mu-mu", "Latte Mumu", "Moomoo Milk") },
            { PBEItem.MoonBall, new PBELocalizedString("ムーンボール", "문볼", "Lune Ball", "Mondball", "Luna Ball", "Luna Ball", "Moon Ball") },
            { PBEItem.MoonStone, new PBELocalizedString("つきのいし", "달의돌", "Pierre Lune", "Mondstein", "Piedra Lunar", "Pietralunare", "Moon Stone") },
            { PBEItem.MuscleBand, new PBELocalizedString("ちからのハチマキ", "힘의머리띠", "Band. Muscle", "Muskelband", "Cinta Fuerte", "Muscolbanda", "Muscle Band") },
            { PBEItem.MuscleWing, new PBELocalizedString("きんりょくのハネ", "근력날개", "Aile Force", "Kraftfeder", "P. Músculo", "Piumpotenza", "Muscle Wing") },
            { PBEItem.MysticWater, new PBELocalizedString("しんぴのしずく", "신비의물방울", "Eau Mystique", "Zauberwasser", "Agua Mística", "Acquamagica", "Mystic Water") },
            { PBEItem.NanabBerry, new PBELocalizedString("ナナのみ", "나나열매", "Baie Nanab", "Nanabbeere", "Baya Latano", "Baccabana", "Nanab Berry") },
            { PBEItem.NestBall, new PBELocalizedString("ネストボール", "네스트볼", "Faiblo Ball", "Nestball", "Nido Ball", "Minor Ball", "Nest Ball") },
            { PBEItem.NetBall, new PBELocalizedString("ネットボール", "넷트볼", "Filet Ball", "Netzball", "Malla Ball", "Rete Ball", "Net Ball") },
            { PBEItem.NeverMeltIce, new PBELocalizedString("とけないこおり", "녹지않는얼음", "Glacéternel", "Ewiges Eis", "Antiderretir", "Gelomai", "NeverMeltIce") },
            { PBEItem.NomelBerry, new PBELocalizedString("ノメルのみ", "노멜열매", "Baie Tronci", "Tronzibeere", "Baya Monli", "Baccalemon", "Nomel Berry") },
            { PBEItem.NormalGem, new PBELocalizedString("ノーマルジュエル", "노말주얼", "Joyau Normal", "Normaljuwel", "G. Normal", "Bijounormale", "Normal Gem") },
            { PBEItem.Nugget, new PBELocalizedString("きんのたま", "금구슬", "Pépite", "Nugget", "Pepita", "Pepita", "Nugget") },
            { PBEItem.OccaBerry, new PBELocalizedString("オッカのみ", "오카열매", "Baie Chocco", "Koakobeere", "Baya Caoca", "Baccacao", "Occa Berry") },
            { PBEItem.OddIncense, new PBELocalizedString("あやしいおこう", "괴상한향로", "Bizar. Encens", "Schrägrauch", "Incie. Raro", "Bizzoaroma", "Odd Incense") },
            { PBEItem.OddKeystone, new PBELocalizedString("かなめいし", "쐐기돌", "Clé de Voûte", "Spiritkern", "P. Espíritu", "Roccianima", "Odd Keystone") },
            { PBEItem.OldAmber, new PBELocalizedString("ひみつのコハク", "비밀의호박", "Vieil Ambre", "Altbernstein", "Ámbar Viejo", "Ambra Antica", "Old Amber") },
            { PBEItem.OldGateau, new PBELocalizedString("もりのヨウカン", "숲의양갱", "Vieux Gâteau", "Spezialität", "Barrita Plus", "Dolce Gateau", "Old Gateau") },
            { PBEItem.OranBerry, new PBELocalizedString("オレンのみ", "오랭열매", "Baie Oran", "Sinelbeere", "Baya Aranja", "Baccarancia", "Oran Berry") },
            { PBEItem.OvalStone, new PBELocalizedString("まんまるいし", "동글동글돌", "Pierre Ovale", "Ovaler Stein", "Piedra Oval", "Pietraovale", "Oval Stone") },
            { PBEItem.PamtreBerry, new PBELocalizedString("シーヤのみ", "자야열매", "Baie Palma", "Pallmbeere", "Baya Plama", "Baccapalma", "Pamtre Berry") },
            { PBEItem.ParalyzeHeal, new PBELocalizedString("まひなおし", "마비치료제", "Anti-Para", "Para-Heiler", "Antiparaliz", "Antiparalisi", "Paralyze Heal") },
            { PBEItem.ParkBall, new PBELocalizedString("パークボール", "파크볼", "Parc Ball", "Parkball", "Parque Ball", "Parco Ball", "Park Ball") },
            { PBEItem.PasshoBerry, new PBELocalizedString("イトケのみ", "꼬시개열매", "Baie Pocpoc", "Foepasbeere", "Baya Pasio", "Baccapasflo", "Passho Berry") },
            { PBEItem.PassOrb, new PBELocalizedString("デルダマ", "딜구슬", "Offrisphère", "Transferorb", "Regalosfera", "Passabilia", "Pass Orb") },
            { PBEItem.PayapaBerry, new PBELocalizedString("ウタンのみ", "야파열매", "Baie Yapap", "Pyapabeere", "Baya Payapa", "Baccapayapa", "Payapa Berry") },
            { PBEItem.Pearl, new PBELocalizedString("しんじゅ", "진주", "Perle", "Perle", "Perla", "Perla", "Pearl") },
            { PBEItem.PearlString, new PBELocalizedString("おだんごしんじゅ", "경단진주", "Perle Triple", "Triperle", "Sarta Perlas", "Trittiperla", "Pearl String") },
            { PBEItem.PechaBerry, new PBELocalizedString("モモンのみ", "복슝열매", "Baie Pêcha", "Pirsifbeere", "Baya Meloc", "Baccapesca", "Pecha Berry") },
            { PBEItem.PersimBerry, new PBELocalizedString("キーのみ", "시몬열매", "Baie Kika", "Persimbeere", "Baya Caquic", "Baccaki", "Persim Berry") },
            { PBEItem.PetayaBerry, new PBELocalizedString("ヤタピのみ", "야타비열매", "Baie Pitaye", "Tahaybeere", "Baya Yapati", "Baccapitaya", "Petaya Berry") },
            { PBEItem.PinapBerry, new PBELocalizedString("パイルのみ", "파인열매", "Baie Nanana", "Sananabeere", "Baya Pinia", "Baccananas", "Pinap Berry") },
            { PBEItem.PinkScarf, new PBELocalizedString("ピンクのバンダナ", "분홍밴드", "Foulard Rose", "Rosa Schal", "Pañuelo Rosa", "Fascia Rosa", "Pink Scarf") },
            { PBEItem.PlumeFossil, new PBELocalizedString("はねのカセキ", "날개화석", "Foss. Plume", "Federfossil", "Fósil Pluma", "Fossilpiuma", "Plume Fossil") },
            { PBEItem.PnkApricorn, new PBELocalizedString("ももぼんぐり", "담홍규토리", "Noigrume Rose", "Aprikoko Pnk", "Bonguri Ros", "Ghic. Rosa", "Pnk Apricorn") },
            { PBEItem.PoisonBarb, new PBELocalizedString("どくバリ", "독바늘", "Pic Venin", "Giftstich", "Flecha Venenosa", "Velenaculeo", "Poison Barb") },
            { PBEItem.PoisonGem, new PBELocalizedString("どくのジュエル", "독주얼", "Joyau Poison", "Giftjuwel", "G. Veneno", "Bijouveleno", "Poison Gem") },
            { PBEItem.PokeBall, new PBELocalizedString("モンスターボール", "몬스터볼", "Poké Ball", "Pokéball", "Poké Ball", "Poké Ball", "Poké Ball") },
            { PBEItem.PokeDoll, new PBELocalizedString("ピッピにんぎょう", "삐삐인형", "Poké Poupée", "Poképuppe", "Poké Muñeco", "Poké Bambola", "Poké Doll") },
            { PBEItem.PokeToy, new PBELocalizedString("ポケじゃらし", "포켓풀", "Poké Plumet", "Pokéwedel", "Pokéseñuelo", "Pokégingillo", "Poké Toy") },
            { PBEItem.PomegBerry, new PBELocalizedString("ザロクのみ", "유석열매", "Baie Grena", "Granabeere", "Baya Grana", "Baccagrana", "Pomeg Berry") },
            { PBEItem.Potion, new PBELocalizedString("キズぐすり", "상처약", "Potion", "Trank", "Poción", "Pozione", "Potion") },
            { PBEItem.PowerAnklet, new PBELocalizedString("パワーアンクル", "파워앵클릿", "Chaîne. Pouv.", "Machtkette", "Franja Recia", "Vigorgliera", "Power Anklet") },
            { PBEItem.PowerBand, new PBELocalizedString("パワーバンド", "파워밴드", "Band. Pouv.", "Machtband", "Banda Recia", "Vigorbanda", "Power Band") },
            { PBEItem.PowerBelt, new PBELocalizedString("パワーベルト", "파워벨트", "Ceint. Pouv.", "Machtgurt", "Cinto Recio", "Vigorfascia", "Power Belt") },
            { PBEItem.PowerBracer, new PBELocalizedString("パワーリスト", "파워리스트", "Poign. Pouv.", "Machtreif", "Brazal Recio", "Vigorcerchio", "Power Bracer") },
            { PBEItem.PowerHerb, new PBELocalizedString("パワフルハーブ", "파워풀허브", "Herbe Pouv.", "Energiekraut", "Hierba Única", "Vigorerba", "Power Herb") },
            { PBEItem.PowerLens, new PBELocalizedString("パワーレンズ", "파워렌즈", "Lent. Pouv.", "Machtlinse", "Lente Recia", "Vigorlente", "Power Lens") },
            { PBEItem.PowerWeight, new PBELocalizedString("パワーウエイト", "파워웨이트", "Poids Pouv.", "Machtgewicht", "Pesa Recia", "Vigorpeso", "Power Weight") },
            { PBEItem.PPMax, new PBELocalizedString("ポイントマックス", "포인트맥스", "PP Max", "AP-Top", "Máx. PP", "PP-Max", "PP Max") },
            { PBEItem.PPUp, new PBELocalizedString("ポイントアップ", "포인트업", "PP Plus", "AP-Plus", "Más PP", "PP-Su", "PP Up") },
            { PBEItem.PremierBall, new PBELocalizedString("プレミアボール", "프레미어볼", "Honor Ball", "Premierball", "Honor Ball", "Premier Ball", "Premier Ball") },
            { PBEItem.PrettyWing, new PBELocalizedString("きれいなハネ", "고운날개", "Jolie Aile", "Prachtfeder", "P. Bella", "Piumabella", "Pretty Wing") },
            { PBEItem.PrismScale, new PBELocalizedString("きれいなウロコ", "고운비늘", "Bel’Écaille", "Schönschuppe", "Escama Bella", "Squama Bella", "Prism Scale") },
            { PBEItem.Protector, new PBELocalizedString("プロテクター", "프로텍터", "Protecteur", "Schützer", "Protector", "Copertura", "Protector") },
            { PBEItem.Protein, new PBELocalizedString("タウリン", "타우린", "Protéine", "Protein", "Proteína", "Proteina", "Protein") },
            { PBEItem.PsychicGem, new PBELocalizedString("エスパージュエル", "에스퍼주얼", "Joyau Psy", "Psychojuwel", "G. Psíquica", "Bijoupsico", "Psychic Gem") },
            { PBEItem.PureIncense, new PBELocalizedString("きよめのおこう", "순결의향로", "Encens Pur", "Scheuchrauch", "Incie. Puro", "Puroaroma", "Pure Incense") },
            { PBEItem.QualotBerry, new PBELocalizedString("タポルのみ", "파비열매", "Baie Qualot", "Qualotbeere", "Baya Ispero", "Baccaloquat", "Qualot Berry") },
            { PBEItem.QuickBall, new PBELocalizedString("クイックボール", "퀵볼", "Rapide Ball", "Flottball", "Veloz Ball", "Velox Ball", "Quick Ball") },
            { PBEItem.QuickClaw, new PBELocalizedString("せんせいのツメ", "선제공격손톱", "Vive Griffe", "Flinkklaue", "Garra Rápida", "Rapidartigli", "Quick Claw") },
            { PBEItem.QuickPowder, new PBELocalizedString("スピードパウダー", "스피드파우더", "Poudre Vite", "Flottstaub", "Polvo Veloz", "Velopolvere", "Quick Powder") },
            { PBEItem.RabutaBerry, new PBELocalizedString("ラブタのみ", "라부탐열매", "Baie Rabuta", "Rabutabeere", "Baya Rautan", "Baccambutan", "Rabuta Berry") },
            { PBEItem.RageCandyBar, new PBELocalizedString("いかりまんじゅう", "분노의호두과자", "Bonbon Rage", "Wutkeks", "Caramelo Furia", "Iramella", "Rage Candy Bar") },
            { PBEItem.RareBone, new PBELocalizedString("きちょうなホネ", "귀중한뼈", "Os Rare", "Steinknochen", "Hueso Raro", "Osso Raro", "Rare Bone") },
            { PBEItem.RareCandy, new PBELocalizedString("ふしぎなアメ", "이상한사탕", "Super Bonbon", "Sonderbonbon", "Caramelo Raro", "Caramella Rara", "Rare Candy") },
            { PBEItem.RawstBerry, new PBELocalizedString("チーゴのみ", "복분열매", "Baie Fraive", "Fragiabeere", "Baya Safre", "Baccafrago", "Rawst Berry") },
            { PBEItem.RazorClaw, new PBELocalizedString("するどいツメ", "예리한손톱", "Griffe Rasoir", "Scharfklaue", "Garrafilada", "Affilartigli", "Razor Claw") },
            { PBEItem.RazorFang, new PBELocalizedString("するどいキバ", "예리한이빨", "Croc Rasoir", "Scharfzahn", "Colmillagudo", "Affilodente", "Razor Fang") },
            { PBEItem.RazzBerry, new PBELocalizedString("ズリのみ", "라즈열매", "Baie Framby", "Himmihbeere", "Baya Frambu", "Baccalampon", "Razz Berry") },
            { PBEItem.ReaperCloth, new PBELocalizedString("れいかいのぬの", "영계의천", "Tissu Fauche", "Düsterumhang", "Telaterrible", "Terrorpanno", "Reaper Cloth") },
            { PBEItem.RedApricorn, new PBELocalizedString("あかぼんぐり", "빨간규토리", "Noigrume Rouge", "Aprikoko Rot", "Bonguri Roj", "Ghic. Rossa", "Red Apricorn") },
            { PBEItem.RedCard, new PBELocalizedString("レッドカード", "레드카드", "Carton Rouge", "Rote Karte", "Tarjeta Roja", "Cartelrosso", "Red Card") },
            { PBEItem.RedFlute, new PBELocalizedString("あかいビードロ", "빨강비드로", "Flûte Rouge", "Rote Flöte", "Flauta Roja", "Flauto Rosso", "Red Flute") },
            { PBEItem.RedScarf, new PBELocalizedString("あかいバンダナ", "빨강밴드", "Foulard Rouge", "Roter Schal", "Pañuelo Rojo", "Fascia Rossa", "Red Scarf") },
            { PBEItem.RedShard, new PBELocalizedString("あかいかけら", "빨강조각", "Tesson Rouge", "Purpurstück", "Parte Roja", "Coccio Rosso", "Red Shard") },
            { PBEItem.RelicBand, new PBELocalizedString("こだいのうでわ", "고대의팔찌", "Vieux Bijou", "Alter Reif", "Brazal", "Bracciantico", "Relic Band") },
            { PBEItem.RelicCopper, new PBELocalizedString("こだいのどうか", "고대의동화", "Vieux Sou", "Alter Heller", "Real Cobre", "Soldantico", "Relic Copper") },
            { PBEItem.RelicCrown, new PBELocalizedString("こだいのおうかん", "고대의왕관", "Vieux Tortil", "Alte Krone", "Cor. Antigua", "Coronantica", "Relic Crown") },
            { PBEItem.RelicGold, new PBELocalizedString("こだいのきんか", "고대의금화", "Vieux Ducat", "Alter Dukat", "Real Oro", "Doblonantico", "Relic Gold") },
            { PBEItem.RelicSilver, new PBELocalizedString("こだいのぎんか", "고대의은화", "Vieil Écu", "Alter Taler", "Real Plata", "Ducatantico", "Relic Silver") },
            { PBEItem.RelicStatue, new PBELocalizedString("こだいのせきぞう", "고대의석상", "Vieux Santon", "Alte Statue", "Efi. Antigua", "Statuantica", "Relic Statue") },
            { PBEItem.RelicVase, new PBELocalizedString("こだいのツボ", "고대의항아리", "Vieux Vase", "Alte Vase", "Ánfora", "Vasantico", "Relic Vase") },
            { PBEItem.RepeatBall, new PBELocalizedString("リピートボール", "리피드볼", "Bis Ball", "Wiederball", "Acopio Ball", "Bis Ball", "Repeat Ball") },
            { PBEItem.Repel, new PBELocalizedString("むしよけスプレー", "벌레회피스프레이", "Repousse", "Schutz", "Repelente", "Repellente", "Repel") },
            { PBEItem.ReplyMail, new PBELocalizedString("おかえしメール", "답장메일", "Lettre Réponse", "Rückbrief", "Carta Respuesta", "Mess. Risp.", "Reply Mail") },
            { PBEItem.ResistWing, new PBELocalizedString("ていこうのハネ", "저항력날개", "Aile Armure", "Abwehrfeder", "P. Aguante", "Piumtutela", "Resist Wing") },
            { PBEItem.RevivalHerb, new PBELocalizedString("ふっかつそう", "부활초", "Herbe Rappel", "Vitalkraut", "Hierba Revivir", "Vitalerba", "Revival Herb") },
            { PBEItem.Revive, new PBELocalizedString("げんきのかけら", "기력의조각", "Rappel", "Beleber", "Revivir", "Revitaliz.", "Revive") },
            { PBEItem.RindoBerry, new PBELocalizedString("リンドのみ", "린드열매", "Baie Ratam", "Grindobeere", "Baya Tamar", "Baccarindo", "Rindo Berry") },
            { PBEItem.RingTarget, new PBELocalizedString("ねらいのまと", "겨냥표적", "Pt de Mire", "Zielscheibe", "Blanco", "Facilsaglio", "Ring Target") },
            { PBEItem.RockGem, new PBELocalizedString("いわのジュエル", "바위주얼", "Joyau Roche", "Gesteinjuwel", "G. Roca", "Bijouroccia", "Rock Gem") },
            { PBEItem.RockIncense, new PBELocalizedString("がんせきおこう", "암석향로", "Encens Roc", "Steinrauch", "Incienso Roca", "Roccioaroma", "Rock Incense") },
            { PBEItem.RockyHelmet, new PBELocalizedString("ゴツゴツメット", "울퉁불퉁멧", "Casque Brut", "Beulenhelm", "Cas. Dentado", "Bitorzolelmo", "Rocky Helmet") },
            { PBEItem.RootFossil, new PBELocalizedString("ねっこのカセキ", "뿌리화석", "Foss. Racine", "Wurzelfossil", "Fósil Raíz", "Radifossile", "Root Fossil") },
            { PBEItem.RoseIncense, new PBELocalizedString("おはなのおこう", "꽃향로", "Encens Fleur", "Rosenrauch", "Inc. Floral", "Rosaroma", "Rose Incense") },
            { PBEItem.RowapBerry, new PBELocalizedString("レンブのみ", "애터열매", "Baie Pommo", "Roselbeere", "Baya Magua", "Baccaroam", "Rowap Berry") },
            { PBEItem.RSVPMail, new PBELocalizedString("おさそいメール", "권유메일", "Lettre Invit", "Einladebrief", "Carta Invitar", "Messaggio Invito", "RSVP Mail") },
            { PBEItem.SacredAsh, new PBELocalizedString("せいなるはい", "성스러운분말", "Cendresacrée", "Zauberasche", "Ceniza Sagrada", "Ceneremagica", "Sacred Ash") },
            { PBEItem.SafariBall, new PBELocalizedString("サファリボール", "사파리볼", "Safari Ball", "Safariball", "Safari Ball", "Safari Ball", "Safari Ball") },
            { PBEItem.SalacBerry, new PBELocalizedString("カムラのみ", "캄라열매", "Baie Sailak", "Salkabeere", "Baya Aslac", "Baccasalak", "Salac Berry") },
            { PBEItem.ScopeLens, new PBELocalizedString("ピントレンズ", "초점렌즈", "Lentilscope", "Scope-Linse", "Periscopio", "Mirino", "Scope Lens") },
            { PBEItem.SeaIncense, new PBELocalizedString("うしおのおこう", "바닷물향로", "Encens Mer", "Seerauch", "Incie. Mar.", "Marearoma", "Sea Incense") },
            { PBEItem.SharpBeak, new PBELocalizedString("するどいくちばし", "예리한부리", "Bec Pointu", "Hackattack", "Pico Afilado", "Beccaffilato", "Sharp Beak") },
            { PBEItem.ShedShell, new PBELocalizedString("きれいなぬけがら", "아름다운허물", "Carapace Mue", "Wechselhülle", "Muda Concha", "Disfoguscio", "Shed Shell") },
            { PBEItem.ShellBell, new PBELocalizedString("かいがらのすず", "조개껍질방울", "Grelot Coque", "Seegesang", "Campana Concha", "Conchinella", "Shell Bell") },
            { PBEItem.ShinyStone, new PBELocalizedString("ひかりのいし", "빛의돌", "Pierre Éclat", "Leuchtstein", "Piedra Día", "Pietrabrillo", "Shiny Stone") },
            { PBEItem.ShoalSalt, new PBELocalizedString("あさせのしお", "여울소금", "Sel Tréfonds", "Küstensalz", "Sal Cardumen", "Sale Ondoso", "Shoal Salt") },
            { PBEItem.ShoalShell, new PBELocalizedString("あさせのかいがら", "여울조개껍질", "Co. Trefonds", "Küstenschale", "C. Cardumen", "Gusciondoso", "Shoal Shell") },
            { PBEItem.ShockDrive, new PBELocalizedString("イナズマカセット", "번개카세트", "Module Choc", "Blitzmodul", "FulgoROM", "Voltmodulo", "Shock Drive") },
            { PBEItem.ShucaBerry, new PBELocalizedString("シュカのみ", "슈캐열매", "Baie Jouca", "Schukebeere", "Baya Acardo", "Baccanaca", "Shuca Berry") },
            { PBEItem.SilkScarf, new PBELocalizedString("シルクのスカーフ", "실크스카프", "Mouch. Soie", "Seidenschal", "Pañuelo Seda", "Sciarpaseta", "Silk Scarf") },
            { PBEItem.SilverPowder, new PBELocalizedString("ぎんのこな", "은빛가루", "Poudre Arg.", "Silberstaub", "Polvo Plata", "Argenpolvere", "SilverPowder") },
            { PBEItem.SitrusBerry, new PBELocalizedString("オボンのみ", "자뭉열매", "Baie Sitrus", "Tsitrubeere", "Baya Zidra", "Baccacedro", "Sitrus Berry") },
            { PBEItem.SkullFossil, new PBELocalizedString("ずがいのカセキ", "두개의화석", "Foss. Crâne", "Kopffossil", "Fósil Cráneo", "Fossilcranio", "Skull Fossil") },
            { PBEItem.SkyPlate, new PBELocalizedString("あおぞらプレート", "푸른하늘플레이트", "Plaque Ciel", "Wolkentafel", "Tabla Cielo", "Lastracielo", "Sky Plate") },
            { PBEItem.SmokeBall, new PBELocalizedString("けむりだま", "연막탄", "Boule Fumée", "Rauchball", "Bola Humo", "Palla Fumo", "Smoke Ball") },
            { PBEItem.SmoothRock, new PBELocalizedString("さらさらいわ", "보송보송바위", "Roche Lisse", "Glattbrocken", "Roca Suave", "Roccialiscia", "Smooth Rock") },
            { PBEItem.SodaPop, new PBELocalizedString("サイコソーダ", "미네랄사이다", "Soda Cool", "Sprudel", "Refresco", "Gassosa", "Soda Pop") },
            { PBEItem.SoftSand, new PBELocalizedString("やわらかいすな", "부드러운모래", "Sable Doux", "Pudersand", "Arena Fina", "Sabbiasoffice", "Soft Sand") },
            { PBEItem.SootheBell, new PBELocalizedString("やすらぎのすず", "평온의방울", "Grelot Zen", "Sanftglocke", "Campana Alivio", "Calmanella", "Soothe Bell") },
            { PBEItem.SoulDew, new PBELocalizedString("こころのしずく", "마음의물방울", "Rosée Âme", "Seelentau", "Rocío Bondad", "Cuorugiada", "Soul Dew") },
            { PBEItem.SpellTag, new PBELocalizedString("のろいのおふだ", "저주의부적", "Rune Sort", "Bannsticker", "Hechizo", "Spettrotarga", "Spell Tag") },
            { PBEItem.SpelonBerry, new PBELocalizedString("ノワキのみ", "메호키열매", "Baie Kiwan", "Kiwanbeere", "Baya Wikano", "Baccamelos", "Spelon Berry") },
            { PBEItem.SplashPlate, new PBELocalizedString("しずくプレート", "물방울플레이트", "Plaque Hydro", "Wassertafel", "Tabla Linfa", "Lastraidro", "Splash Plate") },
            { PBEItem.SpookyPlate, new PBELocalizedString("もののけプレート", "원령플레이트", "Plaque Fantôme", "Spuktafel", "Tabla Terror", "Lastratetra", "Spooky Plate") },
            { PBEItem.SportBall, new PBELocalizedString("コンペボール", "콤페볼", "Compét’Ball", "Turnierball", "Competi Ball", "Gara Ball", "Sport Ball") },
            { PBEItem.StableMulch, new PBELocalizedString("ながながこやし", "오래오래비료", "Fertistable", "Stabilmulch", "Ab. Fijador", "Fertilsaldo", "Stable Mulch") },
            { PBEItem.Stardust, new PBELocalizedString("ほしのすな", "별의모래", "Pouss.Étoile", "Sternenstaub", "Polvo Estelar", "Polvostella", "Stardust") },
            { PBEItem.StarfBerry, new PBELocalizedString("スターのみ", "스타열매", "Baie Frista", "Krambobeere", "Baya Arabol", "Baccambola", "Starf Berry") },
            { PBEItem.StarPiece, new PBELocalizedString("ほしのかけら", "별의조각", "Morc. Étoile", "Sternenstück", "Tr. Estrella", "Pezzo Stella", "Star Piece") },
            { PBEItem.SteelGem, new PBELocalizedString("はがねのジュエル", "강철주얼", "Joyau Acier", "Stahljuwel", "G. Acero", "Bijouacciaio", "Steel Gem") },
            { PBEItem.Stick, new PBELocalizedString("ながねぎ", "대파", "Bâton", "Lauchstange", "Palo", "Gambo", "Stick") },
            { PBEItem.StickyBarb, new PBELocalizedString("くっつきバリ", "끈적끈적바늘", "Piquants", "Klettdorn", "Toxiestrella", "Vischiopunta", "Sticky Barb") },
            { PBEItem.StonePlate, new PBELocalizedString("がんせきプレート", "암석플레이트", "Plaque Roc", "Steintafel", "Tabla Pétrea", "Lastrapietra", "Stone Plate") },
            { PBEItem.SunStone, new PBELocalizedString("たいようのいし", "태양의돌", "Pierresoleil", "Sonnenstein", "Piedra Solar", "Pietrasolare", "Sun Stone") },
            { PBEItem.SuperPotion, new PBELocalizedString("いいキズぐすり", "좋은상처약", "Super Potion", "Supertrank", "Superpoción", "Superpozione", "Super Potion") },
            { PBEItem.SuperRepel, new PBELocalizedString("シルバースプレー", "실버스프레이", "Super Repousse", "Superschutz", "Superrepel", "Superrepell.", "Super Repel") },
            { PBEItem.SweetHeart, new PBELocalizedString("ハートスイーツ", "하트스위트", "Chococœur", "Herzkonfekt", "Cor. Dulce", "Dolcecuore", "Sweet Heart") },
            { PBEItem.SwiftWing, new PBELocalizedString("しゅんぱつのハネ", "순발력날개", "Aile Sprint", "Flinkfeder", "P. Ímpetu", "Piumreazione", "Swift Wing") },
            { PBEItem.TamatoBerry, new PBELocalizedString("マトマのみ", "토망열매", "Baie Tamato", "Tamotbeere", "Baya Tamate", "Baccamodoro", "Tamato Berry") },
            { PBEItem.TangaBerry, new PBELocalizedString("タンガのみ", "리체열매", "Baie Panga", "Tanigabeere", "Baya Yecana", "Baccaitan", "Tanga Berry") },
            { PBEItem.ThanksMail, new PBELocalizedString("かんしゃメール", "감사메일", "Lettre Merci", "Dankesbrief", "Carta Gracias", "Messaggio Grazie", "Thanks Mail") },
            { PBEItem.ThickClub, new PBELocalizedString("ふといホネ", "굵은뼈", "Masse Os", "Kampfknochen", "Hueso Grueso", "Ossospesso", "Thick Club") },
            { PBEItem.Thunderstone, new PBELocalizedString("かみなりのいし", "천둥의돌", "Pierrefoundr", "Donnerstein", "Piedratrueno", "Pietratuono", "Thunderstone") },
            { PBEItem.TimerBall, new PBELocalizedString("タイマーボール", "타이마볼", "Chrono Ball", "Timerball", "Turno Ball", "Timer Ball", "Timer Ball") },
            { PBEItem.TinyMushroom, new PBELocalizedString("ちいさなキノコ", "작은버섯", "Petit Champi", "Minipilz", "Miniseta", "Minifungo", "TinyMushroom") },
            { PBEItem.ToxicOrb, new PBELocalizedString("どくどくだま", "맹독구슬", "Orbe Toxique", "Toxik-Orb", "Toxisfera", "Tossicsfera", "Toxic Orb") },
            { PBEItem.ToxicPlate, new PBELocalizedString("もうどくプレート", "맹독플레이트", "Plaque Toxik", "Gifttafel", "Tabla Tóxica", "Lastrafiele", "Toxic Plate") },
            { PBEItem.TwistedSpoon, new PBELocalizedString("まがったスプーン", "휘어진스푼", "Cuillertordu", "Krummlöffel", "Cuchara Torcida", "Cucchiaiotorto", "TwistedSpoon") },
            { PBEItem.UltraBall, new PBELocalizedString("ハイパーボール", "하이퍼볼", "Hyper Ball", "Hyperball", "Ultra Ball", "Ultra Ball", "Ultra Ball") },
            { PBEItem.UpGrade, new PBELocalizedString("アップグレード", "업그레이드", "Améliorator", "Up-Grade", "Mejora", "Upgrade", "Up-Grade") },
            { PBEItem.WacanBerry, new PBELocalizedString("ソクノのみ", "초나열매", "Baie Parma", "Kerzalbeere", "Baya Gualot", "Baccaparmen", "Wacan Berry") },
            { PBEItem.WaterGem, new PBELocalizedString("みずのジュエル", "물주얼", "Joyau Eau", "Wasserjuwel", "G. Agua", "Bijouacqua", "Water Gem") },
            { PBEItem.WaterStone, new PBELocalizedString("みずのいし", "물의돌", "Pierre Eau", "Wasserstein", "Piedra Agua", "Pietraidrica", "Water Stone") },
            { PBEItem.WatmelBerry, new PBELocalizedString("カイスのみ", "슈박열매", "Baie Stekpa", "Wasmelbeere", "Baya Sambia", "Baccacomero", "Watmel Berry") },
            { PBEItem.WaveIncense, new PBELocalizedString("さざなみのおこう", "잔물결향로", "Encens Vague", "Wellenrauch", "Incienso Aqua", "Ondaroma", "Wave Incense") },
            { PBEItem.WepearBerry, new PBELocalizedString("セシナのみ", "서배열매", "Baie Repoi", "Nirbebeere", "Baya Peragu", "Baccapera", "Wepear Berry") },
            { PBEItem.WhiteFlute, new PBELocalizedString("しろいビードロ", "하양비드로", "Flûteblanche", "Weiße Flöte", "Flauta Blanca", "Flauto Bianco", "White Flute") },
            { PBEItem.WhiteHerb, new PBELocalizedString("しろいハーブ", "하양허브", "Herbeblanche", "Schlohkraut", "Hier. Blanca", "Erbachiara", "White Herb") },
            { PBEItem.WhtApricorn, new PBELocalizedString("しろぼんぐり", "하얀규토리", "Noigrume Blanc", "Aprikoko Wss", "Bongui Bla", "Ghic. Biana", "Wht Apricorn") },
            { PBEItem.WideLens, new PBELocalizedString("こうかくレンズ", "광각렌즈", "Loupe", "Großlinse", "Lupa", "Grandelente", "Wide Lens") },
            { PBEItem.WikiBerry, new PBELocalizedString("ウイのみ", "위키열매", "Baie Wiki", "Wikibeere", "Baya Wiki", "Baccakiwi", "Wiki Berry") },
            { PBEItem.WiseGlasses, new PBELocalizedString("ものしりメガネ", "박식안경", "Lunet. Sages", "Schlauglas", "Gafas Esp.", "Saviocchiali", "Wise Glasses") },
            { PBEItem.XAccuracy, new PBELocalizedString("ヨクアタール", "잘-맞히기", "Précision +", "X-Treffer", "Precisión X", "Precisione X", "X Accuracy") },
            { PBEItem.XAttack, new PBELocalizedString("プラスパワー", "플러스파워", "Attaque +", "X-Angriff", "Ataque X", "Attacco X", "X Attack") },
            { PBEItem.XDefend, new PBELocalizedString("ディフェンダー", "디펜드업", "Défense +", "X-Abwehr", "Defensa X", "Difesa X", "X Defend") },
            { PBEItem.XSpDef, new PBELocalizedString("スペシャルガード", "스페셜가드", "Déf. Spé. +", "X-Spezial-Vert.", "Def. Especial X", "Dif. Speciale X", "X Sp. Def") },
            { PBEItem.XSpecial, new PBELocalizedString("スペシャルアップ", "스페셜업", "Spécial +", "X-Spezial", "Especial X", "Special X", "X Special") },
            { PBEItem.XSpeed, new PBELocalizedString("スピーダー", "스피드업", "Vitesse +", "X-Tempo", "Velocidad X", "Velocità X", "X Speed") },
            { PBEItem.YacheBerry, new PBELocalizedString("ヤチェのみ", "플카열매", "Baie Nanone", "Kiroyabeere", "Baya Rimoya", "Baccamoya", "Yache Berry") },
            { PBEItem.YellowFlute, new PBELocalizedString("きいろビードロ", "노랑비드로", "Flûte Jaune", "Gelbe Flöte", "Fl. Amarilla", "Flauto Gial.", "Yellow Flute") },
            { PBEItem.YellowScarf, new PBELocalizedString("きいろのバンダナ", "노랑밴드", "Foulard Jaune", "Gelber Schal", "Pañuelo Amarillo", "Fascia Gialla", "Yellow Scarf") },
            { PBEItem.YellowShard, new PBELocalizedString("きいろいかけら", "노랑조각", "Tesson Jaune", "Gelbstück", "P. Amarilla", "Coccio Gial.", "Yellow Shard") },
            { PBEItem.YlwApricorn, new PBELocalizedString("きぼんぐり", "노랑규토리", "Noigrume Jaune", "Aprikoko Glb", "Bonguri Ama", "Ghic. Gialla", "Ylw Apricorn") },
            { PBEItem.ZapPlate, new PBELocalizedString("いかずちプレート", "우뢰플레이트", "Plaque Volt", "Blitztafel", "Tabla Trueno", "Lastrasaetta", "Zap Plate") },
            { PBEItem.Zinc, new PBELocalizedString("キトサン", "키토산", "Zinc", "Zink", "Zinc", "Zinco", "Zinc") },
            { PBEItem.ZoomLens, new PBELocalizedString("フォーカスレンズ", "포커스렌즈", "Lentil. Zoom", "Zoomlinse", "Telescopio", "Zoomlente", "Zoom Lens") }
        });
    }
}
