using Kermalis.PokemonBattleEngine.Data;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Kermalis.PokemonBattleEngine.Localization
{
    public static class PBEMoveLocalization
    {
        public static ReadOnlyDictionary<PBEMove, PBELocalizedString> Names { get; } = new ReadOnlyDictionary<PBEMove, PBELocalizedString>(new Dictionary<PBEMove, PBELocalizedString>()
        {
            { PBEMove.None, new PBELocalizedString("--", "--") },
            { PBEMove.Pound, new PBELocalizedString("Pound", "はたく") },
            { PBEMove.KarateChop, new PBELocalizedString("Karate Chop", "からてチョップ") },
            // { PBEMove.3, new PBELocalizedString("DoubleSlap", "おうふくビンタ") },
            // { PBEMove.4, new PBELocalizedString("Comet Punch", "れんぞくパンチ") },
            { PBEMove.MegaPunch, new PBELocalizedString("Mega Punch", "メガトンパンチ") },
            // { PBEMove.6, new PBELocalizedString("Pay Day", "ネコにこばん") },
            { PBEMove.FirePunch, new PBELocalizedString("Fire Punch", "ほのおのパンチ") },
            { PBEMove.IcePunch, new PBELocalizedString("Ice Punch", "れいとうパンチ") },
            { PBEMove.ThunderPunch, new PBELocalizedString("ThunderPunch", "かみなりパンチ") },
            { PBEMove.Scratch, new PBELocalizedString("Scratch", "ひっかく") },
            { PBEMove.ViceGrip, new PBELocalizedString("ViceGrip", "はさむ") },
            // { PBEMove.12, new PBELocalizedString("Guillotine", "ハサミギロチン") },
            // { PBEMove.13, new PBELocalizedString("Razor Wind", "かまいたち") },
            { PBEMove.SwordsDance, new PBELocalizedString("Swords Dance", "つるぎのまい") },
            { PBEMove.Cut, new PBELocalizedString("Cut", "いあいぎり") },
            // { PBEMove.16, new PBELocalizedString("Gust", "かぜおこし") },
            { PBEMove.WingAttack, new PBELocalizedString("Wing Attack", "つばさでうつ") },
            { PBEMove.Whirlwind, new PBELocalizedString("Whirlwind", "ふきとばし") },
            { PBEMove.Fly, new PBELocalizedString("Fly", "そらをとぶ") },
            // { PBEMove.20, new PBELocalizedString("Bind", "しめつける") },
            { PBEMove.Slam, new PBELocalizedString("Slam", "たたきつける") },
            { PBEMove.VineWhip, new PBELocalizedString("Vine Whip", "つるのムチ") },
            { PBEMove.Stomp, new PBELocalizedString("Stomp", "ふみつけ") },
            // { PBEMove.24, new PBELocalizedString("Double Kick", "にどげり") },
            { PBEMove.MegaKick, new PBELocalizedString("Mega Kick", "メガトンキック") },
            // { PBEMove.26, new PBELocalizedString("Jump Kick", "とびげり") },
            // { PBEMove.27, new PBELocalizedString("Rolling Kick", "まわしげり") },
            { PBEMove.SandAttack, new PBELocalizedString("Sand-Attack", "すなかけ") },
            { PBEMove.Headbutt, new PBELocalizedString("Headbutt", "ずつき") },
            { PBEMove.HornAttack, new PBELocalizedString("Horn Attack", "つのでつく") },
            // { PBEMove.31, new PBELocalizedString("Fury Attack", "みだれづき") },
            // { PBEMove.32, new PBELocalizedString("Horn Drill", "つのドリル") },
            { PBEMove.Tackle, new PBELocalizedString("Tackle", "たいあたり") },
            { PBEMove.BodySlam, new PBELocalizedString("Body Slam", "のしかかり") },
            // { PBEMove.35, new PBELocalizedString("Wrap", "まきつく") },
            // { PBEMove.36, new PBELocalizedString("Take Down", "とっしん") },
            // { PBEMove.37, new PBELocalizedString("Thrash", "あばれる") },
            // { PBEMove.38, new PBELocalizedString("Double-Edge", "すてみタックル") },
            { PBEMove.TailWhip, new PBELocalizedString("Tail Whip", "しっぽをふる") },
            { PBEMove.PoisonSting, new PBELocalizedString("Poison Sting", "どくばり") },
            // { PBEMove.41, new PBELocalizedString("Twineedle", "ダブルニードル") },
            // { PBEMove.42, new PBELocalizedString("Pin Missile", "ミサイルばり") },
            { PBEMove.Leer, new PBELocalizedString("Leer", "にらみつける") },
            { PBEMove.Bite, new PBELocalizedString("Bite", "かみつく") },
            { PBEMove.Growl, new PBELocalizedString("Growl", "なきごえ") },
            { PBEMove.Roar, new PBELocalizedString("Roar", "ほえる") },
            { PBEMove.Sing, new PBELocalizedString("Sing", "うたう") },
            { PBEMove.Supersonic, new PBELocalizedString("Supersonic", "ちょうおんぱ") },
            // { PBEMove.49, new PBELocalizedString("SonicBoom", "ソニックブーム") },
            // { PBEMove.50, new PBELocalizedString("Disable", "かなしばり") },
            { PBEMove.Acid, new PBELocalizedString("Acid", "ようかいえき") },
            { PBEMove.Ember, new PBELocalizedString("Ember", "ひのこ") },
            { PBEMove.Flamethrower, new PBELocalizedString("Flamethrower", "かえんほうしゃ") },
            // { PBEMove.54, new PBELocalizedString("Mist", "しろいきり") },
            { PBEMove.WaterGun, new PBELocalizedString("Water Gun", "みずでっぽう") },
            { PBEMove.HydroPump, new PBELocalizedString("Hydro Pump", "ハイドロポンプ") },
            { PBEMove.Surf, new PBELocalizedString("Surf", "なみのり") },
            { PBEMove.IceBeam, new PBELocalizedString("Ice Beam", "れいとうビーム") },
            // { PBEMove.59, new PBELocalizedString("Blizzard", "ふぶき") },
            { PBEMove.Psybeam, new PBELocalizedString("Psybeam", "サイケこうせん") },
            { PBEMove.BubbleBeam, new PBELocalizedString("BubbleBeam", "バブルこうせん") },
            { PBEMove.AuroraBeam, new PBELocalizedString("Aurora Beam", "オーロラビーム") },
            // { PBEMove.63, new PBELocalizedString("Hyper Beam", "はかいこうせん") },
            { PBEMove.Peck, new PBELocalizedString("Peck", "つつく") },
            { PBEMove.DrillPeck, new PBELocalizedString("Drill Peck", "ドリルくちばし") },
            // { PBEMove.66, new PBELocalizedString("Submission", "じごくぐるま") },
            { PBEMove.LowKick, new PBELocalizedString("Low Kick", "けたぐり") },
            // { PBEMove.68, new PBELocalizedString("Counter", "カウンター") },
            // { PBEMove.69, new PBELocalizedString("Seismic Toss", "ちきゅうなげ") },
            { PBEMove.Strength, new PBELocalizedString("Strength", "かいりき") },
            // { PBEMove.71, new PBELocalizedString("Absorb", "すいとる") },
            // { PBEMove.72, new PBELocalizedString("Mega Drain", "メガドレイン") },
            { PBEMove.LeechSeed, new PBELocalizedString("Leech Seed", "やどりぎのタネ") },
            { PBEMove.Growth, new PBELocalizedString("Growth", "せいちょう") },
            { PBEMove.RazorLeaf, new PBELocalizedString("Razor Leaf", "はっぱカッター") },
            // { PBEMove.76, new PBELocalizedString("SolarBeam", "ソーラービーム") },
            { PBEMove.PoisonPowder, new PBELocalizedString("PoisonPowder", "どくのこな") },
            { PBEMove.StunSpore, new PBELocalizedString("Stun Spore", "しびれごな") },
            { PBEMove.SleepPowder, new PBELocalizedString("Sleep Powder", "ねむりごな") },
            // { PBEMove.80, new PBELocalizedString("Petal Dance", "はなびらのまい") },
            { PBEMove.StringShot, new PBELocalizedString("String Shot", "いとをはく") },
            // { PBEMove.82, new PBELocalizedString("Dragon Rage", "りゅうのいかり") },
            // { PBEMove.83, new PBELocalizedString("Fire Spin", "ほのおのうず") },
            { PBEMove.ThunderShock, new PBELocalizedString("ThunderShock", "でんきショック") },
            { PBEMove.Thunderbolt, new PBELocalizedString("Thunderbolt", "１０まんボルト") },
            { PBEMove.ThunderWave, new PBELocalizedString("Thunder Wave", "でんじは") },
            { PBEMove.Thunder, new PBELocalizedString("Thunder", "かみなり") },
            { PBEMove.RockThrow, new PBELocalizedString("Rock Throw", "いわおとし") },
            { PBEMove.Earthquake, new PBELocalizedString("Earthquake", "じしん") },
            // { PBEMove.90, new PBELocalizedString("Fissure", "じわれ") },
            { PBEMove.Dig, new PBELocalizedString("Dig", "あなをほる") },
            { PBEMove.Toxic, new PBELocalizedString("Toxic", "どくどく") },
            { PBEMove.Confusion, new PBELocalizedString("Confusion", "ねんりき") },
            { PBEMove.Psychic, new PBELocalizedString("Psychic", "サイコキネシス") },
            { PBEMove.Hypnosis, new PBELocalizedString("Hypnosis", "さいみんじゅつ") },
            { PBEMove.Meditate, new PBELocalizedString("Meditate", "ヨガのポーズ") },
            { PBEMove.Agility, new PBELocalizedString("Agility", "こうそくいどう") },
            { PBEMove.QuickAttack, new PBELocalizedString("Quick Attack", "でんこうせっか") },
            // { PBEMove.99, new PBELocalizedString("Rage", "いかり") },
            { PBEMove.Teleport, new PBELocalizedString("Teleport", "テレポート") },
            // { PBEMove.101, new PBELocalizedString("Night Shade", "ナイトヘッド") },
            // { PBEMove.102, new PBELocalizedString("Mimic", "ものまね") },
            { PBEMove.Screech, new PBELocalizedString("Screech", "いやなおと") },
            { PBEMove.DoubleTeam, new PBELocalizedString("Double Team", "かげぶんしん") },
            { PBEMove.Recover, new PBELocalizedString("Recover", "じこさいせい") },
            { PBEMove.Harden, new PBELocalizedString("Harden", "かたくなる") },
            { PBEMove.Minimize, new PBELocalizedString("Minimize", "ちいさくなる") },
            { PBEMove.SmokeScreen, new PBELocalizedString("SmokeScreen", "えんまく") },
            { PBEMove.ConfuseRay, new PBELocalizedString("Confuse Ray", "あやしいひかり") },
            { PBEMove.Withdraw, new PBELocalizedString("Withdraw", "からにこもる") },
            { PBEMove.DefenseCurl, new PBELocalizedString("Defense Curl", "まるくなる") },
            { PBEMove.Barrier, new PBELocalizedString("Barrier", "バリアー") },
            { PBEMove.LightScreen, new PBELocalizedString("Light Screen", "ひかりのかべ") },
            // { PBEMove.114, new PBELocalizedString("Haze", "くろいきり") },
            { PBEMove.Reflect, new PBELocalizedString("Reflect", "リフレクター") },
            { PBEMove.FocusEnergy, new PBELocalizedString("Focus Energy", "きあいだめ") },
            // { PBEMove.117, new PBELocalizedString("Bide", "がまん") },
            // { PBEMove.118, new PBELocalizedString("Metronome", "ゆびをふる") },
            // { PBEMove.119, new PBELocalizedString("Mirror Move", "オウムがえし") },
            // { PBEMove.120, new PBELocalizedString("Selfdestruct", "じばく") },
            { PBEMove.EggBomb, new PBELocalizedString("Egg Bomb", "タマゴばくだん") },
            { PBEMove.Lick, new PBELocalizedString("Lick", "したでなめる") },
            { PBEMove.Smog, new PBELocalizedString("Smog", "スモッグ") },
            { PBEMove.Sludge, new PBELocalizedString("Sludge", "ヘドロこうげき") },
            { PBEMove.BoneClub, new PBELocalizedString("Bone Club", "ホネこんぼう") },
            { PBEMove.FireBlast, new PBELocalizedString("Fire Blast", "だいもんじ") },
            { PBEMove.Waterfall, new PBELocalizedString("Waterfall", "たきのぼり") },
            // { PBEMove.128, new PBELocalizedString("Clamp", "からではさむ") },
            { PBEMove.Swift, new PBELocalizedString("Swift", "スピードスター") },
            // { PBEMove.130, new PBELocalizedString("Skull Bash", "ロケットずつき") },
            // { PBEMove.131, new PBELocalizedString("Spike Cannon", "とげキャノン") },
            // { PBEMove.132, new PBELocalizedString("Constrict", "からみつく") },
            { PBEMove.Amnesia, new PBELocalizedString("Amnesia", "ドわすれ") },
            { PBEMove.Kinesis, new PBELocalizedString("Kinesis", "スプーンまげ") },
            { PBEMove.Softboiled, new PBELocalizedString("Softboiled", "タマゴうみ") },
            // { PBEMove.136, new PBELocalizedString("Hi Jump Kick", "とびひざげり") },
            { PBEMove.Glare, new PBELocalizedString("Glare", "へびにらみ") },
            // { PBEMove.138, new PBELocalizedString("Dream Eater", "ゆめくい") },
            { PBEMove.PoisonGas, new PBELocalizedString("Poison Gas", "どくガス") },
            // { PBEMove.140, new PBELocalizedString("Barrage", "たまなげ") },
            // { PBEMove.141, new PBELocalizedString("Leech Life", "きゅうけつ") },
            { PBEMove.LovelyKiss, new PBELocalizedString("Lovely Kiss", "あくまのキッス") },
            // { PBEMove.143, new PBELocalizedString("Sky Attack", "ゴッドバード") },
            { PBEMove.Transform, new PBELocalizedString("Transform", "へんしん") },
            { PBEMove.Bubble, new PBELocalizedString("Bubble", "あわ") },
            { PBEMove.DizzyPunch, new PBELocalizedString("Dizzy Punch", "ピヨピヨパンチ") },
            { PBEMove.Spore, new PBELocalizedString("Spore", "キノコのほうし") },
            { PBEMove.Flash, new PBELocalizedString("Flash", "フラッシュ") },
            // { PBEMove.149, new PBELocalizedString("Psywave", "サイコウェーブ") },
            // { PBEMove.150, new PBELocalizedString("Splash", "はねる") },
            { PBEMove.AcidArmor, new PBELocalizedString("Acid Armor", "とける") },
            { PBEMove.Crabhammer, new PBELocalizedString("Crabhammer", "クラブハンマー") },
            // { PBEMove.153, new PBELocalizedString("Explosion", "だいばくはつ") },
            // { PBEMove.154, new PBELocalizedString("Fury Swipes", "みだれひっかき") },
            // { PBEMove.155, new PBELocalizedString("Bonemerang", "ホネブーメラン") },
            // { PBEMove.156, new PBELocalizedString("Rest", "ねむる") },
            { PBEMove.RockSlide, new PBELocalizedString("Rock Slide", "いわなだれ") },
            { PBEMove.HyperFang, new PBELocalizedString("Hyper Fang", "ひっさつまえば") },
            { PBEMove.Sharpen, new PBELocalizedString("Sharpen", "かくばる") },
            // { PBEMove.160, new PBELocalizedString("Conversion", "テクスチャー") },
            // { PBEMove.161, new PBELocalizedString("Tri Attack", "トライアタック") },
            // { PBEMove.162, new PBELocalizedString("Super Fang", "いかりのまえば") },
            { PBEMove.Slash, new PBELocalizedString("Slash", "きりさく") },
            { PBEMove.Substitute, new PBELocalizedString("Substitute", "みがわり") },
            { PBEMove.Struggle, new PBELocalizedString("Struggle", "わるあがき") },
            // { PBEMove.166, new PBELocalizedString("Sketch", "スケッチ") },
            // { PBEMove.167, new PBELocalizedString("Triple Kick", "トリプルキック") },
            // { PBEMove.168, new PBELocalizedString("Thief", "どろぼう") },
            // { PBEMove.169, new PBELocalizedString("Spider Web", "クモのす") },
            // { PBEMove.170, new PBELocalizedString("Mind Reader", "こころのめ") },
            // { PBEMove.171, new PBELocalizedString("Nightmare", "あくむ") },
            { PBEMove.FlameWheel, new PBELocalizedString("Flame Wheel", "かえんぐるま") },
            // { PBEMove.173, new PBELocalizedString("Snore", "いびき") },
            { PBEMove.Curse, new PBELocalizedString("Curse", "のろい") },
            // { PBEMove.175, new PBELocalizedString("Flail", "じたばた") },
            // { PBEMove.176, new PBELocalizedString("Conversion 2", "テクスチャー２") },
            { PBEMove.Aeroblast, new PBELocalizedString("Aeroblast", "エアロブラスト") },
            // { PBEMove.178, new PBELocalizedString("Cotton Spore", "わたほうし") },
            // { PBEMove.179, new PBELocalizedString("Reversal", "きしかいせい") },
            // { PBEMove.180, new PBELocalizedString("Spite", "うらみ") },
            { PBEMove.PowderSnow, new PBELocalizedString("Powder Snow", "こなゆき") },
            { PBEMove.Protect, new PBELocalizedString("Protect", "まもる") },
            { PBEMove.MachPunch, new PBELocalizedString("Mach Punch", "マッハパンチ") },
            { PBEMove.ScaryFace, new PBELocalizedString("Scary Face", "こわいかお") },
            { PBEMove.FaintAttack, new PBELocalizedString("FaintAttack", "だましうち") },
            { PBEMove.SweetKiss, new PBELocalizedString("Sweet Kiss", "てんしのキッス") },
            // { PBEMove.187, new PBELocalizedString("Belly Drum", "はらだいこ") },
            { PBEMove.SludgeBomb, new PBELocalizedString("Sludge Bomb", "ヘドロばくだん") },
            { PBEMove.MudSlap, new PBELocalizedString("Mud-Slap", "どろかけ") },
            { PBEMove.Octazooka, new PBELocalizedString("Octazooka", "オクタンほう") },
            { PBEMove.Spikes, new PBELocalizedString("Spikes", "まきびし") },
            { PBEMove.ZapCannon, new PBELocalizedString("Zap Cannon", "でんじほう") },
            // { PBEMove.193, new PBELocalizedString("Foresight", "みやぶる") },
            // { PBEMove.194, new PBELocalizedString("Destiny Bond", "みちづれ") },
            // { PBEMove.195, new PBELocalizedString("Perish Song", "ほろびのうた") },
            { PBEMove.IcyWind, new PBELocalizedString("Icy Wind", "こごえるかぜ") },
            { PBEMove.Detect, new PBELocalizedString("Detect", "みきり") },
            // { PBEMove.198, new PBELocalizedString("Bone Rush", "ボーンラッシュ") },
            // { PBEMove.199, new PBELocalizedString("Lock-On", "ロックオン") },
            // { PBEMove.200, new PBELocalizedString("Outrage", "げきりん") },
            { PBEMove.Sandstorm, new PBELocalizedString("Sandstorm", "すなあらし") },
            // { PBEMove.202, new PBELocalizedString("Giga Drain", "ギガドレイン") },
            // { PBEMove.203, new PBELocalizedString("Endure", "こらえる") },
            { PBEMove.Charm, new PBELocalizedString("Charm", "あまえる") },
            // { PBEMove.205, new PBELocalizedString("Rollout", "ころがる") },
            // { PBEMove.206, new PBELocalizedString("False Swipe", "みねうち") },
            { PBEMove.Swagger, new PBELocalizedString("Swagger", "いばる") },
            { PBEMove.MilkDrink, new PBELocalizedString("Milk Drink", "ミルクのみ") },
            { PBEMove.Spark, new PBELocalizedString("Spark", "スパーク") },
            // { PBEMove.210, new PBELocalizedString("Fury Cutter", "れんぞくぎり") },
            { PBEMove.SteelWing, new PBELocalizedString("Steel Wing", "はがねのつばさ") },
            // { PBEMove.212, new PBELocalizedString("Mean Look", "くろいまなざし") },
            // { PBEMove.213, new PBELocalizedString("Attract", "メロメロ") },
            // { PBEMove.214, new PBELocalizedString("Sleep Talk", "ねごと") },
            // { PBEMove.215, new PBELocalizedString("Heal Bell", "いやしのすず") },
            { PBEMove.Return, new PBELocalizedString("Return", "おんがえし") },
            // { PBEMove.217, new PBELocalizedString("Present", "プレゼント") },
            { PBEMove.Frustration, new PBELocalizedString("Frustration", "やつあたり") },
            // { PBEMove.219, new PBELocalizedString("Safeguard", "しんぴのまもり") },
            { PBEMove.PainSplit, new PBELocalizedString("Pain Split", "いたみわけ") },
            { PBEMove.SacredFire, new PBELocalizedString("Sacred Fire", "せいなるほのお") },
            { PBEMove.Magnitude, new PBELocalizedString("Magnitude", "マグニチュード") },
            { PBEMove.DynamicPunch, new PBELocalizedString("DynamicPunch", "ばくれつパンチ") },
            { PBEMove.Megahorn, new PBELocalizedString("Megahorn", "メガホーン") },
            { PBEMove.DragonBreath, new PBELocalizedString("DreagonBreath", "りゅうのいぶき") },
            // { PBEMove.226, new PBELocalizedString("Baton Pass", "バトンタッチ") },
            // { PBEMove.227, new PBELocalizedString("Encore", "アンコール") },
            // { PBEMove.228, new PBELocalizedString("Pursuit", "おいうち") },
            // { PBEMove.229, new PBELocalizedString("Rapid Spin", "こうそくスピン") },
            { PBEMove.SweetScent, new PBELocalizedString("Sweet Scent", "あまいかおり") },
            { PBEMove.IronTail, new PBELocalizedString("Iron Tail", "アイアンテール") },
            { PBEMove.MetalClaw, new PBELocalizedString("Metal Claw", "メタルクロー") },
            { PBEMove.VitalThrow, new PBELocalizedString("Vital Throw", "あてみなげ") },
            { PBEMove.MorningSun, new PBELocalizedString("Morning Sun", "あさのひざし") },
            { PBEMove.Synthesis, new PBELocalizedString("Synthesis", "こうごうせい") },
            { PBEMove.Moonlight, new PBELocalizedString("Moonlight", "つきのひかり") },
            { PBEMove.HiddenPower, new PBELocalizedString("Hidden Power", "めざめるパワー") },
            { PBEMove.CrossChop, new PBELocalizedString("Cross Chop", "クロスチョップ") },
            // { PBEMove.239, new PBELocalizedString("Twister", "たつまき") },
            { PBEMove.RainDance, new PBELocalizedString("Rain Dance", "あまごい") },
            { PBEMove.SunnyDay, new PBELocalizedString("Sunny Day", "にほんばれ") },
            { PBEMove.Crunch, new PBELocalizedString("Crunch", "かみくだく") },
            // { PBEMove.243, new PBELocalizedString("Mirror Coat", "ミラーコート") },
            { PBEMove.PsychUp, new PBELocalizedString("Psych Up", "じこあんじ") },
            { PBEMove.ExtremeSpeed, new PBELocalizedString("ExtremeSpeed", "しんそく") },
            { PBEMove.AncientPower, new PBELocalizedString("AncientPower", "げんしのちから") },
            { PBEMove.ShadowBall, new PBELocalizedString("Shadow Ball", "シャドーボール") },
            // { PBEMove.248, new PBELocalizedString("Future Sight", "みらいよち") },
            { PBEMove.RockSmash, new PBELocalizedString("Rock Smash", "いわくだき") },
            // { PBEMove.250, new PBELocalizedString("Whirlpool", "うずしお") },
            // { PBEMove.251, new PBELocalizedString("Beat Up", "ふくろだたき") },
            // { PBEMove.252, new PBELocalizedString("Fake Out", "ねこだまし") },
            // { PBEMove.253, new PBELocalizedString("Uproar", "さわぐ") },
            // { PBEMove.254, new PBELocalizedString("Stockpile", "たくわえる") },
            // { PBEMove.255, new PBELocalizedString("Spit Up", "はきだす") },
            // { PBEMove.256, new PBELocalizedString("Swallow", "のみこむ") },
            { PBEMove.HeatWave, new PBELocalizedString("Heat Wave", "ねっぷう") },
            { PBEMove.Hail, new PBELocalizedString("Hail", "あられ") },
            // { PBEMove.259, new PBELocalizedString("Torment", "いちゃもん") },
            { PBEMove.Flatter, new PBELocalizedString("Flatter", "おだてる") },
            { PBEMove.WillOWisp, new PBELocalizedString("Will-O-Wisp", "おにび") },
            // { PBEMove.262, new PBELocalizedString("Memento", "おきみやげ") },
            { PBEMove.Facade, new PBELocalizedString("Facade", "からげんき") },
            // { PBEMove.264, new PBELocalizedString("Focus Punch", "きあいパンチ") },
            // { PBEMove.265, new PBELocalizedString("SmellingSalt", "きつけ") },
            // { PBEMove.266, new PBELocalizedString("Follow Me", "このゆびとまれ") },
            // { PBEMove.267, new PBELocalizedString("Nature Power", "しぜんのちから") },
            // { PBEMove.268, new PBELocalizedString("Charge", "じゅうでん") },
            // { PBEMove.269, new PBELocalizedString("Taunt", "ちょうはつ") },
            // { PBEMove.270, new PBELocalizedString("Helping Hand", "てだすけ") },
            // { PBEMove.271, new PBELocalizedString("Trick", "トリック") },
            // { PBEMove.272, new PBELocalizedString("Role Play", "なりきり") },
            // { PBEMove.273, new PBELocalizedString("Wish", "ねがいごと") },
            // { PBEMove.274, new PBELocalizedString("Assist", "ねこのて") },
            // { PBEMove.275, new PBELocalizedString("Ingrain", "ねをはる") },
            { PBEMove.Superpower, new PBELocalizedString("Superpower", "ばかぢから") },
            // { PBEMove.277, new PBELocalizedString("Magic Coat", "マジックコート") },
            // { PBEMove.278, new PBELocalizedString("Recycle", "リサイクル") },
            // { PBEMove.279, new PBELocalizedString("Revenge", "リベンジ") },
            { PBEMove.BrickBreak, new PBELocalizedString("Brick Break", "かわらわり") },
            // { PBEMove.281, new PBELocalizedString("Yawn", "あくび") },
            // { PBEMove.282, new PBELocalizedString("Knock Off", "はたきおとす") },
            { PBEMove.Endeavor, new PBELocalizedString("Endeavor", "がむしゃら") },
            { PBEMove.Eruption, new PBELocalizedString("Eruption", "ふんか") },
            // { PBEMove.285, new PBELocalizedString("Skill Swap", "スキルスワップ") },
            // { PBEMove.286, new PBELocalizedString("Imprison", "ふういん") },
            // { PBEMove.287, new PBELocalizedString("Refresh", "リフレッシュ") },
            // { PBEMove.288, new PBELocalizedString("Grudge", "おんねん") },
            // { PBEMove.289, new PBELocalizedString("Snatch", "よこどり") },
            // { PBEMove.290, new PBELocalizedString("Secret Power", "ひみつのちから") },
            { PBEMove.Dive, new PBELocalizedString("Dive", "ダイビング") },
            // { PBEMove.292, new PBELocalizedString("Arm Thrust", "つっぱり") },
            // { PBEMove.293, new PBELocalizedString("Camouflage", "ほごしょく") },
            { PBEMove.TailGlow, new PBELocalizedString("Tail Glow", "ほたるび") },
            { PBEMove.LusterPurge, new PBELocalizedString("Luster Purge", "ラスターパージ") },
            { PBEMove.MistBall, new PBELocalizedString("Mist Ball", "ミストボール") },
            { PBEMove.FeatherDance, new PBELocalizedString("FeatherDance", "フェザーダンス") },
            { PBEMove.TeeterDance, new PBELocalizedString("Teeter Dance", "フラフラダンス") },
            { PBEMove.BlazeKick, new PBELocalizedString("Blaze Kick", "ブレイズキック") },
            // { PBEMove.300, new PBELocalizedString("Mud Sport", "どろあそび") },
            // { PBEMove.301, new PBELocalizedString("Ice Ball", "アイスボール") },
            { PBEMove.NeedleArm, new PBELocalizedString("Needle Arm", "ニードルアーム") },
            { PBEMove.SlackOff, new PBELocalizedString("Slack Off", "なまける") },
            { PBEMove.HyperVoice, new PBELocalizedString("Hyper Voice", "ハイパーボイス") },
            { PBEMove.PoisonFang, new PBELocalizedString("Poison Fang", "どくどくのキバ") },
            { PBEMove.CrushClaw, new PBELocalizedString("Crush Claw", "ブレイククロー") },
            // { PBEMove.307, new PBELocalizedString("Blast Burn", "ブラストバーン") },
            // { PBEMove.308, new PBELocalizedString("Hydro Cannon", "ハイドロカノン") },
            { PBEMove.MeteorMash, new PBELocalizedString("Meteor Mash", "コメットパンチ") },
            { PBEMove.Astonish, new PBELocalizedString("Astonish", "おどろかす") },
            { PBEMove.WeatherBall, new PBELocalizedString("Weather Ball", "ウェザーボール") },
            // { PBEMove.312, new PBELocalizedString("Aromatherapy", "アロマセラピー") },
            { PBEMove.FakeTears, new PBELocalizedString("Fake Tears", "うそなき") },
            { PBEMove.AirCutter, new PBELocalizedString("Air Cutter", "エアカッター") },
            { PBEMove.Overheat, new PBELocalizedString("Overheat", "オーバーヒート") },
            // { PBEMove.316, new PBELocalizedString("Odor Sleuth", "かぎわける") },
            { PBEMove.RockTomb, new PBELocalizedString("Rock Tomb", "がんせきふうじ") },
            { PBEMove.SilverWind, new PBELocalizedString("Silver Wind", "ぎんいろのかぜ") },
            { PBEMove.MetalSound, new PBELocalizedString("Metal Sound", "きんぞくおん") },
            { PBEMove.GrassWhistle, new PBELocalizedString("GrassWhistle", "くさぶえ") },
            { PBEMove.Tickle, new PBELocalizedString("Tickle", "くすぐる") },
            { PBEMove.CosmicPower, new PBELocalizedString("Cosmic Power", "コスモパワー") },
            { PBEMove.WaterSpout, new PBELocalizedString("Water Spout", "しおふき") },
            { PBEMove.SignalBeam, new PBELocalizedString("Signal Beam", "シグナルビーム") },
            { PBEMove.ShadowPunch, new PBELocalizedString("Shadow Punch", "シャドーパンチ") },
            { PBEMove.Extrasensory, new PBELocalizedString("Extrasensory", "じんつうりき") },
            { PBEMove.SkyUppercut, new PBELocalizedString("Sky Uppercut", "スカイアッパー") },
            // { PBEMove.328, new PBELocalizedString("Sand Tomb", "すなじごく") },
            // { PBEMove.329, new PBELocalizedString("Sheer Cold", "ぜったいれいど") },
            { PBEMove.MuddyWater, new PBELocalizedString("Muddy Water", "だくりゅう") },
            // { PBEMove.331, new PBELocalizedString("Bullet Seed", "タネマシンガン") },
            { PBEMove.AerialAce, new PBELocalizedString("Aerial Ace", "つばめがえし") },
            // { PBEMove.333, new PBELocalizedString("Icicle Spear", "つららばり") },
            { PBEMove.IronDefense, new PBELocalizedString("Iron Defense", "てっぺき") },
            // { PBEMove.335, new PBELocalizedString("Block", "とおせんぼう") },
            { PBEMove.Howl, new PBELocalizedString("Howl", "とおぼえ") },
            { PBEMove.DragonClaw, new PBELocalizedString("Dragon Claw", "ドラゴンクロー") },
            // { PBEMove.338, new PBELocalizedString("Frenzy Plant", "ハードプラント") },
            { PBEMove.BulkUp, new PBELocalizedString("Bulk Up", "ビルドアップ") },
            // { PBEMove.340, new PBELocalizedString("Bounce", "とびはねる") },
            { PBEMove.MudShot, new PBELocalizedString("Mud Shot", "マッドショット") },
            { PBEMove.PoisonTail, new PBELocalizedString("Poison Tail", "ポイズンテール") },
            // { PBEMove.343, new PBELocalizedString("Covet", "ほしがる") },
            // { PBEMove.344, new PBELocalizedString("Volt Tackle", "ボルテッカー") },
            { PBEMove.MagicalLeaf, new PBELocalizedString("Magical Leaf", "マジカルリーフ") },
            { PBEMove.LavaPlume, new PBELocalizedString("Water Sport", "みずあそび") },
            { PBEMove.CalmMind, new PBELocalizedString("Calm Mind", "めいそう") },
            { PBEMove.LeafBlade, new PBELocalizedString("Leaf Blade", "リーフブレード") },
            { PBEMove.DragonDance, new PBELocalizedString("Dragon Dance", "りゅうのまい") },
            // { PBEMove.350, new PBELocalizedString("Rock Blast", "ロックブラスト") },
            { PBEMove.ShockWave, new PBELocalizedString("Shock Wave", "でんげきは") },
            { PBEMove.WaterPulse, new PBELocalizedString("Water Pulse", "みずのはどう") },
            // { PBEMove.353, new PBELocalizedString("Doom Desire", "はめつのねがい") },
            { PBEMove.PsychoBoost, new PBELocalizedString("Psycho Boost", "サイコブースト") },
            // { PBEMove.355, new PBELocalizedString("Roost", "はねやすめ") },
            // { PBEMove.356, new PBELocalizedString("Gravity", "じゅうりょく") },
            // { PBEMove.357, new PBELocalizedString("Miracle Eye", "ミラクルアイ") },
            // { PBEMove.358, new PBELocalizedString("Wake-Up Slap", "めざましビンタ") },
            { PBEMove.HammerArm, new PBELocalizedString("Hammer Arm", "アームハンマー") },
            // { PBEMove.360, new PBELocalizedString("Gyro Ball", "ジャイロボール") },
            // { PBEMove.361, new PBELocalizedString("Healing Wish", "いやしのねがい") },
            { PBEMove.Brine, new PBELocalizedString("Brine", "しおみず") },
            // { PBEMove.363, new PBELocalizedString("Natural Gift", "しぜんのめぐみ") },
            // { PBEMove.364, new PBELocalizedString("Feint", "フェイント") },
            // { PBEMove.365, new PBELocalizedString("Pluck", "ついばむ") },
            // { PBEMove.366, new PBELocalizedString("Tailwind", "おいかぜ") },
            // { PBEMove.367, new PBELocalizedString("Acupressure", "つぼをつく") },
            // { PBEMove.368, new PBELocalizedString("Metal Burst", "メタルバースト") },
            // { PBEMove.369, new PBELocalizedString("U-turn", "とんぼがえり") },
            { PBEMove.CloseCombat, new PBELocalizedString("Close Combat", "インファイト") },
            // { PBEMove.371, new PBELocalizedString("Payback", "しっぺがえし") },
            // { PBEMove.372, new PBELocalizedString("Assurance", "ダメおし") },
            // { PBEMove.373, new PBELocalizedString("Embargo", "さしおさえ") },
            // { PBEMove.374, new PBELocalizedString("Fling", "なげつける") },
            // { PBEMove.375, new PBELocalizedString("Psycho Shift", "サイコシフト") },
            // { PBEMove.376, new PBELocalizedString("Trump Card", "きりふだ") },
            // { PBEMove.377, new PBELocalizedString("Heal Block", "かいふくふうじ") },
            // { PBEMove.378, new PBELocalizedString("Wring Out", "しぼりとる") },
            // { PBEMove.379, new PBELocalizedString("Power Trick", "パワートリック") },
            // { PBEMove.380, new PBELocalizedString("Gastro Acid", "いえき") },
            { PBEMove.LuckyChant, new PBELocalizedString("Lucky Chant", "おまじない") },
            // { PBEMove.382, new PBELocalizedString("Me First", "さきどり") },
            // { PBEMove.383, new PBELocalizedString("Copycat", "まねっこ") },
            // { PBEMove.384, new PBELocalizedString("Power Swap", "パワースワップ") },
            // { PBEMove.385, new PBELocalizedString("Guard Swap", "ガードスワップ") },
            // { PBEMove.386, new PBELocalizedString("Punishment", "おしおき") },
            // { PBEMove.387, new PBELocalizedString("Last Resort", "とっておき") },
            // { PBEMove.388, new PBELocalizedString("Worry Seed", "なやみのタネ") },
            // { PBEMove.389, new PBELocalizedString("Sucker Punch", "ふいうち") },
            { PBEMove.ToxicSpikes, new PBELocalizedString("Toxic Spikes", "どくびし") },
            // { PBEMove.391, new PBELocalizedString("Heart Swap", "ハートスワップ") },
            // { PBEMove.392, new PBELocalizedString("Aqua Ring", "アクアリング") },
            // { PBEMove.393, new PBELocalizedString("Magnet Rise", "でんじふゆう") },
            // { PBEMove.394, new PBELocalizedString("Flare Blitz", "フレアドライブ") },
            { PBEMove.ForcePalm, new PBELocalizedString("Force Palm", "はっけい") },
            { PBEMove.AuraSphere, new PBELocalizedString("Aura Sphere", "はどうだん") },
            { PBEMove.RockPolish, new PBELocalizedString("Rock Polish", "ロックカット") },
            { PBEMove.PoisonJab, new PBELocalizedString("Poison Jab", "どくづき") },
            { PBEMove.DarkPulse, new PBELocalizedString("Dark Pulse", "あくのはどう") },
            { PBEMove.NightSlash, new PBELocalizedString("Night Slash", "つじぎり") },
            { PBEMove.AquaTail, new PBELocalizedString("Aqua Tail", "アクアテール") },
            { PBEMove.SeedBomb, new PBELocalizedString("Seed Bomb", "タネばくだん") },
            { PBEMove.AirSlash, new PBELocalizedString("Air Slash", "エアスラッシュ") },
            { PBEMove.XScissor, new PBELocalizedString("X-Scissor", "シザークロス") },
            { PBEMove.BugBuzz, new PBELocalizedString("Bug Buzz", "むしのさざめき") },
            { PBEMove.DragonPulse, new PBELocalizedString("Dragon Pulse", "りゅうのはどう") },
            { PBEMove.DragonRush, new PBELocalizedString("Dragon Rush", "ドラゴンダイブ") },
            { PBEMove.PowerGem, new PBELocalizedString("Power Gem", "パワージェム") },
            // { PBEMove.409, new PBELocalizedString("Drain Punch", "ドレインパンチ") },
            { PBEMove.VacuumWave, new PBELocalizedString("Vacuum Wave", "しんくうは") },
            { PBEMove.FocusBlast, new PBELocalizedString("Focus Blast", "きあいだま") },
            { PBEMove.EnergyBall, new PBELocalizedString("Energy Ball", "エナジーボール") },
            // { PBEMove.413, new PBELocalizedString("Brave Bird", "ブレイブバード") },
            { PBEMove.EarthPower, new PBELocalizedString("Earth Power", "だいちのちから") },
            // { PBEMove.415, new PBELocalizedString("Switcheroo", "すりかえ") },
            // { PBEMove.416, new PBELocalizedString("Giga Impact", "ギガインパクト") },
            { PBEMove.NastyPlot, new PBELocalizedString("Nasty Plot", "わるだくみ") },
            { PBEMove.BulletPunch, new PBELocalizedString("Bullet Punch", "バレットパンチ") },
            // { PBEMove.419, new PBELocalizedString("Avalanche", "ゆきなだれ") },
            { PBEMove.IceShard, new PBELocalizedString("Ice Shard", "こおりのつぶて") },
            { PBEMove.ShadowClaw, new PBELocalizedString("Shadow Claw", "シャドークロー") },
            // { PBEMove.422, new PBELocalizedString("Thunder Fang", "かみなりのキバ") },
            // { PBEMove.423, new PBELocalizedString("Ice Fang", "こおりのキバ") },
            // { PBEMove.424, new PBELocalizedString("Fire Fang", "ほのおのキバ") },
            { PBEMove.ShadowSneak, new PBELocalizedString("Shadow Sneak", "かげうち") },
            { PBEMove.MudBomb, new PBELocalizedString("Mud Bomb", "どろばくだん") },
            { PBEMove.PsychoCut, new PBELocalizedString("Psycho Cut", "サイコカッター") },
            { PBEMove.ZenHeadbutt, new PBELocalizedString("Zen Headbutt", "しねんのずつき") },
            { PBEMove.MirrorShot, new PBELocalizedString("Mirror Shot", "ミラーショット") },
            { PBEMove.FlashCannon, new PBELocalizedString("Flash Cannon", "ラスターカノン") },
            { PBEMove.RockClimb, new PBELocalizedString("Rock Climb", "ロッククライム") },
            // { PBEMove.432, new PBELocalizedString("Defog", "きりばらい") },
            // { PBEMove.433, new PBELocalizedString("Trick Room", "トリックルーム") },
            { PBEMove.DracoMeteor, new PBELocalizedString("Draco Meteor", "りゅうせいぐん") },
            { PBEMove.Discharge, new PBELocalizedString("Discharge", "ほうでん") },
            // { PBEMove.436, new PBELocalizedString("Lava Plume", "ふんえん") },
            { PBEMove.LeafStorm, new PBELocalizedString("Leaf Storm", "リーフストーム") },
            { PBEMove.PowerWhip, new PBELocalizedString("Power Whip", "パワーウィップ") },
            // { PBEMove.439, new PBELocalizedString("Rock Wrecker", "がんせきほう") },
            { PBEMove.CrossPoison, new PBELocalizedString("Cross Poison", "クロスポイズン") },
            { PBEMove.GunkShot, new PBELocalizedString("Gunk Shot", "ダストシュート") },
            { PBEMove.IronHead, new PBELocalizedString("Iron Head", "アイアンヘッド") },
            { PBEMove.MagnetBomb, new PBELocalizedString("Magnet Bomb", "マグネットボム") },
            { PBEMove.StoneEdge, new PBELocalizedString("Stone Edge", "ストーンエッジ") },
            // { PBEMove.445, new PBELocalizedString("Captivate", "ゆうわく") },
            { PBEMove.StealthRock, new PBELocalizedString("Stealth Rock", "ステルスロック") },
            { PBEMove.GrassKnot, new PBELocalizedString("Grass Knot", "くさむすび") },
            { PBEMove.Chatter, new PBELocalizedString("Chatter", "おしゃべり") },
            // { PBEMove.449, new PBELocalizedString("Judgment", "さばきのつぶて") },
            // { PBEMove.450, new PBELocalizedString("Bug Bite", "むしくい") },
            { PBEMove.ChargeBeam, new PBELocalizedString("Charge Beam", "チャージビーム") },
            // { PBEMove.452, new PBELocalizedString("Wood Hammer", "ウッドハンマー") },
            { PBEMove.AquaJet, new PBELocalizedString("Aqua Jet", "アクアジェット") },
            { PBEMove.AttackOrder, new PBELocalizedString("Attack Order", "こうげきしれい") },
            { PBEMove.DefendOrder, new PBELocalizedString("Defend Order", "ぼうぎょしれい") },
            { PBEMove.HealOrder, new PBELocalizedString("Heal Order", "かいふくしれい") },
            // { PBEMove.457, new PBELocalizedString("Head Smash", "もろはのずつき") },
            // { PBEMove.458, new PBELocalizedString("Double Hit", "ダブルアタック") },
            // { PBEMove.459, new PBELocalizedString("Roar of Time", "ときのほうこう") },
            { PBEMove.SpacialRend, new PBELocalizedString("Spacial Rend", "あくうせつだん") },
            // { PBEMove.461, new PBELocalizedString("Lunar Dance", "みかづきのまい") },
            // { PBEMove.462, new PBELocalizedString("Crush Grip", "にぎりつぶす") },
            // { PBEMove.463, new PBELocalizedString("Magma Storm", "マグマストーム") },
            { PBEMove.DarkVoid, new PBELocalizedString("Dark Void", "ダークホール") },
            { PBEMove.SeedFlare, new PBELocalizedString("Seed Flare", "シードフレア") },
            { PBEMove.OminousWind, new PBELocalizedString("Ominous Wind", "あやしいかぜ") },
            // { PBEMove.467, new PBELocalizedString("Shadow Force", "シャドーダイブ") },
            { PBEMove.HoneClaws, new PBELocalizedString("Hone Claws", "つめとぎ") },
            // { PBEMove.469, new PBELocalizedString("Wide Guard", "ワイドガード") },
            // { PBEMove.470, new PBELocalizedString("Guard Split", "ガードシェア") },
            // { PBEMove.471, new PBELocalizedString("Power Split", "パワーシェア") },
            // { PBEMove.472, new PBELocalizedString("Wonder Room", "ワンダールーム") },
            { PBEMove.Psyshock, new PBELocalizedString("Psyshock", "サイコショック") },
            { PBEMove.Venoshock, new PBELocalizedString("Venoshock", "ベノムショック") },
            // { PBEMove.475, new PBELocalizedString("Autotomize", "ボディパージ") },
            // { PBEMove.476, new PBELocalizedString("Rage Powder", "いかりのこな") },
            // { PBEMove.477, new PBELocalizedString("Telekinesis", "テレキネシス") },
            // { PBEMove.478, new PBELocalizedString("Magic Room", "マジックルーム") },
            // { PBEMove.479, new PBELocalizedString("Smack Down", "うちおとす") },
            { PBEMove.StormThrow, new PBELocalizedString("Storm Throw", "やまあらし") },
            // { PBEMove.481, new PBELocalizedString("Flame Burst", "はじけるほのお") },
            { PBEMove.SludgeWave, new PBELocalizedString("Sludge Wave", "ヘドロウェーブ") },
            { PBEMove.QuiverDance, new PBELocalizedString("Quiver Dance", "ちょうのまい") },
            { PBEMove.HeavySlam, new PBELocalizedString("Heavy Slam", "ヘビーボンバー") },
            // { PBEMove.485, new PBELocalizedString("Synchronoise", "シンクロノイズ") },
            // { PBEMove.486, new PBELocalizedString("Electro Ball", "エレキボール") },
            // { PBEMove.487, new PBELocalizedString("Soak", "みずびたし") },
            { PBEMove.FlameCharge, new PBELocalizedString("Flame Charge", "ニトロチャージ") },
            { PBEMove.Coil, new PBELocalizedString("Coil", "とぐろをまく") },
            { PBEMove.LowSweep, new PBELocalizedString("Low Sweep", "ローキック") },
            { PBEMove.AcidSpray, new PBELocalizedString("Acid Spray", "アシッドボム") },
            // { PBEMove.492, new PBELocalizedString("Foul Play", "イカサマ") },
            // { PBEMove.493, new PBELocalizedString("Simple Beam", "シンプルビーム") },
            // { PBEMove.494, new PBELocalizedString("Entrainment", "なかまづくり") },
            // { PBEMove.495, new PBELocalizedString("After You", "おさきにどうぞ") },
            // { PBEMove.496, new PBELocalizedString("Round", "りんしょう") },
            // { PBEMove.497, new PBELocalizedString("Echoed Voice", "エコーボイス") },
            // { PBEMove.498, new PBELocalizedString("Chip Away", "なしくずし") },
            // { PBEMove.499, new PBELocalizedString("Clear Smog", "クリアスモッグ") },
            // { PBEMove.500, new PBELocalizedString("Stored Power", "アシストパワー") },
            // { PBEMove.501, new PBELocalizedString("Quick Guard", "ファストガード") },
            // { PBEMove.502, new PBELocalizedString("Ally Switch", "サイドチェンジ") },
            { PBEMove.Scald, new PBELocalizedString("Scald", "ねっとう") },
            { PBEMove.ShellSmash, new PBELocalizedString("Shell Smash", "からをやぶる") },
            // { PBEMove.505, new PBELocalizedString("Heal Pulse", "いやしのはどう") },
            { PBEMove.Hex, new PBELocalizedString("Hex", "たたりめ") },
            // { PBEMove.507, new PBELocalizedString("Sky Drop", "フリーフォール") },
            { PBEMove.ShiftGear, new PBELocalizedString("Shift Gear", "ギアチェンジ") },
            // { PBEMove.509, new PBELocalizedString("Circle Throw", "ともえなげ") },
            // { PBEMove.510, new PBELocalizedString("Incinerate", "やきつくす") },
            // { PBEMove.511, new PBELocalizedString("Quash", "さきおくり") },
            // { PBEMove.512, new PBELocalizedString("Acrobatics", "アクロバット") },
            // { PBEMove.513, new PBELocalizedString("Reflect Type", "ミラータイプ") },
            { PBEMove.Retaliate, new PBELocalizedString("Retaliate", "かたきうち") },
            // { PBEMove.515, new PBELocalizedString("Final Gambit", "いのちがけ") },
            // { PBEMove.516, new PBELocalizedString("Bestow", "ギフトパス") },
            { PBEMove.Inferno, new PBELocalizedString("Inferno", "れんごく") },
            // { PBEMove.518, new PBELocalizedString("Water Pledge", "みずのちかい") },
            // { PBEMove.519, new PBELocalizedString("Fire Pledge", "ほのおのちかい") },
            // { PBEMove.520, new PBELocalizedString("Grass Pledge", "くさのちかい") },
            // { PBEMove.521, new PBELocalizedString("Volt Switch", "ボルトチェンジ") },
            { PBEMove.StruggleBug, new PBELocalizedString("Struggle Bug", "むしのていこう") },
            { PBEMove.Bulldoze, new PBELocalizedString("Bulldoze", "じならし") },
            { PBEMove.FrostBreath, new PBELocalizedString("Frost Breath", "こおりのいぶき") },
            // { PBEMove.525, new PBELocalizedString("Dragon Tail", "ドラゴンテール") },
            { PBEMove.WorkUp, new PBELocalizedString("Work Up", "ふるいたてる") },
            { PBEMove.Electroweb, new PBELocalizedString("Electroweb", "エレキネット") },
            // { PBEMove.528, new PBELocalizedString("Wild Charge", "ワイルドボルト") },
            { PBEMove.DrillRun, new PBELocalizedString("Drill Run", "ドリルライナー") },
            // { PBEMove.530, new PBELocalizedString("Dual Chop", "ダブルチョップ") },
            { PBEMove.HeartStamp, new PBELocalizedString("Heart Stamp", "ハートスタンプ") },
            // { PBEMove.532, new PBELocalizedString("Horn Leech", "ウッドホーン") },
            // { PBEMove.533, new PBELocalizedString("Sacred Sword", "せいなるつるぎ") },
            { PBEMove.RazorShell, new PBELocalizedString("Razor Shell", "シェルブレード") },
            { PBEMove.HeatCrash, new PBELocalizedString("Heat Crash", "ヒートスタンプ") },
            { PBEMove.LeafTornado, new PBELocalizedString("Leaf Tornado", "グラスミキサー") },
            { PBEMove.Steamroller, new PBELocalizedString("Steamroller", "ハードローラー") },
            { PBEMove.CottonGuard, new PBELocalizedString("Cotton Guard", "コットンガード") },
            { PBEMove.NightDaze, new PBELocalizedString("Night Daze", "ナイトバースト") },
            { PBEMove.Psystrike, new PBELocalizedString("Psystrike", "サイコブレイク") },
            // { PBEMove.541, new PBELocalizedString("Tail Slap", "スイープビンタ") },
            // { PBEMove.542, new PBELocalizedString("Hurricane", "ぼうふう") },
            // { PBEMove.543, new PBELocalizedString("Head Charge", "アフロブレイク") },
            // { PBEMove.544, new PBELocalizedString("Gear Grind", "ギアソーサー") },
            { PBEMove.SearingShot, new PBELocalizedString("Searing Shot", "かえんだん") },
            { PBEMove.TechnoBlast, new PBELocalizedString("Techno Blast", "テクノバスター") },
            // { PBEMove.547, new PBELocalizedString("Relic Song", "いにしえのうた") },
            { PBEMove.SecretSword, new PBELocalizedString("Secret Sword", "しんぴのつるぎ") },
            { PBEMove.Glaciate, new PBELocalizedString("Glaciate", "こごえるせかい") },
            { PBEMove.BoltStrike, new PBELocalizedString("Bolt Strike", "らいげき") },
            { PBEMove.BlueFlare, new PBELocalizedString("Blue Flare", "あおいほのお") },
            { PBEMove.FieryDance, new PBELocalizedString("Fiery Dance", "ほのおのまい") },
            // { PBEMove.553, new PBELocalizedString("Freeze Shock", "フリーズボルト") },
            // { PBEMove.554, new PBELocalizedString("Ice Burn", "コールドフレア") },
            { PBEMove.Snarl, new PBELocalizedString("Snarl", "バークアウト") },
            { PBEMove.IcicleCrash, new PBELocalizedString("Icicle Crash", "つららおとし") },
            { PBEMove.VCreate, new PBELocalizedString("V-create", "Ｖジェネレート") },
            // { PBEMove.558, new PBELocalizedString("Fusion Flare", "クロスフレイム") },
            // { PBEMove.559, new PBELocalizedString("Fusion Bolt", "クロスサンダー") }
        });
    }
}
