using Kermalis.PokemonBattleEngine.Data;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Kermalis.PokemonBattleEngine.Localization
{
    public static class PBEMoveLocalization
    {
        public static ReadOnlyDictionary<PBEMove, PBELocalizedString> Names { get; } = new ReadOnlyDictionary<PBEMove, PBELocalizedString>(new Dictionary<PBEMove, PBELocalizedString>()
        {
            { PBEMove.None, new PBELocalizedString("--", "--", "--", "--", "--", "--", "--") },
            { PBEMove.Pound, new PBELocalizedString("はたく", "막치기", "Écras’Face", "Pfund", "Destructor", "Botta", "Pound") },
            { PBEMove.KarateChop, new PBELocalizedString("からてチョップ", "태권당수", "Poing-Karaté", "Karateschlag", "Golpe Karate", "Colpokarate", "Karate Chop") },
            // { PBEMove.3, new PBELocalizedString("おうふくビンタ", "연속뺨치기", "Torgnoles", "Duplexhieb", "Doblebofetón", "Doppiasberla", "DoubleSlap") },
            // { PBEMove.4, new PBELocalizedString("れんぞくパンチ", "연속펀치", "Poing Comète", "Kometenhieb", "Puño Cometa", "Cometapugno", "Comet Punch") },
            { PBEMove.MegaPunch, new PBELocalizedString("メガトンパンチ", "메가톤펀치", "Ultimapoing", "Megahieb", "Megapuño", "Megapugno", "Mega Punch") },
            // { PBEMove.6, new PBELocalizedString("ネコにこばん", "고양이돈받기", "Jackpot", "Zahltag", "Día de Pago", "Giornopaga", "Pay Day") },
            { PBEMove.FirePunch, new PBELocalizedString("ほのおのパンチ", "불꽃펀치", "Poing de Feu", "Feuerschlag", "Puño Fuego", "Fuocopugno", "Fire Punch") },
            { PBEMove.IcePunch, new PBELocalizedString("れいとうパンチ", "냉동펀치", "Poinglace", "Eishieb", "Puño Hielo", "Gelopugno", "Ice Punch") },
            { PBEMove.ThunderPunch, new PBELocalizedString("かみなりパンチ", "번개펀치", "Poing-Éclair", "Donnerschlag", "Puño Trueno", "Tuonopugno", "ThunderPunch") },
            { PBEMove.Scratch, new PBELocalizedString("ひっかく", "할퀴기", "Griffe", "Kratzer", "Arañazo", "Graffio", "Scratch") },
            { PBEMove.ViceGrip, new PBELocalizedString("はさむ", "찝기", "Force Poigne", "Klammer", "Agarre", "Presa", "ViceGrip") },
            { PBEMove.Guillotine, new PBELocalizedString("ハサミギロチン", "가위자르기", "Guillotine", "Guillotine", "Guillotina", "Ghigliottina", "Guillotine") },
            // { PBEMove.13, new PBELocalizedString("かまいたち", "칼바람", "Coupe-Vent", "Klingensturm", "V. Cortante", "Ventagliente", "Razor Wind") },
            { PBEMove.SwordsDance, new PBELocalizedString("つるぎのまい", "칼춤", "Danse-Lames", "Schwerttanz", "Danza Espada", "Danzaspada", "Swords Dance") },
            { PBEMove.Cut, new PBELocalizedString("いあいぎり", "풀베기", "Coupe", "Zerschneider", "Corte", "Taglio", "Cut") },
            { PBEMove.Gust, new PBELocalizedString("かぜおこし", "바람일으키기", "Tornade", "Windstoß", "Tornado", "Raffica", "Gust") },
            { PBEMove.WingAttack, new PBELocalizedString("つばさでうつ", "날개치기", "Cru-Aile", "Flügelschlag", "Ataque Ala", "Att. d'Ala", "Wing Attack") },
            { PBEMove.Whirlwind, new PBELocalizedString("ふきとばし", "날려버리기", "Cyclone", "Wirbelwind", "Remolino", "Turbine", "Whirlwind") },
            { PBEMove.Fly, new PBELocalizedString("そらをとぶ", "공중날기", "Vol", "Fliegen", "Vuelo", "Volo", "Fly") },
            // { PBEMove.20, new PBELocalizedString("しめつける", "조이기", "Étreinte", "Klammergriff", "Atadura", "Legatutto", "Bind") },
            { PBEMove.Slam, new PBELocalizedString("たたきつける", "힘껏치기", "Souplesse", "Slam", "Portazo", "Schianto", "Slam") },
            { PBEMove.VineWhip, new PBELocalizedString("つるのムチ", "덩굴채찍", "Fouet Lianes", "Rankenhieb", "Látigo Cepa", "Frustata", "Vine Whip") },
            { PBEMove.Stomp, new PBELocalizedString("ふみつけ", "짓밟기", "Écrasement", "Stampfer", "Pisotón", "Pestone", "Stomp") },
            // { PBEMove.24, new PBELocalizedString("にどげり", "두번치기", "Double Pied", "Doppelkick", "Doble Patada", "Doppiocalcio", "Double Kick") },
            { PBEMove.MegaKick, new PBELocalizedString("メガトンキック", "메가톤킥", "Ultimawashi", "Megakick", "Megapatada", "Megacalcio", "Mega Kick") },
            // { PBEMove.26, new PBELocalizedString("とびげり", "점프킥", "Pied Sauté", "Sprungkick", "Patada Salto", "Calciosalto", "Jump Kick") },
            // { PBEMove.27, new PBELocalizedString("まわしげり", "돌려차기", "Mawashi Geri", "Fegekick", "Patada Giro", "Calciorullo", "Rolling Kick") },
            { PBEMove.SandAttack, new PBELocalizedString("すなかけ", "모래뿌리기", "Jet de Sable", "Sandwirbel", "Ataque Arena", "Turbosabbia", "Sand-Attack") },
            { PBEMove.Headbutt, new PBELocalizedString("ずつき", "박치기", "Coup d’Boule", "Kopfnuss", "Golpe Cabeza", "Bottintesta", "Headbutt") },
            { PBEMove.HornAttack, new PBELocalizedString("つのでつく", "뿔찌르기", "Koud’Korne", "Hornattacke", "Cornada", "Incornata", "Horn Attack") },
            // { PBEMove.31, new PBELocalizedString("みだれづき", "마구찌르기", "Furie", "Furienschlag", "Ataque Furia", "Furia", "Fury Attack") },
            { PBEMove.HornDrill, new PBELocalizedString("つのドリル", "뿔드릴", "Empal’Korne", "Hornbohrer", "Perforador", "Perforcorno", "Horn Drill") },
            { PBEMove.Tackle, new PBELocalizedString("たいあたり", "몸통박치기", "Charge", "Tackle", "Placaje", "Azione", "Tackle") },
            { PBEMove.BodySlam, new PBELocalizedString("のしかかり", "누르기", "Plaquage", "Bodyslam", "Golpe Cuerpo", "Corposcontro", "Body Slam") },
            // { PBEMove.35, new PBELocalizedString("まきつく", "김밥말이", "Ligotage", "Wickel", "Repetición", "Avvolgibotta", "Wrap") },
            // { PBEMove.36, new PBELocalizedString("とっしん", "돌진", "Bélier", "Bodycheck", "Derribo", "Riduttore", "Take Down") },
            // { PBEMove.37, new PBELocalizedString("あばれる", "난동부리기", "Mania", "Fuchtler", "Golpe", "Colpo", "Thrash") },
            { PBEMove.DoubleEdge, new PBELocalizedString("すてみタックル", "이판사판태클", "Damoclès", "Risikotackle", "Doble Filo", "Sdoppiatore", "Double-Edge") },
            { PBEMove.TailWhip, new PBELocalizedString("しっぽをふる", "꼬리흔들기", "Mimi-Queue", "Rutenschlag", "Látigo", "Colpocoda", "Tail Whip") },
            { PBEMove.PoisonSting, new PBELocalizedString("どくばり", "독침", "Dard-Venin", "Giftstachel", "Picotazo Ven", "Velenospina", "Poison Sting") },
            // { PBEMove.41, new PBELocalizedString("ダブルニードル", "더블니들", "Double-Dard", "Duonadel", "Dobleataque", "Doppio Ago", "Twineedle") },
            // { PBEMove.42, new PBELocalizedString("ミサイルばり", "바늘미사일", "Dard-Nuée", "Nadelrakete", "Pin Misil", "Missilspillo", "Pin Missile") },
            { PBEMove.Leer, new PBELocalizedString("にらみつける", "째려보기", "Groz’Yeux", "Silberblick", "Malicioso", "Fulmisguardo", "Leer") },
            { PBEMove.Bite, new PBELocalizedString("かみつく", "물기", "Morsure", "Biss", "Mordisco", "Morso", "Bite") },
            { PBEMove.Growl, new PBELocalizedString("なきごえ", "울음소리", "Rugissement", "Heuler", "Gruñido", "Ruggito", "Growl") },
            { PBEMove.Roar, new PBELocalizedString("ほえる", "울부짖기", "Hurlement", "Brüller", "Rugido", "Boato", "Roar") },
            { PBEMove.Sing, new PBELocalizedString("うたう", "노래하기", "Berceuse", "Gesang", "Canto", "Canto", "Sing") },
            { PBEMove.Supersonic, new PBELocalizedString("ちょうおんぱ", "초음파", "Ultrason", "Superschall", "Supersónico", "Supersuono", "Supersonic") },
            { PBEMove.SonicBoom, new PBELocalizedString("ソニックブーム", "소닉붐", "Sonicboom", "Ultraschall", "Bomba Sónica", "Sonicboom", "SonicBoom") },
            // { PBEMove.50, new PBELocalizedString("かなしばり", "사슬묶기", "Entrave", "Aussetzer", "Anulación", "Inibitore", "Disable") },
            { PBEMove.Acid, new PBELocalizedString("ようかいえき", "용해액", "Acide", "Säure", "Ácido", "Acido", "Acid") },
            { PBEMove.Ember, new PBELocalizedString("ひのこ", "불꽃세례", "Flammèche", "Glut", "Ascuas", "Braciere", "Ember") },
            { PBEMove.Flamethrower, new PBELocalizedString("かえんほうしゃ", "화염방사", "Lance-Flamme", "Flammenwurf", "Lanzallamas", "Lanciafiamme", "Flamethrower") },
            // { PBEMove.54, new PBELocalizedString("しろいきり", "흰안개", "Brume", "Weißnebel", "Neblina", "Nebbia", "Mist") },
            { PBEMove.WaterGun, new PBELocalizedString("みずでっぽう", "물대포", "Pistolet à O", "Aquaknarre", "Pistola Agua", "Pistolacqua", "Water Gun") },
            { PBEMove.HydroPump, new PBELocalizedString("ハイドロポンプ", "하이드로펌프", "Hydrocanon", "Hydropumpe", "Hidrobomba", "Idropompa", "Hydro Pump") },
            { PBEMove.Surf, new PBELocalizedString("なみのり", "파도타기", "Surf", "Surfer", "Surf", "Surf", "Surf") },
            { PBEMove.IceBeam, new PBELocalizedString("れいとうビーム", "냉동빔", "Laser Glace", "Eisstrahl", "Rayo Hielo", "Geloraggio", "Ice Beam") },
            { PBEMove.Blizzard, new PBELocalizedString("ふぶき", "눈보라", "Blizzard", "Blizzard", "Ventisca", "Bora", "Blizzard") },
            { PBEMove.Psybeam, new PBELocalizedString("サイケこうせん", "환상빔", "Rafale Psy", "Psystrahl", "Psicorrayo", "Psicoraggio", "Psybeam") },
            { PBEMove.BubbleBeam, new PBELocalizedString("バブルこうせん", "거품광선", "Bulles d’O", "Blubbstrahl", "Rayo Burbuja", "Bollaraggio", "BubbleBeam") },
            { PBEMove.AuroraBeam, new PBELocalizedString("オーロラビーム", "오로라빔", "Onde Boréale", "Aurorastrahl", "Rayo Aurora", "Raggiaurora", "Aurora Beam") },
            // { PBEMove.63, new PBELocalizedString("はかいこうせん", "파괴광선", "Ultralaser", "Hyperstrahl", "Hiperrayo", "Iper Raggio", "Hyper Beam") },
            { PBEMove.Peck, new PBELocalizedString("つつく", "쪼기", "Picpic", "Schnabel", "Picotazo", "Beccata", "Peck") },
            { PBEMove.DrillPeck, new PBELocalizedString("ドリルくちばし", "회전부리", "Bec Vrille", "Bohrschnabel", "Pico Taladro", "Perforbecco", "Drill Peck") },
            // { PBEMove.66, new PBELocalizedString("じごくぐるま", "지옥의바퀴", "Sacrifice", "Überroller", "Sumisión", "Sottomissione", "Submission") },
            { PBEMove.LowKick, new PBELocalizedString("けたぐり", "안다리걸기", "Balayage", "Fußkick", "Patada Baja", "Colpo Basso", "Low Kick") },
            // { PBEMove.68, new PBELocalizedString("カウンター", "카운터", "Riposte", "Konter", "Contador", "Contatore", "Counter") },
            { PBEMove.SeismicToss, new PBELocalizedString("ちきゅうなげ", "지구던지기", "Frappe Atlas", "Geowurf", "Mov. Sísmico", "Mov. Sismico", "Seismic Toss") },
            { PBEMove.Strength, new PBELocalizedString("かいりき", "괴력", "Force", "Stärke", "Fuerza", "Forza", "Strength") },
            // { PBEMove.71, new PBELocalizedString("すいとる", "흡수", "Vol-Vie", "Absorber", "Absorber", "Assorbimento", "Absorb") },
            // { PBEMove.72, new PBELocalizedString("メガドレイン", "메가드레인", "Méga-Sangsue", "Megasauger", "Megaagotar", "Megassorbim.", "Mega Drain") },
            { PBEMove.LeechSeed, new PBELocalizedString("やどりぎのタネ", "씨뿌리기", "Vampigraine", "Egelsamen", "Drenadoras", "Parassiseme", "Leech Seed") },
            { PBEMove.Growth, new PBELocalizedString("せいちょう", "성장", "Croissance", "Wachstum", "Desarrollo", "Crescita", "Growth") },
            { PBEMove.RazorLeaf, new PBELocalizedString("はっぱカッター", "잎날가르기", "Tranch’Herbe", "Rasierblatt", "Hoja Afilada", "Foglielama", "Razor Leaf") },
            // { PBEMove.76, new PBELocalizedString("ソーラービーム", "솔라빔", "Lance-Soleil", "Solarstrahl", "Rayo Solar", "Solarraggio", "SolarBeam") },
            { PBEMove.PoisonPowder, new PBELocalizedString("どくのこな", "독가루", "Poudre Toxik", "Giftpuder", "Polvo Veneno", "Velenpolvere", "PoisonPowder") },
            { PBEMove.StunSpore, new PBELocalizedString("しびれごな", "저리가루", "Para-Spore", "Stachelspore", "Paralizador", "Paralizzante", "Stun Spore") },
            { PBEMove.SleepPowder, new PBELocalizedString("ねむりごな", "수면가루", "Poudre Dodo", "Schlafpuder", "Somnífero", "Sonnifero", "Sleep Powder") },
            // { PBEMove.80, new PBELocalizedString("はなびらのまい", "꽃잎댄스", "Danse-Fleur", "Blättertanz", "Danza Pétalo", "Petalodanza", "Petal Dance") },
            { PBEMove.StringShot, new PBELocalizedString("いとをはく", "실뿜기", "Sécrétion", "Fadenschuss", "Disp. Demora", "Millebave", "String Shot") },
            { PBEMove.DragonRage, new PBELocalizedString("りゅうのいかり", "용의분노", "Draco-Rage", "Drachenwut", "Furia Dragón", "Ira di Drago", "Dragon Rage") },
            // { PBEMove.83, new PBELocalizedString("ほのおのうず", "회오리불꽃", "Danseflamme", "Feuerwirbel", "Giro Fuego", "Turbofuoco", "Fire Spin") },
            { PBEMove.ThunderShock, new PBELocalizedString("でんきショック", "전기쇼크", "Éclair", "Donnerschock", "Impactrueno", "Tuonoshock", "ThunderShock") },
            { PBEMove.Thunderbolt, new PBELocalizedString("１０まんボルト", "10만볼트", "Tonnerre", "Donnerblitz", "Rayo", "Fulmine", "Thunderbolt") },
            { PBEMove.ThunderWave, new PBELocalizedString("でんじは", "전기자석파", "Cage-Éclair", "Donnerwelle", "Onda Trueno", "Tuononda", "Thunder Wave") },
            { PBEMove.Thunder, new PBELocalizedString("かみなり", "번개", "Fatal-Foudre", "Donner", "Trueno", "Tuono", "Thunder") },
            { PBEMove.RockThrow, new PBELocalizedString("いわおとし", "돌떨구기", "Jet-Pierres", "Steinwurf", "Lanzarrocas", "Sassata", "Rock Throw") },
            { PBEMove.Earthquake, new PBELocalizedString("じしん", "지진", "Séisme", "Erdbeben", "Terremoto", "Terremoto", "Earthquake") },
            { PBEMove.Fissure, new PBELocalizedString("じわれ", "땅가르기", "Abîme", "Geofissur", "Fisura", "Abisso", "Fissure") },
            { PBEMove.Dig, new PBELocalizedString("あなをほる", "구멍파기", "Tunnel", "Schaufler", "Excavar", "Fossa", "Dig") },
            { PBEMove.Toxic, new PBELocalizedString("どくどく", "맹독", "Toxik", "Toxin", "Tóxico", "Tossina", "Toxic") },
            { PBEMove.Confusion, new PBELocalizedString("ねんりき", "염동력", "Choc Mental", "Konfusion", "Confusión", "Confusione", "Confusion") },
            { PBEMove.Psychic, new PBELocalizedString("サイコキネシス", "사이코키네시스", "Psyko", "Psychokinese", "Psíquico", "Psichico", "Psychic") },
            { PBEMove.Hypnosis, new PBELocalizedString("さいみんじゅつ", "최면술", "Hypnose", "Hypnose", "Hipnosis", "Ipnosi", "Hypnosis") },
            { PBEMove.Meditate, new PBELocalizedString("ヨガのポーズ", "요가포즈", "Yoga", "Meditation", "Meditación", "Meditazione", "Meditate") },
            { PBEMove.Agility, new PBELocalizedString("こうそくいどう", "고속이동", "Hâte", "Agilität", "Agilidad", "Agilità", "Agility") },
            { PBEMove.QuickAttack, new PBELocalizedString("でんこうせっか", "전광석화", "Vive-Attaque", "Ruckzuckhieb", "At. Rápido", "Attacco Rapido", "Quick Attack") },
            // { PBEMove.99, new PBELocalizedString("いかり", "분노", "Frénésie", "Raserei", "Furia", "Ira", "Rage") },
            { PBEMove.Teleport, new PBELocalizedString("テレポート", "순간이동", "Téléport", "Teleport", "Teletransp", "Teletrasporto", "Teleport") },
            { PBEMove.NightShade, new PBELocalizedString("ナイトヘッド", "나이트헤드", "Ténèbres", "Nachtnebel", "Tinieblas", "Ombra Nott.", "Night Shade") },
            // { PBEMove.102, new PBELocalizedString("ものまね", "흉내내기", "Copie", "Mimikry", "Mimético", "Mimica", "Mimic") },
            { PBEMove.Screech, new PBELocalizedString("いやなおと", "싫은소리", "Grincement", "Kreideschrei", "Chirrido", "Stridio", "Screech") },
            { PBEMove.DoubleTeam, new PBELocalizedString("かげぶんしん", "그림자분신", "Reflet", "Doppelteam", "Doble Equipo", "Doppioteam", "Double Team") },
            { PBEMove.Recover, new PBELocalizedString("じこさいせい", "HP회복", "Soin", "Genesung", "Recuperación", "Ripresa", "Recover") },
            { PBEMove.Harden, new PBELocalizedString("かたくなる", "단단해지기", "Armure", "Härtner", "Fortaleza", "Rafforzatore", "Harden") },
            { PBEMove.Minimize, new PBELocalizedString("ちいさくなる", "작아지기", "Lilliput", "Komprimator", "Reducción", "Minimizzato", "Minimize") },
            { PBEMove.SmokeScreen, new PBELocalizedString("えんまく", "연막", "Brouillard", "Rauchwolke", "Pantallahumo", "Muro di Fumo", "SmokeScreen") },
            { PBEMove.ConfuseRay, new PBELocalizedString("あやしいひかり", "이상한빛", "Onde Folie", "Konfustrahl", "Rayo Confuso", "Stordiraggio", "Confuse Ray") },
            { PBEMove.Withdraw, new PBELocalizedString("からにこもる", "껍질에숨기", "Repli", "Panzerschutz", "Refugio", "Ritirata", "Withdraw") },
            { PBEMove.DefenseCurl, new PBELocalizedString("まるくなる", "웅크리기", "Boul’Armure", "Einigler", "Rizo Defensa", "Ricciolscudo", "Defense Curl") },
            { PBEMove.Barrier, new PBELocalizedString("バリアー", "배리어", "Bouclier", "Barriere", "Barrera", "Barriera", "Barrier") },
            { PBEMove.LightScreen, new PBELocalizedString("ひかりのかべ", "빛의장막", "Mur Lumière", "Lichtschild", "Pantalla de Luz", "Schermoluce", "Light Screen") },
            // { PBEMove.114, new PBELocalizedString("くろいきり", "흑안개", "Buée Noire", "Dunkelnebel", "Niebla", "Nube", "Haze") },
            { PBEMove.Reflect, new PBELocalizedString("リフレクター", "리플렉터", "Protection", "Reflektor", "Reflejo", "Riflesso", "Reflect") },
            { PBEMove.FocusEnergy, new PBELocalizedString("きあいだめ", "기충전", "Puissance", "Energiefokus", "Foco Energía", "Focalenergia", "Focus Energy") },
            // { PBEMove.117, new PBELocalizedString("がまん", "참기", "Patience", "Geduld", "Venganza", "Pazienza", "Bide") },
            // { PBEMove.118, new PBELocalizedString("ゆびをふる", "손가락흔들기", "Métronome", "Metronom", "Metrónomo", "Metronomo", "Metronome") },
            // { PBEMove.119, new PBELocalizedString("オウムがえし", "따라하기", "Mimique", "Spiegeltrick", "Mov. Espejo", "Speculmossa", "Mirror Move") },
            { PBEMove.Selfdestruct, new PBELocalizedString("じばく", "자폭", "Destruction", "Finale", "Autodestruc", "Autodistruzione", "Selfdestruct") },
            { PBEMove.EggBomb, new PBELocalizedString("タマゴばくだん", "알폭탄", "Bomb’Œuf", "Eierbombe", "Bomba Huevo", "Uovobomba", "Egg Bomb") },
            { PBEMove.Lick, new PBELocalizedString("したでなめる", "핥기", "Léchouille", "Schlecker", "Lengüetazo", "Leccata", "Lick") },
            { PBEMove.Smog, new PBELocalizedString("スモッグ", "스모그", "Purédpois", "Smog", "Polución", "Smog", "Smog") },
            { PBEMove.Sludge, new PBELocalizedString("ヘドロこうげき", "오물공격", "Détritus", "Schlammbad", "Residuos", "Fango", "Sludge") },
            { PBEMove.BoneClub, new PBELocalizedString("ホネこんぼう", "뼈다귀치기", "Massd’Os", "Knochenkeule", "Hueso Palo", "Ossoclava", "Bone Club") },
            { PBEMove.FireBlast, new PBELocalizedString("だいもんじ", "불대문자", "Déflagration", "Feuersturm", "Llamarada", "Fuocobomba", "Fire Blast") },
            { PBEMove.Waterfall, new PBELocalizedString("たきのぼり", "폭포오르기", "Cascade", "Kaskade", "Cascada", "Cascata", "Waterfall") },
            // { PBEMove.128, new PBELocalizedString("からではさむ", "껍질끼우기", "Claquoir", "Schnapper", "Tenaza", "Tenaglia", "Clamp") },
            { PBEMove.Swift, new PBELocalizedString("スピードスター", "스피드스타", "Météores", "Sternschauer", "Rapidez", "Comete", "Swift") },
            // { PBEMove.130, new PBELocalizedString("ロケットずつき", "로케트박치기", "Coud’Krâne", "Schädelwumme", "Cabezazo", "Capocciata", "Skull Bash") },
            // { PBEMove.131, new PBELocalizedString("とげキャノン", "가시대포", "Picanon", "Dornkanone", "Clavo Cañón", "Sparalance", "Spike Cannon") },
            // { PBEMove.132, new PBELocalizedString("からみつく", "휘감기", "Constriction", "Umklammerung", "Restricción", "Limitazione", "Constrict") },
            { PBEMove.Amnesia, new PBELocalizedString("ドわすれ", "망각술", "Amnésie", "Amnesie", "Amnesia", "Amnesia", "Amnesia") },
            { PBEMove.Kinesis, new PBELocalizedString("スプーンまげ", "숟가락휘기", "Télékinésie", "Psykraft", "Kinético", "Cinèsi", "Kinesis") },
            { PBEMove.Softboiled, new PBELocalizedString("タマゴうみ", "알낳기", "E-Coque", "Weichei", "Amortiguador", "Covauova", "Softboiled") },
            // { PBEMove.136, new PBELocalizedString("とびひざげり", "무릎차기", "Pied Voltige", "Turmkick", "Pat. S. Alta", "Calcinvolo", "Hi Jump Kick") },
            { PBEMove.Glare, new PBELocalizedString("へびにらみ", "뱀눈초리", "Intimidation", "Giftblick", "Deslumbrar", "Bagliore", "Glare") },
            // { PBEMove.138, new PBELocalizedString("ゆめくい", "꿈먹기", "Dévorêve", "Traumfresser", "Come Sueños", "Mangiasogni", "Dream Eater") },
            { PBEMove.PoisonGas, new PBELocalizedString("どくガス", "독가스", "Gaz Toxik", "Giftwolke", "Gas Venenoso", "Velenogas", "Poison Gas") },
            // { PBEMove.140, new PBELocalizedString("たまなげ", "구슬던지기", "Pilonnage", "Stakkato", "Presa", "Attacco Pioggia", "Barrage") },
            // { PBEMove.141, new PBELocalizedString("きゅうけつ", "흡혈", "Vampirisme", "Blutsauger", "Chupavidas", "Sanguisuga", "Leech Life") },
            { PBEMove.LovelyKiss, new PBELocalizedString("あくまのキッス", "악마의키스", "Grobisou", "Todeskuss", "Beso Amoroso", "Demonbacio", "Lovely Kiss") },
            // { PBEMove.143, new PBELocalizedString("ゴッドバード", "불새", "Piqué", "Himmelsfeger", "Ataque Aéreo", "Aeroattacco", "Sky Attack") },
            { PBEMove.Transform, new PBELocalizedString("へんしん", "변신", "Morphing", "Wandler", "Transform", "Trasformazione", "Transform") },
            { PBEMove.Bubble, new PBELocalizedString("あわ", "거품", "Écume", "Blubber", "Burbuja", "Bolla", "Bubble") },
            { PBEMove.DizzyPunch, new PBELocalizedString("ピヨピヨパンチ", "잼잼펀치", "Uppercut", "Irrschlag", "Puño Mareo", "Stordipugno", "Dizzy Punch") },
            { PBEMove.Spore, new PBELocalizedString("キノコのほうし", "버섯포자", "Spore", "Pilzspore", "Espora", "Spora", "Spore") },
            { PBEMove.Flash, new PBELocalizedString("フラッシュ", "플래시", "Flash", "Blitz", "Destello", "Flash", "Flash") },
            { PBEMove.Psywave, new PBELocalizedString("サイコウェーブ", "사이코웨이브", "Vague Psy", "Psywelle", "Psicoonda", "Psiconda", "Psywave") },
            // { PBEMove.150, new PBELocalizedString("はねる", "튀어오르기", "Trempette", "Platscher", "Salpicadura", "Splash", "Splash") },
            { PBEMove.AcidArmor, new PBELocalizedString("とける", "녹기", "Acidarmure", "Säurepanzer", "Armad. Ácida", "Scudo Acido", "Acid Armor") },
            { PBEMove.Crabhammer, new PBELocalizedString("クラブハンマー", "찝게햄머", "Pince-Masse", "Krabbhammer", "Martillazo", "Martellata", "Crabhammer") },
            { PBEMove.Explosion, new PBELocalizedString("だいばくはつ", "대폭발", "Explosion", "Explosion", "Explosión", "Esplosione", "Explosion") },
            // { PBEMove.154, new PBELocalizedString("みだれひっかき", "마구할퀴기", "Combo-Griffe", "Kratzfurie", "Golpes Furia", "Sfuriate", "Fury Swipes") },
            // { PBEMove.155, new PBELocalizedString("ホネブーメラン", "뼈다귀부메랑", "Osmerang", "Knochmerang", "Huesomerang", "Ossomerang", "Bonemerang") },
            // { PBEMove.156, new PBELocalizedString("ねむる", "잠자기", "Repos", "Erholung", "Descanso", "Riposo", "Rest") },
            { PBEMove.RockSlide, new PBELocalizedString("いわなだれ", "스톤샤워", "Éboulement", "Steinhagel", "Avalancha", "Frana", "Rock Slide") },
            { PBEMove.HyperFang, new PBELocalizedString("ひっさつまえば", "필살앞니", "Croc de Mort", "Hyperzahn", "Hip. Colmillo", "Iperzanna", "Hyper Fang") },
            { PBEMove.Sharpen, new PBELocalizedString("かくばる", "각지기", "Affûtage", "Schärfer", "Afilar", "Affilatore", "Sharpen") },
            // { PBEMove.160, new PBELocalizedString("テクスチャー", "텍스처", "Adaptation", "Umwandlung", "Conversión", "Conversione", "Conversion") },
            // { PBEMove.161, new PBELocalizedString("トライアタック", "트라이어택", "Triplattaque", "Triplette", "Triataque", "Tripletta", "Tri Attack") },
            { PBEMove.SuperFang, new PBELocalizedString("いかりのまえば", "분노의앞니", "Croc Fatal", "Superzahn", "Superdiente", "Superzanna", "Super Fang") },
            { PBEMove.Slash, new PBELocalizedString("きりさく", "베어가르기", "Tranche", "Schlitzer", "Cuchillada", "Lacerazione", "Slash") },
            { PBEMove.Substitute, new PBELocalizedString("みがわり", "대타출동", "Clonage", "Delegator", "Sustituto", "Sostituto", "Substitute") },
            { PBEMove.Struggle, new PBELocalizedString("わるあがき", "발버둥", "Lutte", "Verzweifler", "Combate", "Scontro", "Struggle") },
            // { PBEMove.166, new PBELocalizedString("スケッチ", "스케치", "Gribouille", "Nachahmer", "Esquema", "Schizzo", "Sketch") },
            // { PBEMove.167, new PBELocalizedString("トリプルキック", "트리플킥", "Triple Pied", "Dreifachkick", "Triplepatada", "Triplocalcio", "Triple Kick") },
            // { PBEMove.168, new PBELocalizedString("どろぼう", "도둑질", "Larcin", "Raub", "Ladrón", "Furto", "Thief") },
            // { PBEMove.169, new PBELocalizedString("クモのす", "거미집", "Toile", "Spinnennetz", "Telaraña", "Ragnatela", "Spider Web") },
            // { PBEMove.170, new PBELocalizedString("こころのめ", "마음의눈", "Lire-Esprit", "Willensleser", "Telépata", "Leggimente", "Mind Reader") },
            // { PBEMove.171, new PBELocalizedString("あくむ", "악몽", "Cauchemar", "Nachtmahr", "Pesadilla", "Incubo", "Nightmare") },
            { PBEMove.FlameWheel, new PBELocalizedString("かえんぐるま", "화염자동차", "Roue de Feu", "Flammenrad", "Rueda Fuego", "Ruotafuoco", "Flame Wheel") },
            // { PBEMove.173, new PBELocalizedString("いびき", "코골기", "Ronflement", "Schnarcher", "Ronquido", "Russare", "Snore") },
            { PBEMove.Curse, new PBELocalizedString("のろい", "저주", "Malédiction", "Fluch", "Maldición", "Maledizione", "Curse") },
            // { PBEMove.175, new PBELocalizedString("じたばた", "바둥바둥", "Fléau", "Dreschflegel", "Azote", "Flagello", "Flail") },
            // { PBEMove.176, new PBELocalizedString("テクスチャー２", "텍스처2", "Conversion 2", "Umwandlung2", "Conversión2", "Conversione2", "Conversion 2") },
            { PBEMove.Aeroblast, new PBELocalizedString("エアロブラスト", "에어로블라스트", "Aéroblast", "Luftstoß", "Aerochorro", "Aerocolpo", "Aeroblast") },
            // { PBEMove.178, new PBELocalizedString("わたほうし", "목화포자", "Spore Coton", "Baumwollsaat", "Esporagodón", "Cottonspora", "Cotton Spore") },
            // { PBEMove.179, new PBELocalizedString("きしかいせい", "기사회생", "Contre", "Gegenschlag", "Inversión", "Contropiede", "Reversal") },
            // { PBEMove.180, new PBELocalizedString("うらみ", "원한", "Dépit", "Groll", "Rencor", "Dispetto", "Spite") },
            { PBEMove.PowderSnow, new PBELocalizedString("こなゆき", "눈싸라기", "Poudreuse", "Pulverschnee", "Nieve Polvo", "Polneve", "Powder Snow") },
            { PBEMove.Protect, new PBELocalizedString("まもる", "방어", "Abri", "Schutzschild", "Protección", "Protezione", "Protect") },
            { PBEMove.MachPunch, new PBELocalizedString("マッハパンチ", "마하펀치", "Mach Punch", "Tempohieb", "Ultrapuño", "Pugnorapido", "Mach Punch") },
            { PBEMove.ScaryFace, new PBELocalizedString("こわいかお", "겁나는얼굴", "Grimace", "Grimasse", "Cara Susto", "Visotruce", "Scary Face") },
            { PBEMove.FaintAttack, new PBELocalizedString("だましうち", "속여때리기", "Feinte", "Finte", "Finta", "Finta", "FaintAttack") },
            { PBEMove.SweetKiss, new PBELocalizedString("てんしのキッス", "천사의키스", "Doux Baiser", "Bitterkuss", "Beso Dulce", "Dolcebacio", "Sweet Kiss") },
            // { PBEMove.187, new PBELocalizedString("はらだいこ", "배북", "Cognobidon", "Bauchtrommel", "Tambor", "Panciamburo", "Belly Drum") },
            { PBEMove.SludgeBomb, new PBELocalizedString("ヘドロばくだん", "오물폭탄", "Bomb-Beurk", "Matschbombe", "Bomba Lodo", "Fangobomba", "Sludge Bomb") },
            { PBEMove.MudSlap, new PBELocalizedString("どろかけ", "진흙뿌리기", "Coud’Boue", "Lehmschelle", "Bofetón Lodo", "Fangosberla", "Mud-Slap") },
            { PBEMove.Octazooka, new PBELocalizedString("オクタンほう", "대포무노포", "Octazooka", "Octazooka", "Pulpocañón", "Octazooka", "Octazooka") },
            { PBEMove.Spikes, new PBELocalizedString("まきびし", "압정뿌리기", "Picots", "Stachler", "Púas", "Punte", "Spikes") },
            { PBEMove.ZapCannon, new PBELocalizedString("でんじほう", "전자포", "Élecanon", "Blitzkanone", "Electrocañón", "Falcecannone", "Zap Cannon") },
            // { PBEMove.193, new PBELocalizedString("みやぶる", "꿰뚫어보기", "Clairvoyance", "Gesichte", "Profecía", "Preveggenza", "Foresight") },
            // { PBEMove.194, new PBELocalizedString("みちづれ", "길동무", "Prlvt Destin", "Abgangsbund", "Mismodestino", "Destinobbl.", "Destiny Bond") },
            // { PBEMove.195, new PBELocalizedString("ほろびのうた", "멸망의노래", "Requiem", "Abgesang", "Canto Mortal", "Ultimocanto", "Perish Song") },
            { PBEMove.IcyWind, new PBELocalizedString("こごえるかぜ", "얼다바람", "Vent Glace", "Eissturm", "Viento Hielo", "Ventogelato", "Icy Wind") },
            { PBEMove.Detect, new PBELocalizedString("みきり", "판별", "Détection", "Scanner", "Detección", "Individua", "Detect") },
            // { PBEMove.198, new PBELocalizedString("ボーンラッシュ", "본러쉬", "Charge-Os", "Knochenhatz", "Ataque Óseo", "Ossoraffica", "Bone Rush") },
            // { PBEMove.199, new PBELocalizedString("ロックオン", "록온", "Verrouillage", "Zielschuss", "Fijar Blanco", "Localizza", "Lock-On") },
            // { PBEMove.200, new PBELocalizedString("げきりん", "역린", "Colère", "Wutanfall", "Enfado", "Oltraggio", "Outrage") },
            { PBEMove.Sandstorm, new PBELocalizedString("すなあらし", "모래바람", "Tempêtesable", "Sandsturm", "Torm. Arena", "Terrempesta", "Sandstorm") },
            // { PBEMove.202, new PBELocalizedString("ギガドレイン", "기가드레인", "Giga-Sangsue", "Gigasauger", "Gigadrenado", "Gigassorbim.", "Giga Drain") },
            // { PBEMove.203, new PBELocalizedString("こらえる", "버티기", "Ténacité", "Ausdauer", "Aguante", "Resistenza", "Endure") },
            { PBEMove.Charm, new PBELocalizedString("あまえる", "애교부리기", "Charme", "Charme", "Encanto", "Fascino", "Charm") },
            // { PBEMove.205, new PBELocalizedString("ころがる", "구르기", "Roulade", "Walzer", "Desenrollar", "Rotolamento", "Rollout") },
            // { PBEMove.206, new PBELocalizedString("みねうち", "칼등치기", "Faux-Chage", "Trugschlag", "Falsotortazo", "Falsofinale", "False Swipe") },
            { PBEMove.Swagger, new PBELocalizedString("いばる", "뽐내기", "Vantardise", "Angeberei", "Contoneo", "Bullo", "Swagger") },
            { PBEMove.MilkDrink, new PBELocalizedString("ミルクのみ", "우유마시기", "Lait à Boire", "Milchgetränk", "Batido", "Buonlatte", "Milk Drink") },
            { PBEMove.Spark, new PBELocalizedString("スパーク", "스파크", "Étincelle", "Funkensprung", "Chispa", "Scintilla", "Spark") },
            // { PBEMove.210, new PBELocalizedString("れんぞくぎり", "연속자르기", "Taillade", "Zornklinge", "Cortefuria", "Tagliofuria", "Fury Cutter") },
            { PBEMove.SteelWing, new PBELocalizedString("はがねのつばさ", "강철날개", "Aile d’Acier", "Stahlflügel", "Ala de Acero", "Alacciaio", "Steel Wing") },
            // { PBEMove.212, new PBELocalizedString("くろいまなざし", "검은눈빛", "Regard Noir", "Horrorblick", "Mal de Ojo", "Malosguardo", "Mean Look") },
            // { PBEMove.213, new PBELocalizedString("メロメロ", "헤롱헤롱", "Attraction", "Anziehung", "Atracción", "Attrazione", "Attract") },
            // { PBEMove.214, new PBELocalizedString("ねごと", "잠꼬대", "Blabla Dodo", "Schlafrede", "Sonámbulo", "Sonnolalia", "Sleep Talk") },
            // { PBEMove.215, new PBELocalizedString("いやしのすず", "치료방울", "Glas de Soin", "Vitalglocke", "Campana Cura", "Rintoccasana", "Heal Bell") },
            { PBEMove.Return, new PBELocalizedString("おんがえし", "은혜갚기", "Retour", "Rückkehr", "Retroceso", "Ritorno", "Return") },
            // { PBEMove.217, new PBELocalizedString("プレゼント", "프레젠트", "Cadeau", "Geschenk", "Presente", "Regalino", "Present") },
            { PBEMove.Frustration, new PBELocalizedString("やつあたり", "화풀이", "Frustration", "Frustration", "Frustración", "Frustrazione", "Frustration") },
            // { PBEMove.219, new PBELocalizedString("しんぴのまもり", "신비의부적", "Rune Protect", "Bodyguard", "Velo Sagrado", "Salvaguardia", "Safeguard") },
            { PBEMove.PainSplit, new PBELocalizedString("いたみわけ", "아픔나누기", "Balance", "Leidteiler", "Divide Dolor", "Malcomune", "Pain Split") },
            { PBEMove.SacredFire, new PBELocalizedString("せいなるほのお", "성스러운불꽃", "Feu Sacré", "Läuterfeuer", "Fuegosagrado", "Magifuoco", "Sacred Fire") },
            { PBEMove.Magnitude, new PBELocalizedString("マグニチュード", "매그니튜드", "Ampleur", "Intensität", "Magnitud", "Magnitudo", "Magnitude") },
            { PBEMove.DynamicPunch, new PBELocalizedString("ばくれつパンチ", "폭발펀치", "Dynamopoing", "Wuchtschlag", "Puñodinámico", "Dinamipugno", "DynamicPunch") },
            { PBEMove.Megahorn, new PBELocalizedString("メガホーン", "메가폰", "Mégacorne", "Vielender", "Megacuerno", "Megacorno", "Megahorn") },
            { PBEMove.DragonBreath, new PBELocalizedString("りゅうのいぶき", "용의숨결", "Dracosouffle", "Feuerodem", "Dragoaliento", "Dragospiro", "DreagonBreath") },
            // { PBEMove.226, new PBELocalizedString("バトンタッチ", "바톤터치", "Relais", "Staffette", "Relevo", "Staffetta", "Baton Pass") },
            // { PBEMove.227, new PBELocalizedString("アンコール", "앵콜", "Encore", "Zugabe", "Otra Vez", "Ripeti", "Encore") },
            // { PBEMove.228, new PBELocalizedString("おいうち", "따라가때리기", "Poursuite", "Verfolgung", "Persecución", "Inseguimento", "Pursuit") },
            // { PBEMove.229, new PBELocalizedString("こうそくスピン", "고속스핀", "Tour Rapide", "Turbodreher", "Giro Rápido", "Rapigiro", "Rapid Spin") },
            { PBEMove.SweetScent, new PBELocalizedString("あまいかおり", "달콤한향기", "Doux Parfum", "Lockduft", "Dulce Aroma", "Profumino", "Sweet Scent") },
            { PBEMove.IronTail, new PBELocalizedString("アイアンテール", "아이언테일", "Queue de Fer", "Eisenschweif", "Cola Férrea", "Codacciaio", "Iron Tail") },
            { PBEMove.MetalClaw, new PBELocalizedString("メタルクロー", "메탈크로우", "Griffe Acier", "Metallklaue", "Garra Metal", "Ferrartigli", "Metal Claw") },
            { PBEMove.VitalThrow, new PBELocalizedString("あてみなげ", "받아던지기", "Corps Perdu", "Überwurf", "Tiro Vital", "Vitaltiro", "Vital Throw") },
            { PBEMove.MorningSun, new PBELocalizedString("あさのひざし", "아침햇살", "Aurore", "Morgengrauen", "Sol Matinal", "Mattindoro", "Morning Sun") },
            { PBEMove.Synthesis, new PBELocalizedString("こうごうせい", "광합성", "Synthèse", "Synthese", "Síntesis", "Sintesi", "Synthesis") },
            { PBEMove.Moonlight, new PBELocalizedString("つきのひかり", "달의불빛", "Rayon Lune", "Mondschein", "Luz Lunar", "Lucelunare", "Moonlight") },
            { PBEMove.HiddenPower, new PBELocalizedString("めざめるパワー", "잠재파워", "Puiss. Cachée", "Kraftreserve", "Poder Oculto", "Introforza", "Hidden Power") },
            { PBEMove.CrossChop, new PBELocalizedString("クロスチョップ", "크로스촙", "Coup-Croix", "Kreuzhieb", "Tajo Cruzado", "Incrocolpo", "Cross Chop") },
            // { PBEMove.239, new PBELocalizedString("たつまき", "회오리", "Ouragan", "Windhose", "Ciclón", "Tornado", "Twister") },
            { PBEMove.RainDance, new PBELocalizedString("あまごい", "비바라기", "Danse Pluie", "Regentanz", "Danza Lluvia", "Pioggiadanza", "Rain Dance") },
            { PBEMove.SunnyDay, new PBELocalizedString("にほんばれ", "쾌청", "Zénith", "Sonnentag", "Día Soleado", "Giornodisole", "Sunny Day") },
            { PBEMove.Crunch, new PBELocalizedString("かみくだく", "깨물어부수기", "Mâchouille", "Knirscher", "Triturar", "Sgranocchio", "Crunch") },
            // { PBEMove.243, new PBELocalizedString("ミラーコート", "미러코트", "Voile Miroir", "Spiegelcape", "Manto Espejo", "Specchiovelo", "Mirror Coat") },
            { PBEMove.PsychUp, new PBELocalizedString("じこあんじ", "자기암시", "Boost", "Psycho-Plus", "Más Psique", "Psicamisù", "Psych Up") },
            { PBEMove.ExtremeSpeed, new PBELocalizedString("しんそく", "신속", "Vit.Extrême", "Turbotempo", "Vel. Extrema", "Extrarapido", "ExtremeSpeed") },
            { PBEMove.AncientPower, new PBELocalizedString("げんしのちから", "원시의힘", "Pouv.Antique", "Antik-Kraft", "Poder Pasado", "Forzantica", "AncientPower") },
            { PBEMove.ShadowBall, new PBELocalizedString("シャドーボール", "섀도볼", "Ball’Ombre", "Spukball", "Bola Sombra", "Palla Ombra", "Shadow Ball") },
            // { PBEMove.248, new PBELocalizedString("みらいよち", "미래예지", "Prescience", "Seher", "Premonición", "Divinazione", "Future Sight") },
            { PBEMove.RockSmash, new PBELocalizedString("いわくだき", "바위깨기", "Éclate-Roc", "Zertrümmerer", "Golpe Roca", "Spaccaroccia", "Rock Smash") },
            // { PBEMove.250, new PBELocalizedString("うずしお", "바다회오리", "Siphon", "Whirlpool", "Torbellino", "Mulinello", "Whirlpool") },
            // { PBEMove.251, new PBELocalizedString("ふくろだたき", "집단구타", "Baston", "Prügler", "Paliza", "Picchiaduro", "Beat Up") },
            // { PBEMove.252, new PBELocalizedString("ねこだまし", "속이다", "Bluff", "Mogelhieb", "Sorpresa", "Bruciapelo", "Fake Out") },
            // { PBEMove.253, new PBELocalizedString("さわぐ", "소란피기", "Brouhaha", "Aufruhr", "Alboroto", "Baraonda", "Uproar") },
            // { PBEMove.254, new PBELocalizedString("たくわえる", "비축하기", "Stockage", "Horter", "Reserva", "Accumulo", "Stockpile") },
            // { PBEMove.255, new PBELocalizedString("はきだす", "토해내기", "Relâche", "Entfessler", "Escupir", "Sfoghenergia", "Spit Up") },
            // { PBEMove.256, new PBELocalizedString("のみこむ", "꿀꺽", "Avale", "Verzehrer", "Tragar", "Introenergia", "Swallow") },
            { PBEMove.HeatWave, new PBELocalizedString("ねっぷう", "열풍", "Canicule", "Hitzewelle", "Onda Ígnea", "Ondacalda", "Heat Wave") },
            { PBEMove.Hail, new PBELocalizedString("あられ", "싸라기눈", "Grêle", "Hagelsturm", "Granizo", "Grandine", "Hail") },
            // { PBEMove.259, new PBELocalizedString("いちゃもん", "트집", "Tourmente", "Folterknecht", "Tormento", "Attaccalite", "Torment") },
            { PBEMove.Flatter, new PBELocalizedString("おだてる", "부추기기", "Flatterie", "Schmeichler", "Camelo", "Adulazione", "Flatter") },
            { PBEMove.WillOWisp, new PBELocalizedString("おにび", "도깨비불", "Feu Follet", "Irrlicht", "Fuego Fatuo", "Fuocofatuo", "Will-O-Wisp") },
            // { PBEMove.262, new PBELocalizedString("おきみやげ", "추억의선물", "Souvenir", "Memento-Mori", "Legado", "Memento", "Memento") },
            { PBEMove.Facade, new PBELocalizedString("からげんき", "객기", "Façade", "Fassade", "Imagen", "Facciata", "Facade") },
            // { PBEMove.264, new PBELocalizedString("きあいパンチ", "힘껏펀치", "Mitra-Poing", "Power-Punch", "Puño Certero", "Centripugno", "Focus Punch") },
            // { PBEMove.265, new PBELocalizedString("きつけ", "정신차리기", "Stimulant", "Riechsalz", "Estímulo", "Maniereforti", "SmellingSalt") },
            // { PBEMove.266, new PBELocalizedString("このゆびとまれ", "날따름", "Par Ici", "Spotlight", "Señuelo", "Sonoqui", "Follow Me") },
            // { PBEMove.267, new PBELocalizedString("しぜんのちから", "자연의힘", "Force-Nature", "Natur-Kraft", "Adaptación", "Naturforza", "Nature Power") },
            // { PBEMove.268, new PBELocalizedString("じゅうでん", "충전", "Chargeur", "Ladevorgang", "Carga", "Sottocarica", "Charge") },
            // { PBEMove.269, new PBELocalizedString("ちょうはつ", "도발", "Provoc", "Verhöhner", "Mofa", "Provocazione", "Taunt") },
            // { PBEMove.270, new PBELocalizedString("てだすけ", "도우미", "Coup d’Main", "Rechte Hand", "Refuerzo", "Altruismo", "Helping Hand") },
            // { PBEMove.271, new PBELocalizedString("トリック", "트릭", "Tourmagik", "Trickbetrug", "Truco", "Raggiro", "Trick") },
            // { PBEMove.272, new PBELocalizedString("なりきり", "역할", "Imitation", "Rollentausch", "Imitación", "Giocodiruolo", "Role Play") },
            // { PBEMove.273, new PBELocalizedString("ねがいごと", "희망사항", "Vœu", "Wunschtraum", "Deseo", "Desiderio", "Wish") },
            // { PBEMove.274, new PBELocalizedString("ねこのて", "조수", "Assistance", "Zuschuss", "Ayuda", "Assistente", "Assist") },
            // { PBEMove.275, new PBELocalizedString("ねをはる", "뿌리박기", "Racines", "Verwurzler", "Arraigo", "Radicamento", "Ingrain") },
            { PBEMove.Superpower, new PBELocalizedString("ばかぢから", "엄청난힘", "Surpuissance", "Kraftkoloss", "Fuerza Bruta", "Troppoforte", "Superpower") },
            // { PBEMove.277, new PBELocalizedString("マジックコート", "매직코트", "Reflet Magik", "Magiemantel", "Capa Mágica", "Magivelo", "Magic Coat") },
            // { PBEMove.278, new PBELocalizedString("リサイクル", "리사이클", "Recyclage", "Aufbereitung", "Reciclaje", "Riciclo", "Recycle") },
            // { PBEMove.279, new PBELocalizedString("リベンジ", "리벤지", "Vendetta", "Vergeltung", "Desquite", "Vendetta", "Revenge") },
            { PBEMove.BrickBreak, new PBELocalizedString("かわらわり", "깨트리다", "Casse-Brique", "Durchbruch", "Demolición", "Breccia", "Brick Break") },
            // { PBEMove.281, new PBELocalizedString("あくび", "하품", "Bâillement", "Gähner", "Bostezo", "Sbadiglio", "Yawn") },
            // { PBEMove.282, new PBELocalizedString("はたきおとす", "탁쳐서떨구기", "Sabotage", "Abschlag", "Desarme", "Privazione", "Knock Off") },
            { PBEMove.Endeavor, new PBELocalizedString("がむしゃら", "죽기살기", "Effort", "Notsituation", "Esfuerzo", "Rimonta", "Endeavor") },
            { PBEMove.Eruption, new PBELocalizedString("ふんか", "분화", "Éruption", "Eruption", "Estallido", "Eruzione", "Eruption") },
            // { PBEMove.285, new PBELocalizedString("スキルスワップ", "스킬스웹", "Échange", "Wertewechsel", "Intercambio", "Baratto", "Skill Swap") },
            // { PBEMove.286, new PBELocalizedString("ふういん", "봉인", "Possessif", "Begrenzer", "Cerca", "Esclusiva", "Imprison") },
            // { PBEMove.287, new PBELocalizedString("リフレッシュ", "리프레쉬", "Régénération", "Heilung", "Alivio", "Rinfrescata", "Refresh") },
            // { PBEMove.288, new PBELocalizedString("おんねん", "원념", "Rancune", "Nachspiel", "Rabia", "Rancore", "Grudge") },
            // { PBEMove.289, new PBELocalizedString("よこどり", "가로챔", "Saisie", "Übernahme", "Robo", "Scippo", "Snatch") },
            // { PBEMove.290, new PBELocalizedString("ひみつのちから", "비밀의힘", "Force Cachée", "Geheimpower", "Daño Secreto", "Forzasegreta", "Secret Power") },
            { PBEMove.Dive, new PBELocalizedString("ダイビング", "다이빙", "Plongée", "Taucher", "Buceo", "Sub", "Dive") },
            // { PBEMove.292, new PBELocalizedString("つっぱり", "손바닥치기", "Cogne", "Armstoß", "Empujón", "Sberletese", "Arm Thrust") },
            // { PBEMove.293, new PBELocalizedString("ほごしょく", "보호색", "Camouflage", "Tarnung", "Camuflaje", "Camuffamento", "Camouflage") },
            { PBEMove.TailGlow, new PBELocalizedString("ほたるび", "반딧불", "Lumiqueue", "Schweifglanz", "Ráfaga", "Codadiluce", "Tail Glow") },
            { PBEMove.LusterPurge, new PBELocalizedString("ラスターパージ", "라스트버지", "Lumi-Éclat", "Scheinwerfer", "Resplandor", "Abbagliante", "Luster Purge") },
            { PBEMove.MistBall, new PBELocalizedString("ミストボール", "미스트볼", "Ball’Brume", "Nebelball", "Bola Neblina", "Foschisfera", "Mist Ball") },
            { PBEMove.FeatherDance, new PBELocalizedString("フェザーダンス", "깃털댄스", "Danse-Plume", "Daunenreigen", "Danza Pluma", "Danzadipiume", "FeatherDance") },
            { PBEMove.TeeterDance, new PBELocalizedString("フラフラダンス", "흔들흔들댄스", "Danse-Folle", "Taumeltanz", "Danza Caos", "Strampadanza", "Teeter Dance") },
            { PBEMove.BlazeKick, new PBELocalizedString("ブレイズキック", "브레이즈킥", "Pied Brûleur", "Feuerfeger", "Patada Ígnea", "Calciardente", "Blaze Kick") },
            // { PBEMove.300, new PBELocalizedString("どろあそび", "흙놀이", "Lance-Boue", "Lehmsuhler", "Chapoteolodo", "Fangata", "Mud Sport") },
            // { PBEMove.301, new PBELocalizedString("アイスボール", "아이스볼", "Ball’Glace", "Frostbeule", "Bola Hielo", "Palla Gelo", "Ice Ball") },
            { PBEMove.NeedleArm, new PBELocalizedString("ニードルアーム", "바늘팔", "Poing Dard", "Nietenranke", "Brazo Pincho", "Pugnospine", "Needle Arm") },
            { PBEMove.SlackOff, new PBELocalizedString("なまける", "태만함", "Paresse", "Tagedieb", "Relajo", "Pigro", "Slack Off") },
            { PBEMove.HyperVoice, new PBELocalizedString("ハイパーボイス", "하이퍼보이스", "Mégaphone", "Schallwelle", "Vozarrón", "Granvoce", "Hyper Voice") },
            { PBEMove.PoisonFang, new PBELocalizedString("どくどくのキバ", "독엄니", "Crochetvenin", "Giftzahn", "Colmillo Ven", "Velenodenti", "Poison Fang") },
            { PBEMove.CrushClaw, new PBELocalizedString("ブレイククロー", "브레이크크루", "Éclategriffe", "Zermalmklaue", "Garra Brutal", "Tritartigli", "Crush Claw") },
            // { PBEMove.307, new PBELocalizedString("ブラストバーン", "블러스트번", "Rafale Feu", "Lohekanonade", "Anillo Ígneo", "Incendio", "Blast Burn") },
            // { PBEMove.308, new PBELocalizedString("ハイドロカノン", "하이드로캐논", "Hydroblast", "Aquahaubitze", "Hidrocañón", "Idrocannone", "Hydro Cannon") },
            { PBEMove.MeteorMash, new PBELocalizedString("コメットパンチ", "코멧펀치", "Poing Météor", "Sternenhieb", "Puño Meteoro", "Meteorpugno", "Meteor Mash") },
            { PBEMove.Astonish, new PBELocalizedString("おどろかす", "놀래키기", "Étonnement", "Erstauner", "Impresionar", "Sgomento", "Astonish") },
            { PBEMove.WeatherBall, new PBELocalizedString("ウェザーボール", "웨더볼", "Ball’Météo", "Meteorologe", "Meteorobola", "Palla Clima", "Weather Ball") },
            // { PBEMove.312, new PBELocalizedString("アロマセラピー", "아로마테라피", "Aromathérapie", "Aromakur", "Aromaterapia", "Aromaterapia", "Aromatherapy") },
            { PBEMove.FakeTears, new PBELocalizedString("うそなき", "거짓울음", "Croco Larme", "Trugträne", "Llanto Falso", "Falselacrime", "Fake Tears") },
            { PBEMove.AirCutter, new PBELocalizedString("エアカッター", "에어컷터", "Tranch’Air", "Windschnitt", "Aire Afilado", "Aerasoio", "Air Cutter") },
            { PBEMove.Overheat, new PBELocalizedString("オーバーヒート", "오버히트", "Surchauffe", "Hitzekoller", "Sofoco", "Vampata", "Overheat") },
            // { PBEMove.316, new PBELocalizedString("かぎわける", "냄새구별", "Flair", "Schnüffler", "Rastreo", "Segugio", "Odor Sleuth") },
            { PBEMove.RockTomb, new PBELocalizedString("がんせきふうじ", "암석봉인", "Tomberoche", "Felsgrab", "Tumba Rocas", "Rocciotomba", "Rock Tomb") },
            { PBEMove.SilverWind, new PBELocalizedString("ぎんいろのかぜ", "은빛바람", "Vent Argenté", "Silberhauch", "Viento Plata", "Ventargenteo", "Silver Wind") },
            { PBEMove.MetalSound, new PBELocalizedString("きんぞくおん", "금속음", "Strido-Son", "Metallsound", "Eco Metálico", "Ferrostrido", "Metal Sound") },
            { PBEMove.GrassWhistle, new PBELocalizedString("くさぶえ", "풀피리", "Siffl’Herbe", "Grasflöte", "Silbato", "Meloderba", "GrassWhistle") },
            { PBEMove.Tickle, new PBELocalizedString("くすぐる", "간지르기", "Chatouille", "Spaßkanone", "Cosquillas", "Solletico", "Tickle") },
            { PBEMove.CosmicPower, new PBELocalizedString("コスモパワー", "코스믹파워", "Force Cosmik", "Kosmik-Kraft", "Masa Cósmica", "Cosmoforza", "Cosmic Power") },
            { PBEMove.WaterSpout, new PBELocalizedString("しおふき", "해수스파우팅", "Giclédo", "Fontränen", "Salpicar", "Zampillo", "Water Spout") },
            { PBEMove.SignalBeam, new PBELocalizedString("シグナルビーム", "시그널빔", "Rayon Signal", "Ampelleuchte", "Doble Rayo", "Segnoraggio", "Signal Beam") },
            { PBEMove.ShadowPunch, new PBELocalizedString("シャドーパンチ", "섀도펀치", "Poing Ombre", "Finsterfaust", "Puño Sombra", "Pugnodombra", "Shadow Punch") },
            { PBEMove.Extrasensory, new PBELocalizedString("じんつうりき", "신통력", "Extrasenseur", "Sondersensor", "Paranormal", "Extrasenso", "Extrasensory") },
            { PBEMove.SkyUppercut, new PBELocalizedString("スカイアッパー", "스카이업퍼", "Stratopercut", "Himmelhieb", "Gancho Alto", "Stramontante", "Sky Uppercut") },
            // { PBEMove.328, new PBELocalizedString("すなじごく", "모래지옥", "Tourbi-Sable", "Sandgrab", "Bucle Arena", "Sabbiotomba", "Sand Tomb") },
            { PBEMove.SheerCold, new PBELocalizedString("ぜったいれいど", "절대영도", "Glaciation", "Eiseskälte", "Frío Polar", "Purogelo", "Sheer Cold") },
            { PBEMove.MuddyWater, new PBELocalizedString("だくりゅう", "탁류", "Ocroupi", "Lehmbrühe", "Agua Lodosa", "Fanghiglia", "Muddy Water") },
            // { PBEMove.331, new PBELocalizedString("タネマシンガン", "기관총", "Balle Graine", "Kugelsaat", "Recurrente", "Semitraglia", "Bullet Seed") },
            { PBEMove.AerialAce, new PBELocalizedString("つばめがえし", "제비반환", "Aéropique", "Aero-Ass", "Golpe Aéreo", "Aeroassalto", "Aerial Ace") },
            // { PBEMove.333, new PBELocalizedString("つららばり", "고드름침", "Stalagtite", "Eisspeer", "Carámbano", "Gelolancia", "Icicle Spear") },
            { PBEMove.IronDefense, new PBELocalizedString("てっぺき", "철벽", "Mur de Fer", "Eisenabwehr", "Def. Férrea", "Ferroscudo", "Iron Defense") },
            // { PBEMove.335, new PBELocalizedString("とおせんぼう", "블록", "Barrage", "Rückentzug", "Bloqueo", "Blocco", "Block") },
            { PBEMove.Howl, new PBELocalizedString("とおぼえ", "멀리짖음", "Grondement", "Jauler", "Aullido", "Gridodilotta", "Howl") },
            { PBEMove.DragonClaw, new PBELocalizedString("ドラゴンクロー", "드래곤크루", "Dracogriffe", "Drachenklaue", "Garra Dragón", "Dragartigli", "Dragon Claw") },
            // { PBEMove.338, new PBELocalizedString("ハードプラント", "하드플랜트", "Végé-Attak", "Fauna-Statue", "Planta Feroz", "Radicalbero", "Frenzy Plant") },
            { PBEMove.BulkUp, new PBELocalizedString("ビルドアップ", "벌크업", "Gonflette", "Protzer", "Corpulencia", "Granfisico", "Bulk Up") },
            // { PBEMove.340, new PBELocalizedString("とびはねる", "뛰어오르다", "Rebond", "Sprungfeder", "Bote", "Rimbalzo", "Bounce") },
            { PBEMove.MudShot, new PBELocalizedString("マッドショット", "머드숏", "Tir de Boue", "Lehmschuss", "Disp. Lodo", "Colpodifango", "Mud Shot") },
            { PBEMove.PoisonTail, new PBELocalizedString("ポイズンテール", "포이즌테일", "Queue-Poison", "Giftschweif", "Cola Veneno", "Velenocoda", "Poison Tail") },
            // { PBEMove.343, new PBELocalizedString("ほしがる", "탐내다", "Implore", "Bezirzer", "Antojo", "Supplica", "Covet") },
            // { PBEMove.344, new PBELocalizedString("ボルテッカー", "볼트태클", "Électacle", "Volttackle", "Placaje Eléc", "Locomovolt", "Volt Tackle") },
            { PBEMove.MagicalLeaf, new PBELocalizedString("マジカルリーフ", "메지컬리프", "Feuille Magik", "Zauberblatt", "Hoja Mágica", "Fogliamagica", "Magical Leaf") },
            // { PBEMove.346, new PBELocalizedString("みずあそび", "물놀이", "Tourniquet", "Nassmacher", "Hidrochorro", "Docciascudo", "Water Sport") },
            { PBEMove.CalmMind, new PBELocalizedString("めいそう", "명상", "Plénitude", "Gedankengut", "Paz Mental", "Calmamente", "Calm Mind") },
            { PBEMove.LeafBlade, new PBELocalizedString("リーフブレード", "리프블레이드", "Lame-Feuille", "Laubklinge", "Hoja Aguda", "Fendifoglia", "Leaf Blade") },
            { PBEMove.DragonDance, new PBELocalizedString("りゅうのまい", "용의춤", "Danse Draco", "Drachentanz", "Danza Dragón", "Dragodanza", "Dragon Dance") },
            // { PBEMove.350, new PBELocalizedString("ロックブラスト", "락블레스트", "Boule Roc", "Felswurf", "Pedrada", "Cadutamassi", "Rock Blast") },
            { PBEMove.ShockWave, new PBELocalizedString("でんげきは", "전격파", "Onde de Choc", "Schockwelle", "Onda Voltio", "Ondashock", "Shock Wave") },
            { PBEMove.WaterPulse, new PBELocalizedString("みずのはどう", "물의파동", "Vibraqua", "Aquawelle", "Hidropulso", "Idropulsar", "Water Pulse") },
            // { PBEMove.353, new PBELocalizedString("はめつのねがい", "파멸의소원", "Carnareket", "Kismetwunsch", "Deseo Oculto", "Obbliderio", "Doom Desire") },
            { PBEMove.PsychoBoost, new PBELocalizedString("サイコブースト", "사이코부스트", "Psycho Boost", "Psyschub", "Psicoataque", "Psicoslancio", "Psycho Boost") },
            // { PBEMove.355, new PBELocalizedString("はねやすめ", "날개쉬기", "Atterrissage", "Ruheort", "Respiro", "Trespolo", "Roost") },
            // { PBEMove.356, new PBELocalizedString("じゅうりょく", "중력", "Gravité", "Erdanziehung", "Gravedad", "Gravità", "Gravity") },
            // { PBEMove.357, new PBELocalizedString("ミラクルアイ", "미라클아이", "Œil Miracle", "Wunderauge", "Gran Ojo", "Miracolvista", "Miracle Eye") },
            // { PBEMove.358, new PBELocalizedString("めざましビンタ", "잠깨움뺨치기", "Réveil Forcé", "Weckruf", "Espabila", "Svegliopacca", "Wake-Up Slap") },
            { PBEMove.HammerArm, new PBELocalizedString("アームハンマー", "암해머", "Marto-Poing", "Hammerarm", "Machada", "Martelpugno", "Hammer Arm") },
            // { PBEMove.360, new PBELocalizedString("ジャイロボール", "자이로볼", "Gyroballe", "Gyroball", "Giro Bola", "Vortexpalla", "Gyro Ball") },
            // { PBEMove.361, new PBELocalizedString("いやしのねがい", "치유소원", "Vœu Soin", "Heilopfer", "Deseo Cura", "Curardore", "Healing Wish") },
            { PBEMove.Brine, new PBELocalizedString("しおみず", "소금물", "Saumure", "Lake", "Salmuera", "Acquadisale", "Brine") },
            // { PBEMove.363, new PBELocalizedString("しぜんのめぐみ", "자연의은혜", "Don Naturel", "Beerenkräfte", "Don Natural", "Dononaturale", "Natural Gift") },
            // { PBEMove.364, new PBELocalizedString("フェイント", "페인트", "Ruse", "Offenlegung", "Amago", "Fintoattacco", "Feint") },
            // { PBEMove.365, new PBELocalizedString("ついばむ", "쪼아대기", "Picore", "Pflücker", "Picoteo", "Spennata", "Pluck") },
            // { PBEMove.366, new PBELocalizedString("おいかぜ", "순풍", "Vent Arrière", "Rückenwind", "Viento Afín", "Ventoincoda", "Tailwind") },
            // { PBEMove.367, new PBELocalizedString("つぼをつく", "경혈찌르기", "Acupression", "Akupressur", "Acupresión", "Acupressione", "Acupressure") },
            // { PBEMove.368, new PBELocalizedString("メタルバースト", "메탈버스트", "Fulmifer", "Metallstoß", "Repr. Metal.", "Metalscoppio", "Metal Burst") },
            // { PBEMove.369, new PBELocalizedString("とんぼがえり", "유턴", "Demi-Tour", "Kehrtwende", "Ida y Vuelta", "Retromarcia", "U-turn") },
            { PBEMove.CloseCombat, new PBELocalizedString("インファイト", "인파이트", "Close Combat", "Nahkampf", "A Bocajarro", "Zuffa", "Close Combat") },
            // { PBEMove.371, new PBELocalizedString("しっぺがえし", "보복", "Représailles", "Gegenstoß", "Vendetta", "Rivincita", "Payback") },
            // { PBEMove.372, new PBELocalizedString("ダメおし", "승부굳히기", "Assurance", "Gewissheit", "Buena Baza", "Garanzia", "Assurance") },
            // { PBEMove.373, new PBELocalizedString("さしおさえ", "금제", "Embargo", "Itemsperre", "Embargo", "Divieto", "Embargo") },
            // { PBEMove.374, new PBELocalizedString("なげつける", "내던지기", "Dégommage", "Schleuder", "Lanzamiento", "Lancio", "Fling") },
            // { PBEMove.375, new PBELocalizedString("サイコシフト", "사이코시프트", "Échange Psy", "Psybann", "Psico-cambio", "Psicotrasfer", "Psycho Shift") },
            // { PBEMove.376, new PBELocalizedString("きりふだ", "마지막수단", "Atout", "Trumpfkarte", "As Oculto", "Asso", "Trump Card") },
            // { PBEMove.377, new PBELocalizedString("かいふくふうじ", "회복봉인", "Anti-Soin", "Heilblockade", "Anticura", "Anticura", "Heal Block") },
            // { PBEMove.378, new PBELocalizedString("しぼりとる", "쥐어짜기", "Essorage", "Auswringen", "Estrujón", "Strizzata", "Wring Out") },
            // { PBEMove.379, new PBELocalizedString("パワートリック", "파워트릭", "Astuce Force", "Krafttrick", "Truco Fuerza", "Ingannoforza", "Power Trick") },
            // { PBEMove.380, new PBELocalizedString("いえき", "위액", "Suc Digestif", "Magensäfte", "Bilis", "Gastroacido", "Gastro Acid") },
            { PBEMove.LuckyChant, new PBELocalizedString("おまじない", "주술", "Air Veinard", "Beschwörung", "Conjuro", "Fortuncanto", "Lucky Chant") },
            // { PBEMove.382, new PBELocalizedString("さきどり", "선취", "Moi d’Abord", "Egotrip", "Yo Primero", "Precedenza", "Me First") },
            // { PBEMove.383, new PBELocalizedString("まねっこ", "흉내쟁이", "Photocopie", "Imitator", "Copión", "Copione", "Copycat") },
            // { PBEMove.384, new PBELocalizedString("パワースワップ", "파워스웹", "Permuforce", "Krafttausch", "Cambia Fue.", "Barattoforza", "Power Swap") },
            // { PBEMove.385, new PBELocalizedString("ガードスワップ", "가드스웹", "Permugarde", "Schutztausch", "Cambia Def.", "Barattoscudo", "Guard Swap") },
            // { PBEMove.386, new PBELocalizedString("おしおき", "혼내기", "Punition", "Strafattacke", "Castigo", "Punizione", "Punishment") },
            // { PBEMove.387, new PBELocalizedString("とっておき", "뒀다쓰기", "Dernierecour", "Zuflucht", "Última Baza", "Ultimascelta", "Last Resort") },
            // { PBEMove.388, new PBELocalizedString("なやみのタネ", "고민씨", "Soucigraine", "Sorgensamen", "Abatidoras", "Affannoseme", "Worry Seed") },
            // { PBEMove.389, new PBELocalizedString("ふいうち", "기습", "Coup Bas", "Tiefschlag", "Golpe Bajo", "Sbigoattacco", "Sucker Punch") },
            { PBEMove.ToxicSpikes, new PBELocalizedString("どくびし", "독압정", "Pics Toxik", "Giftspitzen", "Púas Tóxicas", "Fielepunte", "Toxic Spikes") },
            // { PBEMove.391, new PBELocalizedString("ハートスワップ", "하트스웹", "Permucœur", "Statustausch", "Cambia Almas", "Cuorbaratto", "Heart Swap") },
            // { PBEMove.392, new PBELocalizedString("アクアリング", "아쿠아링", "Anneau Hydro", "Wasserring", "Acua Aro", "Acquanello", "Aqua Ring") },
            // { PBEMove.393, new PBELocalizedString("でんじふゆう", "전자부유", "Vol Magnétik", "Magnetflug", "Levitón", "Magnetascesa", "Magnet Rise") },
            // { PBEMove.394, new PBELocalizedString("フレアドライブ", "플레어드라이브", "Boutefeu", "Flammenblitz", "Envite Ígneo", "Fuococarica", "Flare Blitz") },
            { PBEMove.ForcePalm, new PBELocalizedString("はっけい", "발경", "Forte-Paume", "Kraftwelle", "Palmeo", "Palmoforza", "Force Palm") },
            { PBEMove.AuraSphere, new PBELocalizedString("はどうだん", "파동탄", "Aurasphère", "Aurasphäre", "Esfera Aural", "Forzasfera", "Aura Sphere") },
            { PBEMove.RockPolish, new PBELocalizedString("ロックカット", "록커트", "Poliroche", "Steinpolitur", "Pulimento", "Lucidatura", "Rock Polish") },
            { PBEMove.PoisonJab, new PBELocalizedString("どくづき", "독찌르기", "Direct Toxik", "Gifthieb", "Puya Nociva", "Velenpuntura", "Poison Jab") },
            { PBEMove.DarkPulse, new PBELocalizedString("あくのはどう", "악의파동", "Vibrobscur", "Finsteraura", "Pulso Umbrío", "Neropulsar", "Dark Pulse") },
            { PBEMove.NightSlash, new PBELocalizedString("つじぎり", "깜짝베기", "Tranche-Nuit", "Nachthieb", "Tajo Umbrío", "Nottesferza", "Night Slash") },
            { PBEMove.AquaTail, new PBELocalizedString("アクアテール", "아쿠아테일", "Hydroqueue", "Nassschweif", "Acua Cola", "Idrondata", "Aqua Tail") },
            { PBEMove.SeedBomb, new PBELocalizedString("タネばくだん", "씨폭탄", "Canon Graine", "Samenbomben", "Bomba Germen", "Semebomba", "Seed Bomb") },
            { PBEMove.AirSlash, new PBELocalizedString("エアスラッシュ", "에어슬래시", "Lame d’Air", "Luftschnitt", "Tajo Aéreo", "Eterelama", "Air Slash") },
            { PBEMove.XScissor, new PBELocalizedString("シザークロス", "시저크로스", "Plaie-Croix", "Kreuzschere", "Tijera X", "Forbice X", "X-Scissor") },
            { PBEMove.BugBuzz, new PBELocalizedString("むしのさざめき", "벌레의야단법석", "Bourdon", "Käfergebrumm", "Zumbido", "Ronzio", "Bug Buzz") },
            { PBEMove.DragonPulse, new PBELocalizedString("りゅうのはどう", "용의파동", "Dracochoc", "Drachenpuls", "Pulso Dragón", "Dragopulsar", "Dragon Pulse") },
            { PBEMove.DragonRush, new PBELocalizedString("ドラゴンダイブ", "드래곤다이브", "Dracocharge", "Drachenstoß", "Carga Dragón", "Dragofuria", "Dragon Rush") },
            { PBEMove.PowerGem, new PBELocalizedString("パワージェム", "파워젬", "Rayon Gemme", "Juwelenkraft", "Joya de Luz", "Gemmoforza", "Power Gem") },
            // { PBEMove.409, new PBELocalizedString("ドレインパンチ", "드레인펀치", "Vampipoing", "Ableithieb", "Puño Drenaje", "Assorbipugno", "Drain Punch") },
            { PBEMove.VacuumWave, new PBELocalizedString("しんくうは", "진공파", "Onde Vide", "Vakuumwelle", "Onda Vacío", "Vuotonda", "Vacuum Wave") },
            { PBEMove.FocusBlast, new PBELocalizedString("きあいだま", "기합구슬", "Exploforce", "Fokusstoß", "Onda Certera", "Focalcolpo", "Focus Blast") },
            { PBEMove.EnergyBall, new PBELocalizedString("エナジーボール", "에너지볼", "Éco-Sphère", "Energieball", "Energibola", "Energipalla", "Energy Ball") },
            // { PBEMove.413, new PBELocalizedString("ブレイブバード", "브레이브버드", "Rapace", "Sturzflug", "Pájaro Osado", "Baldeali", "Brave Bird") },
            { PBEMove.EarthPower, new PBELocalizedString("だいちのちから", "대지의힘", "Telluriforce", "Erdkräfte", "Tierra Viva", "Geoforza", "Earth Power") },
            // { PBEMove.415, new PBELocalizedString("すりかえ", "바꿔치기", "Passe-Passe", "Wechseldich", "Trapicheo", "Rapidscambio", "Switcheroo") },
            // { PBEMove.416, new PBELocalizedString("ギガインパクト", "기가임팩트", "Giga Impact", "Gigastoß", "Giga Impacto", "Gigaimpatto", "Giga Impact") },
            { PBEMove.NastyPlot, new PBELocalizedString("わるだくみ", "나쁜음모", "Machination", "Ränkeschmied", "Maquinación", "Congiura", "Nasty Plot") },
            { PBEMove.BulletPunch, new PBELocalizedString("バレットパンチ", "불릿펀치", "Pisto-Poing", "Patronenhieb", "Puño Bala", "Pugnoscarica", "Bullet Punch") },
            // { PBEMove.419, new PBELocalizedString("ゆきなだれ", "눈사태", "Avalanche", "Lawine", "Alud", "Slavina", "Avalanche") },
            { PBEMove.IceShard, new PBELocalizedString("こおりのつぶて", "얼음뭉치", "Éclats Glace", "Eissplitter", "Canto Helado", "Geloscheggia", "Ice Shard") },
            { PBEMove.ShadowClaw, new PBELocalizedString("シャドークロー", "섀도크루", "Griffe Ombre", "Dunkelklaue", "Garra Umbría", "Ombrartigli", "Shadow Claw") },
            // { PBEMove.422, new PBELocalizedString("かみなりのキバ", "번개엄니", "Crocs Éclair", "Donnerzahn", "Colm. Rayo", "Fulmindenti", "Thunder Fang") },
            // { PBEMove.423, new PBELocalizedString("こおりのキバ", "얼음엄니", "Crocs Givre", "Eiszahn", "Colm. Hielo", "Gelodenti", "Ice Fang") },
            // { PBEMove.424, new PBELocalizedString("ほのおのキバ", "불꽃엄니", "Crocs Feu", "Feuerzahn", "Colm. Ígneo", "Rogodenti", "Fire Fang") },
            { PBEMove.ShadowSneak, new PBELocalizedString("かげうち", "야습", "Ombre Portée", "Schattenstoß", "Sombra Vil", "Furtivombra", "Shadow Sneak") },
            { PBEMove.MudBomb, new PBELocalizedString("どろばくだん", "진흙폭탄", "Boue-Bombe", "Schlammbombe", "Bomba Fango", "Pantanobomba", "Mud Bomb") },
            { PBEMove.PsychoCut, new PBELocalizedString("サイコカッター", "사이코커터", "Coupe Psycho", "Psychoklinge", "Psico-corte", "Psicotaglio", "Psycho Cut") },
            { PBEMove.ZenHeadbutt, new PBELocalizedString("しねんのずつき", "사념의박치기", "Psykoud’Boul", "Zen-Kopfstoß", "Cabezazo Zen", "Cozzata Zen", "Zen Headbutt") },
            { PBEMove.MirrorShot, new PBELocalizedString("ミラーショット", "미러숏", "Miroi-Tir", "Spiegelsalve", "Disp. Espejo", "Cristalcolpo", "Mirror Shot") },
            { PBEMove.FlashCannon, new PBELocalizedString("ラスターカノン", "러스터캐논", "Luminocanon", "Lichtkanone", "Foco Respl.", "Cannonflash", "Flash Cannon") },
            { PBEMove.RockClimb, new PBELocalizedString("ロッククライム", "락클라임", "Escalade", "Kraxler", "Treparrocas", "Scalaroccia", "Rock Climb") },
            // { PBEMove.432, new PBELocalizedString("きりばらい", "안개제거", "Anti-Brume", "Auflockern", "Despejar", "Scacciabruma", "Defog") },
            // { PBEMove.433, new PBELocalizedString("トリックルーム", "트릭룸", "Distorsion", "Bizarroraum", "Espacio Raro", "Distortozona", "Trick Room") },
            { PBEMove.DracoMeteor, new PBELocalizedString("りゅうせいぐん", "용성군", "Draco Météor", "Draco Meteor", "Cometa Draco", "Dragobolide", "Draco Meteor") },
            { PBEMove.Discharge, new PBELocalizedString("ほうでん", "방전", "Coup d’Jus", "Ladungsstoß", "Chispazo", "Scarica", "Discharge") },
            { PBEMove.LavaPlume, new PBELocalizedString("ふんえん", "분연", "Ébullilave", "Flammensturm", "Humareda", "Lavasbuffo", "Lava Plume") },
            { PBEMove.LeafStorm, new PBELocalizedString("リーフストーム", "리프스톰", "Tempêteverte", "Blättersturm", "Lluevehojas", "Verdebufera", "Leaf Storm") },
            { PBEMove.PowerWhip, new PBELocalizedString("パワーウィップ", "파워휩", "Mégafouet", "Blattgeißel", "Latigazo", "Vigorcolpo", "Power Whip") },
            // { PBEMove.439, new PBELocalizedString("がんせきほう", "암석포", "Roc-Boulet", "Felswerfer", "Romperrocas", "Devastomasso", "Rock Wrecker") },
            { PBEMove.CrossPoison, new PBELocalizedString("クロスポイズン", "크로스포이즌", "Poison-Croix", "Giftstreich", "Veneno X", "Velenocroce", "Cross Poison") },
            { PBEMove.GunkShot, new PBELocalizedString("ダストシュート", "더스트슈트", "Détricanon", "Mülltreffer", "Lanza Mugre", "Sporcolancio", "Gunk Shot") },
            { PBEMove.IronHead, new PBELocalizedString("アイアンヘッド", "아이언헤드", "Tête de Fer", "Eisenschädel", "Cabezahierro", "Metaltestata", "Iron Head") },
            { PBEMove.MagnetBomb, new PBELocalizedString("マグネットボム", "마그넷봄", "Bombaimant", "Magnetbombe", "Bomba Imán", "Bombagnete", "Magnet Bomb") },
            { PBEMove.StoneEdge, new PBELocalizedString("ストーンエッジ", "스톤에지", "Lame de Roc", "Steinkante", "Roca Afilada", "Pietrataglio", "Stone Edge") },
            // { PBEMove.445, new PBELocalizedString("ゆうわく", "유혹", "Séduction", "Liebreiz", "Seducción", "Incanto", "Captivate") },
            { PBEMove.StealthRock, new PBELocalizedString("ステルスロック", "스텔스록", "Piège de Roc", "Tarnsteine", "Trampa Rocas", "Levitoroccia", "Stealth Rock") },
            { PBEMove.GrassKnot, new PBELocalizedString("くさむすび", "풀묶기", "Nœud Herbe", "Strauchler", "Hierba Lazo", "Laccioerboso", "Grass Knot") },
            { PBEMove.Chatter, new PBELocalizedString("おしゃべり", "수다", "Babil", "Geschwätz", "Cháchara", "Schiamazzo", "Chatter") },
            { PBEMove.Judgment, new PBELocalizedString("さばきのつぶて", "심판의뭉치", "Jugement", "Urteilskraft", "Sentencia", "Giudizio", "Judgment") },
            // { PBEMove.450, new PBELocalizedString("むしくい", "벌레먹음", "Piqûre", "Käferbiss", "Picadura", "Coleomorso", "Bug Bite") },
            { PBEMove.ChargeBeam, new PBELocalizedString("チャージビーム", "차지빔", "Rayon Chargé", "Ladestrahl", "Rayo Carga", "Raggioscossa", "Charge Beam") },
            // { PBEMove.452, new PBELocalizedString("ウッドハンマー", "우드해머", "Martobois", "Holzhammer", "Mazazo", "Mazzuolegno", "Wood Hammer") },
            { PBEMove.AquaJet, new PBELocalizedString("アクアジェット", "아쿠아제트", "Aqua-Jet", "Wasserdüse", "Acua Jet", "Acquagetto", "Aqua Jet") },
            { PBEMove.AttackOrder, new PBELocalizedString("こうげきしれい", "공격지령", "Appel Attak", "Schlagbefehl", "Al Ataque", "Comandourto", "Attack Order") },
            { PBEMove.DefendOrder, new PBELocalizedString("ぼうぎょしれい", "방어지령", "Appel Défens", "Blockbefehl", "A Defender", "Comandoscudo", "Defend Order") },
            { PBEMove.HealOrder, new PBELocalizedString("かいふくしれい", "회복지령", "Appel Soins", "Heilbefehl", "Auxilio", "Comandocura", "Heal Order") },
            // { PBEMove.457, new PBELocalizedString("もろはのずつき", "양날박치기", "Fracass’Tête", "Kopfstoß", "Testarazo", "Zuccata", "Head Smash") },
            // { PBEMove.458, new PBELocalizedString("ダブルアタック", "더블어택", "Coup Double", "Doppelschlag", "Doble Golpe", "Doppiosmash", "Double Hit") },
            // { PBEMove.459, new PBELocalizedString("ときのほうこう", "시간의포효", "Hurle-Temps", "Zeitenlärm", "Distorsión", "Fragortempo", "Roar of Time") },
            { PBEMove.SpacialRend, new PBELocalizedString("あくうせつだん", "공간절단", "Spatio-Rift", "Raumschlag", "Corte Vacío", "Fendispazio", "Spacial Rend") },
            // { PBEMove.461, new PBELocalizedString("みかづきのまい", "초승달춤", "Danse-Lune", "Lunartanz", "Danza Lunar", "Lunardanza", "Lunar Dance") },
            // { PBEMove.462, new PBELocalizedString("にぎりつぶす", "묵사발", "Presse", "Quetschgriff", "Agarrón", "Sbriciolmano", "Crush Grip") },
            // { PBEMove.463, new PBELocalizedString("マグマストーム", "마그마스톰", "Vortex Magma", "Lavasturm", "Lluvia Ígnea", "Magmaclisma", "Magma Storm") },
            { PBEMove.DarkVoid, new PBELocalizedString("ダークホール", "다크홀", "Trou Noir", "Schlummerort", "Brecha Negra", "Vuototetro", "Dark Void") },
            { PBEMove.SeedFlare, new PBELocalizedString("シードフレア", "시드플레어", "Fulmigraine", "Schocksamen", "Fogonazo", "Infuriaseme", "Seed Flare") },
            { PBEMove.OminousWind, new PBELocalizedString("あやしいかぜ", "괴상한바람", "Vent Mauvais", "Unheilböen", "Vien. Aciago", "Funestovento", "Ominous Wind") },
            // { PBEMove.467, new PBELocalizedString("シャドーダイブ", "섀도다이브", "Revenant", "Schemenkraft", "Golpe Umbrío", "Oscurotuffo", "Shadow Force") },
            { PBEMove.HoneClaws, new PBELocalizedString("つめとぎ", "손톱갈기", "Aiguisage", "Klauenwetzer", "Afilagarras", "Unghiaguzze", "Hone Claws") },
            // { PBEMove.469, new PBELocalizedString("ワイドガード", "와이드가드", "Garde Large", "Rundumschutz", "Vastaguardia", "Bodyguard", "Wide Guard") },
            // { PBEMove.470, new PBELocalizedString("ガードシェア", "가드셰어", "PartageGarde", "Schutzteiler", "Isoguardia", "Paridifesa", "Guard Split") },
            // { PBEMove.471, new PBELocalizedString("パワーシェア", "파워셰어", "PartageForce", "Kraftteiler", "Isofuerza", "Pariattacco", "Power Split") },
            // { PBEMove.472, new PBELocalizedString("ワンダールーム", "원더룸", "Zone Étrange", "Wunderraum", "Zona Extraña", "Mirabilzona", "Wonder Room") },
            { PBEMove.Psyshock, new PBELocalizedString("サイコショック", "사이코쇼크", "Choc Psy", "Psychoschock", "Psicocarga", "Psicoshock", "Psyshock") },
            { PBEMove.Venoshock, new PBELocalizedString("ベノムショック", "베놈쇼크", "Choc Venin", "Giftschock", "Cargatóxica", "Velenoshock", "Venoshock") },
            // { PBEMove.475, new PBELocalizedString("ボディパージ", "바디퍼지", "Allègement", "Autotomie", "Aligerar", "Sganciapesi", "Autotomize") },
            // { PBEMove.476, new PBELocalizedString("いかりのこな", "분노가루", "PoudreFureur", "Wutpulver", "Polvo Ira", "Polverabbia", "Rage Powder") },
            // { PBEMove.477, new PBELocalizedString("テレキネシス", "텔레키네시스", "Lévikinésie", "Telekinese", "Telequinesis", "Telecinesi", "Telekinesis") },
            // { PBEMove.478, new PBELocalizedString("マジックルーム", "매직룸", "Zone Magique", "Magieraum", "Zona Mágica", "Magicozona", "Magic Room") },
            // { PBEMove.479, new PBELocalizedString("うちおとす", "떨어뜨리기", "Anti-Air", "Katapult", "Antiaéreo", "Abbattimento", "Smack Down") },
            { PBEMove.StormThrow, new PBELocalizedString("やまあらし", "업어후리기", "Yama Arashi", "Bergsturm", "Llave Corsé", "Tempestretta", "Storm Throw") },
            // { PBEMove.481, new PBELocalizedString("はじけるほのお", "불꽃튀기기", "Rebondifeu", "Funkenflug", "Pirotecnia", "Pirolancio", "Flame Burst") },
            { PBEMove.SludgeWave, new PBELocalizedString("ヘドロウェーブ", "오물웨이브", "Cradovague", "Schlammwoge", "Onda Tóxica", "Fangonda", "Sludge Wave") },
            { PBEMove.QuiverDance, new PBELocalizedString("ちょうのまい", "나비춤", "Papillodanse", "Falterreigen", "Danza Aleteo", "Eledanza", "Quiver Dance") },
            { PBEMove.HeavySlam, new PBELocalizedString("ヘビーボンバー", "헤비봄버", "Tacle Lourd", "Rammboss", "Cuerpopesado", "Pesobomba", "Heavy Slam") },
            // { PBEMove.485, new PBELocalizedString("シンクロノイズ", "싱크로노이즈", "Synchropeine", "Synchrolärm", "Sincrorruido", "Sincrumore", "Synchronoise") },
            // { PBEMove.486, new PBELocalizedString("エレキボール", "일렉트릭볼", "Boule Élek", "Elektroball", "Bola Voltio", "Energisfera", "Electro Ball") },
            // { PBEMove.487, new PBELocalizedString("みずびたし", "물붓기", "Détrempage", "Überflutung", "Anegar", "Inondazione", "Soak") },
            { PBEMove.FlameCharge, new PBELocalizedString("ニトロチャージ", "니트로차지", "Nitrocharge", "Nitroladung", "Nitrocarga", "Nitrocarica", "Flame Charge") },
            { PBEMove.Coil, new PBELocalizedString("とぐろをまく", "똬리틀기", "Enroulement", "Einrollen", "Enrosque", "Arrotola", "Coil") },
            { PBEMove.LowSweep, new PBELocalizedString("ローキック", "로킥", "Balayette", "Fußtritt", "Puntapié", "Calciobasso", "Low Sweep") },
            { PBEMove.AcidSpray, new PBELocalizedString("アシッドボム", "애시드봄", "Bombe Acide", "Säurespeier", "Bomba Ácida", "Acidobomba", "Acid Spray") },
            // { PBEMove.492, new PBELocalizedString("イカサマ", "속임수", "Tricherie", "Schmarotzer", "Juego Sucio", "Ripicca", "Foul Play") },
            // { PBEMove.493, new PBELocalizedString("シンプルビーム", "심플빔", "Rayon Simple", "Wankelstrahl", "Onda Simple", "Ondisinvolta", "Simple Beam") },
            // { PBEMove.494, new PBELocalizedString("なかまづくり", "동료만들기", "Ten-danse", "Zwango", "Danza Amiga", "Saltamicizia", "Entrainment") },
            // { PBEMove.495, new PBELocalizedString("おさきにどうぞ", "당신먼저", "Après Vous", "Galanterie", "Cede Paso", "Cortesia", "After You") },
            // { PBEMove.496, new PBELocalizedString("りんしょう", "돌림노래", "Chant Canon", "Kanon", "Canon", "Coro", "Round") },
            // { PBEMove.497, new PBELocalizedString("エコーボイス", "에코보이스", "Écho", "Widerhall", "Eco Voz", "Echeggiavoce", "Echoed Voice") },
            // { PBEMove.498, new PBELocalizedString("なしくずし", "야금야금", "Attrition", "Zermürben", "Guardia Baja", "Insidia", "Chip Away") },
            // { PBEMove.499, new PBELocalizedString("クリアスモッグ", "클리어스모그", "Bain de Smog", "Klärsmog", "Nieblaclara", "Pulifumo", "Clear Smog") },
            // { PBEMove.500, new PBELocalizedString("アシストパワー", "어시스트파워", "ForceAjoutée", "Kraftvorrat", "Poderreserva", "Veicolaforza", "Stored Power") },
            // { PBEMove.501, new PBELocalizedString("ファストガード", "퍼스트가드", "Prévention", "Rapidschutz", "Anticipo", "Anticipo", "Quick Guard") },
            // { PBEMove.502, new PBELocalizedString("サイドチェンジ", "사이드체인지", "Interversion", "Seitentausch", "Cambio Banda", "Cambiaposto", "Ally Switch") },
            { PBEMove.Scald, new PBELocalizedString("ねっとう", "열탕", "Ébullition", "Siedewasser", "Escaldar", "Idrovampata", "Scald") },
            { PBEMove.ShellSmash, new PBELocalizedString("からをやぶる", "껍질깨기", "Exuviation", "Hausbruch", "Rompecoraza", "Gettaguscio", "Shell Smash") },
            // { PBEMove.505, new PBELocalizedString("いやしのはどう", "치유파동", "Vibra Soin", "Heilwoge", "Pulso Cura", "Ondasana", "Heal Pulse") },
            { PBEMove.Hex, new PBELocalizedString("たたりめ", "병상첨병", "Châtiment", "Bürde", "Infortunio", "Sciagura", "Hex") },
            // { PBEMove.507, new PBELocalizedString("フリーフォール", "프리폴", "Chute Libre", "Freier Fall", "Caída Libre", "Cadutalibera", "Sky Drop") },
            { PBEMove.ShiftGear, new PBELocalizedString("ギアチェンジ", "기어체인지", "Chgt Vitesse", "Gangwechsel", "Cambiomarcha", "Cambiomarcia", "Shift Gear") },
            // { PBEMove.509, new PBELocalizedString("ともえなげ", "배대뒤치기", "Projection", "Überkopfwurf", "Llave Giro", "Ribaltiro", "Circle Throw") },
            // { PBEMove.510, new PBELocalizedString("やきつくす", "불태우기", "Calcination", "Einäschern", "Calcinación", "Bruciatutto", "Incinerate") },
            // { PBEMove.511, new PBELocalizedString("さきおくり", "순서미루기", "À la Queue", "Verzögerung", "Último Lugar", "Spintone", "Quash") },
            // { PBEMove.512, new PBELocalizedString("アクロバット", "애크러뱃", "Acrobatie", "Akrobatik", "Acróbata", "Acrobazia", "Acrobatics") },
            // { PBEMove.513, new PBELocalizedString("ミラータイプ", "미러타입", "Copie Type", "Typenspiegel", "Clonatipo", "Riflettipo", "Reflect Type") },
            { PBEMove.Retaliate, new PBELocalizedString("かたきうち", "원수갚기", "Vengeance", "Heimzahlung", "Represalia", "Nemesi", "Retaliate") },
            { PBEMove.FinalGambit, new PBELocalizedString("いのちがけ", "목숨걸기", "Tout ou Rien", "Wagemut", "Sacrificio", "Azzardo", "Final Gambit") },
            // { PBEMove.516, new PBELocalizedString("ギフトパス", "기프트패스", "Passe-Cadeau", "Offerte", "Ofrenda", "Cediregalo", "Bestow") },
            { PBEMove.Inferno, new PBELocalizedString("れんごく", "연옥", "Feu d’Enfer", "Inferno", "Infierno", "Marchiatura", "Inferno") },
            // { PBEMove.518, new PBELocalizedString("みずのちかい", "물의맹세", "Aire d’Eau", "Wassersäulen", "Voto Agua", "Acquapatto", "Water Pledge") },
            // { PBEMove.519, new PBELocalizedString("ほのおのちかい", "불꽃의맹세", "Aire de Feu", "Feuersäulen", "Voto Fuego", "Fiammapatto", "Fire Pledge") },
            // { PBEMove.520, new PBELocalizedString("くさのちかい", "풀의맹세", "Aire d’Herbe", "Pflanzsäulen", "Voto Planta", "Erbapatto", "Grass Pledge") },
            // { PBEMove.521, new PBELocalizedString("ボルトチェンジ", "볼트체인지", "ChangeÉclair", "Voltwechsel", "Voltiocambio", "Invertivolt", "Volt Switch") },
            { PBEMove.StruggleBug, new PBELocalizedString("むしのていこう", "벌레의저항", "Survinsecte", "Käfertrutz", "Estoicismo", "Entomoblocco", "Struggle Bug") },
            { PBEMove.Bulldoze, new PBELocalizedString("じならし", "땅고르기", "Piétisol", "Dampfwalze", "Terratemblor", "Battiterra", "Bulldoze") },
            { PBEMove.FrostBreath, new PBELocalizedString("こおりのいぶき", "얼음숨결", "SouffleGlacé", "Eisesodem", "Vaho Gélido", "Alitogelido", "Frost Breath") },
            // { PBEMove.525, new PBELocalizedString("ドラゴンテール", "드래곤테일", "Draco-Queue", "Drachenrute", "Cola Dragón", "Codadrago", "Dragon Tail") },
            { PBEMove.WorkUp, new PBELocalizedString("ふるいたてる", "분발", "Rengorgement", "Kraftschub", "Avivar", "Cuordileone", "Work Up") },
            { PBEMove.Electroweb, new PBELocalizedString("エレキネット", "일렉트릭네트", "Toile Élek", "Elektronetz", "Electrotela", "Elettrotela", "Electroweb") },
            // { PBEMove.528, new PBELocalizedString("ワイルドボルト", "와일드볼트", "Éclair Fou", "Stromstoß", "Voltio Cruel", "Sprizzalampo", "Wild Charge") },
            { PBEMove.DrillRun, new PBELocalizedString("ドリルライナー", "드릴라이너", "Tunnelier", "Schlagbohrer", "Taladradora", "Giravvita", "Drill Run") },
            // { PBEMove.530, new PBELocalizedString("ダブルチョップ", "더블촙", "Double Baffe", "Doppelhieb", "Golpe Bis", "Doppiocolpo", "Dual Chop") },
            { PBEMove.HeartStamp, new PBELocalizedString("ハートスタンプ", "하트스탬프", "Crève-Cœur", "Herzstempel", "Arrumaco", "Cuorestampo", "Heart Stamp") },
            // { PBEMove.532, new PBELocalizedString("ウッドホーン", "우드호른", "Encornebois", "Holzgeweih", "Astadrenaje", "Legnicorno", "Horn Leech") },
            // { PBEMove.533, new PBELocalizedString("せいなるつるぎ", "성스러운칼", "Lame Sainte", "Sanctoklinge", "Espadasanta", "Spadasolenne", "Sacred Sword") },
            { PBEMove.RazorShell, new PBELocalizedString("シェルブレード", "셸블레이드", "Coquilame", "Kalkklinge", "Concha Filo", "Conchilama", "Razor Shell") },
            { PBEMove.HeatCrash, new PBELocalizedString("ヒートスタンプ", "히트스탬프", "Tacle Feu", "Brandstempel", "Golpe Calor", "Marchiafuoco", "Heat Crash") },
            { PBEMove.LeafTornado, new PBELocalizedString("グラスミキサー", "그래스믹서", "Phytomixeur", "Grasmixer", "Ciclón Hojas", "Vorticerba", "Leaf Tornado") },
            { PBEMove.Steamroller, new PBELocalizedString("ハードローラー", "하드롤러", "Bulldoboule", "Quetschwalze", "Rodillo Púas", "Rulloduro", "Steamroller") },
            { PBEMove.CottonGuard, new PBELocalizedString("コットンガード", "코튼가드", "Cotogarde", "Watteschild", "Rizo Algodón", "Cotonscudo", "Cotton Guard") },
            { PBEMove.NightDaze, new PBELocalizedString("ナイトバースト", "나이트버스트", "Explonuit", "Nachtflut", "Pulso Noche", "Urtoscuro", "Night Daze") },
            { PBEMove.Psystrike, new PBELocalizedString("サイコブレイク", "사이코브레이크", "Frappe Psy", "Psychostoß", "Onda Mental", "Psicobotta", "Psystrike") },
            // { PBEMove.541, new PBELocalizedString("スイープビンタ", "스위프뺨치기", "Plumo-Queue", "Kehrschelle", "Plumerazo", "Spazzasberla", "Tail Slap") },
            // { PBEMove.542, new PBELocalizedString("ぼうふう", "폭풍", "Vent Violent", "Orkan", "Vendaval", "Tifone", "Hurricane") },
            // { PBEMove.543, new PBELocalizedString("アフロブレイク", "아프로브레이크", "Peignée", "Steinschädel", "Ariete", "Ricciolata", "Head Charge") },
            // { PBEMove.544, new PBELocalizedString("ギアソーサー", "기어소서", "Lancécrou", "Klikkdiskus", "Rueda Doble", "Ingracolpo", "Gear Grind") },
            { PBEMove.SearingShot, new PBELocalizedString("かえんだん", "화염탄", "Incendie", "Flammenball", "Bomba Ígnea", "Sparafuoco", "Searing Shot") },
            { PBEMove.TechnoBlast, new PBELocalizedString("テクノバスター", "테크노버스터", "TechnoBuster", "Techblaster", "Tecno Shock", "Tecnobotto", "Techno Blast") },
            // { PBEMove.547, new PBELocalizedString("いにしえのうた", "옛노래", "Chant Antique", "Urgesang", "Canto Arcaico", "Cantoantico", "Relic Song") },
            { PBEMove.SecretSword, new PBELocalizedString("しんぴのつるぎ", "신비의칼", "Lame Ointe", "Mystoschwert", "Sablemístico", "Spadamistica", "Secret Sword") },
            { PBEMove.Glaciate, new PBELocalizedString("こごえるせかい", "얼다세계", "ÈreGlaciaire", "Eiszeit", "Mundo Gélido", "Gelamondo", "Glaciate") },
            { PBEMove.BoltStrike, new PBELocalizedString("らいげき", "뇌격", "ChargeFoudre", "Blitzschlag", "At. Fulgor", "Lucesiluro", "Bolt Strike") },
            { PBEMove.BlueFlare, new PBELocalizedString("あおいほのお", "푸른불꽃", "Flamme Bleue", "Blauflammen", "Llama Azul", "Fuocoblu", "Blue Flare") },
            { PBEMove.FieryDance, new PBELocalizedString("ほのおのまい", "불꽃춤", "Danse du Feu", "Feuerreigen", "Danza Llama", "Voldifuoco", "Fiery Dance") },
            // { PBEMove.553, new PBELocalizedString("フリーズボルト", "프리즈볼트", "Éclair Gelé", "Frostvolt", "Rayo Gélido", "Elettrogelo", "Freeze Shock") },
            // { PBEMove.554, new PBELocalizedString("コールドフレア", "콜드플레어", "Feu Glacé", "Frosthauch", "Llama Gélida", "Vampagelida", "Ice Burn") },
            { PBEMove.Snarl, new PBELocalizedString("バークアウト", "바크아웃", "Aboiement", "Standpauke", "Alarido", "Urlorabbia", "Snarl") },
            { PBEMove.IcicleCrash, new PBELocalizedString("つららおとし", "고드름떨구기", "Chute Glace", "Eiszapfhagel", "Chuzos", "Scagliagelo", "Icicle Crash") },
            { PBEMove.VCreate, new PBELocalizedString("Ｖジェネレート", "V제너레이트", "CoupVictoire", "V-Generator", "V de Fuego", "Generatore V", "V-create") },
            // { PBEMove.558, new PBELocalizedString("クロスフレイム", "크로스플레임", "Flamme Croix", "Kreuzflamme", "Llama Fusión", "Incrofiamma", "Fusion Flare") },
            // { PBEMove.559, new PBELocalizedString("クロスサンダー", "크로스썬더", "Éclair Croix", "Kreuzdonner", "Rayo Fusión", "Incrotuono", "Fusion Bolt") }
        });
    }
}
