using Kermalis.PokemonBattleEngine.Data;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Kermalis.PokemonBattleEngine.Localization
{
    public static class PBEPokemonLocalization
    {
        public static ReadOnlyDictionary<PBESpecies, PBELocalizedString> Names { get; } = new ReadOnlyDictionary<PBESpecies, PBELocalizedString>(new Dictionary<PBESpecies, PBELocalizedString>()
        {
            { PBESpecies.Bulbasaur, new PBELocalizedString("Bulbasaur", "フシギダネ") },
            { PBESpecies.Ivysaur, new PBELocalizedString("Ivysaur", "フシギソウ") },
            { PBESpecies.Venusaur, new PBELocalizedString("Venusaur", "フシギバナ") },
            { PBESpecies.Charmander, new PBELocalizedString("Charmander", "ヒトカゲ") },
            { PBESpecies.Charmeleon, new PBELocalizedString("Charmeleon", "リザード") },
            { PBESpecies.Charizard, new PBELocalizedString("Charizard", "リザードン") },
            { PBESpecies.Squirtle, new PBELocalizedString("Squirtle", "ゼニガメ") },
            { PBESpecies.Wartortle, new PBELocalizedString("Wartortle", "カメール") },
            { PBESpecies.Blastoise, new PBELocalizedString("Blastoise", "カメックス") },
            { PBESpecies.Caterpie, new PBELocalizedString("Caterpie", "キャタピー") },
            { PBESpecies.Metapod, new PBELocalizedString("Metapod", "トランセル") },
            { PBESpecies.Butterfree, new PBELocalizedString("Butterfree", "バタフリー") },
            { PBESpecies.Weedle, new PBELocalizedString("Weedle", "ビードル") },
            { PBESpecies.Kakuna, new PBELocalizedString("Kakuna", "コクーン") },
            { PBESpecies.Beedrill, new PBELocalizedString("Beedrill", "スピアー") },
            // { PBESpecies.16, new PBELocalizedString("Pidgey", "ポッポ") },
            // { PBESpecies.17, new PBELocalizedString("Pidgeotto", "ピジョン") },
            // { PBESpecies.18, new PBELocalizedString("Pidgeot", "ピジョット") },
            // { PBESpecies.19, new PBELocalizedString("Rattata", "コラッタ") },
            // { PBESpecies.20, new PBELocalizedString("Raticate", "ラッタ") },
            // { PBESpecies.21, new PBELocalizedString("Spearow", "オニスズメ") },
            // { PBESpecies.22, new PBELocalizedString("Fearow", "オニドリル") },
            // { PBESpecies.23, new PBELocalizedString("Ekans", "アーボ") },
            // { PBESpecies.24, new PBELocalizedString("Arbok", "アーボック") },
            { PBESpecies.Pikachu, new PBELocalizedString("Pikachu", "ピカチュウ") },
            { PBESpecies.Raichu, new PBELocalizedString("Raichu", "ライチュウ") },
            // { PBESpecies.27, new PBELocalizedString("Sandshrew", "サンド") },
            // { PBESpecies.28, new PBELocalizedString("Sandslash", "サンドパン") },
            // { PBESpecies.29, new PBELocalizedString("Nidoran♀", "ニドラン♀") },
            // { PBESpecies.30, new PBELocalizedString("Nidorina", "ニドリーナ") },
            // { PBESpecies.31, new PBELocalizedString("Nidoqueen", "ニドクイン") },
            // { PBESpecies.32, new PBELocalizedString("Nidoran♂", "ニドラン♂") },
            // { PBESpecies.33, new PBELocalizedString("Nidorino", "ニドリーノ") },
            // { PBESpecies.34, new PBELocalizedString("Nidoking", "ニドキング") },
            // { PBESpecies.35, new PBELocalizedString("Clefairy", "ピッピ") },
            // { PBESpecies.36, new PBELocalizedString("Clefable", "ピクシー") },
            { PBESpecies.Vulpix, new PBELocalizedString("Vulpix", "ロコン") },
            { PBESpecies.Ninetales, new PBELocalizedString("Ninetales", "キュウコン") },
            // { PBESpecies.39, new PBELocalizedString("Jigglypuff", "プリン") },
            // { PBESpecies.40, new PBELocalizedString("Wigglytuff", "プクリン") },
            // { PBESpecies.41, new PBELocalizedString("Zubat", "ズバット") },
            // { PBESpecies.42, new PBELocalizedString("Golbat", "ゴルバット") },
            // { PBESpecies.43, new PBELocalizedString("Oddish", "ナゾノクサ") },
            // { PBESpecies.44, new PBELocalizedString("Gloom", "クサイハナ") },
            // { PBESpecies.45, new PBELocalizedString("Vileplume", "ラフレシア") },
            // { PBESpecies.46, new PBELocalizedString("Paras", "パラス") },
            // { PBESpecies.47, new PBELocalizedString("Parasect", "パラセクト") },
            // { PBESpecies.48, new PBELocalizedString("Venonat", "コンパン") },
            // { PBESpecies.49, new PBELocalizedString("Venomoth", "モルフォン") },
            // { PBESpecies.50, new PBELocalizedString("Diglett", "ディグダ") },
            // { PBESpecies.51, new PBELocalizedString("Dugtrio", "ダグトリオ") },
            // { PBESpecies.52, new PBELocalizedString("Meowth", "ニャース") },
            // { PBESpecies.53, new PBELocalizedString("Persian", "ペルシアン") },
            // { PBESpecies.54, new PBELocalizedString("Psyduck", "コダック") },
            // { PBESpecies.55, new PBELocalizedString("Golduck", "ゴルダック") },
            // { PBESpecies.56, new PBELocalizedString("Mankey", "マンキー") },
            // { PBESpecies.57, new PBELocalizedString("Primeape", "オコリザル") },
            // { PBESpecies.58, new PBELocalizedString("Growlithe", "ガーディ") },
            // { PBESpecies.59, new PBELocalizedString("Arcanine", "ウインディ") },
            // { PBESpecies.60, new PBELocalizedString("Poliwag", "ニョロモ") },
            // { PBESpecies.61, new PBELocalizedString("Poliwhirl", "ニョロゾ") },
            // { PBESpecies.62, new PBELocalizedString("Poliwrath", "ニョロボン") },
            // { PBESpecies.63, new PBELocalizedString("Abra", "ケーシィ") },
            // { PBESpecies.64, new PBELocalizedString("Kadabra", "ユンゲラー") },
            // { PBESpecies.65, new PBELocalizedString("Alakazam", "フーディン") },
            // { PBESpecies.66, new PBELocalizedString("Machop", "ワンリキー") },
            // { PBESpecies.67, new PBELocalizedString("Machoke", "ゴーリキー") },
            // { PBESpecies.68, new PBELocalizedString("Machamp", "カイリキー") },
            // { PBESpecies.69, new PBELocalizedString("Bellsprout", "マダツボミ") },
            // { PBESpecies.70, new PBELocalizedString("Weepinbell", "ウツドン") },
            // { PBESpecies.71, new PBELocalizedString("Victreebel", "ウツボット") },
            // { PBESpecies.72, new PBELocalizedString("Tentacool", "メノクラゲ") },
            // { PBESpecies.73, new PBELocalizedString("Tentacruel", "ドククラゲ") },
            // { PBESpecies.74, new PBELocalizedString("Geodude", "イシツブテ") },
            // { PBESpecies.75, new PBELocalizedString("Graveler", "ゴローン") },
            // { PBESpecies.76, new PBELocalizedString("Golem", "ゴローニャ") },
            // { PBESpecies.77, new PBELocalizedString("Ponyta", "ポニータ") },
            // { PBESpecies.78, new PBELocalizedString("Rapidash", "ギャロップ") },
            // { PBESpecies.79, new PBELocalizedString("Slowpoke", "ヤドン") },
            // { PBESpecies.80, new PBELocalizedString("Slowbro", "ヤドラン") },
            // { PBESpecies.81, new PBELocalizedString("Magnemite", "コイル") },
            // { PBESpecies.82, new PBELocalizedString("Magneton", "レアコイル") },
            { PBESpecies.Farfetchd, new PBELocalizedString("Farfetch’d", "カモネギ") },
            // { PBESpecies.84, new PBELocalizedString("Doduo", "ドードー") },
            // { PBESpecies.85, new PBELocalizedString("Dodrio", "ドードリオ") },
            // { PBESpecies.86, new PBELocalizedString("Seel", "パウワウ") },
            // { PBESpecies.87, new PBELocalizedString("Dewgong", "ジュゴン") },
            // { PBESpecies.88, new PBELocalizedString("Grimer", "ベトベター") },
            // { PBESpecies.89, new PBELocalizedString("Muk", "ベトベトン") },
            // { PBESpecies.90, new PBELocalizedString("Shellder", "シェルダー") },
            // { PBESpecies.91, new PBELocalizedString("Cloyster", "パルシェン") },
            // { PBESpecies.92, new PBELocalizedString("Gastly", "ゴース") },
            // { PBESpecies.93, new PBELocalizedString("Haunter", "ゴースト") },
            // { PBESpecies.94, new PBELocalizedString("Gengar", "ゲンガー") },
            // { PBESpecies.95, new PBELocalizedString("Onix", "イワーク") },
            // { PBESpecies.96, new PBELocalizedString("Drowzee", "スリープ") },
            // { PBESpecies.97, new PBELocalizedString("Hypno", "スリーパー") },
            // { PBESpecies.98, new PBELocalizedString("Krabby", "クラブ") },
            // { PBESpecies.99, new PBELocalizedString("Kingler", "キングラー") },
            // { PBESpecies.100, new PBELocalizedString("Voltorb", "ビリリダマ") },
            // { PBESpecies.101, new PBELocalizedString("Electrode", "マルマイン") },
            // { PBESpecies.102, new PBELocalizedString("Exeggcute", "タマタマ") },
            // { PBESpecies.103, new PBELocalizedString("Exeggutor", "ナッシー") },
            { PBESpecies.Cubone, new PBELocalizedString("Cubone", "カラカラ") },
            { PBESpecies.Marowak, new PBELocalizedString("Marowak", "ガラガラ") },
            // { PBESpecies.106, new PBELocalizedString("Hitmonlee", "サワムラー") },
            // { PBESpecies.107, new PBELocalizedString("Hitmonchan", "エビワラー") },
            // { PBESpecies.108, new PBELocalizedString("Lickitung", "ベロリンガ") },
            // { PBESpecies.109, new PBELocalizedString("Koffing", "ドガース") },
            // { PBESpecies.110, new PBELocalizedString("Weezing", "マタドガス") },
            // { PBESpecies.111, new PBELocalizedString("Rhyhorn", "サイホーン") },
            // { PBESpecies.112, new PBELocalizedString("Rhydon", "サイドン") },
            { PBESpecies.Chansey, new PBELocalizedString("Chansey", "ラッキー") },
            // { PBESpecies.114, new PBELocalizedString("Tangela", "モンジャラ") },
            // { PBESpecies.115, new PBELocalizedString("Kangaskhan", "ガルーラ") },
            // { PBESpecies.116, new PBELocalizedString("Horsea", "タッツー") },
            // { PBESpecies.117, new PBELocalizedString("Seadra", "シードラ") },
            // { PBESpecies.118, new PBELocalizedString("Goldeen", "トサキント") },
            // { PBESpecies.119, new PBELocalizedString("Seaking", "アズマオウ") },
            // { PBESpecies.120, new PBELocalizedString("Staryu", "ヒトデマン") },
            // { PBESpecies.121, new PBELocalizedString("Starmie", "スターミー") },
            // { PBESpecies.122, new PBELocalizedString("Mr. Mime", "バリヤード") },
            // { PBESpecies.123, new PBELocalizedString("Scyther", "ストライク") },
            // { PBESpecies.124, new PBELocalizedString("Jynx", "ルージュラ") },
            // { PBESpecies.125, new PBELocalizedString("Electabuzz", "エレブー") },
            // { PBESpecies.126, new PBELocalizedString("Magmar", "ブーバー") },
            // { PBESpecies.127, new PBELocalizedString("Pinsir", "カイロス") },
            // { PBESpecies.128, new PBELocalizedString("Tauros", "ケンタロス") },
            // { PBESpecies.129, new PBELocalizedString("Magikarp", "コイキング") },
            // { PBESpecies.130, new PBELocalizedString("Gyarados", "ギャラドス") },
            // { PBESpecies.131, new PBELocalizedString("Lapras", "ラプラス") },
            { PBESpecies.Ditto, new PBELocalizedString("Ditto", "メタモン") },
            { PBESpecies.Eevee, new PBELocalizedString("Eevee", "イーブイ") },
            { PBESpecies.Vaporeon, new PBELocalizedString("Vaporeon", "シャワーズ") },
            { PBESpecies.Jolteon, new PBELocalizedString("Jolteon", "サンダース") },
            { PBESpecies.Flareon, new PBELocalizedString("Flareon", "ブースター") },
            // { PBESpecies.137, new PBELocalizedString("Porygon", "ポリゴン") },
            // { PBESpecies.138, new PBELocalizedString("Omanyte", "オムナイト") },
            // { PBESpecies.139, new PBELocalizedString("Omastar", "オムスター") },
            // { PBESpecies.140, new PBELocalizedString("Kabuto", "カブト") },
            // { PBESpecies.141, new PBELocalizedString("Kabutops", "カブトプス") },
            // { PBESpecies.142, new PBELocalizedString("Aerodactyl", "プテラ") },
            // { PBESpecies.143, new PBELocalizedString("Snorlax", "カビゴン") },
            // { PBESpecies.144, new PBELocalizedString("Articuno", "フリーザー") },
            // { PBESpecies.145, new PBELocalizedString("Zapdos", "サンダー") },
            // { PBESpecies.146, new PBELocalizedString("Moltres", "ファイヤー") },
            // { PBESpecies.147, new PBELocalizedString("Dratini", "ミニリュウ") },
            // { PBESpecies.148, new PBELocalizedString("Dragonair", "ハクリュー") },
            // { PBESpecies.149, new PBELocalizedString("Dragonite", "カイリュー") },
            // { PBESpecies.150, new PBELocalizedString("Mewtwo", "ミュウツー") },
            // { PBESpecies.151, new PBELocalizedString("Mew", "ミュウ") },
            // { PBESpecies.152, new PBELocalizedString("Chikorita", "チコリータ") },
            // { PBESpecies.153, new PBELocalizedString("Bayleef", "ベイリーフ") },
            // { PBESpecies.154, new PBELocalizedString("Meganium", "メガニウム") },
            // { PBESpecies.155, new PBELocalizedString("Cyndaquil", "ヒノアラシ") },
            // { PBESpecies.156, new PBELocalizedString("Quilava", "マグマラシ") },
            // { PBESpecies.157, new PBELocalizedString("Typhlosion", "バクフーン") },
            // { PBESpecies.158, new PBELocalizedString("Totodile", "ワニノコ") },
            // { PBESpecies.159, new PBELocalizedString("Croconaw", "アリゲイツ") },
            // { PBESpecies.160, new PBELocalizedString("Feraligatr", "オーダイル") },
            // { PBESpecies.161, new PBELocalizedString("Sentret", "オタチ") },
            // { PBESpecies.162, new PBELocalizedString("Furret", "オオタチ") },
            // { PBESpecies.163, new PBELocalizedString("Hoothoot", "ホーホー") },
            // { PBESpecies.164, new PBELocalizedString("Noctowl", "ヨルノズク") },
            // { PBESpecies.165, new PBELocalizedString("Ledyba", "レディバ") },
            // { PBESpecies.166, new PBELocalizedString("Ledian", "レディアン") },
            // { PBESpecies.167, new PBELocalizedString("Spinarak", "イトマル") },
            // { PBESpecies.168, new PBELocalizedString("Ariados", "アリアドス") },
            { PBESpecies.Crobat, new PBELocalizedString("Crobat", "クロバット") },
            // { PBESpecies.170, new PBELocalizedString("Chinchou", "チョンチー") },
            // { PBESpecies.171, new PBELocalizedString("Lanturn", "ランターン") },
            { PBESpecies.Pichu, new PBELocalizedString("Pichu", "ピチュー") },
            // { PBESpecies.173, new PBELocalizedString("Cleffa", "ピィ") },
            // { PBESpecies.174, new PBELocalizedString("Igglybuff", "ププリン") },
            // { PBESpecies.175, new PBELocalizedString("Togepi", "トゲピー") },
            // { PBESpecies.176, new PBELocalizedString("Togetic", "トゲチック") },
            // { PBESpecies.177, new PBELocalizedString("Natu", "ネイティ") },
            // { PBESpecies.178, new PBELocalizedString("Xatu", "ネイティオ") },
            // { PBESpecies.179, new PBELocalizedString("Mareep", "メリープ") },
            // { PBESpecies.180, new PBELocalizedString("Flaaffy", "モココ") },
            // { PBESpecies.181, new PBELocalizedString("Ampharos", "デンリュウ") },
            // { PBESpecies.182, new PBELocalizedString("Bellossom", "キレイハナ") },
            // { PBESpecies.183, new PBELocalizedString("Marill", "マリル") },
            { PBESpecies.Azumarill, new PBELocalizedString("Azumarill", "マリルリ") },
            // { PBESpecies.185, new PBELocalizedString("Sudowoodo", "ウソッキー") },
            // { PBESpecies.186, new PBELocalizedString("Politoed", "ニョロトノ") },
            // { PBESpecies.187, new PBELocalizedString("Hoppip", "ハネッコ") },
            // { PBESpecies.188, new PBELocalizedString("Skiploom", "ポポッコ") },
            // { PBESpecies.189, new PBELocalizedString("Jumpluff", "ワタッコ") },
            // { PBESpecies.190, new PBELocalizedString("Aipom", "エイパム") },
            // { PBESpecies.191, new PBELocalizedString("Sunkern", "ヒマナッツ") },
            // { PBESpecies.192, new PBELocalizedString("Sunflora", "キマワリ") },
            // { PBESpecies.193, new PBELocalizedString("Yanma", "ヤンヤンマ") },
            // { PBESpecies.194, new PBELocalizedString("Wooper", "ウパー") },
            // { PBESpecies.195, new PBELocalizedString("Quagsire", "ヌオー") },
            { PBESpecies.Espeon, new PBELocalizedString("Espeon", "エーフィ") },
            { PBESpecies.Umbreon, new PBELocalizedString("Umbreon", "ブラッキー") },
            // { PBESpecies.198, new PBELocalizedString("Murkrow", "ヤミカラス") },
            // { PBESpecies.199, new PBELocalizedString("Slowking", "ヤドキング") },
            { PBESpecies.Misdreavus, new PBELocalizedString("Misdreavus", "ムウマ") },
            { PBESpecies.Unown_A, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_B, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_C, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_D, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_E, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_Exclamation, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_F, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_G, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_H, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_I, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_J, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_K, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_L, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_M, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_N, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_O, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_P, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_Q, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_Question, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_R, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_S, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_T, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_U, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_V, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_W, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_X, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_Y, new PBELocalizedString("Unown", "アンノーン") },
            { PBESpecies.Unown_Z, new PBELocalizedString("Unown", "アンノーン") },
            // { PBESpecies.202, new PBELocalizedString("Wobbuffet", "ソーナンス") },
            // { PBESpecies.203, new PBELocalizedString("Girafarig", "キリンリキ") },
            // { PBESpecies.204, new PBELocalizedString("Pineco", "クヌギダマ") },
            // { PBESpecies.205, new PBELocalizedString("Forretress", "フォレトス") },
            // { PBESpecies.206, new PBELocalizedString("Dunsparce", "ノコッチ") },
            // { PBESpecies.207, new PBELocalizedString("Gligar", "グライガー") },
            // { PBESpecies.208, new PBELocalizedString("Steelix", "ハガネール") },
            // { PBESpecies.209, new PBELocalizedString("Snubbull", "ブルー") },
            // { PBESpecies.210, new PBELocalizedString("Granbull", "グランブル") },
            // { PBESpecies.211, new PBELocalizedString("Qwilfish", "ハリーセン") },
            // { PBESpecies.212, new PBELocalizedString("Scizor", "ハッサム") },
            // { PBESpecies.213, new PBELocalizedString("Shuckle", "ツボツボ") },
            // { PBESpecies.214, new PBELocalizedString("Heracross", "ヘラクロス") },
            // { PBESpecies.215, new PBELocalizedString("Sneasel", "ニューラ") },
            // { PBESpecies.216, new PBELocalizedString("Teddiursa", "ヒメグマ") },
            // { PBESpecies.217, new PBELocalizedString("Ursaring", "リングマ") },
            // { PBESpecies.218, new PBELocalizedString("Slugma", "マグマッグ") },
            // { PBESpecies.219, new PBELocalizedString("Magcargo", "マグカルゴ") },
            // { PBESpecies.220, new PBELocalizedString("Swinub", "ウリムー") },
            // { PBESpecies.221, new PBELocalizedString("Piloswine", "イノムー") },
            // { PBESpecies.222, new PBELocalizedString("Corsola", "サニーゴ") },
            // { PBESpecies.223, new PBELocalizedString("Remoraid", "テッポウオ") },
            // { PBESpecies.224, new PBELocalizedString("Octillery", "オクタン") },
            // { PBESpecies.225, new PBELocalizedString("Delibird", "デリバード") },
            // { PBESpecies.226, new PBELocalizedString("Mantine", "マンタイン") },
            // { PBESpecies.227, new PBELocalizedString("Skarmory", "エアームド") },
            // { PBESpecies.228, new PBELocalizedString("Houndour", "デルビル") },
            // { PBESpecies.229, new PBELocalizedString("Houndoom", "ヘルガー") },
            // { PBESpecies.230, new PBELocalizedString("Kingdra", "キングドラ") },
            // { PBESpecies.231, new PBELocalizedString("Phanpy", "ゴマゾウ") },
            // { PBESpecies.232, new PBELocalizedString("Donphan", "ドンファン") },
            // { PBESpecies.233, new PBELocalizedString("Porygon2", "ポリゴン２") },
            // { PBESpecies.234, new PBELocalizedString("Stantler", "オドシシ") },
            { PBESpecies.Smeargle, new PBELocalizedString("Smeargle", "ドーブル") },
            // { PBESpecies.236, new PBELocalizedString("Tyrogue", "バルキー") },
            // { PBESpecies.237, new PBELocalizedString("Hitmontop", "カポエラー") },
            // { PBESpecies.238, new PBELocalizedString("Smoochum", "ムチュール") },
            // { PBESpecies.239, new PBELocalizedString("Elekid", "エレキッド") },
            // { PBESpecies.240, new PBELocalizedString("Magby", "ブビィ") },
            // { PBESpecies.241, new PBELocalizedString("Miltank", "ミルタンク") },
            { PBESpecies.Blissey, new PBELocalizedString("Blissey", "ハピナス") },
            // { PBESpecies.243, new PBELocalizedString("Raikou", "ライコウ") },
            // { PBESpecies.244, new PBELocalizedString("Entei", "エンテイ") },
            // { PBESpecies.245, new PBELocalizedString("Suicune", "スイクン") },
            // { PBESpecies.246, new PBELocalizedString("Larvitar", "ヨーギラス") },
            // { PBESpecies.247, new PBELocalizedString("Pupitar", "サナギラス") },
            // { PBESpecies.248, new PBELocalizedString("Tyranitar", "バンギラス") },
            // { PBESpecies.249, new PBELocalizedString("Lugia", "ルギア") },
            // { PBESpecies.250, new PBELocalizedString("Ho-Oh", "ホウオウ") },
            // { PBESpecies.251, new PBELocalizedString("Celebi", "セレビィ") },
            // { PBESpecies.252, new PBELocalizedString("Treecko", "キモリ") },
            // { PBESpecies.253, new PBELocalizedString("Grovyle", "ジュプトル") },
            // { PBESpecies.254, new PBELocalizedString("Sceptile", "ジュカイン") },
            { PBESpecies.Torchic, new PBELocalizedString("Torchic", "アチャモ") },
            { PBESpecies.Combusken, new PBELocalizedString("Combusken", "ワカシャモ") },
            { PBESpecies.Blaziken, new PBELocalizedString("Blaziken", "バシャーモ") },
            // { PBESpecies.258, new PBELocalizedString("Mudkip", "ミズゴロウ") },
            // { PBESpecies.259, new PBELocalizedString("Marshtomp", "ヌマクロー") },
            // { PBESpecies.260, new PBELocalizedString("Swampert", "ラグラージ") },
            // { PBESpecies.261, new PBELocalizedString("Poochyena", "ポチエナ") },
            // { PBESpecies.262, new PBELocalizedString("Mightyena", "グラエナ") },
            // { PBESpecies.263, new PBELocalizedString("Zigzagoon", "ジグザグマ") },
            // { PBESpecies.264, new PBELocalizedString("Linoone", "マッスグマ") },
            // { PBESpecies.265, new PBELocalizedString("Wurmple", "ケムッソ") },
            // { PBESpecies.266, new PBELocalizedString("Silcoon", "カラサリス") },
            // { PBESpecies.267, new PBELocalizedString("Beautifly", "アゲハント") },
            // { PBESpecies.268, new PBELocalizedString("Cascoon", "マユルド") },
            // { PBESpecies.269, new PBELocalizedString("Dustox", "ドクケイル") },
            // { PBESpecies.270, new PBELocalizedString("Lotad", "ハスボー") },
            // { PBESpecies.271, new PBELocalizedString("Lombre", "ハスブレロ") },
            // { PBESpecies.272, new PBELocalizedString("Ludicolo", "ルンパッパ") },
            // { PBESpecies.273, new PBELocalizedString("Seedot", "タネボー") },
            // { PBESpecies.274, new PBELocalizedString("Nuzleaf", "コノハナ") },
            // { PBESpecies.275, new PBELocalizedString("Shiftry", "ダーテング") },
            // { PBESpecies.276, new PBELocalizedString("Taillow", "スバメ") },
            // { PBESpecies.277, new PBELocalizedString("Swellow", "オオスバメ") },
            // { PBESpecies.278, new PBELocalizedString("Wingull", "キャモメ") },
            // { PBESpecies.279, new PBELocalizedString("Pelipper", "ペリッパー") },
            // { PBESpecies.280, new PBELocalizedString("Ralts", "ラルトス") },
            // { PBESpecies.281, new PBELocalizedString("Kirlia", "キルリア") },
            // { PBESpecies.282, new PBELocalizedString("Gardevoir", "サーナイト") },
            // { PBESpecies.283, new PBELocalizedString("Surskit", "アメタマ") },
            // { PBESpecies.284, new PBELocalizedString("Masquerain", "アメモース") },
            // { PBESpecies.285, new PBELocalizedString("Shroomish", "キノココ") },
            // { PBESpecies.286, new PBELocalizedString("Breloom", "キノガッサ") },
            // { PBESpecies.287, new PBELocalizedString("Slakoth", "ナマケロ") },
            // { PBESpecies.288, new PBELocalizedString("Vigoroth", "ヤルキモノ") },
            // { PBESpecies.289, new PBELocalizedString("Slaking", "ケッキング") },
            { PBESpecies.Nincada, new PBELocalizedString("Nincada", "ツチニン") },
            { PBESpecies.Ninjask, new PBELocalizedString("Ninjask", "テッカニン") },
            { PBESpecies.Shedinja, new PBELocalizedString("Shedinja", "ヌケニン") },
            // { PBESpecies.293, new PBELocalizedString("Whismur", "ゴニョニョ") },
            // { PBESpecies.294, new PBELocalizedString("Loudred", "ドゴーム") },
            // { PBESpecies.295, new PBELocalizedString("Exploud", "バクオング") },
            // { PBESpecies.296, new PBELocalizedString("Makuhita", "マクノシタ") },
            // { PBESpecies.297, new PBELocalizedString("Hariyama", "ハリテヤマ") },
            // { PBESpecies.298, new PBELocalizedString("Azurill", "ルリリ") },
            // { PBESpecies.299, new PBELocalizedString("Nosepass", "ノズパス") },
            { PBESpecies.Skitty, new PBELocalizedString("Skitty", "エネコ") },
            { PBESpecies.Delcatty, new PBELocalizedString("Delcatty", "エネコロロ") },
            // { PBESpecies.302, new PBELocalizedString("Sableye", "ヤミラミ") },
            // { PBESpecies.303, new PBELocalizedString("Mawile", "クチート") },
            // { PBESpecies.304, new PBELocalizedString("Aron", "ココドラ") },
            // { PBESpecies.305, new PBELocalizedString("Lairon", "コドラ") },
            // { PBESpecies.306, new PBELocalizedString("Aggron", "ボスゴドラ") },
            // { PBESpecies.307, new PBELocalizedString("Meditite", "アサナン") },
            // { PBESpecies.308, new PBELocalizedString("Medicham", "チャーレム") },
            // { PBESpecies.309, new PBELocalizedString("Electrike", "ラクライ") },
            // { PBESpecies.310, new PBELocalizedString("Manectric", "ライボルト") },
            { PBESpecies.Plusle, new PBELocalizedString("Plusle", "プラスル") },
            { PBESpecies.Minun, new PBELocalizedString("Minun", "マイナン") },
            // { PBESpecies.313, new PBELocalizedString("Volbeat", "バルビート") },
            // { PBESpecies.314, new PBELocalizedString("Illumise", "イルミーゼ") },
            // { PBESpecies.315, new PBELocalizedString("Roselia", "ロゼリア") },
            // { PBESpecies.316, new PBELocalizedString("Gulpin", "ゴクリン") },
            // { PBESpecies.317, new PBELocalizedString("Swalot", "マルノーム") },
            // { PBESpecies.318, new PBELocalizedString("Carvanha", "キバニア") },
            // { PBESpecies.319, new PBELocalizedString("Sharpedo", "サメハダー") },
            // { PBESpecies.320, new PBELocalizedString("Wailmer", "ホエルコ") },
            // { PBESpecies.321, new PBELocalizedString("Wailord", "ホエルオー") },
            // { PBESpecies.322, new PBELocalizedString("Numel", "ドンメル") },
            // { PBESpecies.323, new PBELocalizedString("Camerupt", "バクーダ") },
            // { PBESpecies.324, new PBELocalizedString("Torkoal", "コータス") },
            // { PBESpecies.325, new PBELocalizedString("Spoink", "バネブー") },
            // { PBESpecies.326, new PBELocalizedString("Grumpig", "ブーピッグ") },
            // { PBESpecies.327, new PBELocalizedString("Spinda", "パッチール") },
            // { PBESpecies.328, new PBELocalizedString("Trapinch", "ナックラー") },
            // { PBESpecies.329, new PBELocalizedString("Vibrava", "ビブラーバ") },
            // { PBESpecies.330, new PBELocalizedString("Flygon", "フライゴン") },
            // { PBESpecies.331, new PBELocalizedString("Cacnea", "サボネア") },
            // { PBESpecies.332, new PBELocalizedString("Cacturne", "ノクタス") },
            // { PBESpecies.333, new PBELocalizedString("Swablu", "チルット") },
            // { PBESpecies.334, new PBELocalizedString("Altaria", "チルタリス") },
            // { PBESpecies.335, new PBELocalizedString("Zangoose", "ザングース") },
            // { PBESpecies.336, new PBELocalizedString("Seviper", "ハブネーク") },
            // { PBESpecies.337, new PBELocalizedString("Lunatone", "ルナトーン") },
            // { PBESpecies.338, new PBELocalizedString("Solrock", "ソルロック") },
            // { PBESpecies.339, new PBELocalizedString("Barboach", "ドジョッチ") },
            // { PBESpecies.340, new PBELocalizedString("Whiscash", "ナマズン") },
            // { PBESpecies.341, new PBELocalizedString("Corphish", "ヘイガニ") },
            // { PBESpecies.342, new PBELocalizedString("Crawdaunt", "シザリガー") },
            // { PBESpecies.343, new PBELocalizedString("Baltoy", "ヤジロン") },
            // { PBESpecies.344, new PBELocalizedString("Claydol", "ネンドール") },
            { PBESpecies.Lileep, new PBELocalizedString("Lileep", "リリーラ") },
            { PBESpecies.Cradily, new PBELocalizedString("Cradily", "ユレイドル") },
            // { PBESpecies.347, new PBELocalizedString("Anorith", "アノプス") },
            // { PBESpecies.348, new PBELocalizedString("Armaldo", "アーマルド") },
            // { PBESpecies.349, new PBELocalizedString("Feebas", "ヒンバス") },
            // { PBESpecies.350, new PBELocalizedString("Milotic", "ミロカロス") },
            // { PBESpecies.351, new PBELocalizedString("Castform", "ポワルン") },
            // { PBESpecies.352, new PBELocalizedString("Kecleon", "カクレオン") },
            // { PBESpecies.353, new PBELocalizedString("Shuppet", "カゲボウズ") },
            // { PBESpecies.354, new PBELocalizedString("Banette", "ジュペッタ") },
            // { PBESpecies.355, new PBELocalizedString("Duskull", "ヨマワル") },
            // { PBESpecies.356, new PBELocalizedString("Dusclops", "サマヨール") },
            { PBESpecies.Tropius, new PBELocalizedString("Tropius", "トロピウス") },
            // { PBESpecies.358, new PBELocalizedString("Chimecho", "チリーン") },
            { PBESpecies.Absol, new PBELocalizedString("Absol", "アブソル") },
            // { PBESpecies.360, new PBELocalizedString("Wynaut", "ソーナノ") },
            // { PBESpecies.361, new PBELocalizedString("Snorunt", "ユキワラシ") },
            // { PBESpecies.362, new PBELocalizedString("Glalie", "オニゴーリ") },
            // { PBESpecies.363, new PBELocalizedString("Spheal", "タマザラシ") },
            // { PBESpecies.364, new PBELocalizedString("Sealeo", "トドグラー") },
            // { PBESpecies.365, new PBELocalizedString("Walrein", "トドゼルガ") },
            { PBESpecies.Clamperl, new PBELocalizedString("Clamperl", "パールル") },
            // { PBESpecies.367, new PBELocalizedString("Huntail", "ハンテール") },
            // { PBESpecies.368, new PBELocalizedString("Gorebyss", "サクラビス") },
            // { PBESpecies.369, new PBELocalizedString("Relicanth", "ジーランス") },
            // { PBESpecies.370, new PBELocalizedString("Luvdisc", "ラブカス") },
            // { PBESpecies.371, new PBELocalizedString("Bagon", "タツベイ") },
            // { PBESpecies.372, new PBELocalizedString("Shelgon", "コモルー") },
            // { PBESpecies.373, new PBELocalizedString("Salamence", "ボーマンダ") },
            // { PBESpecies.374, new PBELocalizedString("Beldum", "ダンバル") },
            // { PBESpecies.375, new PBELocalizedString("Metang", "メタング") },
            // { PBESpecies.376, new PBELocalizedString("Metagross", "メタグロス") },
            { PBESpecies.Regirock, new PBELocalizedString("Regirock", "レジロック") },
            // { PBESpecies.378, new PBELocalizedString("Regice", "レジアイス") },
            // { PBESpecies.379, new PBELocalizedString("Registeel", "レジスチル") },
            { PBESpecies.Latias, new PBELocalizedString("Latias", "ラティアス") },
            { PBESpecies.Latios, new PBELocalizedString("Latios", "ラティオス") },
            // { PBESpecies.382, new PBELocalizedString("Kyogre", "カイオーガ") },
            // { PBESpecies.383, new PBELocalizedString("Groudon", "グラードン") },
            // { PBESpecies.384, new PBELocalizedString("Rayquaza", "レックウザ") },
            { PBESpecies.Jirachi, new PBELocalizedString("Jirachi", "ジラーチ") },
            // { PBESpecies.386, new PBELocalizedString("Deoxys", "デオキシス") },
            // { PBESpecies.387, new PBELocalizedString("Turtwig", "ナエトル") },
            // { PBESpecies.388, new PBELocalizedString("Grotle", "ハヤシガメ") },
            // { PBESpecies.389, new PBELocalizedString("Torterra", "ドダイトス") },
            // { PBESpecies.390, new PBELocalizedString("Chimchar", "ヒコザル") },
            // { PBESpecies.391, new PBELocalizedString("Monferno", "モウカザル") },
            // { PBESpecies.392, new PBELocalizedString("Infernape", "ゴウカザル") },
            // { PBESpecies.393, new PBELocalizedString("Piplup", "ポッチャマ") },
            // { PBESpecies.394, new PBELocalizedString("Prinplup", "ポッタイシ") },
            // { PBESpecies.395, new PBELocalizedString("Empoleon", "エンペルト") },
            // { PBESpecies.396, new PBELocalizedString("Starly", "ムックル") },
            // { PBESpecies.397, new PBELocalizedString("Staravia", "ムクバード") },
            // { PBESpecies.398, new PBELocalizedString("Staraptor", "ムクホーク") },
            // { PBESpecies.399, new PBELocalizedString("Bidoof", "ビッパ") },
            // { PBESpecies.400, new PBELocalizedString("Bibarel", "ビーダル") },
            // { PBESpecies.401, new PBELocalizedString("Kricketot", "コロボーシ") },
            // { PBESpecies.402, new PBELocalizedString("Kricketune", "コロトック") },
            { PBESpecies.Shinx, new PBELocalizedString("Shinx", "コリンク") },
            { PBESpecies.Luxio, new PBELocalizedString("Luxio", "ルクシオ") },
            { PBESpecies.Luxray, new PBELocalizedString("Luxray", "レントラー") },
            // { PBESpecies.406, new PBELocalizedString("Budew", "スボミー") },
            // { PBESpecies.407, new PBELocalizedString("Roserade", "ロズレイド") },
            // { PBESpecies.408, new PBELocalizedString("Cranidos", "ズガイドス") },
            // { PBESpecies.409, new PBELocalizedString("Rampardos", "ラムパルド") },
            // { PBESpecies.410, new PBELocalizedString("Shieldon", "タテトプス") },
            // { PBESpecies.411, new PBELocalizedString("Bastiodon", "トリデプス") },
            // { PBESpecies.412, new PBELocalizedString("Burmy", "ミノムッチ") },
            // { PBESpecies.413, new PBELocalizedString("Wormadam", "ミノマダム") },
            // { PBESpecies.414, new PBELocalizedString("Mothim", "ガーメイル") },
            // { PBESpecies.415, new PBELocalizedString("Combee", "ミツハニー") },
            // { PBESpecies.416, new PBELocalizedString("Vespiquen", "ビークイン") },
            { PBESpecies.Pachirisu, new PBELocalizedString("Pachirisu", "パチリス") },
            // { PBESpecies.418, new PBELocalizedString("Buizel", "ブイゼル") },
            // { PBESpecies.419, new PBELocalizedString("Floatzel", "フローゼル") },
            // { PBESpecies.420, new PBELocalizedString("Cherubi", "チェリンボ") },
            // { PBESpecies.421, new PBELocalizedString("Cherrim", "チェリム") },
            // { PBESpecies.422, new PBELocalizedString("Shellos", "カラナクシ") },
            // { PBESpecies.423, new PBELocalizedString("Gastrodon", "トリトドン") },
            // { PBESpecies.424, new PBELocalizedString("Ambipom", "エテボース") },
            // { PBESpecies.425, new PBELocalizedString("Drifloon", "フワンテ") },
            // { PBESpecies.426, new PBELocalizedString("Drifblim", "フワライド") },
            // { PBESpecies.427, new PBELocalizedString("Buneary", "ミミロル") },
            // { PBESpecies.428, new PBELocalizedString("Lopunny", "ミミロップ") },
            { PBESpecies.Mismagius, new PBELocalizedString("Mismagius", "ムウマージ") },
            // { PBESpecies.430, new PBELocalizedString("Honchkrow", "ドンカラス") },
            // { PBESpecies.431, new PBELocalizedString("Glameow", "ニャルマー") },
            // { PBESpecies.432, new PBELocalizedString("Purugly", "ブニャット") },
            // { PBESpecies.433, new PBELocalizedString("Chingling", "リーシャン") },
            // { PBESpecies.434, new PBELocalizedString("Stunky", "スカンプー") },
            // { PBESpecies.435, new PBELocalizedString("Skuntank", "スカタンク") },
            // { PBESpecies.436, new PBELocalizedString("Bronzor", "ドーミラー") },
            // { PBESpecies.437, new PBELocalizedString("Bronzong", "ドータクン") },
            // { PBESpecies.438, new PBELocalizedString("Bonsly", "ウソハチ") },
            // { PBESpecies.439, new PBELocalizedString("Mime Jr.", "マネネ") },
            { PBESpecies.Happiny, new PBELocalizedString("Happiny", "ピンプク") },
            // { PBESpecies.441, new PBELocalizedString("Chatot", "ペラップ") },
            // { PBESpecies.442, new PBELocalizedString("Spiritomb", "ミカルゲ") },
            { PBESpecies.Gible, new PBELocalizedString("Gible", "フカマル") },
            { PBESpecies.Gabite, new PBELocalizedString("Gabite", "ガバイト") },
            { PBESpecies.Garchomp, new PBELocalizedString("Garchomp", "ガブリアス") },
            // { PBESpecies.446, new PBELocalizedString("Munchlax", "ゴンベ") },
            { PBESpecies.Riolu, new PBELocalizedString("Riolu", "リオル") },
            { PBESpecies.Lucario, new PBELocalizedString("Lucario", "ルカリオ") },
            // { PBESpecies.449, new PBELocalizedString("Hippopotas", "ヒポポタス") },
            // { PBESpecies.450, new PBELocalizedString("Hippowdon", "カバルドン") },
            // { PBESpecies.451, new PBELocalizedString("Skorupi", "スコルピ") },
            // { PBESpecies.452, new PBELocalizedString("Drapion", "ドラピオン") },
            // { PBESpecies.453, new PBELocalizedString("Croagunk", "グレッグル") },
            // { PBESpecies.454, new PBELocalizedString("Toxicroak", "ドクロッグ") },
            // { PBESpecies.455, new PBELocalizedString("Carnivine", "マスキッパ") },
            // { PBESpecies.456, new PBELocalizedString("Finneon", "ケイコウオ") },
            // { PBESpecies.457, new PBELocalizedString("Lumineon", "ネオラント") },
            // { PBESpecies.458, new PBELocalizedString("Mantyke", "タマンタ") },
            // { PBESpecies.459, new PBELocalizedString("Snover", "ユキカブリ") },
            // { PBESpecies.460, new PBELocalizedString("Abomasnow", "ユキノオー") },
            // { PBESpecies.461, new PBELocalizedString("Weavile", "マニューラ") },
            // { PBESpecies.462, new PBELocalizedString("Magnezone", "ジバコイル") },
            // { PBESpecies.463, new PBELocalizedString("Lickilicky", "ベロベルト") },
            // { PBESpecies.464, new PBELocalizedString("Rhyperior", "ドサイドン") },
            // { PBESpecies.465, new PBELocalizedString("Tangrowth", "モジャンボ") },
            // { PBESpecies.466, new PBELocalizedString("Electivire", "エレキブル") },
            // { PBESpecies.467, new PBELocalizedString("Magmortar", "ブーバーン") },
            // { PBESpecies.468, new PBELocalizedString("Togekiss", "トゲキッス") },
            // { PBESpecies.469, new PBELocalizedString("Yanmega", "メガヤンマ") },
            { PBESpecies.Leafeon, new PBELocalizedString("Leafeon", "リーフィア") },
            { PBESpecies.Glaceon, new PBELocalizedString("Glaceon", "グレイシア") },
            // { PBESpecies.472, new PBELocalizedString("Gliscor", "グライオン") },
            // { PBESpecies.473, new PBELocalizedString("Mamoswine", "マンムー") },
            // { PBESpecies.474, new PBELocalizedString("Porygon-Z", "ポリゴンＺ") },
            // { PBESpecies.475, new PBELocalizedString("Gallade", "エルレイド") },
            // { PBESpecies.476, new PBELocalizedString("Probopass", "ダイノーズ") },
            // { PBESpecies.477, new PBELocalizedString("Dusknoir", "ヨノワール") },
            // { PBESpecies.478, new PBELocalizedString("Froslass", "ユキメノコ") },
            { PBESpecies.Rotom, new PBELocalizedString("Rotom", "ロトム") },
            { PBESpecies.Rotom_Fan, new PBELocalizedString("Rotom", "ロトム") },
            { PBESpecies.Rotom_Frost, new PBELocalizedString("Rotom", "ロトム") },
            { PBESpecies.Rotom_Heat, new PBELocalizedString("Rotom", "ロトム") },
            { PBESpecies.Rotom_Mow, new PBELocalizedString("Rotom", "ロトム") },
            { PBESpecies.Rotom_Wash, new PBELocalizedString("Rotom", "ロトム") },
            { PBESpecies.Uxie, new PBELocalizedString("Uxie", "ユクシー") },
            { PBESpecies.Mesprit, new PBELocalizedString("Mesprit", "エムリット") },
            { PBESpecies.Azelf, new PBELocalizedString("Azelf", "アグノム") },
            { PBESpecies.Dialga, new PBELocalizedString("Dialga", "ディアルガ") },
            { PBESpecies.Palkia, new PBELocalizedString("Palkia", "パルキア") },
            // { PBESpecies.485, new PBELocalizedString("Heatran", "ヒードラン") },
            // { PBESpecies.486, new PBELocalizedString("Regigigas", "レジギガス") },
            { PBESpecies.Giratina, new PBELocalizedString("Giratina", "ギラティナ") },
            { PBESpecies.Giratina_Origin, new PBELocalizedString("Giratina", "ギラティナ") },
            { PBESpecies.Cresselia, new PBELocalizedString("Cresselia", "クレセリア") },
            // { PBESpecies.489, new PBELocalizedString("Phione", "フィオネ") },
            // { PBESpecies.490, new PBELocalizedString("Manaphy", "マナフィ") },
            { PBESpecies.Darkrai, new PBELocalizedString("Darkrai", "ダークライ") },
            // { PBESpecies.492, new PBELocalizedString("Shaymin", "シェイミ") },
            { PBESpecies.Arceus, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Bug, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Dark, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Dragon, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Electric, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Fighting, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Fire, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Flying, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Ghost, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Grass, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Ground, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Ice, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Poison, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Psychic, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Rock, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Steel, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Arceus_Water, new PBELocalizedString("Arceus", "アルセウス") },
            { PBESpecies.Victini, new PBELocalizedString("Victini", "ビクティニ") },
            // { PBESpecies.495, new PBELocalizedString("Snivy", "ツタージャ") },
            // { PBESpecies.496, new PBELocalizedString("Servine", "ジャノビー") },
            // { PBESpecies.497, new PBELocalizedString("Serperior", "ジャローダ") },
            // { PBESpecies.498, new PBELocalizedString("Tepig", "ポカブ") },
            // { PBESpecies.499, new PBELocalizedString("Pignite", "チャオブー") },
            // { PBESpecies.500, new PBELocalizedString("Emboar", "エンブオー") },
            // { PBESpecies.501, new PBELocalizedString("Oshawott", "ミジュマル") },
            // { PBESpecies.502, new PBELocalizedString("Dewott", "フタチマル") },
            // { PBESpecies.503, new PBELocalizedString("Samurott", "ダイケンキ") },
            // { PBESpecies.504, new PBELocalizedString("Patrat", "ミネズミ") },
            // { PBESpecies.505, new PBELocalizedString("Watchog", "ミルホッグ") },
            // { PBESpecies.506, new PBELocalizedString("Lillipup", "ヨーテリー") },
            // { PBESpecies.507, new PBELocalizedString("Herdier", "ハーデリア") },
            // { PBESpecies.508, new PBELocalizedString("Stoutland", "ムーランド") },
            // { PBESpecies.509, new PBELocalizedString("Purrloin", "チョロネコ") },
            // { PBESpecies.510, new PBELocalizedString("Liepard", "レパルダス") },
            // { PBESpecies.511, new PBELocalizedString("Pansage", "ヤナップ") },
            // { PBESpecies.512, new PBELocalizedString("Simisage", "ヤナッキー") },
            // { PBESpecies.513, new PBELocalizedString("Pansear", "バオップ") },
            // { PBESpecies.514, new PBELocalizedString("Simisear", "バオッキー") },
            // { PBESpecies.515, new PBELocalizedString("Panpour", "ヒヤップ") },
            // { PBESpecies.516, new PBELocalizedString("Simipour", "ヒヤッキー") },
            // { PBESpecies.517, new PBELocalizedString("Munna", "ムンナ") },
            // { PBESpecies.518, new PBELocalizedString("Musharna", "ムシャーナ") },
            // { PBESpecies.519, new PBELocalizedString("Pidove", "マメパト") },
            // { PBESpecies.520, new PBELocalizedString("Tranquill", "ハトーボー") },
            // { PBESpecies.521, new PBELocalizedString("Unfezant", "ケンホロウ") },
            // { PBESpecies.522, new PBELocalizedString("Blitzle", "シママ") },
            // { PBESpecies.523, new PBELocalizedString("Zebstrika", "ゼブライカ") },
            // { PBESpecies.524, new PBELocalizedString("Roggenrola", "ダンゴロ") },
            // { PBESpecies.525, new PBELocalizedString("Boldore", "ガントル") },
            // { PBESpecies.526, new PBELocalizedString("Gigalith", "ギガイアス") },
            // { PBESpecies.527, new PBELocalizedString("Woobat", "コロモリ") },
            // { PBESpecies.528, new PBELocalizedString("Swoobat", "ココロモリ") },
            // { PBESpecies.529, new PBELocalizedString("Drilbur", "モグリュー") },
            // { PBESpecies.530, new PBELocalizedString("Excadrill", "ドリュウズ") },
            // { PBESpecies.531, new PBELocalizedString("Audino", "タブンネ") },
            // { PBESpecies.532, new PBELocalizedString("Timburr", "ドッコラー") },
            // { PBESpecies.533, new PBELocalizedString("Gurdurr", "ドテッコツ") },
            // { PBESpecies.534, new PBELocalizedString("Conkeldurr", "ローブシン") },
            // { PBESpecies.535, new PBELocalizedString("Tympole", "オタマロ") },
            // { PBESpecies.536, new PBELocalizedString("Palpitoad", "ガマガル") },
            // { PBESpecies.537, new PBELocalizedString("Seismitoad", "ガマゲロゲ") },
            // { PBESpecies.538, new PBELocalizedString("Throh", "ナゲキ") },
            // { PBESpecies.539, new PBELocalizedString("Sawk", "ダゲキ") },
            // { PBESpecies.540, new PBELocalizedString("Sewaddle", "クルミル") },
            // { PBESpecies.541, new PBELocalizedString("Swadloon", "クルマユ") },
            // { PBESpecies.542, new PBELocalizedString("Leavanny", "ハハコモリ") },
            // { PBESpecies.543, new PBELocalizedString("Venipede", "フシデ") },
            // { PBESpecies.544, new PBELocalizedString("Whirlipede", "ホイーガ") },
            // { PBESpecies.545, new PBELocalizedString("Scolipede", "ペンドラー") },
            // { PBESpecies.546, new PBELocalizedString("Cottonee", "モンメン") },
            // { PBESpecies.547, new PBELocalizedString("Whimsicott", "エルフーン") },
            // { PBESpecies.548, new PBELocalizedString("Petilil", "チュリネ") },
            // { PBESpecies.549, new PBELocalizedString("Lilligant", "ドレディア") },
            // { PBESpecies.550, new PBELocalizedString("Basculin", "バスラオ") },
            // { PBESpecies.551, new PBELocalizedString("Sandile", "メグロコ") },
            // { PBESpecies.552, new PBELocalizedString("Krokorok", "ワルビル") },
            // { PBESpecies.553, new PBELocalizedString("Krookodile", "ワルビアル") },
            // { PBESpecies.554, new PBELocalizedString("Darumaka", "ダルマッカ") },
            // { PBESpecies.555, new PBELocalizedString("Darmanitan", "ヒヒダルマ") },
            // { PBESpecies.556, new PBELocalizedString("Maractus", "マラカッチ") },
            // { PBESpecies.557, new PBELocalizedString("Dwebble", "イシズマイ") },
            // { PBESpecies.558, new PBELocalizedString("Crustle", "イワパレス") },
            // { PBESpecies.559, new PBELocalizedString("Scraggy", "ズルッグ") },
            // { PBESpecies.560, new PBELocalizedString("Scrafty", "ズルズキン") },
            // { PBESpecies.561, new PBELocalizedString("Sigilyph", "シンボラー") },
            // { PBESpecies.562, new PBELocalizedString("Yamask", "デスマス") },
            { PBESpecies.Cofagrigus, new PBELocalizedString("Cofagrigus", "デスカーン") },
            { PBESpecies.Tirtouga, new PBELocalizedString("Tirtouga", "プロトーガ") },
            { PBESpecies.Carracosta, new PBELocalizedString("Carracosta", "アバゴーラ") },
            // { PBESpecies.566, new PBELocalizedString("Archen", "アーケン") },
            // { PBESpecies.567, new PBELocalizedString("Archeops", "アーケオス") },
            // { PBESpecies.568, new PBELocalizedString("Trubbish", "ヤブクロン") },
            // { PBESpecies.569, new PBELocalizedString("Garbodor", "ダストダス") },
            // { PBESpecies.570, new PBELocalizedString("Zorua", "ゾロア") },
            // { PBESpecies.571, new PBELocalizedString("Zoroark", "ゾロアーク") },
            // { PBESpecies.572, new PBELocalizedString("Minccino", "チラーミィ") },
            // { PBESpecies.573, new PBELocalizedString("Cinccino", "チラチーノ") },
            { PBESpecies.Gothita, new PBELocalizedString("Gothita", "ゴチム") },
            { PBESpecies.Gothorita, new PBELocalizedString("Gothorita", "ゴチミル") },
            { PBESpecies.Gothitelle, new PBELocalizedString("Gothitelle", "ゴチルゼル") },
            // { PBESpecies.577, new PBELocalizedString("Solosis", "ユニラン") },
            // { PBESpecies.578, new PBELocalizedString("Duosion", "ダブラン") },
            // { PBESpecies.579, new PBELocalizedString("Reuniclus", "ランクルス") },
            // { PBESpecies.580, new PBELocalizedString("Ducklett", "コアルヒー") },
            // { PBESpecies.581, new PBELocalizedString("Swanna", "スワンナ") },
            // { PBESpecies.582, new PBELocalizedString("Vanillite", "バニプッチ") },
            // { PBESpecies.583, new PBELocalizedString("Vanillish", "バニリッチ") },
            // { PBESpecies.584, new PBELocalizedString("Vanilluxe", "バイバニラ") },
            // { PBESpecies.585, new PBELocalizedString("Deerling", "シキジカ") },
            // { PBESpecies.586, new PBELocalizedString("Sawsbuck", "メブキジカ") },
            { PBESpecies.Emolga, new PBELocalizedString("Emolga", "エモンガ") },
            // { PBESpecies.588, new PBELocalizedString("Karrablast", "カブルモ") },
            // { PBESpecies.589, new PBELocalizedString("Escavalier", "シュバルゴ") },
            // { PBESpecies.590, new PBELocalizedString("Foongus", "タマゲタケ") },
            // { PBESpecies.591, new PBELocalizedString("Amoonguss", "モロバレル") },
            // { PBESpecies.592, new PBELocalizedString("Frillish", "プルリル") },
            // { PBESpecies.593, new PBELocalizedString("Jellicent", "ブルンゲル") },
            { PBESpecies.Alomomola, new PBELocalizedString("Alomomola", "ママンボウ") },
            // { PBESpecies.595, new PBELocalizedString("Joltik", "バチュル") },
            // { PBESpecies.596, new PBELocalizedString("Galvantula", "デンチュラ") },
            // { PBESpecies.597, new PBELocalizedString("Ferroseed", "テッシード") },
            // { PBESpecies.598, new PBELocalizedString("Ferrothorn", "ナットレイ") },
            // { PBESpecies.599, new PBELocalizedString("Klink", "ギアル") },
            // { PBESpecies.600, new PBELocalizedString("Klang", "ギギアル") },
            // { PBESpecies.601, new PBELocalizedString("Klinklang", "ギギギアル") },
            // { PBESpecies.602, new PBELocalizedString("Tynamo", "シビシラス") },
            // { PBESpecies.603, new PBELocalizedString("Eelektrik", "シビビール") },
            // { PBESpecies.604, new PBELocalizedString("Eelektross", "シビルドン") },
            // { PBESpecies.605, new PBELocalizedString("Elgyem", "リグレー") },
            // { PBESpecies.606, new PBELocalizedString("Beheeyem", "オーベム") },
            { PBESpecies.Litwick, new PBELocalizedString("Litwick", "ヒトモシ") },
            { PBESpecies.Lampent, new PBELocalizedString("Lampent", "ランプラー") },
            { PBESpecies.Chandelure, new PBELocalizedString("Chandelure", "シャンデラ") },
            // { PBESpecies.610, new PBELocalizedString("Axew", "キバゴ") },
            // { PBESpecies.611, new PBELocalizedString("Fraxure", "オノンド") },
            // { PBESpecies.612, new PBELocalizedString("Haxorus", "オノノクス") },
            // { PBESpecies.613, new PBELocalizedString("Cubchoo", "クマシュン") },
            // { PBESpecies.614, new PBELocalizedString("Beartic", "ツンベアー") },
            { PBESpecies.Cryogonal, new PBELocalizedString("Cryogonal", "フリージオ") },
            // { PBESpecies.616, new PBELocalizedString("Shelmet", "チョボマキ") },
            // { PBESpecies.617, new PBELocalizedString("Accelgor", "アギルダー") },
            // { PBESpecies.618, new PBELocalizedString("Stunfisk", "マッギョ") },
            // { PBESpecies.619, new PBELocalizedString("Mienfoo", "コジョフー") },
            // { PBESpecies.620, new PBELocalizedString("Mienshao", "コジョンド") },
            { PBESpecies.Druddigon, new PBELocalizedString("Druddigon", "クリムガン") },
            // { PBESpecies.622, new PBELocalizedString("Golett", "ゴビット") },
            // { PBESpecies.623, new PBELocalizedString("Golurk", "ゴルーグ") },
            // { PBESpecies.624, new PBELocalizedString("Pawniard", "コマタナ") },
            // { PBESpecies.625, new PBELocalizedString("Bisharp", "キリキザン") },
            { PBESpecies.Bouffalant, new PBELocalizedString("Bouffalant", "バッフロン") },
            // { PBESpecies.627, new PBELocalizedString("Rufflet", "ワシボン") },
            // { PBESpecies.628, new PBELocalizedString("Braviary", "ウォーグル") },
            // { PBESpecies.629, new PBELocalizedString("Vullaby", "バルチャイ") },
            // { PBESpecies.630, new PBELocalizedString("Mandibuzz", "バルジーナ") },
            // { PBESpecies.631, new PBELocalizedString("Heatmor", "クイタラン") },
            // { PBESpecies.632, new PBELocalizedString("Durant", "アイアント") },
            { PBESpecies.Deino, new PBELocalizedString("Deino", "モノズ") },
            { PBESpecies.Zweilous, new PBELocalizedString("Zweilous", "ジヘッド") },
            { PBESpecies.Hydreigon, new PBELocalizedString("Hydreigon", "サザンドラ") },
            { PBESpecies.Larvesta, new PBELocalizedString("Larvesta", "メラルバ") },
            { PBESpecies.Volcarona, new PBELocalizedString("Volcarona", "ウルガモス") },
            // { PBESpecies.638, new PBELocalizedString("Cobalion", "コバルオン") },
            // { PBESpecies.639, new PBELocalizedString("Terrakion", "テラキオン") },
            // { PBESpecies.640, new PBELocalizedString("Virizion", "ビリジオン") },
            // { PBESpecies.641, new PBELocalizedString("Tornadus", "トルネロス") },
            // { PBESpecies.642, new PBELocalizedString("Thundurus", "ボルトロス") },
            // { PBESpecies.643, new PBELocalizedString("Reshiram", "レシラム") },
            // { PBESpecies.644, new PBELocalizedString("Zekrom", "ゼクロム") },
            // { PBESpecies.645, new PBELocalizedString("Landorus", "ランドロス") },
            // { PBESpecies.646, new PBELocalizedString("Kyurem", "キュレム") },
            // { PBESpecies.647, new PBELocalizedString("Keldeo", "ケルディオ") },
            // { PBESpecies.648, new PBELocalizedString("Meloetta", "メロエッタ") },
            { PBESpecies.Genesect, new PBELocalizedString("Genesect", "ゲノセクト") },
            { PBESpecies.Genesect_Burn, new PBELocalizedString("Genesect", "ゲノセクト") },
            { PBESpecies.Genesect_Chill, new PBELocalizedString("Genesect", "ゲノセクト") },
            { PBESpecies.Genesect_Douse, new PBELocalizedString("Genesect", "ゲノセクト") },
            { PBESpecies.Genesect_Shock, new PBELocalizedString("Genesect", "ゲノセクト") }
        });
    }
}
