using Kermalis.PokemonBattleEngine.Data;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Kermalis.PokemonBattleEngine.Localization
{
    public static class PBEPokemonLocalization
    {
        public static ReadOnlyDictionary<PBESpecies, PBELocalizedString> Names { get; } = new ReadOnlyDictionary<PBESpecies, PBELocalizedString>(new Dictionary<PBESpecies, PBELocalizedString>()
        {
            { PBESpecies.Bulbasaur, new PBELocalizedString("フシギダネ", "이상해씨", "Bulbizarre", "Bisasam", "Bulbasaur", "Bulbasaur", "Bulbasaur") },
            { PBESpecies.Ivysaur, new PBELocalizedString("フシギソウ", "이상해풀", "Herbizarre", "Bisaknosp", "Ivysaur", "Ivysaur", "Ivysaur") },
            { PBESpecies.Venusaur, new PBELocalizedString("フシギバナ", "이상해꽃", "Florizarre", "Bisaflor", "Venusaur", "Venusaur", "Venusaur") },
            { PBESpecies.Charmander, new PBELocalizedString("ヒトカゲ", "파이리", "Salamèche", "Glumanda", "Charmander", "Charmander", "Charmander") },
            { PBESpecies.Charmeleon, new PBELocalizedString("リザード", "리자드", "Reptincel", "Glutexo", "Charmeleon", "Charmeleon", "Charmeleon") },
            { PBESpecies.Charizard, new PBELocalizedString("リザードン", "리자몽", "Dracaufeu", "Glurak", "Charizard", "Charizard", "Charizard") },
            { PBESpecies.Squirtle, new PBELocalizedString("ゼニガメ", "꼬부기", "Carapuce", "Schiggy", "Squirtle", "Squirtle", "Squirtle") },
            { PBESpecies.Wartortle, new PBELocalizedString("カメール", "어니부기", "Carabaffe", "Schillok", "Wartortle", "Wartortle", "Wartortle") },
            { PBESpecies.Blastoise, new PBELocalizedString("カメックス", "거북왕", "Tortank", "Turtok", "Blastoise", "Blastoise", "Blastoise") },
            { PBESpecies.Caterpie, new PBELocalizedString("キャタピー", "캐터피", "Chenipan", "Raupy", "Caterpie", "Caterpie", "Caterpie") },
            { PBESpecies.Metapod, new PBELocalizedString("トランセル", "단데기", "Chrysacier", "Safcon", "Metapod", "Metapod", "Metapod") },
            { PBESpecies.Butterfree, new PBELocalizedString("バタフリー", "버터플", "Papilusion", "Smettbo", "Butterfree", "Butterfree", "Butterfree") },
            { PBESpecies.Weedle, new PBELocalizedString("ビードル", "뿔충이", "Aspicot", "Hornliu", "Weedle", "Weedle", "Weedle") },
            { PBESpecies.Kakuna, new PBELocalizedString("コクーン", "딱충이", "Coconfort", "Kokuna", "Kakuna", "Kakuna", "Kakuna") },
            { PBESpecies.Beedrill, new PBELocalizedString("スピアー", "독침붕", "Dardargnan", "Bibor", "Beedrill", "Beedrill", "Beedrill") },
            // { PBESpecies.16, new PBELocalizedString("ポッポ", "구구", "Roucool", "Taubsi", "Pidgey", "Pidgey", "Pidgey") },
            // { PBESpecies.17, new PBELocalizedString("ピジョン", "피죤", "Roucoups", "Tauboga", "Pidgeotto", "Pidgeotto", "Pidgeotto") },
            // { PBESpecies.18, new PBELocalizedString("ピジョット", "피죤투", "Roucarnage", "Tauboss", "Pidgeot", "Pidgeot", "Pidgeot") },
            // { PBESpecies.19, new PBELocalizedString("コラッタ", "꼬렛", "Rattata", "Rattfratz", "Rattata", "Rattata", "Rattata") },
            // { PBESpecies.20, new PBELocalizedString("ラッタ", "레트라", "Rattatac", "Rattikarl", "Raticate", "Raticate", "Raticate") },
            // { PBESpecies.21, new PBELocalizedString("オニスズメ", "깨비참", "Piafabec", "Habitak", "Spearow", "Spearow", "Spearow") },
            // { PBESpecies.22, new PBELocalizedString("オニドリル", "깨비드릴조", "Rapasdepic", "Ibitak", "Fearow", "Fearow", "Fearow") },
            // { PBESpecies.23, new PBELocalizedString("アーボ", "아보", "Abo", "Rettan", "Ekans", "Ekans", "Ekans") },
            // { PBESpecies.24, new PBELocalizedString("アーボック", "아보크", "Arbok", "Arbok", "Arbok", "Arbok", "Arbok") },
            { PBESpecies.Pikachu, new PBELocalizedString("ピカチュウ", "피카츄", "Pikachu", "Pikachu", "Pikachu", "Pikachu", "Pikachu") },
            { PBESpecies.Raichu, new PBELocalizedString("ライチュウ", "라이츄", "Raichu", "Raichu", "Raichu", "Raichu", "Raichu") },
            // { PBESpecies.27, new PBELocalizedString("サンド", "모래두지", "Sabelette", "Sandan", "Sandshrew", "Sandshrew", "Sandshrew") },
            // { PBESpecies.28, new PBELocalizedString("サンドパン", "고지", "Sablaireau", "Sandamer", "Sandslash", "Sandslash", "Sandslash") },
            // { PBESpecies.29, new PBELocalizedString("ニドラン♀", "니드런♀", "Nidoran♀", "Nidoran♀", "Nidoran♀", "Nidoran♀", "Nidoran♀") },
            // { PBESpecies.30, new PBELocalizedString("ニドリーナ", "니드리나", "Nidorina", "Nidorina", "Nidorina", "Nidorina", "Nidorina") },
            // { PBESpecies.31, new PBELocalizedString("ニドクイン", "니드퀸", "Nidoqueen", "Nidoqueen", "Nidoqueen", "Nidoqueen", "Nidoqueen") },
            // { PBESpecies.32, new PBELocalizedString("ニドラン♂", "니드런♂", "Nidoran♂", "Nidoran♂", "Nidoran♂", "Nidoran♂", "Nidoran♂") },
            // { PBESpecies.33, new PBELocalizedString("ニドリーノ", "니드리노", "Nidorino", "Nidorino", "Nidorino", "Nidorino", "Nidorino") },
            // { PBESpecies.34, new PBELocalizedString("ニドキング", "니드킹", "Nidoking", "Nidoking", "Nidoking", "Nidoking", "Nidoking") },
            // { PBESpecies.35, new PBELocalizedString("ピッピ", "삐삐", "Mélofée", "Piepi", "Clefairy", "Clefairy", "Clefairy") },
            // { PBESpecies.36, new PBELocalizedString("ピクシー", "픽시", "Mélodelfe", "Pixi", "Clefable", "Clefable", "Clefable") },
            { PBESpecies.Vulpix, new PBELocalizedString("ロコン", "식스테일", "Goupix", "Vulpix", "Vulpix", "Vulpix", "Vulpix") },
            { PBESpecies.Ninetales, new PBELocalizedString("キュウコン", "나인테일", "Feunard", "Vulnona", "Ninetales", "Ninetales", "Ninetales") },
            // { PBESpecies.39, new PBELocalizedString("プリン", "푸린", "Rondoudou", "Pummeluff", "Jigglypuff", "Jigglypuff", "Jigglypuff") },
            // { PBESpecies.40, new PBELocalizedString("プクリン", "푸크린", "Grodoudou", "Knuddeluff", "Wigglytuff", "Wigglytuff", "Wigglytuff") },
            { PBESpecies.Zubat, new PBELocalizedString("ズバット", "주뱃", "Nosferapti", "Zubat", "Zubat", "Zubat", "Zubat") },
            { PBESpecies.Golbat, new PBELocalizedString("ゴルバット", "골뱃", "Nosferalto", "Golbat", "Golbat", "Golbat", "Golbat") },
            // { PBESpecies.43, new PBELocalizedString("ナゾノクサ", "뚜벅쵸", "Mystherbe", "Myrapla", "Oddish", "Oddish", "Oddish") },
            // { PBESpecies.44, new PBELocalizedString("クサイハナ", "냄새꼬", "Ortide", "Duflor", "Gloom", "Gloom", "Gloom") },
            // { PBESpecies.45, new PBELocalizedString("ラフレシア", "라플레시아", "Rafflesia", "Giflor", "Vileplume", "Vileplume", "Vileplume") },
            // { PBESpecies.46, new PBELocalizedString("パラス", "파라스", "Paras", "Paras", "Paras", "Paras", "Paras") },
            // { PBESpecies.47, new PBELocalizedString("パラセクト", "파라섹트", "Parasect", "Parasek", "Parasect", "Parasect", "Parasect") },
            // { PBESpecies.48, new PBELocalizedString("コンパン", "콘팡", "Mimitoss", "Bluzuk", "Venonat", "Venonat", "Venonat") },
            // { PBESpecies.49, new PBELocalizedString("モルフォン", "도나리", "Aéromite", "Omot", "Venomoth", "Venomoth", "Venomoth") },
            // { PBESpecies.50, new PBELocalizedString("ディグダ", "디그다", "Taupiqueur", "Digda", "Diglett", "Diglett", "Diglett") },
            // { PBESpecies.51, new PBELocalizedString("ダグトリオ", "닥트리오", "Triopikeur", "Digdri", "Dugtrio", "Dugtrio", "Dugtrio") },
            // { PBESpecies.52, new PBELocalizedString("ニャース", "나옹", "Miaouss", "Mauzi", "Meowth", "Meowth", "Meowth") },
            // { PBESpecies.53, new PBELocalizedString("ペルシアン", "페르시온", "Persian", "Snobilikat", "Persian", "Persian", "Persian") },
            { PBESpecies.Psyduck, new PBELocalizedString("コダック", "고라파덕", "Psykokwak", "Enton", "Psyduck", "Psyduck", "Psyduck") },
            { PBESpecies.Golduck, new PBELocalizedString("ゴルダック", "골덕", "Akwakwak", "Entoron", "Golduck", "Golduck", "Golduck") },
            // { PBESpecies.56, new PBELocalizedString("マンキー", "망키", "Férosinge", "Menki", "Mankey", "Mankey", "Mankey") },
            // { PBESpecies.57, new PBELocalizedString("オコリザル", "성원숭", "Colossinge", "Rasaff", "Primeape", "Primeape", "Primeape") },
            // { PBESpecies.58, new PBELocalizedString("ガーディ", "가디", "Caninos", "Fukano", "Growlithe", "Growlithe", "Growlithe") },
            // { PBESpecies.59, new PBELocalizedString("ウインディ", "윈디", "Arcanin", "Arkani", "Arcanine", "Arcanine", "Arcanine") },
            { PBESpecies.Poliwag, new PBELocalizedString("ニョロモ", "발챙이", "Ptitard", "Quapsel", "Poliwag", "Poliwag", "Poliwag") },
            { PBESpecies.Poliwhirl, new PBELocalizedString("ニョロゾ", "슈륙챙이", "Têtarte", "Quaputzi", "Poliwhirl", "Poliwhirl", "Poliwhirl") },
            { PBESpecies.Poliwrath, new PBELocalizedString("ニョロボン", "강챙이", "Tartard", "Quappo", "Poliwrath", "Poliwrath", "Poliwrath") },
            // { PBESpecies.63, new PBELocalizedString("ケーシィ", "캐이시", "Abra", "Abra", "Abra", "Abra", "Abra") },
            // { PBESpecies.64, new PBELocalizedString("ユンゲラー", "윤겔라", "Kadabra", "Kadabra", "Kadabra", "Kadabra", "Kadabra") },
            // { PBESpecies.65, new PBELocalizedString("フーディン", "후딘", "Alakazam", "Simsala", "Alakazam", "Alakazam", "Alakazam") },
            // { PBESpecies.66, new PBELocalizedString("ワンリキー", "알통몬", "Machoc", "Machollo", "Machop", "Machop", "Machop") },
            // { PBESpecies.67, new PBELocalizedString("ゴーリキー", "근육몬", "Machopeur", "Maschock", "Machoke", "Machoke", "Machoke") },
            // { PBESpecies.68, new PBELocalizedString("カイリキー", "괴력몬", "Mackogneur", "Machomei", "Machamp", "Machamp", "Machamp") },
            // { PBESpecies.69, new PBELocalizedString("マダツボミ", "모다피", "Chétiflor", "Knofensa", "Bellsprout", "Bellsprout", "Bellsprout") },
            // { PBESpecies.70, new PBELocalizedString("ウツドン", "우츠동", "Boustiflor", "Ultrigaria", "Weepinbell", "Weepinbell", "Weepinbell") },
            // { PBESpecies.71, new PBELocalizedString("ウツボット", "우츠보트", "Empiflor", "Sarzenia", "Victreebel", "Victreebel", "Victreebel") },
            // { PBESpecies.72, new PBELocalizedString("メノクラゲ", "왕눈해", "Tentacool", "Tentacha", "Tentacool", "Tentacool", "Tentacool") },
            // { PBESpecies.73, new PBELocalizedString("ドククラゲ", "독파리", "Tentacruel", "Tentoxa", "Tentacruel", "Tentacruel", "Tentacruel") },
            // { PBESpecies.74, new PBELocalizedString("イシツブテ", "꼬마돌", "Racaillou", "Kleinstein", "Geodude", "Geodude", "Geodude") },
            // { PBESpecies.75, new PBELocalizedString("ゴローン", "데구리", "Gravalanch", "Georok", "Graveler", "Graveler", "Graveler") },
            // { PBESpecies.76, new PBELocalizedString("ゴローニャ", "딱구리", "Grolem", "Geowaz", "Golem", "Golem", "Golem") },
            // { PBESpecies.77, new PBELocalizedString("ポニータ", "포니타", "Ponyta", "Ponita", "Ponyta", "Ponyta", "Ponyta") },
            // { PBESpecies.78, new PBELocalizedString("ギャロップ", "날쌩마", "Galopa", "Gallopa", "Rapidash", "Rapidash", "Rapidash") },
            // { PBESpecies.79, new PBELocalizedString("ヤドン", "야돈", "Ramoloss", "Flegmon", "Slowpoke", "Slowpoke", "Slowpoke") },
            // { PBESpecies.80, new PBELocalizedString("ヤドラン", "야도란", "Flagadoss", "Lahmus", "Slowbro", "Slowbro", "Slowbro") },
            // { PBESpecies.81, new PBELocalizedString("コイル", "코일", "Magnéti", "Magnetilo", "Magnemite", "Magnemite", "Magnemite") },
            // { PBESpecies.82, new PBELocalizedString("レアコイル", "레어코일", "Magnéton", "Magneton", "Magneton", "Magneton", "Magneton") },
            { PBESpecies.Farfetchd, new PBELocalizedString("カモネギ", "파오리", "Canarticho", "Porenta", "Farfetch’d", "Farfetch’d", "Farfetch’d") },
            // { PBESpecies.84, new PBELocalizedString("ドードー", "두두", "Doduo", "Dodu", "Doduo", "Doduo", "Doduo") },
            // { PBESpecies.85, new PBELocalizedString("ドードリオ", "두트리오", "Dodrio", "Dodri", "Dodrio", "Dodrio", "Dodrio") },
            // { PBESpecies.86, new PBELocalizedString("パウワウ", "쥬쥬", "Otaria", "Jurob", "Seel", "Seel", "Seel") },
            // { PBESpecies.87, new PBELocalizedString("ジュゴン", "쥬레곤", "Lamantine", "Jugong", "Dewgong", "Dewgong", "Dewgong") },
            // { PBESpecies.88, new PBELocalizedString("ベトベター", "질퍽이", "Tadmorv", "Sleima", "Grimer", "Grimer", "Grimer") },
            // { PBESpecies.89, new PBELocalizedString("ベトベトン", "질뻐기", "Grotadmorv", "Sleimok", "Muk", "Muk", "Muk") },
            // { PBESpecies.90, new PBELocalizedString("シェルダー", "셀러", "Kokiyas", "Muschas", "Shellder", "Shellder", "Shellder") },
            // { PBESpecies.91, new PBELocalizedString("パルシェン", "파르셀", "Crustabri", "Austos", "Cloyster", "Cloyster", "Cloyster") },
            // { PBESpecies.92, new PBELocalizedString("ゴース", "고오스", "Fantominus", "Nebulak", "Gastly", "Gastly", "Gastly") },
            // { PBESpecies.93, new PBELocalizedString("ゴースト", "고우스트", "Spectrum", "Alpollo", "Haunter", "Haunter", "Haunter") },
            // { PBESpecies.94, new PBELocalizedString("ゲンガー", "팬텀", "Ectoplasma", "Gengar", "Gengar", "Gengar", "Gengar") },
            // { PBESpecies.95, new PBELocalizedString("イワーク", "롱스톤", "Onix", "Onix", "Onix", "Onix", "Onix") },
            // { PBESpecies.96, new PBELocalizedString("スリープ", "슬리프", "Soporifik", "Traumato", "Drowzee", "Drowzee", "Drowzee") },
            // { PBESpecies.97, new PBELocalizedString("スリーパー", "슬리퍼", "Hypnomade", "Hypno", "Hypno", "Hypno", "Hypno") },
            // { PBESpecies.98, new PBELocalizedString("クラブ", "크랩", "Krabby", "Krabby", "Krabby", "Krabby", "Krabby") },
            // { PBESpecies.99, new PBELocalizedString("キングラー", "킹크랩", "Krabboss", "Kingler", "Kingler", "Kingler", "Kingler") },
            // { PBESpecies.100, new PBELocalizedString("ビリリダマ", "찌리리공", "Voltorbe", "Voltobal", "Voltorb", "Voltorb", "Voltorb") },
            // { PBESpecies.101, new PBELocalizedString("マルマイン", "붐볼", "Électrode", "Lektrobal", "Electrode", "Electrode", "Electrode") },
            // { PBESpecies.102, new PBELocalizedString("タマタマ", "아라리", "Noeunoeuf", "Owei", "Exeggcute", "Exeggcute", "Exeggcute") },
            // { PBESpecies.103, new PBELocalizedString("ナッシー", "나시", "Noadkoko", "Kokowei", "Exeggutor", "Exeggutor", "Exeggutor") },
            { PBESpecies.Cubone, new PBELocalizedString("カラカラ", "탕구리", "Osselait", "Tragosso", "Cubone", "Cubone", "Cubone") },
            { PBESpecies.Marowak, new PBELocalizedString("ガラガラ", "텅구리", "Ossatueur", "Knogga", "Marowak", "Marowak", "Marowak") },
            // { PBESpecies.106, new PBELocalizedString("サワムラー", "시라소몬", "Kicklee", "Kicklee", "Hitmonlee", "Hitmonlee", "Hitmonlee") },
            // { PBESpecies.107, new PBELocalizedString("エビワラー", "홍수몬", "Tygnon", "Nockchan", "Hitmonchan", "Hitmonchan", "Hitmonchan") },
            // { PBESpecies.108, new PBELocalizedString("ベロリンガ", "내루미", "Excelangue", "Schlurp", "Lickitung", "Lickitung", "Lickitung") },
            // { PBESpecies.109, new PBELocalizedString("ドガース", "또가스", "Smogo", "Smogon", "Koffing", "Koffing", "Koffing") },
            // { PBESpecies.110, new PBELocalizedString("マタドガス", "또도가스", "Smogogo", "Smogmog", "Weezing", "Weezing", "Weezing") },
            // { PBESpecies.111, new PBELocalizedString("サイホーン", "뿔카노", "Rhinocorne", "Rihorn", "Rhyhorn", "Rhyhorn", "Rhyhorn") },
            // { PBESpecies.112, new PBELocalizedString("サイドン", "코뿌리", "Rhinoféros", "Rizeros", "Rhydon", "Rhydon", "Rhydon") },
            { PBESpecies.Chansey, new PBELocalizedString("ラッキー", "럭키", "Leveinard", "Chaneira", "Chansey", "Chansey", "Chansey") },
            // { PBESpecies.114, new PBELocalizedString("モンジャラ", "덩쿠리", "Saquedeneu", "Tangela", "Tangela", "Tangela", "Tangela") },
            // { PBESpecies.115, new PBELocalizedString("ガルーラ", "캥카", "Kangourex", "Kangama", "Kangaskhan", "Kangaskhan", "Kangaskhan") },
            // { PBESpecies.116, new PBELocalizedString("タッツー", "쏘드라", "Hypotrempe", "Seeper", "Horsea", "Horsea", "Horsea") },
            // { PBESpecies.117, new PBELocalizedString("シードラ", "시드라", "Hypocéan", "Seemon", "Seadra", "Seadra", "Seadra") },
            // { PBESpecies.118, new PBELocalizedString("トサキント", "콘치", "Poissirène", "Goldini", "Goldeen", "Goldeen", "Goldeen") },
            // { PBESpecies.119, new PBELocalizedString("アズマオウ", "왕콘치", "Poissoroy", "Golking", "Seaking", "Seaking", "Seaking") },
            // { PBESpecies.120, new PBELocalizedString("ヒトデマン", "별가사리", "Stari", "Sterndu", "Staryu", "Staryu", "Staryu") },
            // { PBESpecies.121, new PBELocalizedString("スターミー", "아쿠스타", "Staross", "Starmie", "Starmie", "Starmie", "Starmie") },
            // { PBESpecies.122, new PBELocalizedString("バリヤード", "마임맨", "M. Mime", "Pantimos", "Mr. Mime", "Mr. Mime", "Mr. Mime") },
            // { PBESpecies.123, new PBELocalizedString("ストライク", "스라크", "Insécateur", "Sichlor", "Scyther", "Scyther", "Scyther") },
            // { PBESpecies.124, new PBELocalizedString("ルージュラ", "루주라", "Lippoutou", "Rossana", "Jynx", "Jynx", "Jynx") },
            // { PBESpecies.125, new PBELocalizedString("エレブー", "에레브", "Élektek", "Elektek", "Electabuzz", "Electabuzz", "Electabuzz") },
            // { PBESpecies.126, new PBELocalizedString("ブーバー", "마그마", "Magmar", "Magmar", "Magmar", "Magmar", "Magmar") },
            // { PBESpecies.127, new PBELocalizedString("カイロス", "쁘사이저", "Scarabrute", "Pinsir", "Pinsir", "Pinsir", "Pinsir") },
            // { PBESpecies.128, new PBELocalizedString("ケンタロス", "켄타로스", "Tauros", "Tauros", "Tauros", "Tauros", "Tauros") },
            { PBESpecies.Magikarp, new PBELocalizedString("コイキング", "잉어킹", "Magicarpe", "Karpador", "Magikarp", "Magikarp", "Magikarp") },
            { PBESpecies.Gyarados, new PBELocalizedString("ギャラドス", "갸라도스", "Léviator", "Garados", "Gyarados", "Gyarados", "Gyarados") },
            // { PBESpecies.131, new PBELocalizedString("ラプラス", "라프라스", "Lokhlass", "Lapras", "Lapras", "Lapras", "Lapras") },
            { PBESpecies.Ditto, new PBELocalizedString("メタモン", "메타몽", "Métamorph", "Ditto", "Ditto", "Ditto", "Ditto") },
            { PBESpecies.Eevee, new PBELocalizedString("イーブイ", "이브이", "Évoli", "Evoli", "Eevee", "Eevee", "Eevee") },
            { PBESpecies.Vaporeon, new PBELocalizedString("シャワーズ", "샤미드", "Aquali", "Aquana", "Vaporeon", "Vaporeon", "Vaporeon") },
            { PBESpecies.Jolteon, new PBELocalizedString("サンダース", "쥬피썬더", "Voltali", "Blitza", "Jolteon", "Jolteon", "Jolteon") },
            { PBESpecies.Flareon, new PBELocalizedString("ブースター", "부스터", "Pyroli", "Flamara", "Flareon", "Flareon", "Flareon") },
            // { PBESpecies.137, new PBELocalizedString("ポリゴン", "폴리곤", "Porygon", "Porygon", "Porygon", "Porygon", "Porygon") },
            // { PBESpecies.138, new PBELocalizedString("オムナイト", "암나이트", "Amonita", "Amonitas", "Omanyte", "Omanyte", "Omanyte") },
            // { PBESpecies.139, new PBELocalizedString("オムスター", "암스타", "Amonistar", "Amoroso", "Omastar", "Omastar", "Omastar") },
            // { PBESpecies.140, new PBELocalizedString("カブト", "투구", "Kabuto", "Kabuto", "Kabuto", "Kabuto", "Kabuto") },
            // { PBESpecies.141, new PBELocalizedString("カブトプス", "투구푸스", "Kabutops", "Kabutops", "Kabutops", "Kabutops", "Kabutops") },
            // { PBESpecies.142, new PBELocalizedString("プテラ", "프테라", "Ptéra", "Aerodactyl", "Aerodactyl", "Aerodactyl", "Aerodactyl") },
            // { PBESpecies.143, new PBELocalizedString("カビゴン", "잠만보", "Ronflex", "Relaxo", "Snorlax", "Snorlax", "Snorlax") },
            // { PBESpecies.144, new PBELocalizedString("フリーザー", "프리져", "Artikodin", "Arktos", "Articuno", "Articuno", "Articuno") },
            // { PBESpecies.145, new PBELocalizedString("サンダー", "썬더", "Électhor", "Zapdos", "Zapdos", "Zapdos", "Zapdos") },
            // { PBESpecies.146, new PBELocalizedString("ファイヤー", "파이어", "Sulfura", "Lavados", "Moltres", "Moltres", "Moltres") },
            // { PBESpecies.147, new PBELocalizedString("ミニリュウ", "미뇽", "Minidraco", "Dratini", "Dratini", "Dratini", "Dratini") },
            // { PBESpecies.148, new PBELocalizedString("ハクリュー", "신뇽", "Draco", "Dragonir", "Dragonair", "Dragonair", "Dragonair") },
            // { PBESpecies.149, new PBELocalizedString("カイリュー", "망나뇽", "Dracolosse", "Dragoran", "Dragonite", "Dragonite", "Dragonite") },
            // { PBESpecies.150, new PBELocalizedString("ミュウツー", "뮤츠", "Mewtwo", "Mewtu", "Mewtwo", "Mewtwo", "Mewtwo") },
            // { PBESpecies.151, new PBELocalizedString("ミュウ", "뮤", "Mew", "Mew", "Mew", "Mew", "Mew") },
            // { PBESpecies.152, new PBELocalizedString("チコリータ", "치코리타", "Germignon", "Endivie", "Chikorita", "Chikorita", "Chikorita") },
            // { PBESpecies.153, new PBELocalizedString("ベイリーフ", "베이리프", "Macronium", "Lorblatt", "Bayleef", "Bayleef", "Bayleef") },
            // { PBESpecies.154, new PBELocalizedString("メガニウム", "메가니움", "Méganium", "Meganie", "Meganium", "Meganium", "Meganium") },
            // { PBESpecies.155, new PBELocalizedString("ヒノアラシ", "브케인", "Héricendre", "Feurigel", "Cyndaquil", "Cyndaquil", "Cyndaquil") },
            // { PBESpecies.156, new PBELocalizedString("マグマラシ", "마그케인", "Feurisson", "Igelavar", "Quilava", "Quilava", "Quilava") },
            // { PBESpecies.157, new PBELocalizedString("バクフーン", "블레이범", "Typhlosion", "Tornupto", "Typhlosion", "Typhlosion", "Typhlosion") },
            // { PBESpecies.158, new PBELocalizedString("ワニノコ", "리아코", "Kaiminus", "Karnimani", "Totodile", "Totodile", "Totodile") },
            // { PBESpecies.159, new PBELocalizedString("アリゲイツ", "엘리게이", "Crocrodil", "Tyracroc", "Croconaw", "Croconaw", "Croconaw") },
            // { PBESpecies.160, new PBELocalizedString("オーダイル", "장크로다일", "Aligatueur", "Impergator", "Feraligatr", "Feraligatr", "Feraligatr") },
            // { PBESpecies.161, new PBELocalizedString("オタチ", "꼬리선", "Fouinette", "Wiesor", "Sentret", "Sentret", "Sentret") },
            // { PBESpecies.162, new PBELocalizedString("オオタチ", "다꼬리", "Fouinar", "Wiesenior", "Furret", "Furret", "Furret") },
            // { PBESpecies.163, new PBELocalizedString("ホーホー", "부우부", "Hoothoot", "Hoothoot", "Hoothoot", "Hoothoot", "Hoothoot") },
            // { PBESpecies.164, new PBELocalizedString("ヨルノズク", "야부엉", "Noarfang", "Noctuh", "Noctowl", "Noctowl", "Noctowl") },
            // { PBESpecies.165, new PBELocalizedString("レディバ", "레디바", "Coxy", "Ledyba", "Ledyba", "Ledyba", "Ledyba") },
            // { PBESpecies.166, new PBELocalizedString("レディアン", "레디안", "Coxyclaque", "Ledian", "Ledian", "Ledian", "Ledian") },
            // { PBESpecies.167, new PBELocalizedString("イトマル", "페이검", "Mimigal", "Webarak", "Spinarak", "Spinarak", "Spinarak") },
            // { PBESpecies.168, new PBELocalizedString("アリアドス", "아리아도스", "Migalos", "Ariados", "Ariados", "Ariados", "Ariados") },
            { PBESpecies.Crobat, new PBELocalizedString("クロバット", "크로뱃", "Nostenfer", "Iksbat", "Crobat", "Crobat", "Crobat") },
            // { PBESpecies.170, new PBELocalizedString("チョンチー", "초라기", "Loupio", "Lampi", "Chinchou", "Chinchou", "Chinchou") },
            // { PBESpecies.171, new PBELocalizedString("ランターン", "랜턴", "Lanturn", "Lanturn", "Lanturn", "Lanturn", "Lanturn") },
            { PBESpecies.Pichu, new PBELocalizedString("ピチュー", "피츄", "Pichu", "Pichu", "Pichu", "Pichu", "Pichu") },
            // { PBESpecies.173, new PBELocalizedString("ピィ", "삐", "Mélo", "Pii", "Cleffa", "Cleffa", "Cleffa") },
            // { PBESpecies.174, new PBELocalizedString("ププリン", "푸푸린", "Toudoudou", "Fluffeluff", "Igglybuff", "Igglybuff", "Igglybuff") },
            // { PBESpecies.175, new PBELocalizedString("トゲピー", "토게피", "Togepi", "Togepi", "Togepi", "Togepi", "Togepi") },
            // { PBESpecies.176, new PBELocalizedString("トゲチック", "토게틱", "Togetic", "Togetic", "Togetic", "Togetic", "Togetic") },
            // { PBESpecies.177, new PBELocalizedString("ネイティ", "네이티", "Natu", "Natu", "Natu", "Natu", "Natu") },
            // { PBESpecies.178, new PBELocalizedString("ネイティオ", "네이티오", "Xatu", "Xatu", "Xatu", "Xatu", "Xatu") },
            // { PBESpecies.179, new PBELocalizedString("メリープ", "메리프", "Wattouat", "Voltilamm", "Mareep", "Mareep", "Mareep") },
            // { PBESpecies.180, new PBELocalizedString("モココ", "보송송", "Lainergie", "Waaty", "Flaaffy", "Flaaffy", "Flaaffy") },
            // { PBESpecies.181, new PBELocalizedString("デンリュウ", "전룡", "Pharamp", "Ampharos", "Ampharos", "Ampharos", "Ampharos") },
            // { PBESpecies.182, new PBELocalizedString("キレイハナ", "아르코", "Joliflor", "Blubella", "Bellossom", "Bellossom", "Bellossom") },
            { PBESpecies.Marill, new PBELocalizedString("マリル", "마릴", "Marill", "Marill", "Marill", "Marill", "Marill") },
            { PBESpecies.Azumarill, new PBELocalizedString("マリルリ", "마릴리", "Azumarill", "Azumarill", "Azumarill", "Azumarill", "Azumarill") },
            // { PBESpecies.185, new PBELocalizedString("ウソッキー", "꼬지모", "Simularbre", "Mogelbaum", "Sudowoodo", "Sudowoodo", "Sudowoodo") },
            { PBESpecies.Politoed, new PBELocalizedString("ニョロトノ", "왕구리", "Tarpaud", "Quaxo", "Politoed", "Politoed", "Politoed") },
            // { PBESpecies.187, new PBELocalizedString("ハネッコ", "통통코", "Granivol", "Hoppspross", "Hoppip", "Hoppip", "Hoppip") },
            // { PBESpecies.188, new PBELocalizedString("ポポッコ", "두코", "Floravol", "Hubelupf", "Skiploom", "Skiploom", "Skiploom") },
            // { PBESpecies.189, new PBELocalizedString("ワタッコ", "솜솜코", "Cotovol", "Papungha", "Jumpluff", "Jumpluff", "Jumpluff") },
            // { PBESpecies.190, new PBELocalizedString("エイパム", "에이팜", "Capumain", "Griffel", "Aipom", "Aipom", "Aipom") },
            // { PBESpecies.191, new PBELocalizedString("ヒマナッツ", "해너츠", "Tournegrin", "Sonnkern", "Sunkern", "Sunkern", "Sunkern") },
            // { PBESpecies.192, new PBELocalizedString("キマワリ", "해루미", "Héliatronc", "Sonnflora", "Sunflora", "Sunflora", "Sunflora") },
            // { PBESpecies.193, new PBELocalizedString("ヤンヤンマ", "왕자리", "Yanma", "Yanma", "Yanma", "Yanma", "Yanma") },
            // { PBESpecies.194, new PBELocalizedString("ウパー", "우파", "Axoloto", "Felino", "Wooper", "Wooper", "Wooper") },
            // { PBESpecies.195, new PBELocalizedString("ヌオー", "누오", "Maraiste", "Morlord", "Quagsire", "Quagsire", "Quagsire") },
            { PBESpecies.Espeon, new PBELocalizedString("エーフィ", "에브이", "Mentali", "Psiana", "Espeon", "Espeon", "Espeon") },
            { PBESpecies.Umbreon, new PBELocalizedString("ブラッキー", "블래키", "Noctali", "Nachtara", "Umbreon", "Umbreon", "Umbreon") },
            // { PBESpecies.198, new PBELocalizedString("ヤミカラス", "니로우", "Cornèbre", "Kramurx", "Murkrow", "Murkrow", "Murkrow") },
            // { PBESpecies.199, new PBELocalizedString("ヤドキング", "야도킹", "Roigada", "Laschoking", "Slowking", "Slowking", "Slowking") },
            { PBESpecies.Misdreavus, new PBELocalizedString("ムウマ", "무우마", "Feuforêve", "Traunfugil", "Misdreavus", "Misdreavus", "Misdreavus") },
            { PBESpecies.Unown_A, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_B, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_C, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_D, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_E, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_Exclamation, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_F, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_G, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_H, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_I, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_J, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_K, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_L, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_M, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_N, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_O, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_P, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_Q, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_Question, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_R, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_S, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_T, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_U, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_V, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_W, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_X, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_Y, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            { PBESpecies.Unown_Z, new PBELocalizedString("アンノーン", "안농", "Zarbi", "Icognito", "Unown", "Unown", "Unown") },
            // { PBESpecies.202, new PBELocalizedString("ソーナンス", "마자용", "Qulbutoké", "Woingenau", "Wobbuffet", "Wobbuffet", "Wobbuffet") },
            // { PBESpecies.203, new PBELocalizedString("キリンリキ", "키링키", "Girafarig", "Girafarig", "Girafarig", "Girafarig", "Girafarig") },
            // { PBESpecies.204, new PBELocalizedString("クヌギダマ", "피콘", "Pomdepik", "Tannza", "Pineco", "Pineco", "Pineco") },
            // { PBESpecies.205, new PBELocalizedString("フォレトス", "쏘콘", "Foretress", "Forstellka", "Forretress", "Forretress", "Forretress") },
            // { PBESpecies.206, new PBELocalizedString("ノコッチ", "노고치", "Insolourdo", "Dummisel", "Dunsparce", "Dunsparce", "Dunsparce") },
            // { PBESpecies.207, new PBELocalizedString("グライガー", "글라이거", "Scorplane", "Skorgla", "Gligar", "Gligar", "Gligar") },
            // { PBESpecies.208, new PBELocalizedString("ハガネール", "강철톤", "Steelix", "Stahlos", "Steelix", "Steelix", "Steelix") },
            // { PBESpecies.209, new PBELocalizedString("ブルー", "블루", "Snubbull", "Snubbull", "Snubbull", "Snubbull", "Snubbull") },
            // { PBESpecies.210, new PBELocalizedString("グランブル", "그랑블루", "Granbull", "Granbull", "Granbull", "Granbull", "Granbull") },
            // { PBESpecies.211, new PBELocalizedString("ハリーセン", "침바루", "Qwilfish", "Baldorfish", "Qwilfish", "Qwilfish", "Qwilfish") },
            // { PBESpecies.212, new PBELocalizedString("ハッサム", "핫삼", "Cizayox", "Scherox", "Scizor", "Scizor", "Scizor") },
            // { PBESpecies.213, new PBELocalizedString("ツボツボ", "단단지", "Caratroc", "Pottrott", "Shuckle", "Shuckle", "Shuckle") },
            // { PBESpecies.214, new PBELocalizedString("ヘラクロス", "헤라크로스", "Scarhino", "Skaraborn", "Heracross", "Heracross", "Heracross") },
            // { PBESpecies.215, new PBELocalizedString("ニューラ", "포푸니", "Farfuret", "Sniebel", "Sneasel", "Sneasel", "Sneasel") },
            // { PBESpecies.216, new PBELocalizedString("ヒメグマ", "깜지곰", "Teddiursa", "Teddiursa", "Teddiursa", "Teddiursa", "Teddiursa") },
            // { PBESpecies.217, new PBELocalizedString("リングマ", "링곰", "Ursaring", "Ursaring", "Ursaring", "Ursaring", "Ursaring") },
            // { PBESpecies.218, new PBELocalizedString("マグマッグ", "마그마그", "Limagma", "Schneckmag", "Slugma", "Slugma", "Slugma") },
            // { PBESpecies.219, new PBELocalizedString("マグカルゴ", "마그카르고", "Volcaropod", "Magcargo", "Magcargo", "Magcargo", "Magcargo") },
            // { PBESpecies.220, new PBELocalizedString("ウリムー", "꾸꾸리", "Marcacrin", "Quiekel", "Swinub", "Swinub", "Swinub") },
            // { PBESpecies.221, new PBELocalizedString("イノムー", "메꾸리", "Cochignon", "Keifel", "Piloswine", "Piloswine", "Piloswine") },
            // { PBESpecies.222, new PBELocalizedString("サニーゴ", "코산호", "Corayon", "Corasonn", "Corsola", "Corsola", "Corsola") },
            // { PBESpecies.223, new PBELocalizedString("テッポウオ", "총어", "Rémoraid", "Remoraid", "Remoraid", "Remoraid", "Remoraid") },
            // { PBESpecies.224, new PBELocalizedString("オクタン", "대포무노", "Octillery", "Octillery", "Octillery", "Octillery", "Octillery") },
            // { PBESpecies.225, new PBELocalizedString("デリバード", "딜리버드", "Cadoizo", "Botogel", "Delibird", "Delibird", "Delibird") },
            // { PBESpecies.226, new PBELocalizedString("マンタイン", "만타인", "Démanta", "Mantax", "Mantine", "Mantine", "Mantine") },
            // { PBESpecies.227, new PBELocalizedString("エアームド", "무장조", "Airmure", "Panzaeron", "Skarmory", "Skarmory", "Skarmory") },
            // { PBESpecies.228, new PBELocalizedString("デルビル", "델빌", "Malosse", "Hunduster", "Houndour", "Houndour", "Houndour") },
            // { PBESpecies.229, new PBELocalizedString("ヘルガー", "헬가", "Démolosse", "Hundemon", "Houndoom", "Houndoom", "Houndoom") },
            // { PBESpecies.230, new PBELocalizedString("キングドラ", "킹드라", "Hyporoi", "Seedraking", "Kingdra", "Kingdra", "Kingdra") },
            // { PBESpecies.231, new PBELocalizedString("ゴマゾウ", "코코리", "Phanpy", "Phanpy", "Phanpy", "Phanpy", "Phanpy") },
            // { PBESpecies.232, new PBELocalizedString("ドンファン", "코리갑", "Donphan", "Donphan", "Donphan", "Donphan", "Donphan") },
            // { PBESpecies.233, new PBELocalizedString("ポリゴン２", "폴리곤2", "Porygon2", "Porygon2", "Porygon2", "Porygon2", "Porygon2") },
            // { PBESpecies.234, new PBELocalizedString("オドシシ", "노라키", "Cerfrousse", "Damhirplex", "Stantler", "Stantler", "Stantler") },
            { PBESpecies.Smeargle, new PBELocalizedString("ドーブル", "루브도", "Queulorior", "Farbeagle", "Smeargle", "Smeargle", "Smeargle") },
            // { PBESpecies.236, new PBELocalizedString("バルキー", "배루키", "Debugant", "Rabauz", "Tyrogue", "Tyrogue", "Tyrogue") },
            // { PBESpecies.237, new PBELocalizedString("カポエラー", "카포에라", "Kapoera", "Kapoera", "Hitmontop", "Hitmontop", "Hitmontop") },
            // { PBESpecies.238, new PBELocalizedString("ムチュール", "뽀뽀라", "Lippouti", "Kussilla", "Smoochum", "Smoochum", "Smoochum") },
            // { PBESpecies.239, new PBELocalizedString("エレキッド", "에레키드", "Élekid", "Elekid", "Elekid", "Elekid", "Elekid") },
            // { PBESpecies.240, new PBELocalizedString("ブビィ", "마그비", "Magby", "Magby", "Magby", "Magby", "Magby") },
            // { PBESpecies.241, new PBELocalizedString("ミルタンク", "밀탱크", "Écrémeuh", "Miltank", "Miltank", "Miltank", "Miltank") },
            { PBESpecies.Blissey, new PBELocalizedString("ハピナス", "해피너스", "Leuphorie", "Heiteira", "Blissey", "Blissey", "Blissey") },
            // { PBESpecies.243, new PBELocalizedString("ライコウ", "라이코", "Raikou", "Raikou", "Raikou", "Raikou", "Raikou") },
            // { PBESpecies.244, new PBELocalizedString("エンテイ", "앤테이", "Entei", "Entei", "Entei", "Entei", "Entei") },
            // { PBESpecies.245, new PBELocalizedString("スイクン", "스이쿤", "Suicune", "Suicune", "Suicune", "Suicune", "Suicune") },
            // { PBESpecies.246, new PBELocalizedString("ヨーギラス", "애버라스", "Embrylex", "Larvitar", "Larvitar", "Larvitar", "Larvitar") },
            // { PBESpecies.247, new PBELocalizedString("サナギラス", "데기라스", "Ymphect", "Pupitar", "Pupitar", "Pupitar", "Pupitar") },
            // { PBESpecies.248, new PBELocalizedString("バンギラス", "마기라스", "Tyranocif", "Despotar", "Tyranitar", "Tyranitar", "Tyranitar") },
            // { PBESpecies.249, new PBELocalizedString("ルギア", "루기아", "Lugia", "Lugia", "Lugia", "Lugia", "Lugia") },
            // { PBESpecies.250, new PBELocalizedString("ホウオウ", "칠색조", "Ho-Oh", "Ho-Oh", "Ho-Oh", "Ho-Oh", "Ho-Oh") },
            // { PBESpecies.251, new PBELocalizedString("セレビィ", "세레비", "Celebi", "Celebi", "Celebi", "Celebi", "Celebi") },
            // { PBESpecies.252, new PBELocalizedString("キモリ", "나무지기", "Arcko", "Geckarbor", "Treecko", "Treecko", "Treecko") },
            // { PBESpecies.253, new PBELocalizedString("ジュプトル", "나무돌이", "Massko", "Reptain", "Grovyle", "Grovyle", "Grovyle") },
            // { PBESpecies.254, new PBELocalizedString("ジュカイン", "나무킹", "Jungko", "Gewaldro", "Sceptile", "Sceptile", "Sceptile") },
            { PBESpecies.Torchic, new PBELocalizedString("アチャモ", "아차모", "Poussifeu", "Flemmli", "Torchic", "Torchic", "Torchic") },
            { PBESpecies.Combusken, new PBELocalizedString("ワカシャモ", "영치코", "Galifeu", "Jungglut", "Combusken", "Combusken", "Combusken") },
            { PBESpecies.Blaziken, new PBELocalizedString("バシャーモ", "번치코", "Braségali", "Lohgock", "Blaziken", "Blaziken", "Blaziken") },
            // { PBESpecies.258, new PBELocalizedString("ミズゴロウ", "물짱이", "Gobou", "Hydropi", "Mudkip", "Mudkip", "Mudkip") },
            // { PBESpecies.259, new PBELocalizedString("ヌマクロー", "늪짱이", "Flobio", "Moorabbel", "Marshtomp", "Marshtomp", "Marshtomp") },
            // { PBESpecies.260, new PBELocalizedString("ラグラージ", "대짱이", "Laggron", "Sumpex", "Swampert", "Swampert", "Swampert") },
            // { PBESpecies.261, new PBELocalizedString("ポチエナ", "포챠나", "Medhyèna", "Fiffyen", "Poochyena", "Poochyena", "Poochyena") },
            // { PBESpecies.262, new PBELocalizedString("グラエナ", "그라에나", "Grahyèna", "Magnayen", "Mightyena", "Mightyena", "Mightyena") },
            // { PBESpecies.263, new PBELocalizedString("ジグザグマ", "지그제구리", "Zigzaton", "Zigzachs", "Zigzagoon", "Zigzagoon", "Zigzagoon") },
            // { PBESpecies.264, new PBELocalizedString("マッスグマ", "직구리", "Linéon", "Geradaks", "Linoone", "Linoone", "Linoone") },
            // { PBESpecies.265, new PBELocalizedString("ケムッソ", "개무소", "Chenipotte", "Waumpel", "Wurmple", "Wurmple", "Wurmple") },
            // { PBESpecies.266, new PBELocalizedString("カラサリス", "실쿤", "Armulys", "Schaloko", "Silcoon", "Silcoon", "Silcoon") },
            // { PBESpecies.267, new PBELocalizedString("アゲハント", "뷰티플라이", "Charmillon", "Papinella", "Beautifly", "Beautifly", "Beautifly") },
            // { PBESpecies.268, new PBELocalizedString("マユルド", "카스쿤", "Blindalys", "Panekon", "Cascoon", "Cascoon", "Cascoon") },
            // { PBESpecies.269, new PBELocalizedString("ドクケイル", "독케일", "Papinox", "Pudox", "Dustox", "Dustox", "Dustox") },
            // { PBESpecies.270, new PBELocalizedString("ハスボー", "연꽃몬", "Nénupiot", "Loturzel", "Lotad", "Lotad", "Lotad") },
            // { PBESpecies.271, new PBELocalizedString("ハスブレロ", "로토스", "Lombre", "Lombrero", "Lombre", "Lombre", "Lombre") },
            // { PBESpecies.272, new PBELocalizedString("ルンパッパ", "로파파", "Ludicolo", "Kappalores", "Ludicolo", "Ludicolo", "Ludicolo") },
            // { PBESpecies.273, new PBELocalizedString("タネボー", "도토링", "Grainipiot", "Samurzel", "Seedot", "Seedot", "Seedot") },
            // { PBESpecies.274, new PBELocalizedString("コノハナ", "잎새코", "Pifeuil", "Blanas", "Nuzleaf", "Nuzleaf", "Nuzleaf") },
            // { PBESpecies.275, new PBELocalizedString("ダーテング", "다탱구", "Tengalice", "Tengulist", "Shiftry", "Shiftry", "Shiftry") },
            // { PBESpecies.276, new PBELocalizedString("スバメ", "테일로", "Nirondelle", "Schwalbini", "Taillow", "Taillow", "Taillow") },
            // { PBESpecies.277, new PBELocalizedString("オオスバメ", "스왈로", "Hélédelle", "Schwalboss", "Swellow", "Swellow", "Swellow") },
            // { PBESpecies.278, new PBELocalizedString("キャモメ", "갈모매", "Goélise", "Wingull", "Wingull", "Wingull", "Wingull") },
            // { PBESpecies.279, new PBELocalizedString("ペリッパー", "패리퍼", "Bekipan", "Pelipper", "Pelipper", "Pelipper", "Pelipper") },
            // { PBESpecies.280, new PBELocalizedString("ラルトス", "랄토스", "Tarsal", "Trasla", "Ralts", "Ralts", "Ralts") },
            // { PBESpecies.281, new PBELocalizedString("キルリア", "킬리아", "Kirlia", "Kirlia", "Kirlia", "Kirlia", "Kirlia") },
            // { PBESpecies.282, new PBELocalizedString("サーナイト", "가디안", "Gardevoir", "Guardevoir", "Gardevoir", "Gardevoir", "Gardevoir") },
            // { PBESpecies.283, new PBELocalizedString("アメタマ", "비구술", "Arakdo", "Gehweiher", "Surskit", "Surskit", "Surskit") },
            // { PBESpecies.284, new PBELocalizedString("アメモース", "비나방", "Maskadra", "Maskeregen", "Masquerain", "Masquerain", "Masquerain") },
            // { PBESpecies.285, new PBELocalizedString("キノココ", "버섯꼬", "Balignon", "Knilz", "Shroomish", "Shroomish", "Shroomish") },
            // { PBESpecies.286, new PBELocalizedString("キノガッサ", "버섯모", "Chapignon", "Kapilz", "Breloom", "Breloom", "Breloom") },
            // { PBESpecies.287, new PBELocalizedString("ナマケロ", "게을로", "Parecool", "Bummelz", "Slakoth", "Slakoth", "Slakoth") },
            // { PBESpecies.288, new PBELocalizedString("ヤルキモノ", "발바로", "Vigoroth", "Muntier", "Vigoroth", "Vigoroth", "Vigoroth") },
            // { PBESpecies.289, new PBELocalizedString("ケッキング", "게을킹", "Monaflèmit", "Letarking", "Slaking", "Slaking", "Slaking") },
            { PBESpecies.Nincada, new PBELocalizedString("ツチニン", "토중몬", "Ningale", "Nincada", "Nincada", "Nincada", "Nincada") },
            { PBESpecies.Ninjask, new PBELocalizedString("テッカニン", "아이스크", "Ninjask", "Ninjask", "Ninjask", "Ninjask", "Ninjask") },
            { PBESpecies.Shedinja, new PBELocalizedString("ヌケニン", "껍질몬", "Munja", "Ninjatom", "Shedinja", "Shedinja", "Shedinja") },
            // { PBESpecies.293, new PBELocalizedString("ゴニョニョ", "소곤룡", "Chuchmur", "Flurmel", "Whismur", "Whismur", "Whismur") },
            // { PBESpecies.294, new PBELocalizedString("ドゴーム", "노공룡", "Ramboum", "Krakeelo", "Loudred", "Loudred", "Loudred") },
            // { PBESpecies.295, new PBELocalizedString("バクオング", "폭음룡", "Brouhabam", "Krawumms", "Exploud", "Exploud", "Exploud") },
            // { PBESpecies.296, new PBELocalizedString("マクノシタ", "마크탕", "Makuhita", "Makuhita", "Makuhita", "Makuhita", "Makuhita") },
            // { PBESpecies.297, new PBELocalizedString("ハリテヤマ", "하리뭉", "Hariyama", "Hariyama", "Hariyama", "Hariyama", "Hariyama") },
            { PBESpecies.Azurill, new PBELocalizedString("ルリリ", "루리리", "Azurill", "Azurill", "Azurill", "Azurill", "Azurill") },
            // { PBESpecies.299, new PBELocalizedString("ノズパス", "코코파스", "Tarinor", "Nasgnet", "Nosepass", "Nosepass", "Nosepass") },
            { PBESpecies.Skitty, new PBELocalizedString("エネコ", "에나비", "Skitty", "Eneco", "Skitty", "Skitty", "Skitty") },
            { PBESpecies.Delcatty, new PBELocalizedString("エネコロロ", "델케티", "Delcatty", "Enekoro", "Delcatty", "Delcatty", "Delcatty") },
            // { PBESpecies.302, new PBELocalizedString("ヤミラミ", "깜까미", "Ténéfix", "Zobiris", "Sableye", "Sableye", "Sableye") },
            // { PBESpecies.303, new PBELocalizedString("クチート", "입치트", "Mysdibule", "Flunkifer", "Mawile", "Mawile", "Mawile") },
            // { PBESpecies.304, new PBELocalizedString("ココドラ", "가보리", "Galekid", "Stollunior", "Aron", "Aron", "Aron") },
            // { PBESpecies.305, new PBELocalizedString("コドラ", "갱도라", "Galegon", "Stollrak", "Lairon", "Lairon", "Lairon") },
            // { PBESpecies.306, new PBELocalizedString("ボスゴドラ", "보스로라", "Galeking", "Stolloss", "Aggron", "Aggron", "Aggron") },
            // { PBESpecies.307, new PBELocalizedString("アサナン", "요가랑", "Méditikka", "Meditie", "Meditite", "Meditite", "Meditite") },
            // { PBESpecies.308, new PBELocalizedString("チャーレム", "요가램", "Charmina", "Meditalis", "Medicham", "Medicham", "Medicham") },
            // { PBESpecies.309, new PBELocalizedString("ラクライ", "썬더라이", "Dynavolt", "Frizelbliz", "Electrike", "Electrike", "Electrike") },
            // { PBESpecies.310, new PBELocalizedString("ライボルト", "썬더볼트", "Élecsprint", "Voltenso", "Manectric", "Manectric", "Manectric") },
            { PBESpecies.Plusle, new PBELocalizedString("プラスル", "플러시", "Posipi", "Plusle", "Plusle", "Plusle", "Plusle") },
            { PBESpecies.Minun, new PBELocalizedString("マイナン", "마이농", "Négapi", "Minun", "Minun", "Minun", "Minun") },
            // { PBESpecies.313, new PBELocalizedString("バルビート", "볼비트", "Muciole", "Volbeat", "Volbeat", "Volbeat", "Volbeat") },
            // { PBESpecies.314, new PBELocalizedString("イルミーゼ", "네오비트", "Lumivole", "Illumise", "Illumise", "Illumise", "Illumise") },
            // { PBESpecies.315, new PBELocalizedString("ロゼリア", "로젤리아", "Rosélia", "Roselia", "Roselia", "Roselia", "Roselia") },
            // { PBESpecies.316, new PBELocalizedString("ゴクリン", "꼴깍몬", "Gloupti", "Schluppuck", "Gulpin", "Gulpin", "Gulpin") },
            // { PBESpecies.317, new PBELocalizedString("マルノーム", "꿀꺽몬", "Avaltout", "Schlukwech", "Swalot", "Swalot", "Swalot") },
            // { PBESpecies.318, new PBELocalizedString("キバニア", "샤프니아", "Carvanha", "Kanivanha", "Carvanha", "Carvanha", "Carvanha") },
            // { PBESpecies.319, new PBELocalizedString("サメハダー", "샤크니아", "Sharpedo", "Tohaido", "Sharpedo", "Sharpedo", "Sharpedo") },
            // { PBESpecies.320, new PBELocalizedString("ホエルコ", "고래왕자", "Wailmer", "Wailmer", "Wailmer", "Wailmer", "Wailmer") },
            // { PBESpecies.321, new PBELocalizedString("ホエルオー", "고래왕", "Wailord", "Wailord", "Wailord", "Wailord", "Wailord") },
            // { PBESpecies.322, new PBELocalizedString("ドンメル", "둔타", "Chamallot", "Camaub", "Numel", "Numel", "Numel") },
            // { PBESpecies.323, new PBELocalizedString("バクーダ", "폭타", "Camérupt", "Camerupt", "Camerupt", "Camerupt", "Camerupt") },
            // { PBESpecies.324, new PBELocalizedString("コータス", "코터스", "Chartor", "Qurtel", "Torkoal", "Torkoal", "Torkoal") },
            // { PBESpecies.325, new PBELocalizedString("バネブー", "피그점프", "Spoink", "Spoink", "Spoink", "Spoink", "Spoink") },
            // { PBESpecies.326, new PBELocalizedString("ブーピッグ", "피그킹", "Groret", "Groink", "Grumpig", "Grumpig", "Grumpig") },
            // { PBESpecies.327, new PBELocalizedString("パッチール", "얼루기", "Spinda", "Pandir", "Spinda", "Spinda", "Spinda") },
            // { PBESpecies.328, new PBELocalizedString("ナックラー", "톱치", "Kraknoix", "Knacklion", "Trapinch", "Trapinch", "Trapinch") },
            // { PBESpecies.329, new PBELocalizedString("ビブラーバ", "비브라바", "Vibraninf", "Vibrava", "Vibrava", "Vibrava", "Vibrava") },
            // { PBESpecies.330, new PBELocalizedString("フライゴン", "플라이곤", "Libégon", "Libelldra", "Flygon", "Flygon", "Flygon") },
            // { PBESpecies.331, new PBELocalizedString("サボネア", "선인왕", "Cacnea", "Tuska", "Cacnea", "Cacnea", "Cacnea") },
            // { PBESpecies.332, new PBELocalizedString("ノクタス", "밤선인", "Cacturne", "Noktuska", "Cacturne", "Cacturne", "Cacturne") },
            // { PBESpecies.333, new PBELocalizedString("チルット", "파비코", "Tylton", "Wablu", "Swablu", "Swablu", "Swablu") },
            // { PBESpecies.334, new PBELocalizedString("チルタリス", "파비코리", "Altaria", "Altaria", "Altaria", "Altaria", "Altaria") },
            // { PBESpecies.335, new PBELocalizedString("ザングース", "쟝고", "Mangriff", "Sengo", "Zangoose", "Zangoose", "Zangoose") },
            // { PBESpecies.336, new PBELocalizedString("ハブネーク", "세비퍼", "Séviper", "Vipitis", "Seviper", "Seviper", "Seviper") },
            // { PBESpecies.337, new PBELocalizedString("ルナトーン", "루나톤", "Séléroc", "Lunastein", "Lunatone", "Lunatone", "Lunatone") },
            // { PBESpecies.338, new PBELocalizedString("ソルロック", "솔록", "Solaroc", "Sonnfel", "Solrock", "Solrock", "Solrock") },
            // { PBESpecies.339, new PBELocalizedString("ドジョッチ", "미꾸리", "Barloche", "Schmerbe", "Barboach", "Barboach", "Barboach") },
            // { PBESpecies.340, new PBELocalizedString("ナマズン", "메깅", "Barbicha", "Welsar", "Whiscash", "Whiscash", "Whiscash") },
            // { PBESpecies.341, new PBELocalizedString("ヘイガニ", "가재군", "Écrapince", "Krebscorps", "Corphish", "Corphish", "Corphish") },
            // { PBESpecies.342, new PBELocalizedString("シザリガー", "가재장군", "Colhomard", "Krebutack", "Crawdaunt", "Crawdaunt", "Crawdaunt") },
            // { PBESpecies.343, new PBELocalizedString("ヤジロン", "오뚝군", "Balbuto", "Puppance", "Baltoy", "Baltoy", "Baltoy") },
            // { PBESpecies.344, new PBELocalizedString("ネンドール", "점토도리", "Kaorine", "Lepumentas", "Claydol", "Claydol", "Claydol") },
            { PBESpecies.Lileep, new PBELocalizedString("リリーラ", "릴링", "Lilia", "Liliep", "Lileep", "Lileep", "Lileep") },
            { PBESpecies.Cradily, new PBELocalizedString("ユレイドル", "릴리요", "Vacilys", "Wielie", "Cradily", "Cradily", "Cradily") },
            // { PBESpecies.347, new PBELocalizedString("アノプス", "아노딥스", "Anorith", "Anorith", "Anorith", "Anorith", "Anorith") },
            // { PBESpecies.348, new PBELocalizedString("アーマルド", "아말도", "Armaldo", "Armaldo", "Armaldo", "Armaldo", "Armaldo") },
            // { PBESpecies.349, new PBELocalizedString("ヒンバス", "빈티나", "Barpau", "Barschwa", "Feebas", "Feebas", "Feebas") },
            // { PBESpecies.350, new PBELocalizedString("ミロカロス", "밀로틱", "Milobellus", "Milotic", "Milotic", "Milotic", "Milotic") },
            // { PBESpecies.351, new PBELocalizedString("ポワルン", "캐스퐁", "Morphéo", "Formeo", "Castform", "Castform", "Castform") },
            // { PBESpecies.352, new PBELocalizedString("カクレオン", "켈리몬", "Kecleon", "Kecleon", "Kecleon", "Kecleon", "Kecleon") },
            // { PBESpecies.353, new PBELocalizedString("カゲボウズ", "어둠대신", "Polichombr", "Shuppet", "Shuppet", "Shuppet", "Shuppet") },
            // { PBESpecies.354, new PBELocalizedString("ジュペッタ", "다크펫", "Branette", "Banette", "Banette", "Banette", "Banette") },
            // { PBESpecies.355, new PBELocalizedString("ヨマワル", "해골몽", "Skelénox", "Zwirrlicht", "Duskull", "Duskull", "Duskull") },
            // { PBESpecies.356, new PBELocalizedString("サマヨール", "미라몽", "Téraclope", "Zwirrklop", "Dusclops", "Dusclops", "Dusclops") },
            { PBESpecies.Tropius, new PBELocalizedString("トロピウス", "트로피우스", "Tropius", "Tropius", "Tropius", "Tropius", "Tropius") },
            // { PBESpecies.358, new PBELocalizedString("チリーン", "치렁", "Éoko", "Palimpalim", "Chimecho", "Chimecho", "Chimecho") },
            { PBESpecies.Absol, new PBELocalizedString("アブソル", "앱솔", "Absol", "Absol", "Absol", "Absol", "Absol") },
            // { PBESpecies.360, new PBELocalizedString("ソーナノ", "마자", "Okéoké", "Isso", "Wynaut", "Wynaut", "Wynaut") },
            // { PBESpecies.361, new PBELocalizedString("ユキワラシ", "눈꼬마", "Stalgamin", "Schneppke", "Snorunt", "Snorunt", "Snorunt") },
            // { PBESpecies.362, new PBELocalizedString("オニゴーリ", "얼음귀신", "Oniglali", "Firnontor", "Glalie", "Glalie", "Glalie") },
            // { PBESpecies.363, new PBELocalizedString("タマザラシ", "대굴레오", "Obalie", "Seemops", "Spheal", "Spheal", "Spheal") },
            // { PBESpecies.364, new PBELocalizedString("トドグラー", "씨레오", "Phogleur", "Seejong", "Sealeo", "Sealeo", "Sealeo") },
            // { PBESpecies.365, new PBELocalizedString("トドゼルガ", "씨카이저", "Kaimorse", "Walraisa", "Walrein", "Walrein", "Walrein") },
            { PBESpecies.Clamperl, new PBELocalizedString("パールル", "진주몽", "Coquiperl", "Perlu", "Clamperl", "Clamperl", "Clamperl") },
            { PBESpecies.Huntail, new PBELocalizedString("ハンテール", "헌테일", "Serpang", "Aalabyss", "Huntail", "Huntail", "Huntail") },
            { PBESpecies.Gorebyss, new PBELocalizedString("サクラビス", "분홍장이", "Rosabyss", "Saganabyss", "Gorebyss", "Gorebyss", "Gorebyss") },
            // { PBESpecies.369, new PBELocalizedString("ジーランス", "시라칸", "Relicanth", "Relicanth", "Relicanth", "Relicanth", "Relicanth") },
            // { PBESpecies.370, new PBELocalizedString("ラブカス", "사랑동이", "Lovdisc", "Liebiskus", "Luvdisc", "Luvdisc", "Luvdisc") },
            // { PBESpecies.371, new PBELocalizedString("タツベイ", "아공이", "Draby", "Kindwurm", "Bagon", "Bagon", "Bagon") },
            // { PBESpecies.372, new PBELocalizedString("コモルー", "쉘곤", "Drackhaus", "Draschel", "Shelgon", "Shelgon", "Shelgon") },
            // { PBESpecies.373, new PBELocalizedString("ボーマンダ", "보만다", "Drattak", "Brutalanda", "Salamence", "Salamence", "Salamence") },
            { PBESpecies.Beldum, new PBELocalizedString("ダンバル", "메탕", "Terhal", "Tanhel", "Beldum", "Beldum", "Beldum") },
            { PBESpecies.Metang, new PBELocalizedString("メタング", "메탕구", "Métang", "Metang", "Metang", "Metang", "Metang") },
            { PBESpecies.Metagross, new PBELocalizedString("メタグロス", "메타그로스", "Métalosse", "Metagross", "Metagross", "Metagross", "Metagross") },
            { PBESpecies.Regirock, new PBELocalizedString("レジロック", "레지락", "Regirock", "Regirock", "Regirock", "Regirock", "Regirock") },
            // { PBESpecies.378, new PBELocalizedString("レジアイス", "레지아이스", "Regice", "Regice", "Regice", "Regice", "Regice") },
            // { PBESpecies.379, new PBELocalizedString("レジスチル", "레지스틸", "Registeel", "Registeel", "Registeel", "Registeel", "Registeel") },
            { PBESpecies.Latias, new PBELocalizedString("ラティアス", "라티아스", "Latias", "Latias", "Latias", "Latias", "Latias") },
            { PBESpecies.Latios, new PBELocalizedString("ラティオス", "라티오스", "Latios", "Latios", "Latios", "Latios", "Latios") },
            // { PBESpecies.382, new PBELocalizedString("カイオーガ", "가이오가", "Kyogre", "Kyogre", "Kyogre", "Kyogre", "Kyogre") },
            // { PBESpecies.383, new PBELocalizedString("グラードン", "그란돈", "Groudon", "Groudon", "Groudon", "Groudon", "Groudon") },
            // { PBESpecies.384, new PBELocalizedString("レックウザ", "레쿠쟈", "Rayquaza", "Rayquaza", "Rayquaza", "Rayquaza", "Rayquaza") },
            { PBESpecies.Jirachi, new PBELocalizedString("ジラーチ", "지라치", "Jirachi", "Jirachi", "Jirachi", "Jirachi", "Jirachi") },
            // { PBESpecies.386, new PBELocalizedString("デオキシス", "테오키스", "Deoxys", "Deoxys", "Deoxys", "Deoxys", "Deoxys") },
            // { PBESpecies.387, new PBELocalizedString("ナエトル", "모부기", "Tortipouss", "Chelast", "Turtwig", "Turtwig", "Turtwig") },
            // { PBESpecies.388, new PBELocalizedString("ハヤシガメ", "수풀부기", "Boskara", "Chelcarain", "Grotle", "Grotle", "Grotle") },
            // { PBESpecies.389, new PBELocalizedString("ドダイトス", "토대부기", "Torterra", "Chelterrar", "Torterra", "Torterra", "Torterra") },
            // { PBESpecies.390, new PBELocalizedString("ヒコザル", "불꽃숭이", "Ouisticram", "Panflam", "Chimchar", "Chimchar", "Chimchar") },
            // { PBESpecies.391, new PBELocalizedString("モウカザル", "파이숭이", "Chimpenfeu", "Panpyro", "Monferno", "Monferno", "Monferno") },
            // { PBESpecies.392, new PBELocalizedString("ゴウカザル", "초염몽", "Simiabraz", "Panferno", "Infernape", "Infernape", "Infernape") },
            // { PBESpecies.393, new PBELocalizedString("ポッチャマ", "팽도리", "Tiplouf", "Plinfa", "Piplup", "Piplup", "Piplup") },
            // { PBESpecies.394, new PBELocalizedString("ポッタイシ", "팽태자", "Prinplouf", "Pliprin", "Prinplup", "Prinplup", "Prinplup") },
            // { PBESpecies.395, new PBELocalizedString("エンペルト", "엠페르트", "Pingoléon", "Impoleon", "Empoleon", "Empoleon", "Empoleon") },
            // { PBESpecies.396, new PBELocalizedString("ムックル", "찌르꼬", "Étourmi", "Staralili", "Starly", "Starly", "Starly") },
            // { PBESpecies.397, new PBELocalizedString("ムクバード", "찌르버드", "Étourvol", "Staravia", "Staravia", "Staravia", "Staravia") },
            // { PBESpecies.398, new PBELocalizedString("ムクホーク", "찌르호크", "Étouraptor", "Staraptor", "Staraptor", "Staraptor", "Staraptor") },
            // { PBESpecies.399, new PBELocalizedString("ビッパ", "비버니", "Keunotor", "Bidiza", "Bidoof", "Bidoof", "Bidoof") },
            // { PBESpecies.400, new PBELocalizedString("ビーダル", "비버통", "Castorno", "Bidifas", "Bibarel", "Bibarel", "Bibarel") },
            // { PBESpecies.401, new PBELocalizedString("コロボーシ", "귀뚤뚜기", "Crikzik", "Zirpurze", "Kricketot", "Kricketot", "Kricketot") },
            // { PBESpecies.402, new PBELocalizedString("コロトック", "귀뚤톡크", "Mélokrik", "Zirpeise", "Kricketune", "Kricketune", "Kricketune") },
            { PBESpecies.Shinx, new PBELocalizedString("コリンク", "꼬링크", "Lixy", "Sheinux", "Shinx", "Shinx", "Shinx") },
            { PBESpecies.Luxio, new PBELocalizedString("ルクシオ", "럭시오", "Luxio", "Luxio", "Luxio", "Luxio", "Luxio") },
            { PBESpecies.Luxray, new PBELocalizedString("レントラー", "렌트라", "Luxray", "Luxtra", "Luxray", "Luxray", "Luxray") },
            // { PBESpecies.406, new PBELocalizedString("スボミー", "꼬몽울", "Rozbouton", "Knospi", "Budew", "Budew", "Budew") },
            // { PBESpecies.407, new PBELocalizedString("ロズレイド", "로즈레이드", "Roserade", "Roserade", "Roserade", "Roserade", "Roserade") },
            // { PBESpecies.408, new PBELocalizedString("ズガイドス", "두개도스", "Kranidos", "Koknodon", "Cranidos", "Cranidos", "Cranidos") },
            // { PBESpecies.409, new PBELocalizedString("ラムパルド", "램펄드", "Charkos", "Rameidon", "Rampardos", "Rampardos", "Rampardos") },
            // { PBESpecies.410, new PBELocalizedString("タテトプス", "방패톱스", "Dinoclier", "Schilterus", "Shieldon", "Shieldon", "Shieldon") },
            // { PBESpecies.411, new PBELocalizedString("トリデプス", "바리톱스", "Bastiodon", "Bollterus", "Bastiodon", "Bastiodon", "Bastiodon") },
            // { PBESpecies.412, new PBELocalizedString("ミノムッチ", "도롱충이", "Cheniti", "Burmy", "Burmy", "Burmy", "Burmy") },
            // { PBESpecies.413, new PBELocalizedString("ミノマダム", "도롱마담", "Cheniselle", "Burmadame", "Wormadam", "Wormadam", "Wormadam") },
            // { PBESpecies.414, new PBELocalizedString("ガーメイル", "나메일", "Papilord", "Moterpel", "Mothim", "Mothim", "Mothim") },
            // { PBESpecies.415, new PBELocalizedString("ミツハニー", "세꿀버리", "Apitrini", "Wadribie", "Combee", "Combee", "Combee") },
            // { PBESpecies.416, new PBELocalizedString("ビークイン", "비퀸", "Apireine", "Honweisel", "Vespiquen", "Vespiquen", "Vespiquen") },
            { PBESpecies.Pachirisu, new PBELocalizedString("パチリス", "파치리스", "Pachirisu", "Pachirisu", "Pachirisu", "Pachirisu", "Pachirisu") },
            // { PBESpecies.418, new PBELocalizedString("ブイゼル", "브이젤", "Mustébouée", "Bamelin", "Buizel", "Buizel", "Buizel") },
            // { PBESpecies.419, new PBELocalizedString("フローゼル", "플로젤", "Mustéflott", "Bojelin", "Floatzel", "Floatzel", "Floatzel") },
            // { PBESpecies.420, new PBELocalizedString("チェリンボ", "체리버", "Ceribou", "Kikugi", "Cherubi", "Cherubi", "Cherubi") },
            // { PBESpecies.421, new PBELocalizedString("チェリム", "체리꼬", "Ceriflor", "Kinoso", "Cherrim", "Cherrim", "Cherrim") },
            // { PBESpecies.422, new PBELocalizedString("カラナクシ", "깝질무", "Sancoki", "Schalellos", "Shellos", "Shellos", "Shellos") },
            // { PBESpecies.423, new PBELocalizedString("トリトドン", "트리토돈", "Tritosor", "Gastrodon", "Gastrodon", "Gastrodon", "Gastrodon") },
            // { PBESpecies.424, new PBELocalizedString("エテボース", "겟핸보숭", "Capidextre", "Ambidiffel", "Ambipom", "Ambipom", "Ambipom") },
            // { PBESpecies.425, new PBELocalizedString("フワンテ", "흔들풍손", "Baudrive", "Driftlon", "Drifloon", "Drifloon", "Drifloon") },
            // { PBESpecies.426, new PBELocalizedString("フワライド", "둥실라이드", "Grodrive", "Drifzepeli", "Drifblim", "Drifblim", "Drifblim") },
            // { PBESpecies.427, new PBELocalizedString("ミミロル", "이어롤", "Laporeille", "Haspiror", "Buneary", "Buneary", "Buneary") },
            // { PBESpecies.428, new PBELocalizedString("ミミロップ", "이어롭", "Lockpin", "Schlapor", "Lopunny", "Lopunny", "Lopunny") },
            { PBESpecies.Mismagius, new PBELocalizedString("ムウマージ", "무우마직", "Magirêve", "Traunmagil", "Mismagius", "Mismagius", "Mismagius") },
            // { PBESpecies.430, new PBELocalizedString("ドンカラス", "돈크로우", "Corboss", "Kramshef", "Honchkrow", "Honchkrow", "Honchkrow") },
            // { PBESpecies.431, new PBELocalizedString("ニャルマー", "나옹마", "Chaglam", "Charmian", "Glameow", "Glameow", "Glameow") },
            // { PBESpecies.432, new PBELocalizedString("ブニャット", "몬냥이", "Chaffreux", "Shnurgarst", "Purugly", "Purugly", "Purugly") },
            // { PBESpecies.433, new PBELocalizedString("リーシャン", "랑딸랑", "Korillon", "Klingplim", "Chingling", "Chingling", "Chingling") },
            // { PBESpecies.434, new PBELocalizedString("スカンプー", "스컹뿡", "Moufouette", "Skunkapuh", "Stunky", "Stunky", "Stunky") },
            // { PBESpecies.435, new PBELocalizedString("スカタンク", "스컹탱크", "Moufflair", "Skuntank", "Skuntank", "Skuntank", "Skuntank") },
            // { PBESpecies.436, new PBELocalizedString("ドーミラー", "동미러", "Archéomire", "Bronzel", "Bronzor", "Bronzor", "Bronzor") },
            // { PBESpecies.437, new PBELocalizedString("ドータクン", "동탁군", "Archéodong", "Bronzong", "Bronzong", "Bronzong", "Bronzong") },
            // { PBESpecies.438, new PBELocalizedString("ウソハチ", "꼬지지", "Manzaï", "Mobai", "Bonsly", "Bonsly", "Bonsly") },
            // { PBESpecies.439, new PBELocalizedString("マネネ", "흉내내", "Mime Jr.", "Pantimimi", "Mime Jr.", "Mime Jr.", "Mime Jr.") },
            { PBESpecies.Happiny, new PBELocalizedString("ピンプク", "핑복", "Ptiravi", "Wonneira", "Happiny", "Happiny", "Happiny") },
            // { PBESpecies.441, new PBELocalizedString("ペラップ", "페라페", "Pijako", "Plaudagei", "Chatot", "Chatot", "Chatot") },
            // { PBESpecies.442, new PBELocalizedString("ミカルゲ", "화강돌", "Spiritomb", "Kryppuk", "Spiritomb", "Spiritomb", "Spiritomb") },
            { PBESpecies.Gible, new PBELocalizedString("フカマル", "딥상어동", "Griknot", "Kaumalat", "Gible", "Gible", "Gible") },
            { PBESpecies.Gabite, new PBELocalizedString("ガバイト", "한바이트", "Carmache", "Knarksel", "Gabite", "Gabite", "Gabite") },
            { PBESpecies.Garchomp, new PBELocalizedString("ガブリアス", "한카리아스", "Carchacrok", "Knakrack", "Garchomp", "Garchomp", "Garchomp") },
            // { PBESpecies.446, new PBELocalizedString("ゴンベ", "먹고자", "Goinfrex", "Mampfaxo", "Munchlax", "Munchlax", "Munchlax") },
            { PBESpecies.Riolu, new PBELocalizedString("リオル", "리오르", "Riolu", "Riolu", "Riolu", "Riolu", "Riolu") },
            { PBESpecies.Lucario, new PBELocalizedString("ルカリオ", "루카리오", "Lucario", "Lucario", "Lucario", "Lucario", "Lucario") },
            // { PBESpecies.449, new PBELocalizedString("ヒポポタス", "히포포타스", "Hippopotas", "Hippopotas", "Hippopotas", "Hippopotas", "Hippopotas") },
            // { PBESpecies.450, new PBELocalizedString("カバルドン", "하마돈", "Hippodocus", "Hippoterus", "Hippowdon", "Hippowdon", "Hippowdon") },
            // { PBESpecies.451, new PBELocalizedString("スコルピ", "스콜피", "Rapion", "Pionskora", "Skorupi", "Skorupi", "Skorupi") },
            // { PBESpecies.452, new PBELocalizedString("ドラピオン", "드래피온", "Drascore", "Piondragi", "Drapion", "Drapion", "Drapion") },
            // { PBESpecies.453, new PBELocalizedString("グレッグル", "삐딱구리", "Cradopaud", "Glibunkel", "Croagunk", "Croagunk", "Croagunk") },
            // { PBESpecies.454, new PBELocalizedString("ドクロッグ", "독개굴", "Coatox", "Toxiquak", "Toxicroak", "Toxicroak", "Toxicroak") },
            // { PBESpecies.455, new PBELocalizedString("マスキッパ", "무스틈니", "Vortente", "Venuflibis", "Carnivine", "Carnivine", "Carnivine") },
            // { PBESpecies.456, new PBELocalizedString("ケイコウオ", "형광어", "Écayon", "Finneon", "Finneon", "Finneon", "Finneon") },
            // { PBESpecies.457, new PBELocalizedString("ネオラント", "네오라이트", "Luminéon", "Lumineon", "Lumineon", "Lumineon", "Lumineon") },
            // { PBESpecies.458, new PBELocalizedString("タマンタ", "타만타", "Babimanta", "Mantirps", "Mantyke", "Mantyke", "Mantyke") },
            // { PBESpecies.459, new PBELocalizedString("ユキカブリ", "눈쓰개", "Blizzi", "Shnebedeck", "Snover", "Snover", "Snover") },
            // { PBESpecies.460, new PBELocalizedString("ユキノオー", "눈설왕", "Blizzaroi", "Rexblisar", "Abomasnow", "Abomasnow", "Abomasnow") },
            // { PBESpecies.461, new PBELocalizedString("マニューラ", "포푸니라", "Dimoret", "Snibunna", "Weavile", "Weavile", "Weavile") },
            // { PBESpecies.462, new PBELocalizedString("ジバコイル", "자포코일", "Magnézone", "Magnezone", "Magnezone", "Magnezone", "Magnezone") },
            // { PBESpecies.463, new PBELocalizedString("ベロベルト", "내룸벨트", "Coudlangue", "Schlurplek", "Lickilicky", "Lickilicky", "Lickilicky") },
            // { PBESpecies.464, new PBELocalizedString("ドサイドン", "거대코뿌리", "Rhinastoc", "Rihornior", "Rhyperior", "Rhyperior", "Rhyperior") },
            // { PBESpecies.465, new PBELocalizedString("モジャンボ", "덩쿠림보", "Bouldeneu", "Tangoloss", "Tangrowth", "Tangrowth", "Tangrowth") },
            // { PBESpecies.466, new PBELocalizedString("エレキブル", "에레키블", "Élekable", "Elevoltek", "Electivire", "Electivire", "Electivire") },
            // { PBESpecies.467, new PBELocalizedString("ブーバーン", "마그마번", "Maganon", "Magbrant", "Magmortar", "Magmortar", "Magmortar") },
            // { PBESpecies.468, new PBELocalizedString("トゲキッス", "토게키스", "Togekiss", "Togekiss", "Togekiss", "Togekiss", "Togekiss") },
            // { PBESpecies.469, new PBELocalizedString("メガヤンマ", "메가자리", "Yanmega", "Yanmega", "Yanmega", "Yanmega", "Yanmega") },
            { PBESpecies.Leafeon, new PBELocalizedString("リーフィア", "리피아", "Phyllali", "Folipurba", "Leafeon", "Leafeon", "Leafeon") },
            { PBESpecies.Glaceon, new PBELocalizedString("グレイシア", "글레이시아", "Givrali", "Glaziola", "Glaceon", "Glaceon", "Glaceon") },
            // { PBESpecies.472, new PBELocalizedString("グライオン", "글라이온", "Scorvol", "Skorgro", "Gliscor", "Gliscor", "Gliscor") },
            // { PBESpecies.473, new PBELocalizedString("マンムー", "맘모꾸리", "Mammochon", "Mamutel", "Mamoswine", "Mamoswine", "Mamoswine") },
            // { PBESpecies.474, new PBELocalizedString("ポリゴンＺ", "폴리곤Z", "Porygon-Z", "Porygon-Z", "Porygon-Z", "Porygon-Z", "Porygon-Z") },
            // { PBESpecies.475, new PBELocalizedString("エルレイド", "엘레이드", "Gallame", "Galagladi", "Gallade", "Gallade", "Gallade") },
            // { PBESpecies.476, new PBELocalizedString("ダイノーズ", "대코파스", "Tarinorme", "Voluminas", "Probopass", "Probopass", "Probopass") },
            // { PBESpecies.477, new PBELocalizedString("ヨノワール", "야느와르몽", "Noctunoir", "Zwirrfinst", "Dusknoir", "Dusknoir", "Dusknoir") },
            // { PBESpecies.478, new PBELocalizedString("ユキメノコ", "눈여아", "Momartik", "Frosdedje", "Froslass", "Froslass", "Froslass") },
            { PBESpecies.Rotom, new PBELocalizedString("ロトム", "로토무", "Motisma", "Rotom", "Rotom", "Rotom", "Rotom") },
            { PBESpecies.Rotom_Fan, new PBELocalizedString("ロトム", "로토무", "Motisma", "Rotom", "Rotom", "Rotom", "Rotom") },
            { PBESpecies.Rotom_Frost, new PBELocalizedString("ロトム", "로토무", "Motisma", "Rotom", "Rotom", "Rotom", "Rotom") },
            { PBESpecies.Rotom_Heat, new PBELocalizedString("ロトム", "로토무", "Motisma", "Rotom", "Rotom", "Rotom", "Rotom") },
            { PBESpecies.Rotom_Mow, new PBELocalizedString("ロトム", "로토무", "Motisma", "Rotom", "Rotom", "Rotom", "Rotom") },
            { PBESpecies.Rotom_Wash, new PBELocalizedString("ロトム", "로토무", "Motisma", "Rotom", "Rotom", "Rotom", "Rotom") },
            { PBESpecies.Uxie, new PBELocalizedString("ユクシー", "유크시", "Créhelf", "Selfe", "Uxie", "Uxie", "Uxie") },
            { PBESpecies.Mesprit, new PBELocalizedString("エムリット", "엠라이트", "Créfollet", "Vesprit", "Mesprit", "Mesprit", "Mesprit") },
            { PBESpecies.Azelf, new PBELocalizedString("アグノム", "아그놈", "Créfadet", "Tobutz", "Azelf", "Azelf", "Azelf") },
            { PBESpecies.Dialga, new PBELocalizedString("ディアルガ", "디아루가", "Dialga", "Dialga", "Dialga", "Dialga", "Dialga") },
            { PBESpecies.Palkia, new PBELocalizedString("パルキア", "펄기아", "Palkia", "Palkia", "Palkia", "Palkia", "Palkia") },
            // { PBESpecies.485, new PBELocalizedString("ヒードラン", "히드런", "Heatran", "Heatran", "Heatran", "Heatran", "Heatran") },
            // { PBESpecies.486, new PBELocalizedString("レジギガス", "레지기가스", "Regigigas", "Regigigas", "Regigigas", "Regigigas", "Regigigas") },
            { PBESpecies.Giratina, new PBELocalizedString("ギラティナ", "기라티나", "Giratina", "Giratina", "Giratina", "Giratina", "Giratina") },
            { PBESpecies.Giratina_Origin, new PBELocalizedString("ギラティナ", "기라티나", "Giratina", "Giratina", "Giratina", "Giratina", "Giratina") },
            { PBESpecies.Cresselia, new PBELocalizedString("クレセリア", "크레세리아", "Cresselia", "Cresselia", "Cresselia", "Cresselia", "Cresselia") },
            // { PBESpecies.489, new PBELocalizedString("フィオネ", "피오네", "Phione", "Phione", "Phione", "Phione", "Phione") },
            // { PBESpecies.490, new PBELocalizedString("マナフィ", "마나피", "Manaphy", "Manaphy", "Manaphy", "Manaphy", "Manaphy") },
            { PBESpecies.Darkrai, new PBELocalizedString("ダークライ", "다크라이", "Darkrai", "Darkrai", "Darkrai", "Darkrai", "Darkrai") },
            // { PBESpecies.492, new PBELocalizedString("シェイミ", "쉐이미", "Shaymin", "Shaymin", "Shaymin", "Shaymin", "Shaymin") },
            { PBESpecies.Arceus, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Bug, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Dark, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Dragon, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Electric, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Fighting, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Fire, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Flying, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Ghost, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Grass, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Ground, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Ice, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Poison, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Psychic, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Rock, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Steel, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Arceus_Water, new PBELocalizedString("アルセウス", "아르세우스", "Arceus", "Arceus", "Arceus", "Arceus", "Arceus") },
            { PBESpecies.Victini, new PBELocalizedString("ビクティニ", "비크티니", "Victini", "Victini", "Victini", "Victini", "Victini") },
            { PBESpecies.Snivy, new PBELocalizedString("ツタージャ", "주리비얀", "Vipélierre", "Serpifeu", "Snivy", "Snivy", "Snivy") },
            { PBESpecies.Servine, new PBELocalizedString("ジャノビー", "샤비", "Lianaja", "Efoserp", "Servine", "Servine", "Servine") },
            { PBESpecies.Serperior, new PBELocalizedString("ジャローダ", "샤로다", "Majaspic", "Serpiroyal", "Serperior", "Serperior", "Serperior") },
            { PBESpecies.Tepig, new PBELocalizedString("ポカブ", "뚜꾸리", "Gruikui", "Floink", "Tepig", "Tepig", "Tepig") },
            { PBESpecies.Pignite, new PBELocalizedString("チャオブー", "차오꿀", "Grotichon", "Ferkokel", "Pignite", "Pignite", "Pignite") },
            { PBESpecies.Emboar, new PBELocalizedString("エンブオー", "염무왕", "Roitiflam", "Flambirex", "Emboar", "Emboar", "Emboar") },
            // { PBESpecies.501, new PBELocalizedString("ミジュマル", "수댕이", "Moustillon", "Ottaro", "Oshawott", "Oshawott", "Oshawott") },
            // { PBESpecies.502, new PBELocalizedString("フタチマル", "쌍검자비", "Mateloutre", "Zwottronin", "Dewott", "Dewott", "Dewott") },
            // { PBESpecies.503, new PBELocalizedString("ダイケンキ", "대검귀", "Clamiral", "Admurai", "Samurott", "Samurott", "Samurott") },
            // { PBESpecies.504, new PBELocalizedString("ミネズミ", "보르쥐", "Ratentif", "Nagelotz", "Patrat", "Patrat", "Patrat") },
            // { PBESpecies.505, new PBELocalizedString("ミルホッグ", "보르그", "Miradar", "Kukmarda", "Watchog", "Watchog", "Watchog") },
            // { PBESpecies.506, new PBELocalizedString("ヨーテリー", "요테리", "Ponchiot", "Yorkleff", "Lillipup", "Lillipup", "Lillipup") },
            // { PBESpecies.507, new PBELocalizedString("ハーデリア", "하데리어", "Ponchien", "Terribark", "Herdier", "Herdier", "Herdier") },
            // { PBESpecies.508, new PBELocalizedString("ムーランド", "바랜드", "Mastouffe", "Bissbark", "Stoutland", "Stoutland", "Stoutland") },
            // { PBESpecies.509, new PBELocalizedString("チョロネコ", "쌔비냥", "Chacripan", "Felilou", "Purrloin", "Purrloin", "Purrloin") },
            // { PBESpecies.510, new PBELocalizedString("レパルダス", "레파르다스", "Léopardus", "Kleoparda", "Liepard", "Liepard", "Liepard") },
            // { PBESpecies.511, new PBELocalizedString("ヤナップ", "야나프", "Feuillajou", "Vegimak", "Pansage", "Pansage", "Pansage") },
            // { PBESpecies.512, new PBELocalizedString("ヤナッキー", "야나키", "Feuiloutan", "Vegichita", "Simisage", "Simisage", "Simisage") },
            // { PBESpecies.513, new PBELocalizedString("バオップ", "바오프", "Flamajou", "Grillmak", "Pansear", "Pansear", "Pansear") },
            // { PBESpecies.514, new PBELocalizedString("バオッキー", "바오키", "Flamoutan", "Grillchita", "Simisear", "Simisear", "Simisear") },
            // { PBESpecies.515, new PBELocalizedString("ヒヤップ", "앗차프", "Flotajou", "Sodamak", "Panpour", "Panpour", "Panpour") },
            // { PBESpecies.516, new PBELocalizedString("ヒヤッキー", "앗차키", "Flotoutan", "Sodachita", "Simipour", "Simipour", "Simipour") },
            // { PBESpecies.517, new PBELocalizedString("ムンナ", "몽나", "Munna", "Somniam", "Munna", "Munna", "Munna") },
            // { PBESpecies.518, new PBELocalizedString("ムシャーナ", "몽얌나", "Mushana", "Somnivora", "Musharna", "Musharna", "Musharna") },
            // { PBESpecies.519, new PBELocalizedString("マメパト", "콩둘기", "Poichigeon", "Dusselgurr", "Pidove", "Pidove", "Pidove") },
            // { PBESpecies.520, new PBELocalizedString("ハトーボー", "유토브", "Colombeau", "Navitaub", "Tranquill", "Tranquill", "Tranquill") },
            // { PBESpecies.521, new PBELocalizedString("ケンホロウ", "켄호로우", "Déflaisan", "Fasasnob", "Unfezant", "Unfezant", "Unfezant") },
            // { PBESpecies.522, new PBELocalizedString("シママ", "줄뮤마", "Zébibron", "Elezeba", "Blitzle", "Blitzle", "Blitzle") },
            // { PBESpecies.523, new PBELocalizedString("ゼブライカ", "제브라이카", "Zéblitz", "Zebritz", "Zebstrika", "Zebstrika", "Zebstrika") },
            // { PBESpecies.524, new PBELocalizedString("ダンゴロ", "단굴", "Nodulithe", "Kiesling", "Roggenrola", "Roggenrola", "Roggenrola") },
            // { PBESpecies.525, new PBELocalizedString("ガントル", "암트르", "Géolithe", "Sedimantur", "Boldore", "Boldore", "Boldore") },
            // { PBESpecies.526, new PBELocalizedString("ギガイアス", "기가이어스", "Gigalithe", "Brockoloss", "Gigalith", "Gigalith", "Gigalith") },
            // { PBESpecies.527, new PBELocalizedString("コロモリ", "또르박쥐", "Chovsourir", "Fleknoil", "Woobat", "Woobat", "Woobat") },
            // { PBESpecies.528, new PBELocalizedString("ココロモリ", "맘박쥐", "Rhinolove", "Fletiamo", "Swoobat", "Swoobat", "Swoobat") },
            // { PBESpecies.529, new PBELocalizedString("モグリュー", "두더류", "Rototaupe", "Rotomurf", "Drilbur", "Drilbur", "Drilbur") },
            // { PBESpecies.530, new PBELocalizedString("ドリュウズ", "몰드류", "Minotaupe", "Stalobor", "Excadrill", "Excadrill", "Excadrill") },
            // { PBESpecies.531, new PBELocalizedString("タブンネ", "다부니", "Nanméouïe", "Ohrdoch", "Audino", "Audino", "Audino") },
            // { PBESpecies.532, new PBELocalizedString("ドッコラー", "으랏차", "Charpenti", "Praktibalk", "Timburr", "Timburr", "Timburr") },
            // { PBESpecies.533, new PBELocalizedString("ドテッコツ", "토쇠골", "Ouvrifier", "Strepoli", "Gurdurr", "Gurdurr", "Gurdurr") },
            // { PBESpecies.534, new PBELocalizedString("ローブシン", "노보청", "Bétochef", "Meistagrif", "Conkeldurr", "Conkeldurr", "Conkeldurr") },
            // { PBESpecies.535, new PBELocalizedString("オタマロ", "동챙이", "Tritonde", "Schallquap", "Tympole", "Tympole", "Tympole") },
            // { PBESpecies.536, new PBELocalizedString("ガマガル", "두까비", "Batracné", "Mebrana", "Palpitoad", "Palpitoad", "Palpitoad") },
            // { PBESpecies.537, new PBELocalizedString("ガマゲロゲ", "두빅굴", "Crapustule", "Branawarz", "Seismitoad", "Seismitoad", "Seismitoad") },
            // { PBESpecies.538, new PBELocalizedString("ナゲキ", "던지미", "Judokrak", "Jiutesto", "Throh", "Throh", "Throh") },
            // { PBESpecies.539, new PBELocalizedString("ダゲキ", "타격귀", "Karaclée", "Karadonis", "Sawk", "Sawk", "Sawk") },
            // { PBESpecies.540, new PBELocalizedString("クルミル", "두르보", "Larveyette", "Strawickl", "Sewaddle", "Sewaddle", "Sewaddle") },
            // { PBESpecies.541, new PBELocalizedString("クルマユ", "두르쿤", "Couverdure", "Folikon", "Swadloon", "Swadloon", "Swadloon") },
            // { PBESpecies.542, new PBELocalizedString("ハハコモリ", "모아머", "Manternel", "Matrifol", "Leavanny", "Leavanny", "Leavanny") },
            // { PBESpecies.543, new PBELocalizedString("フシデ", "마디네", "Venipatte", "Toxiped", "Venipede", "Venipede", "Venipede") },
            // { PBESpecies.544, new PBELocalizedString("ホイーガ", "휠구", "Scobolide", "Rollum", "Whirlipede", "Whirlipede", "Whirlipede") },
            // { PBESpecies.545, new PBELocalizedString("ペンドラー", "펜드라", "Brutapode", "Cerapendra", "Scolipede", "Scolipede", "Scolipede") },
            // { PBESpecies.546, new PBELocalizedString("モンメン", "소미안", "Doudouvet", "Waumboll", "Cottonee", "Cottonee", "Cottonee") },
            // { PBESpecies.547, new PBELocalizedString("エルフーン", "엘풍", "Farfaduvet", "Elfun", "Whimsicott", "Whimsicott", "Whimsicott") },
            // { PBESpecies.548, new PBELocalizedString("チュリネ", "치릴리", "Chlorobule", "Lilminip", "Petilil", "Petilil", "Petilil") },
            // { PBESpecies.549, new PBELocalizedString("ドレディア", "드레디어", "Fragilady", "Dressella", "Lilligant", "Lilligant", "Lilligant") },
            // { PBESpecies.550, new PBELocalizedString("バスラオ", "배쓰나이", "Bargantua", "Barschuft", "Basculin", "Basculin", "Basculin") },
            // { PBESpecies.551, new PBELocalizedString("メグロコ", "깜눈크", "Mascaïman", "Ganovil", "Sandile", "Sandile", "Sandile") },
            // { PBESpecies.552, new PBELocalizedString("ワルビル", "악비르", "Escroco", "Rokkaiman", "Krokorok", "Krokorok", "Krokorok") },
            // { PBESpecies.553, new PBELocalizedString("ワルビアル", "악비아르", "Crocorible", "Rabigator", "Krookodile", "Krookodile", "Krookodile") },
            // { PBESpecies.554, new PBELocalizedString("ダルマッカ", "달막화", "Darumarond", "Flampion", "Darumaka", "Darumaka", "Darumaka") },
            // { PBESpecies.555, new PBELocalizedString("ヒヒダルマ", "불비달마", "Darumacho", "Flampivian", "Darmanitan", "Darmanitan", "Darmanitan") },
            // { PBESpecies.556, new PBELocalizedString("マラカッチ", "마라카치", "Maracachi", "Maracamba", "Maractus", "Maractus", "Maractus") },
            // { PBESpecies.557, new PBELocalizedString("イシズマイ", "돌살이", "Crabicoque", "Lithomith", "Dwebble", "Dwebble", "Dwebble") },
            // { PBESpecies.558, new PBELocalizedString("イワパレス", "암팰리스", "Crabaraque", "Castellith", "Crustle", "Crustle", "Crustle") },
            // { PBESpecies.559, new PBELocalizedString("ズルッグ", "곤율랭", "Baggiguane", "Zurrokex", "Scraggy", "Scraggy", "Scraggy") },
            // { PBESpecies.560, new PBELocalizedString("ズルズキン", "곤율거니", "Baggaïd", "Irokex", "Scrafty", "Scrafty", "Scrafty") },
            // { PBESpecies.561, new PBELocalizedString("シンボラー", "심보러", "Cryptéro", "Symvolara", "Sigilyph", "Sigilyph", "Sigilyph") },
            { PBESpecies.Yamask, new PBELocalizedString("デスマス", "데스마스", "Tutafeh", "Makabaja", "Yamask", "Yamask", "Yamask") },
            { PBESpecies.Cofagrigus, new PBELocalizedString("デスカーン", "데스니칸", "Tutankafer", "Echnatoll", "Cofagrigus", "Cofagrigus", "Cofagrigus") },
            { PBESpecies.Tirtouga, new PBELocalizedString("プロトーガ", "프로토가", "Carapagos", "Galapaflos", "Tirtouga", "Tirtouga", "Tirtouga") },
            { PBESpecies.Carracosta, new PBELocalizedString("アバゴーラ", "늑골라", "Mégapagos", "Karippas", "Carracosta", "Carracosta", "Carracosta") },
            // { PBESpecies.566, new PBELocalizedString("アーケン", "아켄", "Arkéapti", "Flapteryx", "Archen", "Archen", "Archen") },
            // { PBESpecies.567, new PBELocalizedString("アーケオス", "아케오스", "Aéroptéryx", "Aeropteryx", "Archeops", "Archeops", "Archeops") },
            // { PBESpecies.568, new PBELocalizedString("ヤブクロン", "깨봉이", "Miamiasme", "Unratütox", "Trubbish", "Trubbish", "Trubbish") },
            // { PBESpecies.569, new PBELocalizedString("ダストダス", "더스트나", "Miasmax", "Deponitox", "Garbodor", "Garbodor", "Garbodor") },
            // { PBESpecies.570, new PBELocalizedString("ゾロア", "조로아", "Zorua", "Zorua", "Zorua", "Zorua", "Zorua") },
            // { PBESpecies.571, new PBELocalizedString("ゾロアーク", "조로아크", "Zoroark", "Zoroark", "Zoroark", "Zoroark", "Zoroark") },
            // { PBESpecies.572, new PBELocalizedString("チラーミィ", "치라미", "Chinchidou", "Picochilla", "Minccino", "Minccino", "Minccino") },
            // { PBESpecies.573, new PBELocalizedString("チラチーノ", "치라치노", "Pashmilla", "Chillabell", "Cinccino", "Cinccino", "Cinccino") },
            { PBESpecies.Gothita, new PBELocalizedString("ゴチム", "고디탱", "Scrutella", "Mollimorba", "Gothita", "Gothita", "Gothita") },
            { PBESpecies.Gothorita, new PBELocalizedString("ゴチミル", "고디보미", "Mesmérella", "Hypnomorba", "Gothorita", "Gothorita", "Gothorita") },
            { PBESpecies.Gothitelle, new PBELocalizedString("ゴチルゼル", "고디모아젤", "Sidérella", "Morbitesse", "Gothitelle", "Gothitelle", "Gothitelle") },
            // { PBESpecies.577, new PBELocalizedString("ユニラン", "유니란", "Nucléos", "Monozyto", "Solosis", "Solosis", "Solosis") },
            // { PBESpecies.578, new PBELocalizedString("ダブラン", "듀란", "Méios", "Mitodos", "Duosion", "Duosion", "Duosion") },
            // { PBESpecies.579, new PBELocalizedString("ランクルス", "란쿨루스", "Symbios", "Zytomega", "Reuniclus", "Reuniclus", "Reuniclus") },
            // { PBESpecies.580, new PBELocalizedString("コアルヒー", "꼬지보리", "Couaneton", "Piccolente", "Ducklett", "Ducklett", "Ducklett") },
            // { PBESpecies.581, new PBELocalizedString("スワンナ", "스완나", "Lakmécygne", "Swaroness", "Swanna", "Swanna", "Swanna") },
            // { PBESpecies.582, new PBELocalizedString("バニプッチ", "바닐프티", "Sorbébé", "Gelatini", "Vanillite", "Vanillite", "Vanillite") },
            // { PBESpecies.583, new PBELocalizedString("バニリッチ", "바닐리치", "Sorboul", "Gelatroppo", "Vanillish", "Vanillish", "Vanillish") },
            // { PBESpecies.584, new PBELocalizedString("バイバニラ", "배바닐라", "Sorbouboul", "Gelatwino", "Vanilluxe", "Vanilluxe", "Vanilluxe") },
            // { PBESpecies.585, new PBELocalizedString("シキジカ", "사철록", "Vivaldaim", "Sesokitz", "Deerling", "Deerling", "Deerling") },
            // { PBESpecies.586, new PBELocalizedString("メブキジカ", "바라철록", "Haydaim", "Kronjuwild", "Sawsbuck", "Sawsbuck", "Sawsbuck") },
            { PBESpecies.Emolga, new PBELocalizedString("エモンガ", "에몽가", "Emolga", "Emolga", "Emolga", "Emolga", "Emolga") },
            // { PBESpecies.588, new PBELocalizedString("カブルモ", "딱정곤", "Carabing", "Laukaps", "Karrablast", "Karrablast", "Karrablast") },
            // { PBESpecies.589, new PBELocalizedString("シュバルゴ", "슈바르고", "Lançargot", "Cavalanzas", "Escavalier", "Escavalier", "Escavalier") },
            // { PBESpecies.590, new PBELocalizedString("タマゲタケ", "깜놀버슬", "Trompignon", "Tarnpignon", "Foongus", "Foongus", "Foongus") },
            // { PBESpecies.591, new PBELocalizedString("モロバレル", "뽀록나", "Gaulet", "Hutsassa", "Amoonguss", "Amoonguss", "Amoonguss") },
            // { PBESpecies.592, new PBELocalizedString("プルリル", "탱그릴", "Viskuse", "Quabbel", "Frillish", "Frillish", "Frillish") },
            // { PBESpecies.593, new PBELocalizedString("ブルンゲル", "탱탱겔", "Moyade", "Apoquallyp", "Jellicent", "Jellicent", "Jellicent") },
            { PBESpecies.Alomomola, new PBELocalizedString("ママンボウ", "맘복치", "Mamanbo", "Mamolida", "Alomomola", "Alomomola", "Alomomola") },
            // { PBESpecies.595, new PBELocalizedString("バチュル", "파쪼옥", "Statitik", "Wattzapf", "Joltik", "Joltik", "Joltik") },
            // { PBESpecies.596, new PBELocalizedString("デンチュラ", "전툴라", "Mygavolt", "Voltula", "Galvantula", "Galvantula", "Galvantula") },
            // { PBESpecies.597, new PBELocalizedString("テッシード", "철시드", "Grindur", "Kastadur", "Ferroseed", "Ferroseed", "Ferroseed") },
            // { PBESpecies.598, new PBELocalizedString("ナットレイ", "너트령", "Noacier", "Tentantel", "Ferrothorn", "Ferrothorn", "Ferrothorn") },
            // { PBESpecies.599, new PBELocalizedString("ギアル", "기어르", "Tic", "Klikk", "Klink", "Klink", "Klink") },
            // { PBESpecies.600, new PBELocalizedString("ギギアル", "기기어르", "Clic", "Kliklak", "Klang", "Klang", "Klang") },
            // { PBESpecies.601, new PBELocalizedString("ギギギアル", "기기기어르", "Cliticlic", "Klikdiklak", "Klinklang", "Klinklang", "Klinklang") },
            // { PBESpecies.602, new PBELocalizedString("シビシラス", "저리어", "Anchwatt", "Zapplardin", "Tynamo", "Tynamo", "Tynamo") },
            // { PBESpecies.603, new PBELocalizedString("シビビール", "저리릴", "Lampéroie", "Zapplalek", "Eelektrik", "Eelektrik", "Eelektrik") },
            // { PBESpecies.604, new PBELocalizedString("シビルドン", "저리더프", "Ohmassacre", "Zapplarang", "Eelektross", "Eelektross", "Eelektross") },
            // { PBESpecies.605, new PBELocalizedString("リグレー", "리그레", "Lewsor", "Pygraulon", "Elgyem", "Elgyem", "Elgyem") },
            // { PBESpecies.606, new PBELocalizedString("オーベム", "벰크", "Neitram", "Megalon", "Beheeyem", "Beheeyem", "Beheeyem") },
            { PBESpecies.Litwick, new PBELocalizedString("ヒトモシ", "불켜미", "Funécire", "Lichtel", "Litwick", "Litwick", "Litwick") },
            { PBESpecies.Lampent, new PBELocalizedString("ランプラー", "램프라", "Mélancolux", "Laternecto", "Lampent", "Lampent", "Lampent") },
            { PBESpecies.Chandelure, new PBELocalizedString("シャンデラ", "샹델라", "Lugulabre", "Skelabra", "Chandelure", "Chandelure", "Chandelure") },
            // { PBESpecies.610, new PBELocalizedString("キバゴ", "터검니", "Coupenotte", "Milza", "Axew", "Axew", "Axew") },
            // { PBESpecies.611, new PBELocalizedString("オノンド", "액슨도", "Incisache", "Sharfax", "Fraxure", "Fraxure", "Fraxure") },
            // { PBESpecies.612, new PBELocalizedString("オノノクス", "액스라이즈", "Tranchodon", "Maxax", "Haxorus", "Haxorus", "Haxorus") },
            // { PBESpecies.613, new PBELocalizedString("クマシュン", "코고미", "Polarhume", "Petznief", "Cubchoo", "Cubchoo", "Cubchoo") },
            // { PBESpecies.614, new PBELocalizedString("ツンベアー", "툰베어", "Polagriffe", "Siberio", "Beartic", "Beartic", "Beartic") },
            { PBESpecies.Cryogonal, new PBELocalizedString("フリージオ", "프리지오", "Hexagel", "Frigometri", "Cryogonal", "Cryogonal", "Cryogonal") },
            // { PBESpecies.616, new PBELocalizedString("チョボマキ", "쪼마리", "Escargaume", "Schnuthelm", "Shelmet", "Shelmet", "Shelmet") },
            // { PBESpecies.617, new PBELocalizedString("アギルダー", "어지리더", "Limaspeed", "Hydragil", "Accelgor", "Accelgor", "Accelgor") },
            // { PBESpecies.618, new PBELocalizedString("マッギョ", "메더", "Limonde", "Flunschlik", "Stunfisk", "Stunfisk", "Stunfisk") },
            // { PBESpecies.619, new PBELocalizedString("コジョフー", "비조푸", "Kungfouine", "Lin-Fu", "Mienfoo", "Mienfoo", "Mienfoo") },
            // { PBESpecies.620, new PBELocalizedString("コジョンド", "비조도", "Shaofouine", "Wie-Shu", "Mienshao", "Mienshao", "Mienshao") },
            { PBESpecies.Druddigon, new PBELocalizedString("クリムガン", "크리만", "Drakkarmin", "Shardrago", "Druddigon", "Druddigon", "Druddigon") },
            // { PBESpecies.622, new PBELocalizedString("ゴビット", "골비람", "Gringolem", "Golbit", "Golett", "Golett", "Golett") },
            // { PBESpecies.623, new PBELocalizedString("ゴルーグ", "골루그", "Golemastoc", "Golgantes", "Golurk", "Golurk", "Golurk") },
            // { PBESpecies.624, new PBELocalizedString("コマタナ", "자망칼", "Scalpion", "Gladiantri", "Pawniard", "Pawniard", "Pawniard") },
            // { PBESpecies.625, new PBELocalizedString("キリキザン", "절각참", "Scalproie", "Caesurio", "Bisharp", "Bisharp", "Bisharp") },
            { PBESpecies.Bouffalant, new PBELocalizedString("バッフロン", "버프론", "Frison", "Bisofank", "Bouffalant", "Bouffalant", "Bouffalant") },
            // { PBESpecies.627, new PBELocalizedString("ワシボン", "수리둥보", "Furaiglon", "Geronimatz", "Rufflet", "Rufflet", "Rufflet") },
            // { PBESpecies.628, new PBELocalizedString("ウォーグル", "워글", "Gueriaigle", "Washakwil", "Braviary", "Braviary", "Braviary") },
            // { PBESpecies.629, new PBELocalizedString("バルチャイ", "벌차이", "Vostourno", "Skallyk", "Vullaby", "Vullaby", "Vullaby") },
            // { PBESpecies.630, new PBELocalizedString("バルジーナ", "버랜지나", "Vaututrice", "Grypheldis", "Mandibuzz", "Mandibuzz", "Mandibuzz") },
            // { PBESpecies.631, new PBELocalizedString("クイタラン", "앤티골", "Aflamanoir", "Furnifraß", "Heatmor", "Heatmor", "Heatmor") },
            // { PBESpecies.632, new PBELocalizedString("アイアント", "아이앤트", "Fermite", "Fermicula", "Durant", "Durant", "Durant") },
            { PBESpecies.Deino, new PBELocalizedString("モノズ", "모노두", "Solochi", "Kapuno", "Deino", "Deino", "Deino") },
            { PBESpecies.Zweilous, new PBELocalizedString("ジヘッド", "디헤드", "Diamat", "Duodino", "Zweilous", "Zweilous", "Zweilous") },
            { PBESpecies.Hydreigon, new PBELocalizedString("サザンドラ", "삼삼드래", "Trioxhydre", "Trikephalo", "Hydreigon", "Hydreigon", "Hydreigon") },
            { PBESpecies.Larvesta, new PBELocalizedString("メラルバ", "활화르바", "Pyronille", "Ignivor", "Larvesta", "Larvesta", "Larvesta") },
            { PBESpecies.Volcarona, new PBELocalizedString("ウルガモス", "불카모스", "Pyrax", "Ramoth", "Volcarona", "Volcarona", "Volcarona") },
            // { PBESpecies.638, new PBELocalizedString("コバルオン", "코바르온", "Cobaltium", "Kobalium", "Cobalion", "Cobalion", "Cobalion") },
            // { PBESpecies.639, new PBELocalizedString("テラキオン", "테라키온", "Terrakium", "Terrakium", "Terrakion", "Terrakion", "Terrakion") },
            // { PBESpecies.640, new PBELocalizedString("ビリジオン", "비리디온", "Viridium", "Viridium", "Virizion", "Virizion", "Virizion") },
            // { PBESpecies.641, new PBELocalizedString("トルネロス", "토네로스", "Boréas", "Boreos", "Tornadus", "Tornadus", "Tornadus") },
            // { PBESpecies.642, new PBELocalizedString("ボルトロス", "볼트로스", "Fulguris", "Voltolos", "Thundurus", "Thundurus", "Thundurus") },
            // { PBESpecies.643, new PBELocalizedString("レシラム", "레시라무", "Reshiram", "Reshiram", "Reshiram", "Reshiram", "Reshiram") },
            // { PBESpecies.644, new PBELocalizedString("ゼクロム", "제크로무", "Zekrom", "Zekrom", "Zekrom", "Zekrom", "Zekrom") },
            // { PBESpecies.645, new PBELocalizedString("ランドロス", "랜드로스", "Démétéros", "Demeteros", "Landorus", "Landorus", "Landorus") },
            // { PBESpecies.646, new PBELocalizedString("キュレム", "큐레무", "Kyurem", "Kyurem", "Kyurem", "Kyurem", "Kyurem") },
            // { PBESpecies.647, new PBELocalizedString("ケルディオ", "케르디오", "Keldeo", "Keldeo", "Keldeo", "Keldeo", "Keldeo") },
            // { PBESpecies.648, new PBELocalizedString("メロエッタ", "메로엣타", "Meloetta", "Meloetta", "Meloetta", "Meloetta", "Meloetta") },
            { PBESpecies.Genesect, new PBELocalizedString("ゲノセクト", "게노세크트", "Genesect", "Genesect", "Genesect", "Genesect", "Genesect") },
            { PBESpecies.Genesect_Burn, new PBELocalizedString("ゲノセクト", "게노세크트", "Genesect", "Genesect", "Genesect", "Genesect", "Genesect") },
            { PBESpecies.Genesect_Chill, new PBELocalizedString("ゲノセクト", "게노세크트", "Genesect", "Genesect", "Genesect", "Genesect", "Genesect") },
            { PBESpecies.Genesect_Douse, new PBELocalizedString("ゲノセクト", "게노세크트", "Genesect", "Genesect", "Genesect", "Genesect", "Genesect") },
            { PBESpecies.Genesect_Shock, new PBELocalizedString("ゲノセクト", "게노세크트", "Genesect", "Genesect", "Genesect", "Genesect", "Genesect") }
        });
    }
}
